### ISSUE TITLE
Markdown Cell Shortcut?

### ISSUE THREAD

**Issue by riyavsinha** [marimo-team/marimo#1003]
### Description

I have to type `mo.md()` first to start a markdown cell / get the markdown editor to show up (I think?)

### Suggested solution

Have either a shortcut (cmd+shift+m?) or UI method in a cell's six-dot menu to convert a cell to markdown instead, so I can immediately start text using the markdown editor

**Comment by akshayka** [comment]
> I have to type mo.md() first to start a markdown cell / get the markdown editor to show up (I think?)

Yes, that's right.

In marimo, there are only Python cells; we don't have a distinction between Python and Markdown cells. The markdown editor is just a friendly skin over `mo.md()`.

> Have either a shortcut (cmd+shift+m?) 

We'd welcome a PR adding a keyboard shortcut (potentially the one you suggest, if it plays well across browsers) that toggles the markdown view when possible -- this would work on empty cells, as well as cells starting with `mo.md`.
