### ISSUE TITLE
Updateable static html links

### ISSUE THREAD

**Issue by riyavsinha** [marimo-team/marimo#1005]
### Description

When using "Share > Publish HTML to Web", the static generated URL is not saved anywhere in the notebook, and so each time I click that button it tries to generate a new link.

I understand this makes sense as someone else who tries to run a copy of the notebook should not be able to arbitrarily make changes to the saved static html, but it does make things difficult if I want to share updates with collaborators, as the ideal scenario would be I can share a link with them once and they can keep checking it for updates.

### Suggested solution

Perhaps some sort of `marimo login` CLI command which can perform some OAuth and save auth info locally. Then somehow linking the auth info to the static html link which could either be stored in the notebook, or a local hidden file? Not sure the best way to go about it.

**Comment by akshayka** [comment]
Hey @riyavsinha , thanks for the feature request. `marimo login` is a very interesting idea, but we're not quite there yet.

In the meantime, we're building a simple online workspace with authentication that could support something like this. We can add you to that -- can you send us an email at contact@marimo.io? Then we can get you set up.

**Comment by mscolnick** [comment]
Going to close this as this is available in https://marimo.io/ now
