### ISSUE TITLE
Dark mode application for charts and graphs aka "smart" dark mode

### ISSUE THREAD

**Issue by vrtnis** [marimo-team/marimo#1012]
### Description

This is somewhat related to dark mode issue #547 which was closed by #556. Generally speaking, python notebook users may have a need for dark mode applied to interactive elements charts and graphs (which remain bright white backgrounds on otherwise dark mode notebooks).

Users seem to address the issue manually by applying specific styles - see datapoints below
https://stackoverflow.com/questions/75429196/vs-code-jupyter-notebook-dark-theme-for-interactive-elements
https://stackoverflow.com/questions/58206394/dark-mode-plots-in-jupyter-notebook-python

### Suggested solution

One suggestion would be to use an api (or the underlying MIT licensed model) used by https://invertornot.com/ if additionally enabled by the user through the system theme menu. 

https://github.com/mattismegevand/invertornot

### Alternative

Short of simple color inversion or altering image brightness globally, there doesn't seem to be another alternative.  

### Additional context

Could appeal to users who extensively work with images, chart, graph outputs.  Just wanted to create an issue here for better visibility in case anyone wants to comment.

**Comment by mscolnick** [comment]
> which remain bright white backgrounds on otherwise dark mode notebooks

Which charts and graphs do this specifically?

**Comment by vrtnis** [comment]
To reproduce try the Plotting example in marimo.new and switch to the dark theme.  
![screenshot10-59-25](https://github.com/marimo-team/marimo/assets/123119434/a4783151-1e0a-47d1-84bb-3ed342fd68ad)
Thought that perhaps the plot image could be transformed like this (used "smart" inversion):
![screenshot11-02-44](https://github.com/marimo-team/marimo/assets/123119434/7fcf8754-8707-4817-a5cf-720399b71c7c)

**Comment by mscolnick** [comment]
This is coming from `plt` which returns an image. Are you suggesting we invert the image? I'm not sure how to do that effectively in all cases. 

Could you use `plt.style.use('dark_background')`?

**Comment by vrtnis** [comment]
yes, auto-inverting the image was my initial thought, but totally agree that it will be tricky for all use cases with varying outputs.  plt.style.use('dark_background') is definitely a good alternative!

**Comment by mscolnick** [comment]
Yea not all images are graph/charts, and even then may not work well inverted (color may mean something - like red/green).

Something we can consider doing is adding a way for the python code to know the dark/light mode: e.g `plt.style.use('dark_background' if mo.meta.theme  == 'dark' else None)`

**Comment by marie-cloet2000** [comment]
I am using marimo's dark mode with `plt.style.use('dark_background')`, but the figure background is still white: 

<img width="714" height="538" alt="Image" src="https://github.com/user-attachments/assets/55a29ade-af7b-4e4f-a7fb-476d57c7dc51" />

I presume this is related to the notebook setting for `plt.show`, perhaps figures are automatically displayed with a white background. Is there a way to solve this?
