### ISSUE TITLE
Restarting kernel in marimo.app loses changes to **code**

### ISSUE THREAD

**Issue by srobertjames** [marimo-team/marimo#1013]
### Describe the bug

1. Write code in marimo.app
2. Save it
3. Make changes but don't save them
4. Restart the kernel

Expected: Vars change, but code cells remain
Actual: Code cells are lost

### Environment

marimo.app

### Code to reproduce

See above

**Comment by akshayka** [comment]
@mscolnick, restart kernel in WASM just refreshes the page and I suppose relies on local storage to restore code? I guess one could get into weird state if you had multiple marimo.app playgrounds open ...?

Maybe instead restart kernel should grab the code on the page, encode it to create a new playground link with the notebook's code, and navigate there ...?

**Comment by srobertjames** [comment]
At the very least: The current warning message tells you you'll lose vars in RAM, which is very misleading - it makes you think it behaves like a Jupyter notebook.  At the least, change the text to "Warning: You will lose any unsaved files".  Or even better: Block the restart unless you save (giving an option to save).

That is, until this is fixed - or if fixing it is impossible, the most important thing is to communicate what happens.  It is very painful to lose unsaved code.

**Comment by mscolnick** [comment]
I've made it a bit more defensive in saving your code (and with a warning) in this PR #1018

@srobertjames , you can also turn on autosave (i.e 1 second) which will keep your code saved at all times
