### ISSUE TITLE
Deleting a cell doesn't let you redefine the cell's variables

### ISSUE THREAD

**Issue by riyavsinha** [marimo-team/marimo#1016]
### Describe the bug

After a cell is deleted or a variable is even just declared in a cell, I cannot move that variable declaration to a different cell

Steps:

1. Create and run cell with `x = 4`
2. Delete cell
3. Create and run new cell with `x = 3`

Error:

```
This cell wasn't run because it has errors
The variable 'x' was defined by another cell:

Tip:
Try merging this cell with the above cells. Alternatively, rename 'x' to '_x' to make the variable private to this cell.
```

(Side note, I don't think merging cells is a thing right now right? Tried searching the [docs](https://docs.marimo.io/search.html?q=merge&check_keywords=yes&area=default))

I can see the use of private variables as being good practice to do generally, but when a cell is deleted it would still be nice to be able to free up that variable for redeclaration.

I ran into this when I was simply trying to reorganize my notebook a bit.

### Environment

(was just reproducing on marimo.app)

**Comment by akshayka** [comment]
Thanks for opening this issue @riyavsinha. I tried but I'm unable to reproduce the issue.

Are you still able to repro it? If so, could you send a video of your reproduction, or any other way for us to reproduce it?

**Comment by riyavsinha** [comment]
Sure! This is in marimo.app, but it also happened in my local env running `marimo notebook edit`

https://github.com/marimo-team/marimo/assets/33243383/a49257c8-966e-4830-badf-e66878fb4818

**Comment by akshayka** [comment]
Thank you! That's very helpful. It's specific to deleting via the context menu, as opposed to the trash icon  -- looks like we forget to send a message to the kernel when that happens. Will fix.
