### ISSUE TITLE
Minor issues with filesystem and grid/vertical layout

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1031]
reported by @fuenfundachtzig :

              First of all, thanks for the great work on marimo!

I noticed a few inconveniences:
- [x] When there is a bad symbolic link in a directory, [this line][1] will lead to an "Internal Server Error". ("Bad" can either be a recursive link (`ln -s broken`) or a link pointing to a non-existing file (`ln -s broken notthere`).)
- [x] Saving will allow filenames such as "." or ".." to be used as regular filenames.
- [x] When switching to the grid layout in app mode and back to vertical layout, the layout file is not deleted, in my case leading to an empty app being shown with `marimo run ...`

[1]: https://github.com/marimo-team/marimo/blob/413bc9dbb20aa7be86b6cf661606134583ae5e6b/marimo/_server/files/os_file_system.py#L46

_Originally posted by @fuenfundachtzig in https://github.com/marimo-team/marimo/issues/503#issuecomment-2027717863_

**Comment by fuenfundachtzig** [comment]
Mini PR to fix first issue in #1034

**Comment by fuenfundachtzig** [comment]
Thanks for fixing these!
