### ISSUE TITLE
Feedback when computation finishes

### ISSUE THREAD

**Issue by Eloitor** [marimo-team/marimo#1039]
### Description

When running long computations I'm often waiting for it to finish. I'd like to get some feedback when computation finishes.

### Suggested solution

- Configurable audio feedback
- Configurable browser notifications

**Comment by dmadisetti** [comment]
colab changes the favicon for running, idle and failed- great visual cue from different tab

**Comment by wasimsandhu** [comment]
Grabbing this next 🥸 cc @akshayka

**Comment by akshayka** [comment]
Sounds good! Let's do the favicon solution suggested in this thread?

**Comment by wasimsandhu** [comment]
Sure! Favicon alert by default, do we want optional settings to allow audio alerts and browser notifications too?

**Comment by mscolnick** [comment]
@wasimsandhu i think those notifications could be valuable. 

Probably behind a setting and I think maybe only when the page is not active (there a DOM attribute to check if the document is active/visible)

**Comment by wasimsandhu** [comment]
Picking this up this week 🫡

**Comment by mscolnick** [comment]
Closed by https://github.com/marimo-team/marimo/pull/1634
