### ISSUE TITLE
Marimo plotly Scale to full width when mo.center and mo.tabs is used

### ISSUE THREAD

**Issue by AsgerJ95** [marimo-team/marimo#1064]
### Description

Using mo.ui.plotly it seems that the figure does not scale correctly to full width if mo.center(mo.ui.tabs()) is used. 

It would be nice to have this functionality, e.g. if you have different plot under various tabs.

Figures works fine if included in  

<img width="716" alt="Marimo Plotly Scale " src="https://github.com/marimo-team/marimo/assets/143942092/a1142766-2e06-4bd3-bae2-3ca5400f8008">

### Suggested solution

Centering working when also using tabs to fit the whole of the full-width. 

When not using centering. 
<img width="791" alt="Marimo Plotly Scale w o  centering" src="https://github.com/marimo-team/marimo/assets/143942092/7fad25f9-5570-4813-9deb-d3b934abf5da">

It would be nice if centering did not influence the graph in this way and if you could scale it independently. 

### Additional context

The following will results in the scaling. 

test = **PLOTLY FIGURE**
test_tabs = mo.center(mo.ui.tabs({"💾 Test tab": test}))
test_tabs

**Comment by mscolnick** [comment]
Just to be clear - you want a full width chart (or responsive) with the tabs centered above the charts? 

The tabs themselves don't support centering - calling `tabs.center()` or `mo.center(tabs)` will center the tabs and its content. So even if you get the chart back to full width (e.g. with `.style({"width": "100%"})`), the tabs are back to left-aligned. 

1) We could support aligning the tabs themselves within their container (e.g. alignment along it's content)
2) You can separate the tabs from the plots

```python
import marimo

__generated_with = "0.3.9-dev8"
app = marimo.App(width="full")


@app.cell
def __():
    import marimo as mo
    import pandas as pd
    import plotly.express as px
    return mo, pd, px


@app.cell
def __(mo):
    mo.md("# Issue 1064")
    return


@app.cell
def __(px):
    plot1 = px.scatter(x=[0, 1, 4, 9, 16], y=[0, 1, 2, 3, 4])
    plot2 = px.scatter(x=[2, 3, 6, 11, 18], y=[2, 3, 4, 5, 6])
    return plot1, plot2


@app.cell
def __(mo):
    tabs = mo.ui.tabs(
        {
            "💾 Tab 1": "",
            "💾 Tab 2": "",
        }
    )
    return tabs,


@app.cell
def __(mo, plot1, plot2, tabs):
    def render_tab_content():
        if tabs.value == "💾 Tab 1":
            return plot1
        elif tabs.value == "💾 Tab 2":
            return plot2
        else:
            return ""


    mo.vstack([tabs.center(), render_tab_content()])
    return render_tab_content,


if __name__ == "__main__":
    app.run()
```

https://marimo.app/l/gb4fnc
