### ISSUE TITLE
Add logarithmic scale support for Slider

### ISSUE THREAD

**Issue by AsgerJ95** [marimo-team/marimo#1065]
### Description

Log scale Slider: volume, voice pitch, voice speed, etc.

### Suggested solution

Would be great to see log10 scale support working.

### Alternative

A slider with values in dB, which is represented linearly, then read the selected value x and calculate the power afterwards.

**Comment by mscolnick** [comment]
I think a more long-term solution would just allowing custom `steps` and you can create the log scale in python.

We use [Radix slider](https://www.radix-ui.com/primitives/docs/components/slider) which does not support non-linear steps. When we add this feature, 
1) we can make do some stuff under the hood to make `min=0, max=steps.length`, and convert `value=steps[idx]`
2) we can to switch to [Ranger](https://tanstack.com/ranger/latest/docs/framework/react/api/custom-steps) which does support custom steps.
