### ISSUE TITLE
Column-major tables

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1080]
`mo.ui.table` expects row-oriented data, which works well in many but not all contexts. In ML and other data applications, data is often stored in columnar formats (parquet, arrow, ...).

We should support columnar data in `mo.ui.table`. A simple way to get started would be to support `pyarrow.Table`. Selection on the frontend would be on columns instead of rows. 

- [x] Support pyarrow tables
- [ ] Add an option to select by column instead of row

**Comment by mscolnick** [comment]
Going to close this as we support pyarrow now. We can re-open if column selection is requested
