### ISSUE TITLE
Matplotlib interactive plot in grid mode has extremely long white space

### ISSUE THREAD

**Issue by KristofPusztai** [marimo-team/marimo#1088]
### Describe the bug

When trying to edit an app in grid mode with a matplotlib plot in interactive mode, there's an extremely long white space that makes adding and editing these interactive plots in grid mode almost impossible.

Without interactive mode (excluding the mo.mpl.interactive call), the plot is shown as intended.

Example video of the issue:
[https://github.com/marimo-team/marimo/assets/52759282/5563b6fd-9ce1-446c-97d9-b178ee9e1799](https://github.com/marimo-team/marimo/assets/52759282/5563b6fd-9ce1-446c-97d9-b178ee9e1799)

### Environment

{
  "marimo": "0.3.9",
  "OS": "Darwin",
  "OS Version": "23.4.0",
  "Processor": "i386",
  "Python Version": "3.9.19",
  "Binaries": {
    "Browser": "123.0.6312.107",
    "Node": "v20.11.1"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.4.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.3.0"
  }
}

### Code to reproduce

```python
data.plot.bar()
 
mo.mpl.interactive(plt.gca())
```

**Comment by mscolnick** [comment]
This should be fixed by https://github.com/marimo-team/marimo/pull/1087 which just merged, but not released yet.

**Comment by akshayka** [comment]
@KristofPusztai can you let us know if you're still experiencing this on the latest version of marimo? Just released. If not, we'll close this issue.

**Comment by KristofPusztai** [comment]
Yup it is fixed, closing issue
