### ISSUE TITLE
Not able to deploy marimo app with docker with version 0.3.0 or higher

### ISSUE THREAD

**Issue by TobiasEnergyMachines** [marimo-team/marimo#1093]
### Describe the bug

Hi,

I am following this [tutorial]( https://docs.marimo.io/guides/deploying/deploying_docker.html) and I am not able to run the marimo app in a dockerfile when the marimo version is 0.3.0 or higher. I have tested the following versions:

Working with:
0.2.5
0.2.9

Not working with:
0.3.0
0.3.1
0.3.2
0.3.3
0.3.9
0.3.10

The http://localhost:8080/ looks like this:

![image](https://github.com/marimo-team/marimo/assets/157477515/421a3f46-6b0b-4185-b8ac-0df2babf50e7)

### Environment

Have test with the following python-image versions:
3.9-slim (as in tutorial)
3.10-slim
3.11-slim
3.12-slim

### Code to reproduce

[tutorial]( https://docs.marimo.io/guides/deploying/deploying_docker.html)

**Comment by akshayka** [comment]
Closing this because I believe Myles' suggestion to be correct. Feel free to re-open if you still have issues.

**Comment by TobiasEnergyMachines** [comment]
Using   `--host "0.0.0.0` gives a different error message:

<img width="797" alt="image" src="https://github.com/marimo-team/marimo/assets/157477515/a6c57806-df01-4792-83c9-c03441d7828e">


+++++ Marimo app:
```
import marimo

__generated_with = "0.3.12"
app = marimo.App()


@app.cell
def __():
    import marimo as mo

    return (mo,)


@app.cell
def __(mo):
    mo.md("# This is my test app")
    return


if __name__ == "__main__":
    app.run()
```


+++++ Dockerfile:
```
FROM python:3.12-slim
WORKDIR /app

COPY --link requirements.txt .
RUN pip install -r requirements.txt

COPY --link app.py .

EXPOSE 8080

CMD [ "marimo", "run", "app.py", "--host", "0.0.0.0", "-p", "8080"]
```

**Comment by mscolnick** [comment]
@TobiasEnergyMachines, what commands are you running to build your Docker container? For reference, this is what I did on my computer and it worked:

0. I added `# syntax=docker/dockerfile:1.4` to the top of my Dockerfile since `--link` in a newer feature
1. `docker build -t my_app .`
2. `docker run -p 8080:8080 -it my_app`
3. Visit http://localhost:8080/

**Comment by TobiasEnergyMachines** [comment]
Thanks for getting back on quick notice. 

I am using those exact docker commands and now also added the syntax line to the top of the dockerfile. 
However the issue persists for me. 
I can also add that I have checked on chrome and edge. 
And again if marimo < 0.3.0 then it works.

**Comment by mscolnick** [comment]
@TobiasEnergyMachines, can you share the output of your terminal when you run `docker run -p 8080:8080 -it my_app`?

In your original, you are visiting `http://0.0.0.0:8080/`- can you visit http://localhost:8080/ instead?

**Comment by TobiasEnergyMachines** [comment]
> @TobiasEnergyMachines, can you share the output of your terminal when you run `docker run -p 8080:8080 -it my_app`?
> 
> In your original, you are visiting `http://0.0.0.0:8080/`- can you visit http://localhost:8080/ instead?

Yes it works - thank you for clearing that up
