### ISSUE TITLE
Reopen: Not able to deploy marimo app with docker with version 0.3.0 or higher

### ISSUE THREAD

**Issue by TobiasEnergyMachines** [marimo-team/marimo#1123]
### Describe the bug

Reopening issue:
https://github.com/marimo-team/marimo/issues/1093#issuecomment-2051130250

### Environment

marimo >= 0.3.0

**Comment by mscolnick** [comment]
Not sure if https://github.com/marimo-team/marimo/issues/1093 was not Re-openable for you (let me know if it was locked), but I re-opened it, so we can keep context to one thread

**Comment by TobiasEnergyMachines** [comment]
Thank you.
Yes I am not able to reopen an issue.
