### ISSUE TITLE
Go to cell defining something

### ISSUE THREAD

**Issue by Eloitor** [marimo-team/marimo#1126]
### Description

Quickly go to the cell defining a variable or a function.

### Suggested solution

- An item in the right click menu.
- A keyboard shortcut.

**Comment by robmck1995** [comment]
I didn't factor https://github.com/marimo-team/marimo/pull/1365 in when making these changes.

Here's the plan I used to make the change:
https://glide.agenticlabs.com/sharing?userId=65bae76b7fbfb1c20ac1f3b8&taskId=ghM1mqX

Do we think this needs to be updated based on the new functionality of `goToDefinition`? It looked like from my testing that `goToDefinition` just focused on the first instance of the variable within the cell, not across cells?
