### ISSUE TITLE
Detect if notebook is running as a script

### ISSUE THREAD

**Issue by twrightsman** [marimo-team/marimo#1138]
### Description

Configure notebook behavior depending on if it is running interactively or non-interactively. For example, run the analysis on a smaller subset of data if running interactively or on the full dataset if running as a script.

### Suggested solution

There is a private API added in https://github.com/marimo-team/marimo/commit/a08c27f425256121fc7718e5d42bb0256b2429f1, but there is no public API that I am aware of to detect if running as a script.

Perhaps something like `mo.context.runtime_type() == mo.context.runtime.SCRIPT`, as an enum example.

### Alternative

https://github.com/marimo-team/marimo/issues/1137 would sidestep this, as behavior could be configured for scripts by passing different command-line options.

**Comment by akshayka** [comment]
Thanks for opening these issues.

I like #1137 -- that's something that we do plan to support. Should we close this in favor of #1137?

**Comment by twrightsman** [comment]
> Should we close this in favor of https://github.com/marimo-team/marimo/issues/1137?

That sounds reasonable. Thanks for looking!

**Comment by akshayka** [comment]
Decided to implement this — easy and valuable. Thanks for the suggestion!
