### ISSUE TITLE
Re-arrange multiple cells in edit view

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1152]
### Description

The ability to move multiple cells in the editor at a time.

### Suggested solution

Select multiple cells via box selection (mouse click and drag), then drag to move the cells. Selected cells could also be moved with the usual keyboard shortcuts.

### Alternative

- Similar functionality, but in the minimap.
- If #1085 is implemented, a drag handle for sections demarcated by markdown headers

### Additional context

https://discord.com/channels/1059888774789730424/1059888774789730427/1230175318220865636

**Comment by mscolnick** [comment]
If someone does pick this up, using one of the helper panels (maybe the Dependency Viewer Panel / mini-map) instead of the main view may easier to rearrange the cells.

**Comment by mscolnick** [comment]
Original ask: 
| I have a notebook that's structured in sections/subsections using markdown headers, and i would like to reorder the sections

This was resolved by https://github.com/marimo-team/marimo/pull/1826
