### ISSUE TITLE
plotly (and other widgets) selections and zoom should be possible to keep between cell updates

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#1161]
### Description

If I have a cell with a plotly figure, I then select in it, and/or zoom in it and then the cell is rerun, the selection and zoom are lost.

This may be a good default (or not), but I would like optionally to keep the selection and zoom.

This is not trivial since rerunning the cell may produce a totally different plot for which the selection/zoom would not make sense.

This is not plotly specific, but will need specific implementation for each widget.

### Suggested solution

I propose a best effort that is controllable with a switch i.e. API wise:

```python
import marimo as mo
import plotly.express as px
fig = px.scatter(x=[1,2,3,4,5,6], y=[1,2,3,2,3,4])

mo.ui.plotly(fig, persist_user_modifications=True)
# or maybe just "persist". suggestions welcome.
```

Which will examine the previous instance and copy the selection & zoom over to the new.

What do you think?

I am not familiar enough with the code base yet to do this, but given pointers I could try!

### Alternative

This can be done right now by wrapping the plotly object I guess, as long as it has the zoom / select state on it.

### Additional context

Here is an example of why this would be wanted:

[Screencast from 2024-04-18 09-55-41.webm](https://github.com/marimo-team/marimo/assets/103570620/0fe63d5e-48cb-409a-8447-9f6c7b53e0c0)

**Comment by mscolnick** [comment]
@alefminus - i think you can all `fig.update_layout(dragmode=<value>` and value can be `dragmode: "zoom" | "pan" | "select" | "lasso" | "orbit" | "turntable" | False`
https://plotly.com/python/reference/layout/#layout-dragmode
