### ISSUE TITLE
Autoreload fails for modules that import certain third-party modules

### ISSUE THREAD

**Issue by anibali** [marimo-team/marimo#1174]
### Describe the bug

Python files that include certain third-party modules (e.g., `spacy`, `torch`, `pandas`) fail to autoreload in marimo.

I've tracked the issue down to the function `_depends_on` in `module_watcher.py`: https://github.com/marimo-team/marimo/blob/main/marimo/_runtime/reload/module_watcher.py#L49

A workaround is to explicitly exclude the problematic modules when constructing the ModuleFinder instance, e.g. `ModuleFinder(excludes=["spacy", "torch", "pandas"])`. It would be great if there was some way for marimo to automatically exclude all non-project modules.

### Environment

{
  "marimo": "0.4.1",
  "OS": "Linux",
  "OS Version": "6.1.0-20-amd64",
  "Processor": "",
  "Python Version": "3.10.13",
  "Binaries": {
    "Browser": "124.0.6367.60",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.4.0",
    "jedi": "0.19.1",
    "markdown": "3.5.2",
    "pymdown-extensions": "10.7",
    "pygments": "2.17.2",
    "tomlkit": "0.12.3",
    "uvicorn": "0.27.1",
    "starlette": "0.37.1",
    "websocket": "missing",
    "typing-extensions": "4.9.0",
    "black": "24.2.0"
  }
}

**Comment by akshayka** [comment]
>  It would be great if there was some way for marimo to automatically exclude all non-project modules.

This is a good idea. Perhaps we can check if the module is in site-packages, and if so ignore.

**Comment by akshayka** [comment]
@anibali , this will be released in the next version of marimo, maybe today. Thanks for the bug report and suggestion!
