### ISSUE TITLE
Marimo async raising "ValueError: signal only works in main thread of the main interpreter"

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#1175]
### Describe the bug

I'm trying to run some async code whenever I press a button. Instead of running the code, marimo throws an error

"ValueError: signal only works in main thread of the main interpreter".

I should add the error only shows for "marimo run ...", while it works for marimo edit.

### Environment

{
  "marimo": "0.4.1",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "123.0.6312.123",
    "Node": "v14.16.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.9.0",
    "black": "24.3.0"
  }
}

### Code to reproduce

Here's a simple example that throws the error when you press the button "run":

```python
 
import marimo
 
__generated_with = "0.4.1"
app = marimo.App()
 
 
@app.cell
def __():
    import marimo as mo
    import asyncio
    return asyncio, mo
 
 
@app.cell
def __(asyncio):
    async def run_async_generator():
        await asyncio.sleep(1)
        yield "hello"
        await asyncio.sleep(2)
        yield "world"
    return run_async_generator,
 
 
@app.cell
def __(mo):
    button = mo.ui.button(label="run")
    button
    return button,
 
 
@app.cell
async def __(button, run_async_generator):
    if button:
        async for s in run_async_generator():
            print(s)
    return s,
 
 
if __name__ == "__main__":
    app.run()
 
```

**Comment by mrdobalina2k** [comment]
In fact, this doesn't work on the spinner example on the [documentation](https://docs.marimo.io/api/status.html#spinner) either:

```python

import marimo

__generated_with = "0.4.1"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    rerun = mo.ui.button("Rerun")
    rerun
    return rerun,


@app.cell
async def __(mo, rerun):
    import asyncio
    rerun
    with mo.status.spinner(title="Loading...") as _spinner:
      await asyncio.sleep(1)
      _spinner.update("Almost done")
      await asyncio.sleep(1)
      _spinner.update("Done")
    return asyncio,


if __name__ == "__main__":
    app.run()

**Comment by mscolnick** [comment]
just adding additional context for others: this works on `mac os`, so might be a windows issue

**Comment by mrdobalina2k** [comment]
I tried this on wsl2 as well.. same issue.

```
{
  "marimo": "0.4.1",
  "OS": "Linux",
  "OS Version": "5.15.146.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.12.1",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "missing",
    "black": "24.3.0"
  }
}

**Comment by mscolnick** [comment]
Sorry I missed that this only shows up in `run` mode as well (I tried to repro while in edit). Thanks for reporting
