### ISSUE TITLE
plotly.zoom / plotly.layout reactivity (i.e. mandelbrot)

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#1177]
### Description

I want to have a plot, and then zoom in and have another calculation triggered off of it.

I don't have a specific use case, so a made up one would be a mandelbrot set or a map - the trigger allows you to refine the rendered image in the same plot. This would apply to plotly.

### Suggested solution

Expose the current layout the same was as the current selection is.

**Comment by mscolnick** [comment]
I actually just added this state to the frontend - we can expose this to the python. im not sure the best API, but if you don't want to wait to use this, you can unsafely call `_selection_data` on the `mo.ui.plotly()` object

**Comment by mscolnick** [comment]
Good question - we have mo.output.replace and mo.output.append https://docs.marimo.io/api/outputs.html#outputs

You can update the ui if you are still in a loop or long running process in the same cell.

**Comment by mscolnick** [comment]
Oh awesome, this is a great example. Thanks for sharing
