### ISSUE TITLE
cell deletion undo stack

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#1192]
### Description

After deleting a cell I'd like to undo it.

### Suggested solution

Keep an undo stack of operations at the cell level - this is not trivial since it is not clear how it is affected by other operations. At the cell level I guess also move up/down topmost/bottommost need to be in it.

**Comment by mscolnick** [comment]
When you delete a cell, there is an undo button in the bottom right to undo it (acts like a stack). Is that what you are talking about?

**Comment by akshayka** [comment]
The hotkey is ctrl-shit-z, ctrl-z undoes edits to specific cells.

**Comment by mscolnick** [comment]
@alefminus there actually isn't a hotkey at the moment. It was `ctrl-shift-z` but I think that conflicted with undo delete of text.  We can consider adding it back or incorporating it in just `ctrl-z`. 

in the meantime, i've added this to the command palette and a toast in #1209
