### ISSUE TITLE
View Marimo progress bars in terminal

### ISSUE THREAD

**Issue by twrightsman** [marimo-team/marimo#1194]
### Description

See any `mo.status.progress_bar`s also in the terminal, like `tqdm`.

### Suggested solution

Not quite sure how this would be implemented :slightly_smiling_face:

**Comment by mscolnick** [comment]
we don't really have a pattern internally with our plugins/utils for displaying for UI vs for the terminal. 

you can build this in your own notebook, using [mo.running_in_notebook](https://docs.marimo.io/api/miscellaneous.html#marimo.running_in_notebook). 

You could do something like:

```python
my_list = mo.status.status.progress_bar(list)
if mo.running_in_notebook():
  my_list = tqdm(my_list)

for i in my_list:
```

(i havent tested the above, so might have some typos)

If you have a good pattern for this, it would be great to bring this back into core (if you are open to contributing it)

**Comment by mscolnick** [comment]
Going to close this as the above snippet should solve this
