### ISSUE TITLE
all on_change handlers in an dynamic array only refer to the last registered handler

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#1202]
### Describe the bug

When doing dynamic elements, it is [recommended](https://github.com/marimo-team/marimo/issues/647) to use the mo.ui.array element, and assign the values to a global variable. However, when assigning on_change handlers to each element within the array, it seems all array elements are only assigned the last element on_change handler.

### Environment

{
  "marimo": "0.4.2",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "123.0.6312.123",
    "Node": "v14.16.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.9.0",
    "black": "24.3.0"
  }
}

### Code to reproduce

Here's a code to reproduce the issue:

try to change the values in elements 1-9 and observe how the console prints "element 9" always, although I'm passing the element index through the lambda function.

```python
import marimo
 
__generated_with = "0.4.2"
app = marimo.App()
 
 
@app.cell
def __():
    import marimo as mo
    return mo,
 
 
@app.cell
def __(mo):
    def on_change_element(i: int, v: float):
        print("element", i)
        print("value", v)
    elements = [mo.ui.number(start=0, stop=10, value=0, on_change=lambda v: on_change_element(i, v)) for i in range(10)]
    return elements, on_change_element
 
 
@app.cell
def __(elements, mo):
 
 
    array=mo.ui.array(elements)
    return array,
 
 
@app.cell
def __(array):
    array
    return
 
 
if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
This is because in Python, closures are late-binding. This means that every closure (lambda) you make is bound to `i==9`. This isn't a bug in marimo but rather a quirk in Python.

I can add this to our FAQ in our docs. You can learn more about this quirk of Python here: https://github.com/marimo-team/marimo/discussions/613#discussioncomment-8238141

**Comment by mrdobalina2k** [comment]
that's very interesting, so following your suggestion, I can do this instead:

```python

def on_change_element_factory(i):
    def on_change_element(v: float):
        print("element", i)
        print("value", v)
    return on_change_element
elements = [mo.ui.number(start=0, stop=10, value=0, on_change= on_change_element_factory(i)) for i in range(10)]
