### ISSUE TITLE
"String contains an invalid character" when running leafmap.foliumap

### ISSUE THREAD

**Issue by fuenfundachtzig** [marimo-team/marimo#1241]
### Describe the bug

The code below gives the following error:
![image](https://github.com/marimo-team/marimo/assets/8006302/3b4ab1fc-c34c-41f8-8aaf-e6c692f3ef86)

### Environment

{
  "marimo": "0.4.5",
  "OS": "Linux",
  "OS Version": "5.4.0-176-generic",
  "Processor": "x86_64",
  "Python Version": "3.8.10",
  "Binaries": {
    "Browser": "124.0.6367.60",
    "Node": "v18.20.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "6.4.0",
    "jedi": "0.18.0",
    "markdown": "3.5",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.8.0",
    "black": "23.3.0"
  }
}

### Code to reproduce

import leafmap.foliumap as leafmap
m = leafmap.Map(center=(40, -100), zoom=4)
m

**Comment by mscolnick** [comment]
I have a fix out for it https://github.com/marimo-team/marimo/pull/1243, should get this released to you today
