### ISSUE TITLE
Open notebook from file panel no longer works

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1244]
### Describe the bug

Clicking the "Open Notebook" From the file panel no longer works if the app was opened with home.

Currently prompts to close the current notebook (it could just start a new session), and restarts the current kernel without changing the notebook

Could be an opportunity to surface notebooks in file tab as well to make navigation a bit easier

### Environment

0.4.5 HEAD

### Code to reproduce

workflow

**Comment by mscolnick** [comment]
Thanks for finding this - I agree, i thikn we can make this better now that we can have multiple notebooks running at the same time. Ill look into this today

**Comment by mscolnick** [comment]
I have the fix here: https://github.com/marimo-team/marimo/pull/1246

But i didnt change anything about the UX and showing more stuff from the homepage. I didnt want to block this fix on a probably larger effort. 

------

Will move the better navigation conversation to the discord
