### ISSUE TITLE
VSCode extension 

### ISSUE THREAD

**Issue by aangelopoulos** [marimo-team/marimo#1260]
### Describe the bug

If you close and quickly reopen a VSCode embedded browser tab, it will display the following error message. Only after a minute or so of having the tab closed does it allow you to reconnect to the session.

<img width="634" alt="image" src="https://github.com/marimo-team/marimo/assets/25397074/3601d656-9e5c-4cee-8d64-266b5dd54b10">

### Environment

{
  "marimo": "0.4.7",
  "OS": "Linux",
  "OS Version": "6.5.0-4-amd64",
  "Processor": "x86_64",
  "Python Version": "3.9.19",
  "Binaries": {
    "Browser": "--",
    "Node": "v16.20.2"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "6.0.0",
    "jedi": "0.18.2",
    "markdown": "3.6",
    "pymdown-extensions": "10.8",
    "pygments": "2.14.0",
    "tomlkit": "0.12.4",
    "uvicorn": "0.22.0",
    "starlette": "0.27.0",
    "websocket": "missing",
    "typing-extensions": "4.9.0",
    "black": "24.4.2"
  }
}

### Code to reproduce

This is a VSCode extension issue. I am using extension v0.1.13.

**Comment by mscolnick** [comment]
How quickly are you closing/reopening? Are you using a keyboard shortcut? I am trying to repro (~3 seconds), and cannot repro myself

**Comment by aangelopoulos** [comment]
I'm not using a keyboard shortcut. All I'm doing is

1. Open `visualize.py`, my marimo notebook
2. Click the lightning bolt, then "start marimo server (edit)"
3. The embedded browser opens, and things start running.
4. I close the embedded browser by clicking the x. 
5. I go back to the lightning bolt and click "Open in embedded browser"

I just checked again, and this causes the error on my system.

**Comment by mscolnick** [comment]
Thanks for this info - it seems like it is not closing the previous connection for whatever reason. I will continue to investigate

**Comment by mscolnick** [comment]
@aangelopoulos - we've made various improvements to the vscode plugin over the past week. can you give this another try and let us know if you experience this issue?

**Comment by mscolnick** [comment]
Going to close this, please re-open if you still hit this

**Comment by aangelopoulos** [comment]
Thanks Myles -- I'll get to this when I get a chance!

Best,
Anastasios Angelopoulos
https://people.eecs.berkeley.edu/~angelopoulos/
