### ISSUE TITLE
Dedent breaks islands client side

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1266]
### Describe the bug

See:
https://dmadisetti.github.io/quarto-marimo/ui.html

breaks because values like:
```
def fn(x):
    pass
```

get turned into
```
def fn(x):
pass
```

there's the `raw` flag on the non-reactive side. Couple ways to go about this, I include 2 in the relevant PR:

 1. propagating the raw flag to the client
 2. just removing dedent client side

### Environment

islands head

### Code to reproduce

```python
generator.add_code("""def fn():
    pass
""", raw=True)
```

works server side but breaks client side

**Comment by mscolnick** [comment]
I can fix this

**Comment by mscolnick** [comment]
Nvm you already got it, thanks!
