### ISSUE TITLE
unsanitized html fragment causing createElement failure

### ISSUE THREAD

**Issue by niv-gv** [marimo-team/marimo#1270]
### Describe the bug

Opening a notebook resulted in "Something went wrong" message with the text:

```
Failed to execute 'createElement' on 'Document': The tag name provided ('core::iter::adapters::genericshunt<i,r') is not a valid name.
```

It seems the left angular bracket there is being used as a tag name, or another character is invalid. The string itself is produced by the panic of a polars call, but I don't believe it is material to the bug itself - marimo should handle any python output.

I'll try to create a minimal reproducer, reporting hoping the error itself might be enough.

marimo 0.4.7

### Environment

{
  "marimo": "0.4.7",
  "OS": "Linux",
  "OS Version": "6.8.7-300.fc40.x86_64",
  "Processor": "",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.12.2"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.11.0",
    "black": "24.4.2"
  }
}

### Code to reproduce

none yet.

**Comment by niv-gv** [comment]
I do have a stack trace from the developer console but it is the minified / obfuscated version so not sure it helps:
```javascript
2index-BSODrr5r.js:46 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('core::iter::adapters::genericshunt<i,r') is not a valid name.
    at QRt (http://crete:2718/assets/index-BSODrr5r.js:46:16897)
    at h6e (http://crete:2718/assets/index-BSODrr5r.js:46:40391)
    at O6e (http://crete:2718/assets/index-BSODrr5r.js:46:40140)
    at CRt (http://crete:2718/assets/index-BSODrr5r.js:46:40001)
    at a7 (http://crete:2718/assets/index-BSODrr5r.js:46:39849)
    at zre (http://crete:2718/assets/index-BSODrr5r.js:46:36178)
    at u6e (http://crete:2718/assets/index-BSODrr5r.js:46:35117)
    at S (http://crete:2718/assets/index-BSODrr5r.js:31:1548)
    at MessagePort.D (http://crete:2718/assets/index-BSODrr5r.js:31:1907)
```

**Comment by mscolnick** [comment]
thanks for reporting - ill look into this. if/when you can send a repro with code, that would be super helpful - even if it is partial code.

**Comment by mscolnick** [comment]
This sounds likes its coming from `html-react-parser`. And we might not be sanitizing the error coming from polars (or from anywhere), and polars just happens to output a tag-looking text. This is helpful

**Comment by mscolnick** [comment]
What browser are you using? This doesnt fail for me on chrome/safari. It could be an OS thing as well. Regardless, we should sanitize this to be safe

**Comment by mscolnick** [comment]
I have a fix now https://github.com/marimo-team/marimo/pull/1275

Thanks for the details issue - it helped in tracking this down

**Comment by mscolnick** [comment]
I added a command to build from source unminified - I will merge this into `main`: https://github.com/marimo-team/marimo/pull/1287

```
NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=development make fe -B
```

**Comment by mscolnick** [comment]
This looks pretty much expected (minus the missing "unamed" text) 

Those messages from React are just warnings and actually expected. React doesn't support custom elements (yet, next release they will). 

But the render should no longer fail on an unnamed element.

**Comment by mscolnick** [comment]
We can/should sanitize `<` and `>` so `unamed` will appear, as it should. But quickly adding a sanitize on the way out in the backend does make other colorized stacktrace appear so i need to investigate the best way to do that

**Comment by mscolnick** [comment]
I dont think it's the cleanest, but this will sanitize it correct https://github.com/marimo-team/marimo/pull/1297

**Comment by mscolnick** [comment]
Yea that's a known warning tht fixing will break some interactions so we leave it.
