### ISSUE TITLE
Add typo check to make py-test 😢

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1316]
### Description

I guess I can't spell and I keep triggering it

### Suggested solution

Just another make rule

### Alternative

I learn to spell!

**Comment by mscolnick** [comment]
I would like to actually add pre-commit, that is optional and only contains fast check

**Comment by akshayka** [comment]
This is typically what's used to configure pre-commit for Python projects: https://pre-commit.com/index.html

An optional pre-commit with fast checks sounds good to me!
