### ISSUE TITLE
ui.dataframe transforms incorrectly assume string column names

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1319]
### Describe the bug

Applying a transform to a Pandas dataframe with the default integer column index, using `ui.dataframe`, fails:

![image](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/c53b7b24-61b0-4fe5-a27b-a5f99412f032/7b1d090b-f156-4cef-a44b-727d8fa3e31d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS9jNTNiN2IyNC02MWIwLTRmZTUtYTI3Yi1hNWY5OTQxMmYwMzIvN2IxZDA5MGItZjE1Ni00Y2VmLWE0NGItNzI3ZDhmYTNlMzFkIiwiaWF0IjoxNzE0OTI2MDQzLCJleHAiOjMzMjg1NDg2MDQzfQ.XrWW2HZW4n4AH0aoqGsQ9W8LF7qenHNZZIP9jZwdhWE "=809x")

because the generated code assumes that the indices are strings:

```
df_next = df
df_next = df_next[df_next["2"] > 0]
```

whereas it should be

```
df_next = df
df_next = df_next[df_next[2] > 0]
```

### Environment

{
  "marimo": "0.4.11",
  "OS": "Darwin",
  "OS Version": "22.5.0",
  "Processor": "arm",
  "Python Version": "3.9.19",
  "Binaries": {
    "Browser": "124.0.6367.119",
    "Node": "v21.5.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "5.10.2",
    "jedi": "0.19.1",
    "markdown": "3.4.1",
    "pymdown-extensions": "9.9.2",
    "pygments": "2.17.2",
    "tomlkit": "0.12.1",
    "uvicorn": "0.27.0",
    "starlette": "0.37.1",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "23.9.1"
  }
}

### Code to reproduce

```
import marimo

__generated_with = "0.4.11"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __():
    import pandas as pd
    return pd,


@app.cell
def __():
    import random


    def row(columns):
        return [
            "".join(random.choices("abcdefghikjlmnopqrstuvwxyz", k=8)),
            "".join(random.choices("abcdefghikjlmnopqrstuvwxyz", k=8)),
        ] + [random.randint(1000, 100000) for i in range(columns - 2)]
    return random, row


@app.cell
def __(pd, row):
    df = pd.DataFrame([row(3) for _ in range(10)])
    return df,


@app.cell
def __(df, mo):
    uidf = mo.ui.dataframe(df)
    uidf
    return uidf,


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
Fixed by #1322
