### ISSUE TITLE
On resume session (browser refresh), execution time is lost

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1330]
### Describe the bug

From @delennc: reconnecting to an active notebook, you lose the info on how long it took to run each cell.

### Environment

{
  "marimo": "0.4.10",
  "OS": "Linux",
  "OS Version": "6.5.0-27-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "123.0.6312.122",
    "Node": "v18.13.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "6.1.0",
    "jedi": "0.19.0",
    "markdown": "3.4.4",
    "pymdown-extensions": "10.3",
    "pygments": "2.16.1",
    "tomlkit": "0.12.0",
    "uvicorn": "0.24.0.post1",
    "starlette": "0.27.0",
    "websocket": "missing",
    "typing-extensions": "4.8.0",
    "black": "23.3.0"
  }
}

**Comment by mscolnick** [comment]
this is because we keep track of the execution time on the frontend. we should move this to the backend into the SessionView (and pass it down)

**Comment by wasimsandhu** [comment]
Grabbing this one.
