### ISSUE TITLE
Home doesn't detect new files

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1348]
### Describe the bug

I think home is a great start for a splash page- I've been using it more.
But it doesn't detect new files. It looks like it polls running_notebooks (you could sneak the info in there), but also why not websockets for pubsub

### Environment

markdown experimental branch

### Code to reproduce

Create a new file in the directory home is running

**Comment by mscolnick** [comment]
I can add a refresh button above the notebooks. Searching can be expensive (depending on the directory) and websockets is probably overkill. Thoughts?

**Comment by dmadisetti** [comment]
I don't think WebSockets are totally overkill if there's potential for home interaction to expand. But yea, the engineering effort for notebook status alone is not worth it.

I think a refresh button is what colab and jupyter allow for in their sidebars

**Comment by dmadisetti** [comment]
Toggling "Include Markdown" works as a workaround rn

**Comment by mscolnick** [comment]
https://github.com/marimo-team/marimo/pull/1759 will fix this - it adds Refresh button (although, its not shown in the screenshot)
