### ISSUE TITLE
Can't convert Jupyter notebook that uses await on marimo.io/convert

### ISSUE THREAD

**Issue by dpaleka** [marimo-team/marimo#1364]
### Describe the bug

I open https://marimo.io/convert, paste, click "edit in marimo", and it does"

> **Something went wrong**
> ```
> Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 393, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<exec>", line 10, in <module> File "/lib/python3.11/site-packages/marimo/_pyodide/pyodide_session.py", line 91, in create_session app_file_manager = AppFileManager(filename=filename) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/marimo/_server/file_manager.py", line 28, in __init__ self.app = self._load_app(self.path) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/marimo/_server/file_manager.py", line 91, in _load_app app = codegen.get_app(path) ^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/marimo/_ast/codegen.py", line 220, in get_app spec.loader.exec_module(marimo_app) File "<frozen importlib._bootstrap_external>", line 936, in exec_module File "<frozen importlib._bootstrap_external>", line 1074, in get_code File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/marimo/notebook.py", line 191 ) = await retrieve_summarize_and_rank_articles( SyntaxError: 'await' outside async function 
>```

### Environment

Whatever is on `marimo.app`

**Comment by mscolnick** [comment]
Any chance you can link a minimal repro? I was able to add `await` to a cell that would get converted. I am also upgrading it (from 0.3.3 -> 0.5.2), so maybe there was an edge case with `await` we didnt support.

**Comment by dpaleka** [comment]
Now it works with my notebook. I guess it was the upgrade.

I mean, the _notebook_ doesn't work, because I forgot I import some internal packages, but marimo works as intended. The notebook looks like a notebook, it raises correct errors like `An ancestor raised an exception (ModuleNotFoundError)`, etc.

**Comment by mscolnick** [comment]
sweet!
