### ISSUE TITLE
Split Cell Hotkey

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1372]
### Description

Many of our users have asked for the ability to split cells using a hotkey. This would be a great first issue.

### Suggested solution

A hotkey to split a cell at the current line into two cells, similar to Jupyter. Maybe `Ctrl+Shift+-`.

**Comment by robmck1995** [comment]
Implementation created with the help of Glide. Plan below, there are a few discrepancies that were resolved locally.

https://glide.agenticlabs.com/sharing?userId=65bae76b7fbfb1c20ac1f3b8&taskId=miIvJdg
