### ISSUE TITLE
Callout on mo.sidebar causes browser to freeze in edit mode

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#1384]
### Describe the bug

Just playing around with the new mo.sidebar component. I tried to use a public HTML method (callout), which caused the browser to completely stop responding, and I have to close the tab and stop marimo.

### Environment

{
  "marimo": "0.5.2",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "123.0.6312.123",
    "Node": "v14.16.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.9.0",
    "black": "24.3.0"
  }
}

### Code to reproduce

```python

import marimo

__generated_with = "0.5.2"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    mo.sidebar(
        [
            mo.md("World"),
            mo.ui.switch()
        
        ]
    ).callout("warn")
    return


@app.cell
def __(mo):
    mo.md("Hi")
    return


if __name__ == "__main__":
    app.run()

**Comment by mscolnick** [comment]
oh interesting - we should probably just disable the fluid API (callout, center, styles, etc) for sidebar, or wrap its inner contents in them
