### ISSUE TITLE
Possibility of redirecting error messages to browser console after opting in

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#1403]
### Description

I'm hosting an application on a remote server, that I don't have direct access to. For whatever reason my application behaves differently remotely than locally, as some of the UI components aren't rendering. To find out why, I would very much like to see the error messages, but these are hidden away when the application runs.

### Suggested solution

I propose a feature in which the user can opt in by setting an env variable like MARIMO_DEBUG=True, which causes stdout/stderr to be routed to the browser console. All output should somehow contain metadata about the cell, from which they are generated, in order to help debug components.

### Alternative

The alternative is to have direct access to a server on which the application is hosted. This is not always possible.

**Comment by metaboulie** [comment]
You can use `marimo run notebook.py --redirect-console-to-browser` to redirect error messages to browser console in run mode after the next release of marimo 🙂
