### ISSUE TITLE
no undo for split cell

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#1408]
### Describe the bug

1. Split cell using the new (awesome) shortcut Ctrl+'
2. Press Ctrl-Z

Nothing happens

### Environment

```json
{
  "marimo": "0.6.0",
  "OS": "Linux",
  "OS Version": "6.8.7-300.fc40.x86_64",
  "Processor": "",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.12.2"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.11.0",
    "black": "24.4.2"
  }
}
```

### Code to reproduce

Any cell.

**Comment by mscolnick** [comment]
Our undo (ctrl-z) functionality only works the cell editor. We can add a toast so that you can undo with a button click - and bind the Ctrl-Z to that button.

**Comment by akshayka** [comment]
Thanks for reporting!

> Is it a purely implementation detail, i.e. would you like to have a shared
> undo stack or do you prefer separate stacks?

We prefer separate stacks. Sometimes you want to undo all edits to a cell -- just hold `Ctrl + z` -- without worrying about crossing cell boundaries or bringing back cells you meant to delete.

We can also add a hotkey for undoing actions on the entire cell array, in addition to the toast.

**Comment by wasimsandhu** [comment]
Grabbing this one next 🙂

**Comment by wasimsandhu** [comment]
Completed!

**Comment by wasimsandhu** [comment]
Forgot to test an edge case... if you split a cell, edit cell #1, and then click undo, it does not recreate the original cell's code. 

Additionally, if the toast disappears, your chance to undo the split is gone.

**Comment by mscolnick** [comment]
Fixed by https://github.com/marimo-team/marimo/pull/2018, thanks @wasimsandhu!
