### ISSUE TITLE
Add SymPy equation rendering support such that the ouput is on parity with Jupyter's rendering when using SymPy.

### ISSUE THREAD

**Issue by kamyuen** [marimo-team/marimo#1412]
### Description

There is currently no way to render equations properly when using SymPy. In Jupyter notebook one usually just calls init_printing() at the beginning of a notebook to allow all subsequent output to be rendered in mathematical notation.
Importing SymPy in and calling init_printing() has absolutely no effect and equations are simple output as text.
To see the issue just follow the SymPy documentation for setting up this feature https://docs.sympy.org/latest/tutorials/intro-tutorial/printing.html

### Suggested solution

Since SymPy has multiple fallbacks on how to render the output, it may be a case of initially capturing the resulting MathJax and rendering using Marimo's _md_ function, just a guess.

**Comment by mscolnick** [comment]
In the meantime, you can do this:

```python
from sympy import latex
import marimo as mo

def print_sympy(obj):
    return mo.md(f"""
    \[
    {latex(obj)}
    \]
    """)
```

Playground:  https://marimo.app/l/n2kkic

**Comment by agostof** [comment]
Adding on to the solution by @mscolnick, you can try adding the `_mime_` method to the classes you want to render.
``` python
...
from sympy import Symbol as SymbolSympy
from sympy import Integral as IntegralSympy

class Symbol(SymbolSympy):
    def _mime_(self) -> tuple[str, str]:
         return ("text/html", print_sympy(self).text)

class Integral(IntegralSympy):
    def _mime_(self) -> tuple[str, str]:
        return ("text/html", print_sympy(self).text)
...
x, y, z = symbols('x y z', cls=Symbol)
...
```
Playground: https://marimo.app/l/t1huwf

**Comment by mscolnick** [comment]
@agostof - your patch is quite nice

if you or @kamyuen or anyone else wants to make a contribution to the repo - you can add this to `marimo/_output/formatters`

**Comment by agostof** [comment]
@mscolnick Thanks!

It turns out that patching `sympy.core.basic.Printable` works nicely.
I am adding a [formatter](https://github.com/agostof/marimo/tree/sympy-fmt) and will submit a PR.
