### ISSUE TITLE
Propose a New Pull Request Template for the Repository

### ISSUE THREAD

**Issue by Haleshot** [marimo-team/marimo#1413]
### Description

The current repository lacks a standardized Pull Request (PR) template, which can lead to inconsistent PR submissions and insufficient information for reviewers. 

### Reason for the Proposal:
1. **Consistency**: A PR template ensures that all contributors provide essential information, leading to uniform and easy-to-review PRs.
2. **Clarity**: It helps contributors understand what information is required, reducing the back-and-forth communication between contributors and maintainers.
3. **Efficiency**: By providing a checklist and specific sections for required information, it speeds up the review process.
4. **Quality**: Encourages contributors to adhere to best practices and guidelines, improving the overall quality of contributions.

I intend to submit a PR for this issue with the proposed PR template.

### Suggested solution

Introduce a standardized Pull Request (PR) template to the repository. This template will guide contributors to provide necessary information such as a summary of changes, detailed descriptions, additional context, and a checklist before submission. This will ensure clarity and efficiency in the PR review process.

### Alternative

Just having a set of guidelines or a checklist in the repository's contributing.md file instead of a formal PR template. However, this approach relies on contributors consistently following the guidelines, which may not be as effective as an enforced template in ensuring all necessary information is provided uniformly.

**Comment by mscolnick** [comment]
Fixed in #1413, thanks!
