### ISSUE TITLE
Renaming notebook doesn't change title of tab

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1428]
### Describe the bug

When a notebook is renamed in the editor, its title in the browser tab didn't change. The title should change to reflect the new notebook name.

### Environment

```
{
  "marimo": "0.6.0",
  "OS": "Darwin",
  "OS Version": "22.5.0",
  "Processor": "arm",
  "Python Version": "3.9.19",
  "Binaries": {
    "Browser": "124.0.6367.209",
    "Node": "v21.5.0"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "6.4.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.11.0",
    "black": "23.3.0"
  }
}
```

**Comment by vrtnis** [comment]
Just tried to resolve this with changes to the edit app component.  modified `handleFilenameChange` (i.e., added document.title = name || "Untitled Notebook";) to update tab title when the filename changes and handle cases where name might be null.  
Also, added a `useEffect` hook to ensure the document title is set correctly whenever the filename changes with our default value (i.e.," "Untitled Notebook") if filename is null.  Here is a screen recording:

https://github.com/marimo-team/marimo/assets/123119434/e807af2f-6466-4102-84a0-5aca227e09f7
