### ISSUE TITLE
Notebook in the "Coming from Jupyter" section of docs throws an error

### ISSUE THREAD

**Issue by zane** [marimo-team/marimo#1435]
### Describe the bug

I visited the "[Coming from Jupyter](https://docs.marimo.io/guides/coming_from_jupyter.html)" page, but the notebook failed to load. The error message was:

> ```
> ASM_CONSTS[code] is not a function
> ```
>
> If this is an issue with marimo, please report it on [GitHub](https://github.com/marimo-team/marimo/issues).

### Environment

Not applicable. WASM execution.

### Code to reproduce

macOS Sonoma
14.5

Mozilla Firefox 
126.0 (64-bit

**Comment by mscolnick** [comment]
unfortunately the whole playground is down (we are on the latest version of pyodide, which we probably should pin instead). 

in the meantime, if you run marimo locally, `marimo tutorial for-jupyter-users` should work fine

**Comment by mscolnick** [comment]
yep that is expected. this is to teach you that you cannot redeclare variables like you can in jupyter
