### ISSUE TITLE
ASM_CONSTS[code] is not a function

### ISSUE THREAD

**Issue by arniwesth** [marimo-team/marimo#1436]
### Describe the bug

When trying to run the Webassembly-powered playground I get
```
ASM_CONSTS[code] is not a function
``` 

### Environment

Mac M1 Pro
MacOS 14.4.1
Chrome Version 124.0.6367.208 (Official Build) (arm64)

### Code to reproduce

Choose any playground example on the website

**Comment by mscolnick** [comment]
our apologies! should be back now (pls hard refresh)
