### ISSUE TITLE
Resuming session (refresh) loses stale status

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1444]
### Describe the bug

- Autorun on startup disabled; all cells are marked as stale
- Refresh the browser tab
- Cells are no longer marked as stale, but they should be

Context:
- BE doesn't know when a cell has been edited, and additionally might not be aware of cells in an un-instantiated notebook

### Environment

`0.6.0`

**Comment by wasimsandhu** [comment]
Picking this one up!

**Comment by wasimsandhu** [comment]
Couldn't reproduce this one.

1. No autorun on startup, lazy runtime, marked cells as stale
1. Refresh browser
1. Cells are still marked stale

![image](https://github.com/marimo-team/marimo/assets/7220175/f25f61b5-6fce-4d78-95e8-c20705d7e66a)
