### ISSUE TITLE
Scratchpad

### ISSUE THREAD

**Issue by PatrickCleary** [marimo-team/marimo#1464]
### Description

I find Notebooks become cluttered with non-essential code while iterating. This code is mostly from testing and checking variables.

### Suggested solution

I've always felt that a scratchpad in Notebooks would solve the above issue in addition to some others. Three use cases:

1. Check the value of a variable
2. Draft a cell while simultaneously being able to scroll through notebook and look at previous cells.
3. Test code without altering variables

Quick mockup (after making this I realized it may belong on the left side with the other tab options):
![image](https://github.com/marimo-team/marimo/assets/46229349/2c28cfa7-7014-477d-a9c4-e54e586f9814)

**Comment by mscolnick** [comment]
@PatrickCleary thanks for the feature request (and great design). this is something requested before. we can add this. is this something you would be interested in contributing or pairing on? if not, i am sure i can get to it at some point

**Comment by PatrickCleary** [comment]
I would take a crack at it! Would you be able to share some quick context on how you'd recommend approaching?

**Comment by mscolnick** [comment]
@PatrickCleary 

I think we can put this in the sidebar for now as a new helper panel. We can add a new endpoint for run_scratch_code which runs Python with the existing global variables but does not add itself to the dependency graph. The scratch doesn't need to be reactive either. It can return the console or visual outputs via the websocket infrastructure we have -  we can add new ws messages. 

Feel free to implement as much as you want - and then we can fill in the gaps. 

I really like your version history with arrow up/down too - up to you if you want to implement that in the first iteration.

**Comment by PatrickCleary** [comment]
Started on this. Left one question on a draft PR and also if someone wanted to give it a quick glance to make sure I'm on the right track that would be great.

**Comment by mscolnick** [comment]
Closed by https://github.com/marimo-team/marimo/pull/1821

Thanks for your help @PatrickCleary!
