### ISSUE TITLE
file_browser() option to select folder paths (and all files at once)

### ISSUE THREAD

**Issue by timoleistner** [marimo-team/marimo#1478]
### Description

I would like to be able to select only a folder path via the `file_browser()` UI element.

### Suggested solution

Add a filetype "folder" option to the `filetypes` initialization argument of mo.ui.file_browser().
Something like the following:
```mo.ui.file_browser(filetypes=["directory"])```
```mo.ui.file_browser(filetypes=["folder"])```
and then return the folder path as the `value` attribute.

### Alternative

As an additional feature, it would be nice to be able to select all files in a folder at once when selecting files via `file_browser()` via an extra checkbox. If I have a lot of files and only a few I don't want to select, this would spare a lot of clicking.

**Comment by wasimsandhu** [comment]
Picking this one up!

**Comment by wasimsandhu** [comment]
Having the ability to select all files within a folder is useful. I can add a "Select All Files" button for that.

As the main utility of the file browser is for selecting files, I would argue that additionally allowing folders to be selected might be overkill.

**Comment by timoleistner** [comment]
Thank you for picking this up!
As for the folder selection, I would argue that according to the Unix philosophy "Everything is a file", therefore folders are too.
I think it would just be very versatile, and also would spare an additional click for the user.
Having the folderpath would allow to directly feed this string to another python function which expects folder paths.

For example I want the user to select a folder where all experimental result files are located and then process these files according to a certain workflow. There could be subdirectories and so on.

**Comment by wasimsandhu** [comment]
That's a fair point! I will add this on.

**Comment by mscolnick** [comment]
Closed by https://github.com/marimo-team/marimo/pull/1558 (will be in the next release)
Nice job @wasimsandhu!

**Comment by chriswithers-fuse** [comment]
Looks like this subsequently lost the option to select both files and directories?

Should I open a new issue for the feature request?
My use case is a browser for parquet, json and deltalake files.

"file" works fire for the first two, but deltalake are actually directories, so I can't have a single ergonomic UI unless I can select delta lake directories in the same file_browser as parquet and json files...

**Comment by kirangadhave** [comment]
@chriswithers-fuse Can you please file a new issue for this? I will investigate it. Thanks 🙏🏽 

Feel free to tag me/assign me in the new issue.

**Comment by chriswithers-fuse** [comment]
@kirangadhave: done here: https://github.com/marimo-team/marimo/issues/9402
