### ISSUE TITLE
Can't get github copilot to work with nginx and oauth2 

### ISSUE THREAD

**Issue by JTriggerFish** [marimo-team/marimo#1484]
### Describe the bug

I am running a marimo server on a public server, behind nginx and oauth2 with my github account as login.
I think I am doing everything correctly in terms of forwarding my cookies and authentication through in the oauth2 and nginx configs and my browser is logged in to github, however copilot does not connect from within marimo.
It does connect if I run marimo locally on my host machine that runs the browser

I can't find a way to access detailed logs to try and troubleshoot, the server is run as: 
marimo edit test.py --headless --host 0.0.0.0 --port 3000 --no-token
and the --log-level DEBUG option is not accepted

Thank you !

### Environment

{
  "marimo": "0.6.6",
  "OS": "Linux",
  "OS Version": "6.8.0-31-generic",
  "Processor": "x86_64",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.19.1"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.11.0",
    "black": "24.4.2"
  }
}

**Comment by dmadisetti** [comment]
This might help! https://github.com/marimo-team/marimo/pull/1474

**Comment by dmadisetti** [comment]
@JTriggerFish --proxy is live in 6.11

so you can do

`marimo -l DEBUG edit --proxy www.myserver.com --port <port for nginx>`

(-l DEBUG has to come first) or if you have tls set up:

`marimo -l DEBUG edit --proxy www.myserver.com:443 --port <port for nginx>`

LMK if either of those fix the issue.

**Comment by JTriggerFish** [comment]
Thank you ! I tried but it didn't help. The DEBUG log flag does show copilot being enabled:

`[D 240530 11:54:18 runtime:1439] received request SetUserConfigRequest(config={'completion': {'activate_on_typing': True, 'copilot': True}, 'save': {'autosave': 'after_delay', 'autosave_delay': 1000, 'format_on_save': False}, 'formatting': {'line_length': 79}, 'keymap': {'preset': 'default'}, 'runtime': {'auto_instantiate': True, 'on_cell_change': 'autorun', 'auto_reload': 'off'}, 'display': {'theme': 'light', 'code_editor_font_size': 14, 'cell_output': 'above'}, 'package_management': {'manager': 'pip'}, 'ai': {'open_ai': {}}, 'experimental': {}, 'server': {'follow_symlink': False, 'browser': 'default'}})`

However I get "unable to connect" and no further info on that.

I'm running marimo as: 
marimo -l DEBUG edit --proxy www.myserver.com/marimo --port 3000 --no-token

Note that the "/marimo" part of the address seems to be ignored and the requests still go to the main page:
https://www.myserver.com/?file=test.py

This still works because I redirect the base url to marimo, here is my nginx conf for reference:

`server {
    listen 80;
    server_name myserver.com www.myserver.com;

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name myserver.com www.myserver.com;

    ssl_certificate /etc/ssl/myserver.com/fullchain.pem;
    ssl_certificate_key /etc/ssl/myserver.com/myserver.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # OAuth2 Proxy configuration
    location /oauth2/ {
        proxy_pass http://localhost:4180/oauth2/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
    }

    location /auth/ {
        proxy_pass http://localhost:4180/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
    }

    # JupyterLab configuration
    location /jupyter/ {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/start;
        proxy_pass http://localhost:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
        rewrite ^/jupyter/(.*) /jupyter/$1 break;
    }

    # Marimo server configuration
    location /marimo/ {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/start;
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
        rewrite ^/marimo/(.*) /$1 break;
    }
    # Ensure all other requests are proxied to the Marimo server
    location / {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/start;
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
    }
}`

**Comment by dmadisetti** [comment]
Woops. Guess I didn't consider paths. There might be an easy fix for that. I noticed you have --no-token. Does the auth token work?

**Comment by JTriggerFish** [comment]
Let me give that a try later. The reason I have —no-token is that I have oauth2 taking care of the security so it’s a bit redundant

**Comment by dmadisetti** [comment]
PR in

So the routes are not as straightforward. I'm sure it can be done, but my very naive attempt left me with a broken API unless I did much more configuring.

I think you can solve that with just nginx though

**Comment by dmadisetti** [comment]
@JTriggerFish Here's what I had locally: https://github.com/AnotherGroupChat/marimo/tree/path-attempt
Ideally, I think this should work out of the box before it makes its way upstream. I think it'll work with your additional redirect rewrites, but I don't think this should be synced until it's not broken
