### ISSUE TITLE
`mo.lazy` preview code shown in documentation running incorrectly

### ISSUE THREAD

**Issue by Haleshot** [marimo-team/marimo#1490]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

The example code provided for the `LazyComponent` in the `docs/api/layouts` section is not functioning correctly due to a missing library - `random` import. This is causing the following issue error popup:
> [!CAUTION]
> Function call (name: load, args: {}) failed with exception name 'random' is not defined

I plan to submit a Pull Request (PR) with the following changes:

### Your Suggestion for Changes

To resolve this issue, I plan to:

1. Import the random function.
2. Ensure the updated example code runs as expected.

This PR will ensure that the documentation previews its demo in the right way, running without any errors/issues.

**Comment by akshayka** [comment]
Thank you for the issue report and the PR!
