### ISSUE TITLE
Sidebar mixed with command palette, original sidebar, etc

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#1495]
### Describe the bug

<img width="304" alt="Screenshot 2024-05-27 at 14 13 47" src="https://github.com/marimo-team/marimo/assets/114637443/e92a8835-9811-4dcb-9a98-f42d9a8579f7">
<img width="291" alt="Screenshot 2024-05-27 at 14 14 03" src="https://github.com/marimo-team/marimo/assets/114637443/7f231424-fcdc-4973-bb48-8a61f9eff9f7">
the created siderbar is mixed with some existed stuff, making the notebook look strange.

### Environment

{
  "marimo": "0.6.8",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "125.0.6422.112",
    "Node": "v22.2.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "missing",
    "black": "24.4.2"
  }
}

### Code to reproduce

import marimo as mo

mo.sidebar(
    [
        mo.md("# marimo"),
        mo.nav_menu(
            {
                "#home": f"{mo.icon('lucide:home')} Home",
                "#about": f"{mo.icon('lucide:user')} About",
                "#contact": f"{mo.icon('lucide:phone')} Contact",
                "#contact": f"{mo.icon('lucide:phone')} Contact",
                "Links": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "1": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "2": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "3": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "4": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "5": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "6": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
                "7": {
                    "https://twitter.com/marimo_io": "Twitter",
                    "https://github.com/marimo-team/marimo": "GitHub",
                },
            },
            orientation="vertical",
        ),
    ]
)

**Comment by akshayka** [comment]
Thanks for reporting! A fix will be out soon.
