### ISSUE TITLE
batch wrapped elements don't react to changes

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#1497]
### Describe the bug

I'm wrapping one element inside a batch call, to add markup text to that component, along with a button. I want the button to do something, based on the value of the component that I just wrapped. However, when I change the state of the wrapped component, the original component never changes state as well. 

### Environment

{
  "marimo": "0.6.8",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "123.0.6312.123",
    "Node": "v14.16.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.9.0",
    "black": "24.3.0"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.6.8"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    def dropdown_factory():
        dropdown = mo.ui.dropdown(options=["hello", "world"])
        return dropdown

    dropdown = dropdown_factory()
        
    return dropdown, dropdown_factory


@app.cell
def __(dropdown, mo):
    def on_click(*args):
        print("value is", dropdown.value)

    button = mo.ui.button(label="show value of dropdown", on_click=on_click)

    wrapped_dropdown  = mo.md("""

    {dropdown}

    {button}
    """).batch(dropdown=dropdown, button=button)

    wrapped_dropdown
    return button, on_click, wrapped_dropdown


if __name__ == "__main__":
    app.run()

**Comment by akshayka** [comment]
If I understand what you're saying, that's how batch works. It clones the element it wraps, returning a new element. Interacting with the batch doesn't update the value of the element it was based on.

**Comment by mrdobalina2k** [comment]
Ok. I tried searching the faq, but this may not be completely clear from the docs.
