### ISSUE TITLE
matplotlib doesn't show elements out of bbox

### ISSUE THREAD

**Issue by ebetica** [marimo-team/marimo#1510]
### Describe the bug

If I do something like:

```
fig.legend(..., bbox_to_anchor=(0.98, 0.5))
```

then the legend is "out of frame", because .98 is as rightmost as possible. `plt.savefig(bbox_inches='tight')` works properly when we save it, but it doesn't display the legend properly in marimo. Can we display pyplot figures like the savefig behavior? 

### Environment

```
{
  "marimo": "0.6.10",
  "OS": "Linux",
  "OS Version": "5.19.17-coreweave",
  "Processor": "x86_64",
  "Python Version": "3.10.0",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.9.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.3.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.5",
    "uvicorn": "0.28.0",
    "starlette": "0.36.3",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.4.2"
  }
}
```

**Comment by mscolnick** [comment]
@ebetica do you have a minimal repro to help me (or someone) fix the issue

**Comment by ebetica** [comment]
This seems to reproduce:
```
plt.plot([1, 2])
plt.legend(["asdf"], bbox_to_anchor=(1.2, 0.5))
```

<img width="757" alt="image" src="https://github.com/marimo-team/marimo/assets/3605224/028dfbcb-5e6f-4e62-a1a8-dbee0885bc91">

**Comment by mscolnick** [comment]
thanks @ebetica - i have a fix incoming

**Comment by ebetica** [comment]
🚀 🚀 🚀
