### ISSUE TITLE
How to run the pyodide version of marimo locally

### ISSUE THREAD

**Issue by wwj718** [marimo-team/marimo#1515]
### Describe the bug

 According to the guidance of [marimo + pyodide](https://github.com/marimo-team/marimo/blob/main/pyodide/DOCS.md#running-the-frontend-against-the-latest-deploy-on-pypi)   

```bash
cd frontend
PYODIDE=true pnpm dev
```

Encountered the following problems

<img width="1440" alt="image" src="https://github.com/marimo-team/marimo/assets/3153878/c8e05955-af5e-4d03-a49c-8f8232634f3a">

### Environment

marimo env:

```
{
  "marimo": "0.6.11",
  "OS": "Darwin",
  "OS Version": "23.3.0",
  "Processor": "arm",
  "Python Version": "3.10.10",
  "Binaries": {
    "Browser": "125.0.6422.112",
    "Node": "v20.11.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.12.0",
    "black": "24.4.2"
  }
}
```

- pnpm 9.1.3
- marimo source code version: 0.6.11

**Comment by wwj718** [comment]
What's puzzling is that both Chrome and Arc (based on Chromium) block it, but Safari works fine!

**Comment by wwj718** [comment]
Thanks for helping me solve this problem.

I want to deploy pyodide marimo on a server, I produced dist folder  through `PYODIDE=true pnpm build`.

both Chrome and Safari  encountered many 404 errors:

<img width="1425" alt="image" src="https://github.com/marimo-team/marimo/assets/3153878/91ec77ef-9acf-41ef-8f46-1fd3064211ad">

**Comment by mscolnick** [comment]
`PYODIDE=true pnpm build` is not a thing, you can only run pyodide locally in develop mode. To host on your own server, you'll need to write a custom HTML file and host all the marimo assets (js/css/fonts).

**Comment by mscolnick** [comment]
Going to close this for now, please re-open if you are blocked.
