### ISSUE TITLE
Seaborn Facetgrids do not show

### ISSUE THREAD

**Issue by ebetica** [marimo-team/marimo#1529]
### Describe the bug

title

### Environment

{
  "marimo": "0.6.10",
  "OS": "Linux",
  "OS Version": "6.5.3-coreweave",
  "Processor": "x86_64",
  "Python Version": "3.10.0",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.9.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.3.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.17.2",
    "tomlkit": "0.12.5",
    "uvicorn": "0.28.0",
    "starlette": "0.36.3",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.4.2"
  }
}

### Code to reproduce

tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col="time",  row="sex")
g.map(sns.scatterplot, "total_bill", "tip")
g.figure

**Comment by mscolnick** [comment]
What is the expected?

This is what i see
<img width="973" alt="image" src="https://github.com/marimo-team/marimo/assets/2753772/393704ff-105d-4c76-a401-62d14b9f6fde">
https://marimo.app/l/3dhfag

**Comment by ebetica** [comment]
Okay super weird! I think it was a different bug. I'm using the VSCode extension via Remote-SSH, and sometimes I have to go through, stop the server, and remove all port forwards, or else the app will bug out. It sometimes displays an empty screen, and I guess in this case the plots did not show. Sorry about that. Maybe it's a rogue marimo server that starts on the same port or some other nonsense that's happening.
