### ISSUE TITLE
Data Explorer column name Bug

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1530]
### Describe the bug

@mscolnick super cool feature! just trying it out for the very first time.

![Screenshot 2024-05-30 at 20-06-14 \_home_dylan_src_marimo_taskmaster md](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/5f8fb46b-80c9-43aa-99f1-fa72190f6f62/779c4c9a-b81f-4f71-b70c-56379e7d928e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS81ZjhmYjQ2Yi04MGM5LTQzYWEtOTlmMS1mYTcyMTkwZjZmNjIvNzc5YzRjOWEtYjgxZi00ZjcxLWI3MGMtNTYzNzllN2Q5MjhlIiwiaWF0IjoxNzE3MTE1MDg4LCJleHAiOjMzMjg3Njc1MDg4fQ.Q9sdA6p1Gs-mXuHtbvNRD05U8cHBL4O-Clv-lqUUvqk)

Using this data [https://docs.google.com/spreadsheets/d/1S8L34lUyaaV78K02_eAAS-URsKxrWxY1aHT9qKXSoe8/edit#gid=619359118](https://docs.google.com/spreadsheets/d/1S8L34lUyaaV78K02_eAAS-URsKxrWxY1aHT9qKXSoe8/edit#gid=619359118)

Also breaks for non-quote characters like:

![image](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/c31b98fa-aae5-4d87-9f15-aadc6a8610b2/6905025e-a97e-4a01-87fa-cf1c1940e818?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS9jMzFiOThmYS1hYWU1LTRkODctOWYxNS1hYWRjNmE4NjEwYjIvNjkwNTAyNWUtYTk3ZS00YTAxLTg3ZmEtY2YxYzE5NDBlODE4IiwiaWF0IjoxNzE3MTE1MDg4LCJleHAiOjMzMjg3Njc1MDg4fQ.e0Otbte6gAD1aq07QOXqMcc2dEq-u7cL_ZaloPZu9Ag)

### Environment

head

### Code to reproduce

```python
file_name = '/home/dylan/downloads/Taskmaster Contestant Ranking - Series 17.xlsx' # path to file + file name
sheet = "Series 17 Episode 9" # sheet name or sheet number or list of sheet numbers and names
 
df = pd.read_excel(file_name, sheet_name=sheet)
# print(df.head()) # print first 5 rows of the dataframe
df
```

**Comment by mscolnick** [comment]
@dmadisetti nice finds - should handle this more gracefully in this PR https://github.com/marimo-team/marimo/pull/1531

**Comment by mscolnick** [comment]
re-opening for the other small edge-case
