### ISSUE TITLE
Unable to capture user-defined module updates

### ISSUE THREAD

**Issue by chenller** [marimo-team/marimo#1542]
### Describe the bug

If I create a file named `tools.py`, then I create a cell and run 'import tools', then I add a function to `tools.py` (such as `def fun1()`). Run the cell again, and the error 'AttributeError: module 'tools' has no attribute' fun1 'appears. It seems that Morimo cannot recognize the new changes in the file `tools.py`.
If I don't use Notebook and instead use Marimo, this bug will severely limit the application of Marimo

### Environment

marimo 0.6.13

### Code to reproduce

cell1:
`import tools`
cell2:
`tools.fun1()`

**Comment by mscolnick** [comment]
There is a setting "On module change":
>  Whether marimo should automatically reload modules before executing cells. If "lazy", marimo will mark cells affected by > module modifications as stale; if "autorun", affected cells will be automatically re-run.

What is your setting currently?

**Comment by chenller** [comment]
The function I expect is : 
1. When I import a module such as `tools.py`, if I modify `tools.py`, the imported module will not track the latest changes. It is "lazy". 
2. When I import a module such as `tools.py`, and then modify `tools.py`. When I run the code that imports the module again, the latest changes to the module will be loaded.

This means that morimo does not need to monitor module changes in real time, but only needs to re-import the module when I run the code to reload it. Marimo should not automatically reload modules before executing a unit of code. This behavior only occurs when encountering `import xxx` code execution.

**Comment by mscolnick** [comment]
This is how "lazy" operates. You can enable that with the setting in the top-right dropdown menu.

**Comment by chenller** [comment]
The problem I encountered is:
The content of `tools.py` is
```python
def fun1():
    print('fun1')
```
- step1: Run cell 0.
```python
import tools
```
- step2: Run cell 1.
```python
print(dir(tools))
```
Output is:
![image](https://github.com/marimo-team/marimo/assets/62296334/dd76fac6-e79e-4f95-85de-34324d5ca424)
-  step3: Add a function `fun2` to `tools.py` and save.
```python
def fun1():
    print('fun1')
def fun2():
    print('fun2')
```
-  step4: Rerun cell 0 and then rerun cell 1.
I received the same output as before. It seems that the new `tools` variable did not import `fun2`.
![image](https://github.com/marimo-team/marimo/assets/62296334/fee44857-99af-4cfb-83b6-4713da0c5b63)
This does not meet my expected outcome.

**Comment by mscolnick** [comment]
Can you copy your settings with: `marimo config show`

**Comment by chenller** [comment]
I have resolved this issue and thank you very much for your answer. Marimo is very user-friendly, and I will use it in future development.

**Comment by qbilius** [comment]
I'm facing the same issue (marimo 0.6.25). I tried both `auto_reload = "autorun"` and `auto_reload = "lazy"` but neither sees the changes in the imported module.
