### ISSUE TITLE
Bad display of mo.ui.table distributions widget on Firefox

### ISSUE THREAD

**Issue by tomsquest** [marimo-team/marimo#1562]
### Describe the bug

Using `mo.ui.table(df)` leads to distribution widgets being "on-top" of the table when using firefox.

Adblocker is disabled, or anything I could think of.

### Using firefox 126.0.2 on Ubuntu 22.04

![image](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/1f512dda-cb49-466c-8c22-d371f0a63d07/2f05891b-839d-41f8-a8ad-1207c731ec3d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS8xZjUxMmRkYS1jYjQ5LTQ2NmMtOGMyMi1kMzcxZjBhNjNkMDcvMmYwNTg5MWItODM5ZC00MWY4LWE4YWQtMTIwN2M3MzFlYzNkIiwiaWF0IjoxNzE3NjgyODg1LCJleHAiOjMzMjg4MjQyODg1fQ.HMpR5fMnHAvGb_nhc6ixYER8n9F6ASQFwKLiQ3dpwS0)

### Using Chromium 125.0.6422.112 on same host

![image](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/ee6b4035-e2b9-41f4-b7e6-fb33fcfeb56d/d157c0c6-e32d-48c1-9ac6-3bdb90a934bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS9lZTZiNDAzNS1lMmI5LTQxZjQtYjdlNi1mYjMzZmNmZWI1NmQvZDE1N2MwYzYtZTMyZC00OGMxLTlhYzYtM2JkYjkwYTkzNGJiIiwiaWF0IjoxNzE3NjgyODg1LCJleHAiOjMzMjg4MjQyODg1fQ.qhxDgdNEmPVPIeDpgJ51hDY0FIlv0Xqm1ErUKxC6YiI)

### Environment

```json
{
  "marimo": "0.6.15",
  "OS": "Linux",
  "OS Version": "6.5.0-35-generic",
  "Processor": "x86_64",
  "Python Version": "3.11.9",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.11.1"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "missing",
    "black": "24.4.2"
  }
}
```

### Code to reproduce

1. Run `marimo edit https://raw.githubusercontent.com/marimo-team/marimo/main/examples/third_party/polars_example.py`.
2. Scroll to the later cells.

Or:

```python
import marimo as mo
import pandas as pd

df = pd.read_json("data.jsonl", lines=True)

mo.ui.table(df)
```

**Comment by mscolnick** [comment]
thanks for filing this, fixing it now

**Comment by akshayka** [comment]
@tomsquest , just cut a new release (0.6.16). It should be available on PyPI within 10 minutes or so.

**Comment by tomsquest** [comment]
@akshayka Fixed!
You were really fast to fix it.
Many thanks!

By the way, excellent product. I really like it :+1:
