### ISSUE TITLE
Special case staleness detection of "import-only" cells

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1570]
If a cell _only_ contains import statements, then on re-run, names that were already defined shouldn't be considered when computing the descendants of that cell.

For example, the user runs:

```python
import pandas as pd
```
Then modifies the cell to be 

```python
import pandas as pd
import numpy as np
```

In this case, `pd` should not be used when finding descendants of the cell, to prevent unnecessary re-runs.

This only applies to cells that only have imports. If the cell had statements/expressions other than imports, e.g.

```python
import pandas as pd
import numpy as np

pd.set_options(...)
```

then `pd` would be used to find descendants, ie the behavior would be as of today.

NOTE: When module reloading is enabled, behavior should be as it is today. In this example, `pd` would still be used to find the children of the cell.

**Comment by akshayka** [comment]
cc @wasimsandhu

**Comment by wasimsandhu** [comment]
Grabbing this one :)

**Comment by wasimsandhu** [comment]
Sorry for the delay, taking a look this week!
