### ISSUE TITLE
ui.table: full-table sorting

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1573]
### Description

Enhance `ui.table()` to sort on the entire table contents.

Right now, mo.ui.table truncates tables to 10,000 rows. When you sort a column, eg sort descending, it only sorts on the truncated data -- and this sorting happens in the frontend. This has been confusing for our users. Instead, we would like sorting to happen on the backend. 

This feature fits with our priority of making marimo the best place to work with data.

### Suggested solution

This could be implemented by adding a "sort" Function to ui.table -- UIElements have a way of exposing RPC/Functions to the frontend.

Example of `Function` registration: https://github.com/marimo-team/marimo/blob/main/marimo/_plugins/ui/_impl/table.py#L211-L222

**Comment by akshayka** [comment]
cc @wasimsandhu

**Comment by akshayka** [comment]
The same enhancement could also be made to `mo.ui.dataframe()`

**Comment by wasimsandhu** [comment]
Picking this up!

**Comment by wasimsandhu** [comment]
Completed in #1581 :)
