### ISSUE TITLE
Download as button is not responsive

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1577]
Hey, big fan of marimo here. I was trying to use WASM to embed it in a website I'm developing. I see this new button isn't quite responsive. Are you planning on making it not visible as a config or put it in the end of the notebook or maybe a bit above?

![image](https://github.com/marimo-team/marimo/assets/41552687/8146790c-dc90-4139-b0b4-302a5e1edad1)

_Originally posted by @jevalentini in https://github.com/marimo-team/marimo/issues/1469#issuecomment-2155693106_

**Comment by MadGanGithub** [comment]
Hi @akshayka @scls19fr @tlpinney @ideoforms @dbrans ,
 I'd like to work on this issue. Could you please assign it to me?

**Comment by mscolnick** [comment]
@MadGanGithub, awesome! i assigned it to you. let me know if you need any help getting setting up - we can chat in discord. 

as far as implementation, i was thinking we could have a smaller button (maybe triple dots and minimal with no background).
for responsiveness you can use tailwind's responsive classname utilities (https://tailwindcss.com/docs/responsive-design) to hide and show each button depending on screensize

**Comment by mscolnick** [comment]
@MadGanGithub, I took this over and snuck the fix in this PR https://github.com/marimo-team/marimo/pull/1845
