### ISSUE TITLE
Include html headings in `View outline`

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#1582]
### Describe the bug

Sometimes I need to put a heading in the center of the output, in this case `<h2 align="center">XYZ</h2>` is convenience, but in the outline panel, the outline excludes these html headings

<img width="489" alt="Screenshot 2024-06-09 at 14 19 33" src="https://github.com/marimo-team/marimo/assets/114637443/a8260c91-0800-499c-912f-df038545daab">

### Environment

{
  "marimo": "0.6.17",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "125.0.6422.142",
    "Node": "v22.2.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "black": "24.4.2"
  }
}

**Comment by mscolnick** [comment]
You need to add an `id` to the `<h1/h2/h3>`, otherwise the heading is not clickable/navigate-able.

```
mo.md("""
# Heading 1

<h2 id="custom">Heading 2</h2>
""")
```

<img width="986" alt="image" src="https://github.com/marimo-team/marimo/assets/2753772/f236ed41-f533-4a1d-bedb-cf08cf8d0871">
