### ISSUE TITLE
Notebooks with large dataframes hang when opening

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1586]
Hi there,cool for implementing that new feature! 

Could it be, that the datasources panel automaticly retrieves informations from every datasource? As an Ibis-table can be a connection to a very large databasetable this could take a while and it would be nice to surpress this on demand.

With the change from #1522, my old notebook hangs when opening

_Originally posted by @szst11 in https://github.com/marimo-team/marimo/issues/1522#issuecomment-2158671559_

**Comment by mscolnick** [comment]
@szst11, it gets information for only tables that are declared as variables. it also only grabs the following information:
* num rows
* num columns
* column names / dtype

however, for ibis, we do convert it to a pyarrow table which could be the expensive portion. we can look into just loading the schema, and lazily get the rows/columns when asked
