### ISSUE TITLE
Opening "Home" in directory of only markdown notebooks is not navigable. External directory in general not navigable.

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1593]
### Describe the bug

With no python notebooks, there's no "click to see markdown notebooks", so the home page is just stuck.

I wouldn't mind having this as a config option, since I mainly use markdown notebooks now.

![image](https://github.com/marimo-team/marimo/assets/2689338/8119b822-0e28-4027-a1ef-1b6f22ebda57)
(There are a bunch of notebooks in here)

vs

![image](https://github.com/marimo-team/marimo/assets/2689338/f55824e1-c1be-4845-9be2-8f76014e6cea)

### Environment

Head

**Comment by dmadisetti** [comment]
Related, for refresh: https://github.com/marimo-team/marimo/issues/1348

A workaround now is toggling "show notebooks", which does a refresh.

**Comment by dmadisetti** [comment]
OK- was doubly confused because:

```bash
$ marimo edit notes/
```

Lists directory of `notes/`, but then trying to edit one of the files opens up `./notebook.py` instead of `./notes/notebook.py`

**Comment by mscolnick** [comment]
oh that is indeed a bug - also if you are using markdown a lot, i can put "Include Markdown" checkbox state into local storage

**Comment by dmadisetti** [comment]
That would be nice! I think home in general has a lot of potential. Useful as is , because I can have multiple sessions- but no navigable way back to home and not much useful information on it.

Livebook
![image](https://github.com/marimo-team/marimo/assets/2689338/2341b498-9986-4a70-8337-f6fc29aaee03)

I was going to share a picture of jupyter, but it's less useful than marimo
