### ISSUE TITLE
ui.dataframe with Ibis support

### ISSUE THREAD

**Issue by szst11** [marimo-team/marimo#1607]
### Description

The feature of exploring and transforming a pandas dataframe with ui.dataframe is really amazing.
If this would be possible with an Ibis-table, Marimo would be able to explore data in a database, just in the same way.

### Suggested solution

create ibis code snippets in a similar way like the pandas snippets and add an option to only display a limited number of rows in the preview.

**Comment by mscolnick** [comment]
we had a similar request for Polars (#616). I can look into extending this to support different types of dataframes

**Comment by rupurt** [comment]
It would be rad to support Ibis. That would open up marimo to a lot of different backends.

**Comment by mscolnick** [comment]
@rupurt @szst11, I am adding support for ibis in #2188 

Would it be useful for you to get the SQL/python equivalent as well (basically GUI to code)?

**Comment by rupurt** [comment]
@mscolnick amazing. Do you mean that we could use the Python/SQL Ibis API directly? That would be useful for sure.

**Comment by mscolnick** [comment]
@rupurt - I was thinking we could show the equivalent code for Python/SQL, like we do with pandas

**Comment by rupurt** [comment]
Gotcha. Yeah that would also be super useful
