### ISSUE TITLE
Publish VSCode extension to Open VSX

### ISSUE THREAD

**Issue by q-wertz** [marimo-team/marimo#1615]
### Description

Currently you publish the VSCode extension to the official Visual Studio Marketplace (which is already very nice :blush:). It would be great if you also make the app available on [Open VSX](https://open-vsx.org) which is an open-source registry for VS Code extensions and managed by the Eclipse foundation.

Thus users of VSCodium could also use the app seamlessly.

### Suggested solution

The publishing process is described in their [wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by mscolnick** [comment]
will do this today!

**Comment by mscolnick** [comment]
looks like they are having [some issues](https://github.com/eclipse/openvsx/issues/945), but once that resolved, ill publish it

**Comment by q-wertz** [comment]
Thx 😍

**Comment by q-wertz** [comment]
Ah sorry. Didn't see it is already requested in the correct project https://github.com/marimo-team/vscode-marimo/issues/26

**Comment by mscolnick** [comment]
It has be published: https://open-vsx.org/extension/marimo-team/vscode-marimo, and extension verification in progress (https://github.com/EclipseFdn/open-vsx.org/issues/2653)
