### ISSUE TITLE
h4 - h6 missing from TOC panel

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1617]
### Describe the bug

Maybe this is expected behavior, but only h1-h3 show in the TOC
![image](https://github.com/marimo-team/marimo/assets/2689338/0e8a4c05-438b-4c38-8a47-6a28251cdcdc)

### Environment

Head

### Code to reproduce

https://marimo.app/l/el4hxt

**Comment by mscolnick** [comment]
this was an intentional choice - I didnt find this it was useful and added noise

**Comment by dmadisetti** [comment]
Cool, closing this out

I normally get to h4, I don't think I would have noticed if it was h5

h1 document title
h2 sections
h3 break down of sections
h4 asides/ code for break down

But maybe I'll explore a different format

**Comment by hugoboia** [comment]
I agree with Dylan, I usually get to h4 too and think it could be useful.
But I understand when Myles says it adds noise: it's far more readable without h4.

Could it be something configurable, similar to the number of rows shown per page on the rich table (that defaults to 25 but allows changing)?

Perhaps the title of the outline panel could be used:

<img width="731" height="61" alt="Image" src="https://github.com/user-attachments/assets/a5918ac9-a801-4a13-b3d5-fca8ae461b41" />

Or maybe a dropdown, to save space.
