### ISSUE TITLE
Name of marimo notebook tab title in browser should just be the name of the file (not include filepath)

### ISSUE THREAD

**Issue by delennc** [marimo-team/marimo#1630]
### Describe the bug

I have 10+ marimo notebooks open, and I can't tell which one is which because the tab title starts with the name of the directory (since they are nested 2 directories deep from where I ran `marimo edit`)

![Screenshot 2024-06-17 at 2 08 35 PM](https://github.com/marimo-team/marimo/assets/29712687/b7e6ecc3-a44b-461b-80b9-1ed715739309)

### Environment

0.6.19

**Comment by ericjanto** [comment]
I'll give this a try
