### ISSUE TITLE
Can't find new marimo notebook in marimo homepage

### ISSUE THREAD

**Issue by delennc** [marimo-team/marimo#1631]
### Describe the bug

I had a marimo kernel already running and I used the command line to copy an existing notebook with a new name, but I can't find the new marimo notebook in the list of All Notebooks in the marimo homepage, even after refreshing. It only showed up once I restarted the kernel. Would be extra nice if there was a feature to clone a notebook directly from the homepage

### Environment

0.6.19

**Comment by mscolnick** [comment]
Closed by https://github.com/marimo-team/marimo/pull/1759 - there is a refresh button now or you can refresh the page.
