### ISSUE TITLE
The "Run all modified cells" button is always yellow

### ISSUE THREAD

**Issue by foxcroftjn** [marimo-team/marimo#1656]
### Describe the bug

As of version 0.6.20, the "Run all modified cells" button in the bottom right corner is always yellow, and when pressed, will re-run every cell regardless of whether it is stale.

### Environment

```json
{
  "marimo": "0.6.20",
  "OS": "Linux",
  "OS Version": "5.15.133.1-microsoft-standard-WSL2",
  "Processor": "",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.14.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "missing",
    "black": "24.4.2"
  }
}
```

### Code to reproduce

This can be reproduced with an empty notebook. Even if there is only one empty cell, the "Run all modified cells" button will always be colored yellow and will re-run the empty cell when pressed.

**Comment by akshayka** [comment]
Thanks for reporting. Can you share the contents of your `~/.marimo.toml`? In particular it would be helpful to know if you have autorun on startup enabled or disabled, the behavior on cell change, and if the module reloader is active.

**Comment by akshayka** [comment]
@foxcroftjn Just cut a release for version 0.6.21. It contains the fix, and should be on PyPI momentarily.

Let me know if you still have issues.

Thanks again for reporting this!
