### ISSUE TITLE
Special variable name "__" not treated as local

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#1675]
### Describe the bug

I don't think this is really a bug / big issue, but opening an issue just to document it.

"__" is considered a global variable, and is not hidden from other cells.

I just caught it when very lazily assigning var names

### Environment

head

### Code to reproduce

https://marimo.app/l/1uelf3

**Comment by ontowhee** [comment]
I'm new to marimo and learning the internals of python! I would love to help and work on this issue.

You mention this is not really a bug. What is the desired behavior for referencing `__` across cells? Or are you suggesting that there be documentation for this? Or should this raise an error, and what error would that be?

Thanks for the code example. I was able to create a notebook, https://marimo.app/?slug=l6y37x,  to illustrate that a private variable raises the `NameError` when referenced in another cell. If it is desirable to "hide" `__` across cells, would it also raise a `NameError`? How does that affect the fact that `__` is a global variable?

**Comment by dmadisetti** [comment]
marimo secretly renames all variables that start with _ to `_<cell name>_<variable name>` somehow these variables are falling through the filter

This is likely a problem during static analysis in `_ast/visitor `
