### ISSUE TITLE
Patched urllib does not seem to work outside of Pandas

### ISSUE THREAD

**Issue by mrchrisadams** [marimo-team/marimo#1681]
### Describe the bug

Urllib does not seem to be patched when making network requests outside of Pandas in a WASM notebook.

I can see this was investigated in #934  (improvement: patch urllib in bootstrap to support networking) for WASM notebooks, and I can see Pandas working in a sample notebook fine. However using urllib directly does not seem to work as expected.

### Environment

I am using the WASM version of Marimo, on the Marimo platform.

### Code to reproduce

I've created a notebook demonstrating the behaviour below - with Pandas making network requests successfully, but urllib failing.

https://marimo.io/p/@mrchrisadams/making-network-requests

**Comment by mrchrisadams** [comment]
I think I've seen the issue now - it seems to be related to CORS support on the server you are trying to make a network request to.

**Comment by mscolnick** [comment]
Going to close this - let me know if you have any other questions/issues
