### ISSUE TITLE
remote connection

### ISSUE THREAD

**Issue by ericYH01** [marimo-team/marimo#1732]
### Describe the bug

per https://docs.marimo.io/faq.html#faq-remote , I am trying to remotely connect to a server (192.168.0.99)
the command is "marimo --headless --host 0.0.0.0 --port 7999"
however, I can't access to the remote marimo server by entering following command within my local browser:
> http://192.168.0.99:7999

### Environment

remote server: ubuntu 22.04 LTS
local machine: win11 + edge browser

-------
update
-------
when using port different from common used like 8080,  one shall remember to allow the ufw. Say,

$ sudo ufw allow 7999/tcp
$ sudo ufw reload

**Comment by mscolnick** [comment]
the command needs to be `marimo edit --headless ...`
