### ISSUE TITLE
Navigate to top/bottom when toggleing `focusTop`/`focusBottom`

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#1733]
### Description

When toggling the commands `global.focusTop` and `global.focusBottom`, the view of the notebook should automatically be focused on the top/bottom.

Similar features should be applied to `cell.focusUp` and `cell.focusDown`.

### Suggested solution

Update the function `focusTopCell` in the file `marimo/frontend/src/core/cells/cells.ts`.

**Comment by mscolnick** [comment]
Thanks for pointing this out - i have the fix here https://github.com/marimo-team/marimo/issues/1733
