### ISSUE TITLE
keep installing packages already installed

### ISSUE THREAD

**Issue by ericYH01** [marimo-team/marimo#1736]
### Describe the bug

When running cell, mo poped up an installation window suggesting package notinstalled.
After installation (within the editor, or external), the window keeps show up.
![image](https://github.com/marimo-team/marimo/assets/83878418/e5747e00-bd65-4b1f-9b56-4f7049263356)
Installing package as suggested:
![image](https://github.com/marimo-team/marimo/assets/83878418/398bae8e-4507-4ae1-b641-89d8167f6355)
the window shows again.
![image](https://github.com/marimo-team/marimo/assets/83878418/e5747e00-bd65-4b1f-9b56-4f7049263356)

### Environment

ubuntu 22.04. Running in a conda virtualenv.

### Code to reproduce

# Import necessary libraries for the project 
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import numpy as np 
import random 
import gc 

# Import PyTorch Geometric libraries 
import torch_geometric.transforms as T 
import torch_geometric.utils
from torch_geometric.datasets import Planetoid
from torch_geometric.utils import spmm

**Comment by akshayka** [comment]
Thanks for reporting. I tried to reproduce but couldn't unfortunately.

@ericYH01 , any more information you can share? For example, how did you install marimo into the conda env? And did you use the defaut `pip` installer to install the packages? Finally, what do you see in the your terminal window during this process, if anything?

**Comment by ericYH01** [comment]
to make things easier, I recreate a new virtualenv (miniconda)
![擷取選取區域_003](https://github.com/marimo-team/marimo/assets/83878418/80f3ebcc-0814-4e39-ada6-bed8fcc4d974)

then start marimo in headless mode

`$ marimo edit --headless --host 0.0.0.0 --port 7071 --no-token`


https://github.com/marimo-team/marimo/assets/83878418/d9c2c519-f6d3-4c38-a036-fe3ea9b4773b

![擷取選取區域_001](https://github.com/marimo-team/marimo/assets/83878418/02c6970a-8084-47f1-9c9b-87d6671b6705)
![擷取選取區域_002](https://github.com/marimo-team/marimo/assets/83878418/af8ca587-3836-45a9-a50c-1e0522d8bc7d)


besides, I'd tried on windows-based edge browser, and ubuntu-desktop-based Chrome browser. The situation still happened.
However, it works fine when running the same code on local marimo.

**Comment by mscolnick** [comment]
@ericYH01 are you still seeing this? there has been some changes to auto-installation

**Comment by mscolnick** [comment]
Going to close this, @ericYH01 please re-open if you are still seeing this issue.
