### ISSUE TITLE
View as Python (from markdown) keyboard shortcut not working

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#1737]
### Describe the bug

`mo.md(f"")` should be able to be viewed as markdown, just like `mo.md("")` and `mo.md(r"")`

I prefer the original behavior of `view as markdown` command, which let me freely view a cell as python or markdown, and now if a cell is viewed as markdown, the key command won't provide the view of python

### Environment

```json
{
  "marimo": "0.7.0",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "v22.3.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "black": "24.4.2"
  }
}
```

**Comment by akshayka** [comment]
Hey @metaboulie -- this was an intentional decision (see https://github.com/marimo-team/marimo/pull/1728). There are a few edge cases to handle when viewing format strings as markdown, and they were causing more problems than they were solving.

**Comment by akshayka** [comment]
Reopening and renaming issue — I missed your comment about the view as Python keyboard shortcut not working. We'll fix that. Thanks for letting us know
