### ISSUE TITLE
terminal escape codes visible in windows cmd terminal when running `marimo edit`

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1748]
### Describe the bug

```C:\Users\user>marimo edit
←[33mUpdate available 0.6.26 → 0.7.0←[0m
Run ←[32mpip install --upgrade marimo←[0m to upgrade.


        ←[1;32mCreate or edit notebooks in your browser←[0m 📝

        ←[32mURL←[0m: ←[1mhttp://127.0.0.1:2719?access_token=OapqfwxOHZMrTCEeY2DuAw←[0m
```

All those `[32m` and `[0m` appear making it hard to read the ouput.

### Environment

{
  "marimo": "0.6.26",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "black": "23.7.0"
  }
}

### Code to reproduce

1. Go to the lower left search bar.
2. type `cmd` followed by enter
3. in the resulting terminal type `marimo edit` followed by enter

**Comment by mscolnick** [comment]
@ggggggggg we don't currently have any maintainers (or contributors) with a windows setup. 

hopefully someone with a windows setup and help debug and contribute the fix.

**Comment by ggggggggg** [comment]
Well then I'm impressed it works as well as it does. On another windows machine the terminal looks colored just as expected. So it's not fundamental. 

![image](https://github.com/user-attachments/assets/033fc789-5a67-429d-a863-69e98e57079f)

Marimo env for the machine with colored terminal output. Maybe it's related to windows 10 vs 11 since the working machine is windows 11?
```{
  "marimo": "0.7.9",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 142 Stepping 10, GenuineIntel",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.0",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.4"
  }
}
```

**Comment by wasimsandhu** [comment]
Just checking, are you using Windows Terminal or Windows Command Prompt on Windows 11?

**Comment by mscolnick** [comment]
I wonder if we should be using `click.echo` (which claims to be more environment friendly) instead of `print`.

**Comment by mscolnick** [comment]
Closing this as I think this is fixed by checking if we support colors: https://github.com/marimo-team/marimo/pull/3146/files#diff-92c30eba0f093c2dfa5a0bd78433068066664c81f11bdb5822902b2889295c5cR13-R39
