### ISSUE TITLE
marimo edit hangs

### ISSUE THREAD

**Issue by FrostMiKu** [marimo-team/marimo#1757]
### Describe the bug

I exec `marimo edit --headless` on the Ubuntu server, but nothing was printed.

it seems to hang. I can not connect it in browse or vscode.

![image](https://github.com/marimo-team/marimo/assets/8232546/7d40f242-ffa9-40a3-a38a-8aaaa85636da)

`marimo tutorial` and `marimo run` can exec right.

I tried to install 0.6.26 0.7.0 and 0.7.1, got the same problem.

I tried to enable the DEBUG logger but still nothing was printed.

![IMG_7378](https://github.com/marimo-team/marimo/assets/8232546/2f43fc1b-b46f-45da-83dd-1e10cf3a0511)

### Environment

{
  "marimo": "0.6.26",
  "OS": "Linux",
  "OS Version": "5.4.0-186-generic",
  "Processor": "x86_64",
  "Python Version": "3.11.0",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "black": "24.4.2"
  }
}

**Comment by akshayka** [comment]
Thanks for reporting. I tried to reproduce but wasn't able to yet.

Does `marimo edit main.py` without headless work?

**Comment by FrostMiKu** [comment]
> marimo edit main.py

![image](https://github.com/marimo-team/marimo/assets/8232546/c78cc5be-663c-4c6e-b1ef-f6393de72a35)

It does not work.

---

When I finished eating (**about 2 hours later**), the terminal showed `localhost contacted. waiting for reply... `

After I press command + c, the program works as shown:

![image](https://github.com/marimo-team/marimo/assets/8232546/f9ce3d35-965f-4e25-9c3d-9716fe857568)

It's working

**Comment by FrostMiKu** [comment]
Now `marimo edit` is working correctly.

That's weird.

**Comment by mscolnick** [comment]
That is odd - @FrostMiKu is this good to close?

**Comment by FrostMiKu** [comment]
> That is odd - @FrostMiKu is this good to close?

yep
