### ISSUE TITLE
`mo.ui.table` for Pandas Dataframe do not work in HTML exports

### ISSUE THREAD

**Issue by nchachereau** [marimo-team/marimo#1768]
### Describe the bug

When exporting the notebook to HTML, cells that display a Pandas DataFrame using `marimo.ui.table` output an empty table and the following error message:

> Error
> this is undefined

### Environment

```
{
  "marimo": "0.7.1",
  "OS": "Linux",
  "OS Version": "6.5.0-41-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "v12.22.9"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "black": "24.4.2"
  }
}
```

### Code to reproduce

One cell containing the following is enough:

```python
import pandas as pd
pd.DataFrame(
    range(10)
)
```

**Comment by mscolnick** [comment]
@nchachereau thanks for reporting - i have a fix out. hopefully released soon

**Comment by nchachereau** [comment]
@mscolnick Sorry to report that the fix is incomplete… I now get a new error:

> NetworkError when attempting to fetch resource.

**Comment by mscolnick** [comment]
Apologies - I guess the unit tests were not enough. I'll look into this again

**Comment by nchachereau** [comment]
Thank you! I can confirm that it is going to work once released.
