### ISSUE TITLE
Changing the position of a set of cells

### ISSUE THREAD

**Issue by VivaldoMendes** [marimo-team/marimo#1773]
### Description

I need to change the position of a **_set of cells_** (not just one cell)  inside a notebook. In other apps (e.g., Pluto), I can select a set of cells and use the drag-and-drop facility to move them to the position I need (I can also copy + paste that entire set of cells into another notebook).

I have tried this drag facility in Marimo. As far as I can see, I can do the same if I do it **_one cell_** at a time. I have also tried using VScode for that task. In VScode's pane, I can move the cells I need to another position, no problem with that. However, I have to kill the VScode session and start a new session to see the changes implemented in the marimo's pane. Am I doing something wrong? 

Moving a set of cells into a different position inside a notebook is very useful, e.g., when using notebooks as a set of exercises. It is very common to change the order of the exercises from time to time, either when creating new exercises or modifying existing ones.

Thanks

### Suggested solution

drag-and-drop for more than one cell

**Comment by mscolnick** [comment]
This will only work in a subset of cases - but you can now move group of cells if they are collapsed under the same section, since we now (next release) support collapsible sections (H1, H2, H3)

**Comment by VivaldoMendes** [comment]
That is wonderful.  Thanks.
