### ISSUE TITLE
Feedback when stale cell is queued (lazy executor)

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1788]
### Describe the bug

Reported by @bmeyers

quality of life request: when using lazy execution mode, it would be nice to have a indicator of "queued" cells. If a cell is executing, and I click the run button on other cells, they will execute after the current cell is complete. But there's no feedback that the cell has gone from a "stale" state to a "queued" state. Sometime, this can cause the user to click the run button twice, which results in the queued cell executing twice. If the cell is computationally expensive, this can be pretty annoying! 

### Environment

0.7.3

**Comment by mscolnick** [comment]
I think there is a deeper fix of deduping `CellExecutionRequests` like we do with `SetUIElementRequests`

**Comment by akshayka** [comment]
This can also happen when the executor is set to autorun (just saw it happen).

**Comment by akshayka** [comment]
>  I think there is a deeper fix of deduping CellExecutionRequests like we do with SetUIElementRequests


Yea. I think the fix is two-part:

1. dedupe execution requests
2. communicate a queued status, even if the kernel is busy (eg, busy running a cell)

2 (and 1) could be handled on the backend by introducing a new thread.

**Comment by akshayka** [comment]
@bmeyers this is now fixed and will be included in the next release. Thanks for bringing to our attention!
