### ISSUE TITLE
Callouts: a bug and a suggestion

### ISSUE THREAD

**Issue by VivaldoMendes** [marimo-team/marimo#1796]
### Description

I have tried using callouts in marimo. Two comments. 

Firstly, when most people think about callout blocks, they think about them in terms of markdown code, not computational code. However, the examples I have found on the marimo website use **_computational cells_** instead of **_markdown cells_**. If some newbies come into marimo like me, we will try instinctively using markdown cells for such purpose because that is what most people do when writing things that include such callouts. Moreover, using computational cells makes the code lengthy and rambling, and it could be more user-friendly. 

Secondly, I figured out that we can use the traditional way of rendering callouts in marimo by following the usual process:

1. Open a markdown cell
2. Use: ```!!! + type + title```

As far as I can see, marimo accepts the following types: tip, note, danger, warning, and caution. It may take more, but I did not test that. Without a type and/or a title it also works.

Two points in using markdown cells for producing callouts in Marimo: a **_bug-** and a **_suggestion_**. The bug is that in the callout's title, marimo changes automatically small letters into capital letters. See example below:

![a](https://github.com/user-attachments/assets/a8f4b5c0-0fb7-409d-b7ca-56a6bb3782b9)

Still, in the bug case, if we type `** some title**` , the set `**...**` creates an empty line between the callout's title and the text. This empty line is usually very convenient. However, I only discovered it by chance: I needed to test a bold text. See example below:

![aa](https://github.com/user-attachments/assets/c35a906d-f064-4ab6-894e-071600032c2d)

Finally, a suggestion. The colors marimo gives to the different types of callouts I tested in the **_dark mode_** are very close to the default dark mode in marimo. So, when we look at them, the main reason we use such editorial tricks (call the reader's attention) vanishes. I suggest allowing for a higher contrast between the original dark theme of marimo and the different types of callouts. See example below for the lack of contrast:
![aaa](https://github.com/user-attachments/assets/4b8ae14c-fa60-4fdc-b79e-6d64d3305a1f)

Thanks

### Suggested solution

Eliminate the bug + higher color contrast.

**Comment by dmadisetti** [comment]
Related: https://github.com/marimo-team/marimo/issues/1673

I think marimo just uses python's str.title (https://docs.python.org/3/library/stdtypes.html#str.title)

but maybe that's a bit too paternalistic? Thanks for the detailed investigation

**Comment by mscolnick** [comment]
We were capitalizing - i've removed it here: https://github.com/marimo-team/marimo/pull/1802/files#diff-945e550739685ddd5ad5fea7591c24f051a15ef7b8d0ae16468a7d7f769071fcL21
