### ISSUE TITLE
Brush Transparency Issue in Chart Rendering

### ISSUE THREAD

**Issue by HikariIce** [marimo-team/marimo#1811]
### Describe the bug

---
name: Brush Transparency Issue
about: Report issues with brush transparency not applying correctly during selection
title: "[BUG] Selected vs Unselected areas transparency mismatch in brush usage"
labels: bug, graphics, transparency
assignees: ''

---

**Describe the Bug**
When using the brush tool to select certain areas of the chart, I expect the unselected regions to become more transparent while the selected area remains unchanged. However, after making a selection, some parts of the unselected regions remain at full opacity (100%), despite setting their transparency levels lower.

![mmexport1721179469774](https://github.com/user-attachments/assets/ea941d65-5c85-408a-bd45-a0e29baa80cf)
![mmexport1721179474545](https://github.com/user-attachments/assets/8ecf4450-1ae5-41b7-b828-4d2ddca6a360)
![Snipaste_2024-07-17_09-27-59](https://github.com/user-attachments/assets/7575927e-020e-4fc7-8864-4b805a7a3ca2)

**Expected Behavior**
All unselected regions should uniformly adopt the new transparency level, allowing for a clear visual distinction between selected and unselected areas.

![Snipaste_2024-07-17_09-29-09](https://github.com/user-attachments/assets/45550f71-577b-4818-b9ed-da3ef4b5e6ea)

### Environment

{
  "marimo": "0.7.0",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 151 Stepping 5, GenuineIntel",
  "Python Version": "3.12.1",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.12.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.11.0",
    "black": "24.4.2"
  }
}

### Code to reproduce

```python
import marimo as mo
import altair as alt
from vega_datasets import data
```
---
```python
stocks = data.stocks()
stock_brush = alt.selection_interval(encodings=["x"])
stock_chart = mo.ui.altair_chart(
    alt.Chart(stocks)
    .mark_line(point=True)
    .encode(x="date", y="price", color="symbol")
    .add_params(stock_brush)
)

stock_chart
```

**Comment by mscolnick** [comment]
`mo.ui.altair_chart` adds it's own selection, which is probably conflicting with the selection you are passing. you can instead just remove `mo.ui.altair_chart` or remove `.add_params(stock_brush)`

**Comment by mscolnick** [comment]
I might've mis-understood the original issue. Is this an issue on `marimo`? For example, are you able to configure the desired effect without `mo.ui.altair_chart` and only using `alt.Chart`?

**Comment by HikariIce** [comment]
> `mo.ui.altair_chart` adds it's own selection, which is probably conflicting with the selection you are passing. you can instead just remove `mo.ui.altair_chart` or remove `.add_params(stock_brush)`

I am looking for a brush tool that operates horizontally rather than in a block shape. Is there a way to achieve something similar to `encodings=['x']` ?

**Comment by HikariIce** [comment]
> I might've mis-understood the original issue. Is this an issue on `marimo`? For example, are you able to configure the desired effect without `mo.ui.altair_chart` and only using `alt.Chart`?

I can indeed use `alt.Chart` only, but i want the reactivity between marimo cells

**Comment by mscolnick** [comment]
Got it - could you include what you want to achieve, but with only `alt.Chart` and not using `mo.ui.altair_chart`. This would help me reverse back into what I need to change, since both get compiled down into a vega-lite spec which will be easier to compare.

**Comment by HikariIce** [comment]
Thank you for reply. My goal is to display data (maybe a large amount) points in a line graph, with a brush to scale up.

using `alt.Chart` like this:
```python
brush = alt.selection_interval(encodings=['x'])

chart_overview = alt.Chart(traces, height=150, width=550).mark_line().encode(
    x = 'index:Q',
    y = 'value:Q',
    color = 'traces:N'
).add_params(brush)

chart_detail = alt.Chart(traces).mark_line().encode(
    x = 'index:Q',
    y = 'value:Q',
    color = 'traces:N'
).transform_filter(brush)
```
but to ensure fast rendering speed, I need to sample the data using a custom algorithm. When using a brush for horizontal selection, Resample the selected area based on the sampling.

what I want is using `mo.ui.altair_chart` to get the brush range reactively:
```python
chart_overview =mo.ui.altair_chart(
   alt.Chart(traces, height=150, width=550).mark_line().encode(
      x = 'index:Q',
      y = 'value:Q',
      color = 'traces:N'
  ).add_params(brush)
)
sampled_data = my_custom_sample_alg(chat_overview.value)
chart_detail = alt.Chart(sampled_data).mark_line().encode(
    x = 'index:Q',
    y = 'value:Q',
    color = 'traces:N'
)
```
or some other method like `on_change`, which not provide in altair.

**Comment by HikariIce** [comment]
Well, I understand your point now. I will consider disabling the Marimo selection for now. Of course, improved opacity in future versions would be even better.

Thank you for taking the time to respond amidst your busy schedule.

**Comment by mscolnick** [comment]
You could maybe do something similar to this example: https://altair-viz.github.io/gallery/select_mark_area.html

We could consider adding this to our selection, but it changes the chart quite a bit more (adding a new layer) than what we do currently to add selection (add a new param).

I am going to close this for now, if there is any action on marimo, we can re-open
