### ISSUE TITLE
SyntaxError causes cell to lock up

### ISSUE THREAD

**Issue by seantur** [marimo-team/marimo#1823]
### Describe the bug

In 0.7.6 I noticed that a SyntaxError is causing the cell to lock up. The cell output is dark, and if I fix the syntax error and rerun the cell, nothing happens. Reloading the page seems to make it responsive again. It still seems to be present on 0.7.7

This does not happen with a NameError, and does not happen on 0.7.5.

![Screenshot 2024-07-18 at 8 35 03 AM](https://github.com/user-attachments/assets/c5077e5c-2ed9-4dd5-a5f3-4c77087e2e38)

### Environment

```
{
  "marimo": "0.7.7",
  "OS": "Darwin",
  "OS Version": "23.4.0",
  "Processor": "arm",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "102.0.5005.61",
    "Node": "v22.2.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "missing",
    "ruff": "0.5.2"
  }
}
```

### Code to reproduce

A SyntaxError seems to be all it takes:

`a[]`

**Comment by akshayka** [comment]
Thanks, working on a fix -- will release soon.

**Comment by akshayka** [comment]
@seantur, we've just cut version 0.7.8 which includes the fix. It should be on PyPI momentarily. Please reopen this issue if you still run into problems, and thanks so much for reporting.
