### ISSUE TITLE
A small bug and one shortcut gone (or two)

### ISSUE THREAD

**Issue by VivaldoMendes** [marimo-team/marimo#1832]
### Describe the bug

I am testing Marimo. By chance, I encountered a small bug (see image below).

The bug is related to the use of the backslash in markdown mode. If I type, `I am "nuts"` the two primes imply that the output will be: `I am \"nuts\"`. 

The shortcut.  I am using the latest version of marimo (0.7.8). In this new version, I spotted that the shortcut `Ctrl+M` , available in previous versions, is unavailable anymore. This shortcut allowed us to change a cell into Markdown mode without using the mouse. If we insert many new markdown cells (and people usually do that in notebooks), we must resort to horrible, time-consuming mouse movements. This is highly inefficient.

Finally, I have an idea that in previous versions of marimo there was another shortcut that was also very useful: `Shift+Enter`. It ran a cell and opened a new one below. Very handy also.

Keyboard shortcuts are very useful for two reasons: they increase typing speed and reduce the physical problems that people may develop from using a computer every day (like tendinitis). 

Thanks
![a](https://github.com/user-attachments/assets/2518d84a-0a52-4feb-b6df-609dfb661486)

### Environment

????

**Comment by mscolnick** [comment]
For the markdown shortcut - I "fixed" a bug to make it stricter, by only letting you switch to markdown if its compatible. But i can see a use case to still let the user switch to markdown, regardless.

For `shift+enter`, its still there. it moves to the next cell if there is, or otherwise creates a new one. that hasnt changed.

For the main bug mentioned (escaping quotes), we will fix this

**Comment by mscolnick** [comment]
The change for being more lenient on markdown is here: https://github.com/marimo-team/marimo/pull/1834

**Comment by VivaldoMendes** [comment]
I was wrong about the `Shift+enter` shortcut. Yes, it is still available. I did not notice that the shortcut only runs a cell and opens a new one if it runs the notebook's **_last cell_**. If it is in the middle of the notebook, it runs a cell and jumps to the next one. That is great.

I'm sorry for not understanding the context of your comment: "Switch to Markdown if it's compatible." I may be missing some vital subtlety here. However, in my mind, if a cell is opened in Markdown mode, it will accept only Markdown code. I am not thinking in terms of Quarto functionalities, where we write a plain text notebook format with code fences. 

Thanks for the feedback.

**Comment by VivaldoMendes** [comment]
More on the bug. The bug related to double primes in Markdown cells does not appear if we use **_callout blocks_** in those cells. Please take a look at the image below.  However, it does appear in standard text inside a Markdown cell.

![a](https://github.com/user-attachments/assets/77aba152-1378-4a89-b82c-418c3ab5b675)

**Comment by mscolnick** [comment]
It was because we switched the default markdown formatting to be `mo.md(r""" ...` instead of `mo.md(""" ...` in order to fix latex rendering. (cc @akshayka)

**Comment by akshayka** [comment]
I'll explore a couple options for fixing this today
