### ISSUE TITLE
TOC in static export of the notebook

### ISSUE THREAD

**Issue by VivaldoMendes** [marimo-team/marimo#1837]
### Describe the bug

I am unsure if I am doing something wrong when saving a static version of a marimo notebook.  Everything works fine, the HTML file is created and I can open it in any browser. However, the Table of Contents in the active version is not available.  

Thanks

### Environment

I am on a Windows 10 machine, using Python v3.12 and marimo v0.7.9.

**Comment by mscolnick** [comment]
This is not a bug - we just dont show the sidebar when exporting as a static export

**Comment by mscolnick** [comment]
Is this something you would be open to contributing?

**Comment by VivaldoMendes** [comment]
@mscolnick , Sorry about my wrong choice of words. Thanks for correcting the title. 

Regarding my contribution, I do not know how to help beyond the feedback I have provided.  I am more of a user than a developer.  I use computing for a living in my teaching and research (I am an economist), and I have used Julia and Pluto extensively over the last 5 years (Matlab user in the old days). I am at ease using computation and a notebook, but I am not knowledgeable enough to enter the developer's territory. 

To test Marimo, I have just finished replicating one of my Pluto notebooks. Unfortunately, notebooks are (or have to be) quite large for teaching (it is useless to write down a notebook with one/two exercises in this activity). It involves 13 exercises, 20 plots, reading several data frames, some simple linear algebra, and a lot of Markdown. I think I have a good idea about how Marimo compares with other notebooks by now.  If I can help with this, I will be glad to help.

Finally, let me congratulate you and Akshay on a beautiful piece of software. For some reason, I did not enjoy IPyflow (as well as some minor variations on the reactive camp of notebooks; I like Observable, but JS is not my lawn). However, when I tried Marimo, it seemed well thought out and implemented. Nevertheless, I believe certain aspects of the notebook's architecture deserve to be improved if there are expectations of marimo's widespread adoption in teaching activities. It looks like a wonderful piece of software for such a job.

Thanks.

**Comment by mscolnick** [comment]
No worries, it's all good. We are looking at marimo all day so makes sense why the table of contents is not there, while I can totally understand it's a bug. 

If it's something you'd like (as opposed to just letting us know of it), happy to keep the issue open so maybe someone else can pick it up. I think it makes sense to have a tiny table of contents in static and read-only mode.

**Comment by akshayka** [comment]
Just tested on 0.7.11, and the TOC is not included in HTML export.

**Comment by LukeDRussell** [comment]
I'd like an automatic ToC in the exported HTML as well.
