### ISSUE TITLE
Add option to "copy as pathname" to files/folders on the file browser panel

### ISSUE THREAD

**Issue by hugoboia** [marimo-team/marimo#1838]
### Description

On the file browser panel, for all kinds of files/folders, we can see, move (dragging/dropping), delete, rename and preview, and for supported files we can also open them in the editor. Those options appear when clicking on the 3 dots icon, when hovering the file with the mouse cursor.
For now there is no option to copy the path to the file/folder.

### Suggested solution

The suggestion is to add "copy as pathname" on the 3 dots menu, similar to what we have on macOS Finder (when holding option key), so we do not need to open the OSs File Explorer to find the path to read files inside the notebook.

**Comment by mscolnick** [comment]
Great suggestion, I've added this here: https://github.com/marimo-team/marimo/pull/1841

**Comment by hugoboia** [comment]
That's awesome!
Thank you!
