### ISSUE TITLE
outputting dataframe with tons of columns crashed all marimo browser tabs

### ISSUE THREAD

**Issue by delennc** [marimo-team/marimo#1846]
### Describe the bug

Outputted a dataframe with lots of columns. Caused the tab to go unresponsive, and killing the page resulted in all marimo browser tabs dying (had many notebooks open in the marimo edit session). Had to restart the kernel, because refreshing the tabs and even the home page didn't do anything (all hung on browser refresh).

### Environment

0.7.5

**Comment by mscolnick** [comment]
can you give an example of "tons"? we can reduce the row clamping for dataframes with lots of columns

**Comment by mscolnick** [comment]
alternatively, could you give some row limits that work with your dataframe?
