### ISSUE TITLE
Running `mo.mpl.interactive` in script mode will hang

### ISSUE THREAD

**Issue by shunichironomura** [marimo-team/marimo#1869]
### Describe the bug

The attached minimal reproducible code (`a.py`) can be run by `marimo edit a.py` or `marimo run a.py`. However, when I run it by `python a.py`, it will not exit or raise any exception. When I send `Ctrl+C`, it will terminate with the following traceback:

```
Exception ignored in: <module 'threading' from '/home/nomura/.pyenv/versions/3.12.4/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/home/nomura/.pyenv/versions/3.12.4/lib/python3.12/threading.py", line 1622, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

### Environment

```
{
  "marimo": "0.7.11",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.3.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.1",
    "websockets": "12.0",
    "typing-extensions": "missing",
    "ruff": "0.5.4"
  }
}
```

### Code to reproduce

```python
import marimo

__generated_with = "0.7.11"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __():
    import matplotlib.pyplot as plt
    return plt,


@app.cell
def __(mo, plt):
    plt.plot([1, 2])
    mo.mpl.interactive(plt.gcf())
    return

if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
Thanks for supporting. `mpl.interactive` isn't supposed to be supported in script mode (do you want to use it in script mode?), but we regressed that — it used to throw an error when used in a script.

**Comment by shunichironomura** [comment]
Okay, I wasn't aware of that, sorry.

> do you want to use it in script mode?
It would be nice if I could prototype in the notebook mode with `mpl.interactive`, and then run it in script mode without needing to manually remove `mpl.interactive`. But it's not a strong reqruiement.

**Comment by akshayka** [comment]
> Okay, I wasn't aware of that, sorry.
> 
> > do you want to use it in script mode?
> 
> It would be nice if I could prototype in the notebook mode with `mpl.interactive`, and then run it in script mode without needing to manually remove `mpl.interactive`. But it's not a strong reqruiement.

Yep, makes sense! Thanks for reporting. The fix will be included in the next release, and instead of raising an error it will just log a warning.

**Comment by akshayka** [comment]
It will still work (but it hasn't worked for a while). I can remove the warning.
