### ISSUE TITLE
mo.ui.dataframe isnt letting me filter columns of pandas df with dtype datetime64[ns] and float

### ISSUE THREAD

**Issue by ayushwd** [marimo-team/marimo#1880]
### Describe the bug

while filtering a pandas dataframe, I am not able to filter the columns with dtype datetime64[ns] and float while in the transformed df filter column window it says the column cannot be filtered.
Images for reference
![Screenshot from 2024-07-25 13-38-43
![Screenshot from 2024-07-25 13-38-59](https://github.com/user-attachments/assets/d3d3170e-bfcc-4e93-88d7-b4020cdf5dbb)
](https://github.com/user-attachments/assets/a1934408-8c95-4da9-b5d8-9a8f427f2651)

### Environment

{
  "marimo": "0.7.11",
  "OS": "Linux",
  "OS Version": "3.10.0-1160.105.1.el7.x86_64",
  "Processor": "x86_64",
  "Python Version": "3.11.5",
  "Binaries": {
    "Browser": "122.0.6261.69",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.1",
    "websockets": "12.0",
    "typing-extensions": "4.9.0",
    "ruff": "0.5.4"
  }
}

**Comment by mscolnick** [comment]
We haven't gotten to supporting date filtering. 
We can look into prioritizing it.  We are also open to a contribution, if this is something you'd like to tackle.

**Comment by ayushwd** [comment]
Hi Myles, I noted that this issue arises when I open my marimo notebook with an environment containing marimo version 0.7.11 while opening the same notebook with an environment with marimo version 0.3.2 allows me to filter on dates as well as float values.

P.S. also noted that the transformed dataframe takes the dtype date and number for datetime64[ns] and float type column while the old marimo version i.e. 0.3.2 the transformed dataframe takes the default datetime64[ns] and float dtype.

**Comment by mscolnick** [comment]
oh got it - then this is definitely a regression. I think I have an idea and can look into it today

**Comment by mscolnick** [comment]
Fix incoming (https://github.com/marimo-team/marimo/pull/1891)
