### ISSUE TITLE
marimo edit C:\Users\user\Desktop\python\pkg\examples finds notebooks, but can't open them

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1895]
### Describe the bug

I ran `marimo edit C:\Users\user\Desktop\python\pkg\examples` with a fully qualified path. It opened the page with running notebooks, recent notebooks, workspace. It lists all the notebooks in `examples`. But when I click on one I get a error screenshotted below. When I use a relative path, starting in `C:\Users\user\Desktop\python\pkg\` and running `marimo edit examples` then it works expected.

Error:
![image](https://github.com/user-attachments/assets/b3b38603-d06a-4345-b327-3953d5e56f00)

### Environment

{
  "marimo": "0.7.12",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.5.5"
  }
}

**Comment by akshayka** [comment]
Thank you for reporting and the reproduction. I confirm that I can reproduce.
