### ISSUE TITLE
Ancestor cell links don't move focus to the failed cell

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1917]
### Describe the bug

Ancestor cell links don't move focus to the failed cell. I feel like I've seen this work before, so this issue might be intermittent, but currently it doesn't work for me at all. BTW this is a super useful feature!

### Environment

{
  "marimo": "0.7.12",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.5.5"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.7.12"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __():
    a = 1
    return a,


@app.cell
def __():
    c = 4/0
    return c,


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __():
    return


@app.cell
def __(c):
    print(c + 1)
    return


@app.cell
def __():
    b = 1
    return b,


if __name__ == "__main__":
    app.run()
```
`marimo edit` the above notebook, scroll to the bottom. Click on the link in the screenshot. It doesn't move focus up to the failed cell. If they are both visible at the same time, it will increase the highlighting on the failed cell.
![image](https://github.com/user-attachments/assets/de8b50cf-cc80-4fb8-814d-890a0a818c0c)

These links still move focus:
![image](https://github.com/user-attachments/assets/7630f1d5-ee6d-4d88-b264-f18761dc79c9)

**Comment by mscolnick** [comment]
Thanks for reporting. This has already been fixed, but not released yet here: https://github.com/marimo-team/marimo/pull/1905

**Comment by akshayka** [comment]
@ggggggggg , version 0.7.13 is now released with the fix.
