### ISSUE TITLE
option to set print fewer decimal places in datafames

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1929]
### Description

I would like to have marimo fit more columns on the screen when printing dataframes. One way to help with this would be to be able to provide guidance on how to print values more compact. 

### Suggested solution

I think being able to specify how many significant figures I'm interested in would help a lot. Maybe something like `mo.ui.dataframe(df, sig_figs_all = 4)` to use the same value for all columns and `mo.ui.dataframe(df, sig_figs_all=3, sig_figs ={"a":4, "b":5})` to specify columns. Or some way to set it for the whole notebook by default.

### Additional context

I'm running out of space!
![image](https://github.com/user-attachments/assets/3bd8d87a-39e5-4178-a806-a8e3cbdeeefb)

Here the gain columns I probalby only care about 2 sig figs. The `e` columns are numbers that were typed with fewer sig figs, so they look nicer. For the `ph` columns I'm interested in about 4 sig figs. I don't want to round the numbers because I want further computations to us more than those amount of sig figs. Those are just what I need to reason about the data.

**Comment by mscolnick** [comment]
You can already do this today with `format_mapping` in `mo.ui.table()`

Here is an example:

```python
# format_mapping is a dict keyed by column names,
# with values as formatting functions or strings
def format_name(name):
    return name.upper()


table = mo.ui.table(
    data=[
        {"first_name": "Michael", "last_name": "Scott", "age": 45},
        {"first_name": "Dwight", "last_name": "Schrute", "age": 40},
    ],
    format_mapping={
        "first_name": format_name,  # Use callable to format first names
        "age": "{:.1f}".format,  # Use string format for age
    },
    label="Format Mapping",
)
```

You can see this from the docs as well.

**Comment by akshayka** [comment]
I believe @ggggggggg is using `ui.dataframe`, which has not been updated to take a `format_mapping`.

**Comment by ggggggggg** [comment]
`format_mapping` certainly seems sufficient. Perhaps I would still like a way to set a default numeric formatter. But I can't get it to work.

Using the above example in a cell I get
```python
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\marimo\_runtime\executor.py", line 192, in execute_cell
    exec(cell.body, glbls)
  File "C:\Users\user\AppData\Local\Temp\marimo_23228\__marimo__cell_Hbol_.py", line 3, in <module>
    table = mo.ui.table(
TypeError: table.__init__() got an unexpected keyword argument 'format_mapping'
```

And it doesn't show up in my live docs.
![image](https://github.com/user-attachments/assets/4e5a10bd-6011-4d36-b5f4-5ed967088210)

This is despite me updating marimo this morning.
{
  "marimo": "0.7.12",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.5.5"
  }
}

**Comment by akshayka** [comment]
The latest version on PyPI is 0.7.14. It looks like conda forge is one release behind on 0.7.13.

**Comment by ggggggggg** [comment]
`mo.ui.table(format_mapping=...)` does what I was asking for, so closing this.
