### ISSUE TITLE
`marimo edit` stuck on update check in Internet-restricted environment

### ISSUE THREAD

**Issue by mutongx** [marimo-team/marimo#1936]
### Describe the bug

I'm using marimo behind a firewall that blocks all Internet connections. Running `marimo edit` stucks forever and prints out nothing, and after some debugging I found marimo stuck in update check, and specifically at the following `urlopen` call, which sends a request to https://pypi.org/pypi/marimo/json.

https://github.com/marimo-team/marimo/blob/43b6ea9889be897fea910f279b9693fd96cadd09/marimo/_cli/upgrade.py#L93

I'm currently adding a `timeout` option in my venv as a dirty workaround. Not sure about what's the best way to fix this. Maybe marimo can provide a way to disable update checks?

I can try to implement if the marimo team think it's OK.

### Environment

```
{
  "marimo": "0.7.14",
  "OS": "Linux",
  "OS Version": "5.15.0-52-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.0",
    "uvicorn": "0.30.3",
    "starlette": "0.38.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.5"
  }
}
```

**Comment by mscolnick** [comment]
Oh that's a good call out. I can see that being problematic. 

It would be great if you could make the contribution. Also, maybe we should provide a default timeout, if you don't mind doing that in the same PR. Otherwise, we can get to it among our own priorities. 

Thanks for filing this.

**Comment by mutongx** [comment]
Yes I can make the contribution. I will submit a PR in a few days.
