### ISSUE TITLE
Markdown cells using dark font with dark background

### ISSUE THREAD

**Issue by hugoboia** [marimo-team/marimo#1949]
### Describe the bug

When using markdown cells, markdown headings (the ones using '#') are using dark colored font when theme is changed to dark, making it difficult to read.
It is even worse when downloading the notebook as PNG or plotting as PDF, because even normal text (other than markdown headings) appear in dark color.

### Environment

I'm currently using version 0.7.16, but I've noticed this behavior after 0.7.14 (the one that introduced PDF printing).

### Code to reproduce

- Open a notebook in edit mode, create a markdown cell and type "# Heading" inside;
- On "settings > display" change "theme" to "dark".

**Comment by akshayka** [comment]
Thanks for reporting. It looks like this was broken in https://github.com/marimo-team/marimo/pull/1892

**Comment by akshayka** [comment]
@hugoboia , thanks for reporting. Version 0.7.17 includes the fix. It should be available on PyPI within 10-20 minutes.

**Comment by hugoboia** [comment]
That's awesome!
Thank you!
