### ISSUE TITLE
Printing / showing charts generated with plotnine

### ISSUE THREAD

**Issue by tomsing1** [marimo-team/marimo#1953]
### Describe the bug

I am trying to output charts generated with the plotnine module (version 0.13.6). 

When I paste the content of the `__()` function definition (e.g. from `from plotnine ...` to ` p.show())` shown below into a cell in an interactive marimo session (with `marimo edit`), the chart is shown (see screenshot). A warning is logged in the console that recommends using the `plot.show()` method - which I am already using. When I run the file as an app (via `marimo run`), the chart is not generated at all.

<img width="709" alt="screenshot" src="https://github.com/user-attachments/assets/c55602cb-b11b-4a0e-af47-77df5501aee2">

Console:

```
/Users/me/miniconda3/envs/marimo/lib/python3.12/site-packages/marimo/_messaging/ops.py:469: FutureWarning: Using print(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().
```

Are charts generated with `plotnine` supported by marimo, yet? Or perhaps I am missing something to get them to be displayed correctly?

### Environment

{
  "marimo": "0.7.17",
  "OS": "Darwin",
  "OS Version": "23.5.0",
  "Processor": "arm",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "127.0.6533.89",
    "Node": "v21.6.2"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.4.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8",
    "pygments": "2.17.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.11.0",
    "ruff": "0.5.5"
  }
}

### Code to reproduce

import marimo

__generated_with = "0.7.17"
app = marimo.App(width="medium")

@app.cell
def __():
    from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
    from plotnine.data import mtcars

    p = (
        ggplot(mtcars, aes("wt", "mpg", color="factor(gear)"))
        + geom_point()
        + stat_smooth(method="lm")
        + facet_wrap("gear")
    )
    p.show()
    return aes, facet_wrap, geom_point, ggplot, mtcars, p, stat_smooth

if __name__ == "__main__":
    app.run()

**Comment by akshayka** [comment]
@tomsing1, the appropriate function is `draw`, which returns a matplotlib figure that marimo can show.

The `show()` method calls' `show` method, which doesn't return anything but instead emits to marimo's console area.

![image](https://github.com/user-attachments/assets/c76c4b40-0f6e-4116-b220-2c23e8e85718)

```
import marimo

__generated_with = "0.7.14"
app = marimo.App(width="medium")


@app.cell
def __():
    from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
    from plotnine.data import mtcars
    return aes, facet_wrap, geom_point, ggplot, mtcars, stat_smooth


@app.cell
def __(aes, facet_wrap, geom_point, ggplot, mtcars, stat_smooth):
    p = (
        ggplot(mtcars, aes("wt", "mpg", color="factor(gear)"))
        + geom_point()
        + stat_smooth(method="lm")
        + facet_wrap("gear")
    )
    p.draw()
    return p,


if __name__ == "__main__":
    app.run()
```
