### ISSUE TITLE
Configure how much runtime information autocompletion uses

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#1960]
### Describe the bug

I have a variable, and used tab completion, and it did not show the fields of the variable. It only shows the fields of the return type of the function the variable came from. I have an actual object, I want to see it's fields and functions, not just what it can know from type annotations.

### Environment

{
  "marimo": "0.7.17",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "126.0.6478.127",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.5.5"
  }
}

### Code to reproduce

First if I just create the object without using type annotation, I can see both fields with tab completion.
![image](https://github.com/user-attachments/assets/7116989f-9a90-4fa3-91b0-21f2129b067d)

Then if I return the same exact object via a type annotated function, I can only see the fields known via the type annotation. It feels like I'm being punished for trying to adopt type annotation by having less access to runtime information.
![image](https://github.com/user-attachments/assets/7f0d737f-bd26-4cd9-8034-da2cd85b81ef)

**Comment by akshayka** [comment]
I believe the behavior makes sense. If `return_b` claims to return an instance of `A`, code shouldn't assume it has access to fields of `B`; `b2.b` won't pass type-checking of the type checker thinks `b2` is of type `A`. So the type annotated code is stricter, because presumably you're adopting type annotations because you want to enforce better coding practices.

**Comment by ggggggggg** [comment]
I understand that argument, it does make sense. But marmio multiple uses, not only the best coding practices uses. It's also basically a debugger in a lot of my usage and there I want the runtime information wtihout the need to edit the code I'm debugging. Would you consider a toggle in the settings to change this behavior?

Or at least make it respect a function like
```python
def reveal(x):
    return x
```
to strip type annotation for debugging.

See `reveal` not working here
![image](https://github.com/user-attachments/assets/2ff12765-fe78-4f2c-ac3f-6343e14eba1e)

**Comment by akshayka** [comment]
Okay, I understand your perspective, thank you for explaining.

I would indeed consider that. The only thing is that we currently use Jedi for completion and mean to migrate off it, since it's not actively developed. So I'm hesitant to add new features, since it could make migration more difficult.

**Comment by ggggggggg** [comment]
Closing this in favor of #1963
