### ISSUE TITLE
Teaching use cases: e.g., render markdown cells by default + hide markdown source

### ISSUE THREAD

**Issue by odanoburu** [marimo-team/marimo#1975]
### Description

My problem is the following: I am teaching and I want to have an app view (like Slides, Vertical, Grid) geared to this use case. 

The normal edit view is almost good enough, but I would love to have markdown cells work similarly to the ones in Jupyter notebooks, where they are rendered by default, with the user having to double click (or press Enter) to edit them. Is there a way to do that? The problem with the edit view is that it is a bit distracting to have both the source markdown and the rendered markdown together (plus I have to render it manually every time since I'm not running my cells automatically when the notebook opens). Another small issue is that for teaching maybe showing the results below the cell is better, since the focus is on the code, not the results, but I can live with that (although it might be easy to add a configuration option).

An option is have another app view, or a way of customizing the Slides view; if I could have a way of indicating that I want a certain code cell to show up in the slides it would be adequate too, although it might not be very ergonomic if I ever need to go back to some other slide.

I am aware these ideas might all be feature creep inducing, however. Thanks for marimo by the way! I'm enjoying it :)

### Suggested solution

Add one of the suggested customizations, if they align with marimo's project goals.

**Comment by akshayka** [comment]
> rendered by default, with the user having to double click (or press Enter) to edit them.

We don't plan on doing this. Unlike Jupyter, in marimo markdown is produced by evaluating a Python function — this lets you interpolate Python values into your markdown with an f-string, for example (`mo.md(f"")`). But this also means if the user tells us they don't want notebooks to automatically execute on startup, that means we can't render markdown automatically either. Hopefully this is something you and your students can get used to.

> I would love to have markdown cells work similarly to the ones in Jupyter notebooks, where they are rendered by default, with the user having to double click (or press Enter) to edit them. Is there a way to do that?

We may have this one day. In the meantime, you can hide the code for a cell to make it less distracting through the cell action menu: https://docs.marimo.io/guides/editor_features/overview.html#cell-actions.

> Another small issue is that for teaching maybe showing the results below the cell is better, since the focus is on the code, not the results,

This is configurable via the notebook settings (gear icon, top right of the editor)

> if I could have a way of indicating that I want a certain code cell to show up in the slides it would be adequate too

That's interesting, we hadn't considered making code visible in the slide. I can see that being a helpful configuration option.

**Comment by odanoburu** [comment]
Thank you for the tips, that helps a lot! I don't know how I missed the configuration for result placement before, I did check for it…

> That's interesting, we hadn't considered making code visible in the slide. I can see that being a helpful configuration option.

I can see this being useful in a technical meeting too, not just in a teaching context. Maybe some kind of magic command system would solve this and other problems (there could be a 'always-render on startup' command or something). But I understand this might introduce bloat if not well thought out. I'm satisfied enough with the hide cell action and the results being below the cell for now :) Thanks again. Feel free to close this issue or change its title to reflect this feature request btw.

**Comment by Andrew-S-Rosen** [comment]
I stumbled upon this because I had somewhat similar questions about selectively showing code in the preview view. But just wanted to say that I'm definitely using marimo for teaching a graduate-level engineering course this fall. I think it'll be a great use case!

**Comment by odanoburu** [comment]
Hey @akshayka, I've using marimo for the past few weeks with no big problems so far, so thanks again! Two minor points that came up were:
- the apparent upper limit on the font size (I had to zoom in with the browser so the students in the back could read the notebook). Of course that depends on the projector and screen resolution too;
- the JSON output of multiple values returned by a cell: if the last statement (and expression) on a cell is `True, False`, the output seems to be `json.dumps((True, False))`, which then uses JS syntax for True/False. This can be confusing to Python newcomers… I understand if there's a reason for this, but if there isn't maybe using something like [ast.unparse](https://docs.python.org/3/library/ast.html#ast.unparse) would be better, although that's far from a pretty-printer. There's a workaround for this though, I can just use `print(True, False)`.

Do tell me if you'd like me to open new issues or just write up smaller issues like these in this thread.

**Comment by akshayka** [comment]
@odanoburu Thanks for the additional feedback — new issues will be easier for us to track, if you don't mind!

I will fix the upper limit on the code font size right now
