### ISSUE TITLE
Return to "home" from an open notebook

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1984]
### Description

Our users would like to return to the marimo "homepage" (which has the list of marimo notebooks in a directory, and is what you see if you run `marimo edit` without a filename) from an open notebook.

### Suggested solution

This could be via a button in the notebook actions/hamburger menu, or something more prominent like a home icon. When returning to home, the notebook would remain running.

**Comment by wasimsandhu** [comment]
Grabbing this one 🥷

**Comment by akshayka** [comment]
Closed by #1997
