### ISSUE TITLE
Slides Configuration: Show Code

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#1985]
### Description

From @odanoburu, #1975: A slide configuration to optionally show code in slides, in addition to output. 

### Suggested solution

When configured to show code, the entire cell editor is shown, together with its output. The configuration could be through the `--include-code` CLI arg.

**Comment by mscolnick** [comment]
@odanoburu - could you help us by letting us know how you may want to use the code in the slides? what sort of configuration would help?

For example, we are looking to answer:
- Should this be a small collapsible footer that expands up? Or does it come from the side?
- Should this overlap (e.g. 20%) of the slide or push the content up? Or can it be "pinned"?
- Should it be sliding?

**Comment by mscolnick** [comment]
Closing this since it is now possible with [`mo.show_code()`](https://docs.marimo.io/api/outputs.html#marimo.show_code)

```python
def factorial(n: int) -> int:
    if n == 0:
        return 1
    return n * factorial(n - 1)


mo.show_code(factorial(5))
```
