### ISSUE TITLE
list repr should use columns

### ISSUE THREAD

**Issue by majidaldo** [marimo-team/marimo#1987]
### Description

the list repr gives you all elements in a column which wastes horizontal space

### Suggested solution

using columns fills out this horizontal space.

**Comment by akshayka** [comment]
Thanks for the suggestion.

You mean this?

<img width="865" alt="image" src="https://github.com/user-attachments/assets/cebf180d-1bf4-4772-87c7-071a4f3a0044">

We don't plan to change this representation anytime soon. You can collapse the representation to save vertical space. Alternatively, convert the list to a string:

<img width="818" alt="image" src="https://github.com/user-attachments/assets/6a6ea7fb-9424-4a80-894d-90f7434deb56">
