### ISSUE TITLE
Optimization of the update check action at startup

### ISSUE THREAD

**Issue by dingzb** [marimo-team/marimo#2002]
### Description

I often experience long startup times when using Marimo. After reviewing the code, I found that during the first startup each day, marimo will checks for updates by accessing the URL `https://pypi.org/pypi/marimo/json`. The response from this API is relatively large (over 62k for version 0.7.19, under good network conditions, it takes about 25 seconds to complete the check). 

### Suggested solution

1. Add an option to not check for updates, for example `--disable-check-update`
2. Change the update check API to `https://pypi.org/rss/project/marimo/releases.xml`, as this API response is smaller(2.3k).
3. Add a default timeout for update checks to prevent excessively long waiting times.

**Comment by dmadisetti** [comment]
Thanks for the note, the flag actually does exist as:

https://github.com/marimo-team/marimo/blob/124f457d40619d869bc201517ca3d60ebe0784c3/marimo/_cli/cli.py#L254

But I do think the endpoint change makes sense, but maybe marginal? There is a timeout of 5 seconds, but maybe that's not working? 25 seconds seems a little long

**Comment by mscolnick** [comment]
This seems to be faster, but using a non-public api

```python
import requests
from packaging import version
import re
from urllib.parse import urljoin

def get_latest_version(package_name, timeout=5):
    url = f"https://pypi.org/simple/{package_name}/"
    
    try:
        response = requests.get(url, timeout=timeout)
        response.raise_for_status()
    except requests.RequestException as e:
        return f"Error: {e}"

    version_pattern = re.compile(r'>({}-([^<]+)).tar.gz<'.format(re.escape(package_name)))
    versions = version_pattern.findall(response.text)
    
    if not versions:
        return "No versions found"
    
    latest_version = max(versions, key=lambda v: version.parse(v[1]))
    return latest_version[1]

package_name = "marimo"
latest_version = get_latest_version(package_name)
print(f"The latest version of {package_name} is: {latest_version}")
```

**Comment by dingzb** [comment]
> Thanks for the note, the flag actually does exist as:
> 
> https://github.com/marimo-team/marimo/blob/124f457d40619d869bc201517ca3d60ebe0784c3/marimo/_cli/cli.py#L254
> 

That's work,  I checked the code in my local version and didn't see this update, I should pull the code promptly.

> But I do think the endpoint change makes sense, but maybe marginal? There is a timeout of 5 seconds, but maybe that's not working? 25 seconds seems a little long

The timeout setting is appropriate,  (25s timeout occurs only in cases of bad network, with the `--skip-update-check` option, these issues are no longer a problem).

Thanks!

**Comment by dingzb** [comment]
> This seems to be faster, but using a non-public api
> 
> ```python
> import requests
> from packaging import version
> import re
> from urllib.parse import urljoin
> 
> def get_latest_version(package_name, timeout=5):
>     url = f"https://pypi.org/simple/{package_name}/"
>     
>     try:
>         response = requests.get(url, timeout=timeout)
>         response.raise_for_status()
>     except requests.RequestException as e:
>         return f"Error: {e}"
> 
>     version_pattern = re.compile(r'>({}-([^<]+)).tar.gz<'.format(re.escape(package_name)))
>     versions = version_pattern.findall(response.text)
>     
>     if not versions:
>         return "No versions found"
>     
>     latest_version = max(versions, key=lambda v: version.parse(v[1]))
>     return latest_version[1]
> 
> package_name = "marimo"
> latest_version = get_latest_version(package_name)
> print(f"The latest version of {package_name} is: {latest_version}")
> ```

Thank for you replay. Yes, the response speed is indeed faster, Just as you mentioned, this API is a `Legacy API`. I think  `https://pypi.org/rss/project/<project_name>/releases.xml` will be better, although it is primarily intended for RSS subscription.
