### ISSUE TITLE
Track database objects in  dataflow graph

### ISSUE THREAD

**Issue by firerain42** [marimo-team/marimo#2019]
### Description

I really like the SQL integration.
However, when database objects like tables and views are created in SQL cells, other cells that depend on these might not be executed in the correct order.

```python
import marimo

__generated_with = "0.7.20"
app = marimo.App(width="medium")


@app.cell
def __(mo, my_table):
    _df = mo.sql(
        f"""
        SELECT * FROM my_table
        """
    )
    return


@app.cell
def __(mo, my_view):
    _df = mo.sql(
        f"""
        SELECT * FROM my_view
        """
    )
    return


@app.cell
def __(mo):
    _df = mo.sql(
        f"""
        CREATE OR REPlACE TABLE my_table (a text);
        INSERT INTO my_table (VALUES ('foo'), ('bar'));
        """
    )
    return


@app.cell
def __(mo):
    _df = mo.sql(
        f"""
        CREATE VIEW my_view AS (SELECT * FROM my_table WHERE a LIKE 'f%o')
        """
    )
    return


@app.cell(hide_code=True)
def __():
    import marimo as mo
    import pandas as pd
    return mo, pd


if __name__ == "__main__":
    app.run()
```

### Suggested solution

Include the created tables, views, etc and their references in the dataflow graph.

### Alternative

As a workaround users can track the dependencies through python objects:
```python
import marimo

__generated_with = "0.7.20"
app = marimo.App(width="medium")


@app.cell
def __(db_my_table, mo, my_table):
    db_my_table

    _df = mo.sql(
        f"""
        SELECT * FROM my_table
        """
    )
    return


@app.cell
def __(db_my_view, mo, my_view):
    db_my_view

    _df = mo.sql(
        f"""
        SELECT * FROM my_view
        """
    )
    return


@app.cell
def __(mo):
    db_my_table = None
    _df = mo.sql(
        f"""
        CREATE OR REPlACE TABLE my_table (a text);
        INSERT INTO my_table (VALUES ('foo'), ('bar'));
        """
    )
    return db_my_table,


@app.cell
def __(db_my_table, mo):
    db_my_table
    db_my_view = None
    _df = mo.sql(
        f"""
        CREATE VIEW my_view AS (SELECT * FROM my_table WHERE a LIKE 'f%o')
        """
    )
    return db_my_view,


@app.cell(hide_code=True)
def __():
    import marimo as mo
    import pandas as pd
    return mo, pd


if __name__ == "__main__":
    app.run()
```
For this pure SQL cells can't be used.
Even worse, this leaves the user in charge of making sure that all database objects are tracked correctly. If one is missed the reproducibility of the notebook relies on the placement of the cells (just like in jupyter notebooks).

**Comment by dmadisetti** [comment]
Extracting references from the SQL is already done, so this should work for handling workflow without the verbosity

```python
    my_view = mo.sql(
        f"""
        CREATE VIEW my_view AS (SELECT * FROM my_table WHERE a LIKE 'f%o')
        """
    )
```

```python
    my_table = mo.sql(
        f"""
        CREATE OR REPlACE TABLE my_table (a text);
        INSERT INTO my_table (VALUES ('foo'), ('bar'));
        """
    )
```

But `my_view` and `my_table` will be None. It would be nice if the creation statements created dataframes as well.
So if `CREATE OR REPlACE TABLE my_table (a text)` is a standalone statement, the variable `my_table` is auto set if the reference is not private- to enforce that the sql table and variable matched.

**Comment by akshayka** [comment]
Thanks for reporting. I have it on my TODO list to look into parsing SQL definitions and references more thoroughly, perhaps using `sqlglot`, and integrating them into the dataflow graph.

**Comment by dmadisetti** [comment]
So just a note, duckdb has a native `duckdb.tokenize()`, and the grammar is pretty fixed: https://github.com/duckdb/duckdb/blob/main/third_party/libpg_query/grammar/statements/create.y so could directly leverage that

**Comment by akshayka** [comment]
> So just a note, duckdb has a native `duckdb.tokenize()`, and the grammar is pretty fixed: https://github.com/duckdb/duckdb/blob/main/third_party/libpg_query/grammar/statements/create.y so could directly leverage that

Oh nice, even better. I'll look into that.
