### ISSUE TITLE
.marimo.toml frequently reset

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#2022]
### Describe the bug

No sure if this is because I run unit tests frequently or what- but I find my `.marimo.toml` is commonly reset, which is a little frustrating for when I'm doing non-marimo work. Or maybe with version upgrades? Not sure, haven't dug into it too deep

One mitigation method might be to have directory level `.marimo.toml` files, that only defaults to ~/.marimo.toml if an overriding one isn't found while traversing up the tree (This isn't in the docs, and I haven't checked source if this already exists).

Posting here, because I'd bet others have run into this as well.

### Environment

HEAD

**Comment by mscolnick** [comment]
@dmadisetti I am pretty sure it is a leaky test that is doing that.
