### ISSUE TITLE
Render URLs in tables as hyperlinks

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#2023]
### Description

For tables with string columns, it would be convenient if marimo automatically rendered URLs as hyperlinks. 

### Suggested solution

Use a regular expression to detect whether a string value is a URL, and if so display it as a hyperlink.

### Alternative

Users can embed markdown objects in tables, but this complicates exporting tables as CSVs (right now we implicitly call `str` on objects, which serializes them as `Html`, not useful).

**Comment by mscolnick** [comment]
Here is a quick (untested) react component that can detect and render hyperlinks: 
```python
const UrlDetector = ({ text }) => {
  const urlRegex = /(https?:\/\/[^\s]+)/g;

  const createMarkup = (text) => {
    const parts = text.split(urlRegex);
    
    return parts.map((part, index) => {
      if (part.match(urlRegex)) {
        return (
          <a key={index} href={part} target="_blank" rel="noopener noreferrer">
            {part}
          </a>
        );
      }
      return part;
    });
  };

  return <>{createMarkup(text)}</>;
};
```

**Comment by rpattekar** [comment]
take

**Comment by mscolnick** [comment]
hi @rpattekar, i apologies, i already did this one (#2026). I wanted to try out the new GitHub Copilot Workspace and wanted to try it on an easier feature.
