### ISSUE TITLE
Add Cell button unclickable on tiling window

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2035]
### Describe the bug

When working on tiling windows (or smaller windows), add cell buttons on the left side of each cell are unclickable

I'm using `aerospace` for tiling window, not sure if it's a specfic issue with `aerospace`.

https://github.com/user-attachments/assets/f65b5589-b9dc-433b-bec5-a584b96cd47d

### Environment

```json
{
  "marimo": "0.7.20",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.5.1"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.2"
  }
}
```

**Comment by mscolnick** [comment]
I think there is some overlapping hover areas or css that is making it disappear. its likely a css change on the hover-target area outside the cells
