### ISSUE TITLE
"Create permalink" delivers a link to intro tutorial, rather than my notebook

### ISSUE THREAD

**Issue by davidnmora** [marimo-team/marimo#2049]
### Describe the bug

1. I published [this notebook](https://github.com/davidnmora/energy-data/blob/main/Gas%20Price%20Roller%20Coaster.py) to WASM. I am running locally in the browser on Mac using pip.
2. I opened [the link](https://marimo.app/#code/JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoAODtltRGDBMEyVBwCCQgBQ1y9RixAVgAVxAsANHEFhMMWgBs8igOKIAznDAoAxnjhQIh41Di2IlslBYBKDGgAAroc9i5o5HgAZnDY0r4AXGhwKXCgkLCiKCAQOlY5GKlp4NDwYIgE5JZ51uTJqemlcATqYACeNQRghQ0lmVGqBLYwEM4WPSmNmRZ4iABG0AQ1FgTjRSsWHDMw+nR4ytIWMG3GilVQANY4KOR+9ZN98EgwYIYQMIbAcxztr+81rxg90ceBgqigSwGQxGY20OW0XW0YHISMMMG0GwCwSEoTw4UiMTiOUSwJyHBA5GkwKKPhY-CKRQAxHAABIQKhwOiIABuDgkyjsFTg5BQ3OABBwnPmtCs3LEFB0bwlFmAkRBMEQwEMcBw1RswHsFgA-BMGQBJVZgYBQBVzDr0YBWABMbAAjGw4AA5ACaABVQHgrB4CERhgqLLZSN5rG90XAAFQAbQAIqLxZKAMp0YBRGBWcUjOAAJTwvKgMwAutI6DAXhYEgB6BvIWzZ3kcAhtAzKTYeEANqiDjtdgO9iD90CIfDlfAWBsu90NtgAViXTobc1UKqIFjnbCdyhgdk2NZAhl88Y4pqZjOZydIiDgFgg4MN19SZvcL8M5AIAHJ4CicVyB0Tsn3TYxtD7Gw8D2VZgF5YUHyfF8oENDFck-I5aFbBVZlbBBQTsOARnwehiDgKInBAJ9S2IRBtXIHMomIQh4GfV9AzgQ48AcRMHSsAh3jwBYIAuSjoAQaAHEiDUtQsKsazrRsGxwWg6FUb4+wbKoxV-HISAbQhiBwNoAFoqg1Dc3jmBskHFBtk2IBC8AAUhdABVDN3LYEAtUDHyRRcggfLAYgfMjK0NR87kLB83U4pdfV7B+NpfESOB3xSMy4FTBD02FR0NSGBwwrcSLaEfZRLHBLj4wY7UchGNxeWzWxjAseMdFsWwnF3axNM+WxHE8cgLG0PVBsdPYQLtEi9jgAAxCh6O1FlgBwOgqEQDoJHIPyCCKkgDAgAhqVSHLzCsZKuOQBxxSiQxSGAU6dHIAArLcyBAwtngI4MyD6ZAOi85M4DlQxVDwc6UjpelUn8GlQXBM6MGxMBcXxaJYkwaRkRJIo-I6zAgt5AhMDKzAKo1TAKkoBKKbsBxmGRDgbUQShbAsblpD-JSwHrJsSCoDg1PoTSt2IAG2NCccdJ5VUCAMxAjKIKBTIsh87M1Ah5asyJRQoTWrKJwMScN8nKepxBacqXBLEZg08FCbm-0R1IbTBCEEH8ixzeCiniCpwRKtt+mHZuzQsRCMJDAibGiV9-2ycDqBg6im26ftv3I6kgnUiQAAPTA2lmNxmDJVRgDZip8EwCxPgNjgqPHevnMDaRTb90nCFT9PQ6zhmbo4UvkG0AYXGoVUFF9KAof8UkIHJSkYcouHV+ZRatWjGgHSWciSIDRxa7wBI4FdABOABmAA2OAcpdJ0r9XgBvIuS7LgBfVf16Kd2Uk9ijUQxdR5QCjmjGOeI44EhxlSIoUJhijEMONUkiAQFlyjoTJOPdLZB2tmHbOjt7CYNSICEhKQNjkLgIXT4IAqEnFAFHfOKQYFRGgM8D+yBpCgOYQyQB3sWB-hYHAAA1JRP8L9QGfz-ImMyToEgVlNIEBBMJkGhEQLhYEMCRSICoFTU6oZvr10jLWIOfwYCd3FHCNBvD4GqEnuQGIFdsEWz7vgweEcmar0cSILuyde5WxDjTDxOcmaJlXkUSxxMcFuKCZnO2Q8mYjzLnAAAPBXGxcAABkETUhRLNjEwJGcCGJKdsk5AcAAB8ziCD-wZIojecAADC7MyDzQcBGKMFFzGr0BM3DatVpBARwCqAAXiYaQ7ptA33SqvTppi07mJEBsLYJjvDmLgQyLZllECMEcVQrZKRC6KC7sKC21gKLWy0LklIbRFAPSeidJYHNPpHAVAlawTN4ZbIXocuAzI9ogU+DuL8IY8DDAKgfSABY1iHL6Rsm5wooiJiUL7M5wULnlTiSwCsBzDmOJRQ856r0XlfXeXqL5uLEXAsDMcU4f4zJ-m0IipAlxiCMD-BAP8q9fmHOZBmUE7TqFmTQY6UCIFzKiqsLQmUV4-l9JoaAaQ8ZFUgDqUUPpDCQDKq1byrZAKQzvFIA4fCDBoUEHgLvBgB9QGrzYW4YAaQlgkAlHgaQjithcjComNgFZbFwrRBwMghcLGIqKAS1FHV0Vk0xe4bFFYOBaggLYRMwAqV-L+RGolTy3qvO+jqClTscWJreCmtNeKM0SSgBw0B7rkUsFAcWpNZa-UVozWwi1YyTAXzbX8rkHKUCbRgNyytKQ9UMn5XQdkQqenysDTQ+YeJpAsAALJoryjGgAChRJp2L1WkMDScRdhhl0WkesSpYe080KiunATdTNuKg18HcOdMAg1GDdSwDMayKKbtjHACAMQ11Ro3YQO9O64ngysGex5L1L0fTJSBW996i37oAcjb2fScCRniAEcNwt9FgrDJQeZ3gKaxk7mgzhUAOAQyhj63FwDqO0YYvR10frgT8KWDovRwZDEUGMV0xZsZx7sNINR6OOJY7x0JLjPxhS8FxJKZ4p2vDVUiETPJ1xRSB4JJU-YFFpycGxquQmg68Q4QuIDjp4JenQlO0M2i4zZU40Z2LUXeIiiihao01p6zinikhKIXgQlBBz05tJW8kCHybrufFBZn20TtMBd0+HezBmWDZrg7mxDBbrqUvJGgzznGMNLFVdoLVAQcw4wIIgZQ2AmDMBYNgey5NMAsCSEUEIc8CDxCAA) (successfully), clicked "create permalink" and got [this link](https://marimo.app/?slug=9bo03f), which is to the intro

PS just started using marimo, it's an absolute joy! Thanks for building it!

### Environment

NA

### Code to reproduce

The file: https://github.com/davidnmora/energy-data/blob/main/Gas%20Price%20Roller%20Coaster.py

**Comment by mscolnick** [comment]
It looks like the permalink was not properly saved - the code may not have been saved before creating the permalink. Here is a working permalink: https://marimo.app/l/6n8zsp
