### ISSUE TITLE
mo.callout neglects headings

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2050]
### Describe the bug

<img width="1359" alt="Screenshot 2024-08-20 at 17 39 35" src="https://github.com/user-attachments/assets/5416abd7-e387-42ae-b38d-3966e528b65e">

### Environment

```json
{
  "marimo": "0.8.0",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.5.1"
  },
  "Requirements": {
    "click": "8.1.3",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.18.0",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.2"
  }
}
```

**Comment by mscolnick** [comment]
hey @metaboulie - what is the use case for this? are you just looking to style a heading? 

I'm not sure we want to expose headings inside callouts (or any nested headings - like in tabs, accordions, etc) to the Outline

**Comment by metaboulie** [comment]
yeah I'm just looking to style a markdown block with headings in it
