### ISSUE TITLE
Broken links at https://docs.marimo.io/guides

### ISSUE THREAD

**Issue by vadim0x60** [marimo-team/marimo#2052]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

I am having trouble accessing the [guides](https://docs.marimo.io/guides) on the documentation website. Every link leads to a 404 page.

### Your Suggestion for Changes

Fix broken links

**Comment by mscolnick** [comment]
Hi @vadim0x60 - curious how you got to the URL <https://docs.marimo.io/guides>?  The correct url is <https://docs.marimo.io/guides/index.html>, all those links should work.

**Comment by vadim0x60** [comment]
Ah! Indeed they do.
I got to these wrong URLs from Google, it seems to index the wrong ones for some reason

**Comment by mscolnick** [comment]
got it, thanks, i can look into redirecting or fixing the crawling

**Comment by mscolnick** [comment]
Looks like Google is now getting the correct links (not sure when that changed). Verified the site.xml is correct:
https://docs.marimo.io/sitemap.xml
