### ISSUE TITLE
LaTeX displayed as raw text instead of math formulae in plotly

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2060]
### Describe the bug

[Plotly uses MathJax](https://plotly.com/python/LaTeX/) to render LaTeX mathematical formulas and notation. 

But [marimo doesn't use MathJax](https://github.com/marimo-team/marimo/blob/8b96051d364400417637019a80aa1694e6aaf458/marimo/_output/md.py#L15)

This makes LaTeX displayed as raw text instead of math formulae in plotly

**In Jupyter**
<img width="925" alt="Screenshot 2024-08-21 at 17 36 40" src="https://github.com/user-attachments/assets/22401bde-ef08-46c9-9525-e3ea6d2b38f0">

**In marimo**
<img width="786" alt="Screenshot 2024-08-21 at 17 35 03" src="https://github.com/user-attachments/assets/be903519-20c9-4cca-b783-8bee11666f8a">

Thoughts:

Implement a logic to render LaTeX correctly in plotly formatter

### Environment

```json
{
  "marimo": "0.8.0",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.5.1"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.2",
    "websockets": "12.0",
    "typing-extensions": "missing",
    "ruff": "0.6.1"
  }
}
```

### Code to reproduce

```python
# import marimo as mo
import plotly.express as px

px.line(
    x=[1, 2, 3, 4],
    y=[1, 4, 9, 16],
    title=r"$\alpha_{1c} = 352 \pm 11 \text{ km s}^{-1}$",
).update_layout(
    xaxis_title=r"$\sqrt{(n_\text{c}(t|{T_\text{early}}))}$",
    yaxis_title=r"$d, r \text{ (solar radius)}$",
)
```

**Comment by mscolnick** [comment]
Thanks for finding this! Do you know how jupyter is handling this / hooking in to the formatter?

**Comment by rgouveiamendes** [comment]
Hi! Did you try this?
https://stackoverflow.com/questions/44333065/string-variable-as-latex-in-pyplot

**Comment by metaboulie** [comment]
@rgouveiamendes Thanks for pointing this out. Yeah, this works for `matplotlib`, but doesn't work for `plotly`.

**Comment by metaboulie** [comment]
> Thanks for finding this! Do you know how jupyter is handling this / hooking in to the formatter?
Sorry, I have limited knowledge of Jupyter.

**Comment by metaboulie** [comment]
I think Jupyter actually does nothing for plotly, since I can't find any code about plotly in their repo.

The reason might be that, in Jupyter user needs to call `fig.show()` to display the figure, but in marimo user doesn't need to call `fig.show()`, just `fig` can do the job.

However, if call `fig.show()` in marimo, the jumped figure renders LaTeX correctly. 

So it's about `fig.show()` and `fig` I suppose

**Comment by mscolnick** [comment]
thanks for the investigation @metaboulie!

it might be our custom formatter for plotly (maybe missing config, or not converting to the plotly json correctly)
marimo/_output/formatters/plotly_formatters.py

**Comment by metaboulie** [comment]
I tried to modify `plotly_formatters` as below:

```python
html_content = build_stateless_plugin(
    component_name="marimo-plotly",
    args={"figure": json, "config": resolved_config},
)

# Include MathJax script for LaTeX rendering
mathjax_script = (
    '<script type="text/javascript" async '
    'src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">'
    '</script>'
)

return Html(mathjax_script + html_content)
```

because `pio.to_html(include_mathjax="cdn")` appears to do the same thing, adding a script tag that references a MathJax CDN location to the output.

However, it doesn't work

https://plotly.com/python-api-reference/generated/plotly.io.to_html.html

**Comment by Light2Dark** [comment]
This works as a quick fix.
```
import marimo as mo
import plotly.express as px

# no async so it executes immediately
script = '''<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"></script>'''

fig_html = px.line(
    x=[1, 2, 3, 4],
    y=[1, 4, 9, 16],
    title=r"$\alpha_{1c} = 352 \pm 11 \text{ km s}^{-1}$",
).update_layout(
    xaxis_title=r"$\sqrt{(n_\text{c}(t|{T_\text{early}}))}$",
    yaxis_title=r"$d, r \text{ (solar radius)}$",
).to_html()

mo.iframe(script + fig_html)
```

@metaboulie  

> I tried to modify `plotly_formatters` as below:
> return Html(mathjax_script + html_content)

Yeah, the scripts aren't executed when returned from the backend. I tried returning a console.log script and it would not execute. Not sure why as I see the script tag on the frontend. 🤔

**Comment by metaboulie** [comment]
@Light2Dark 

I think it has something to do with `_build_attr`

https://github.com/marimo-team/marimo/blob/c461eb592df52917cc7bf3981a16f34e392b86dd/marimo/_plugins/core/web_component.py#L45-L54

where __backslashes__ and __dollar sign__ are encoded, which may let `mathjax_script` not recognize the latex string.

you can print the result of `build_stateless_plugin` and the latex part is formatted as below

```
 &quot;title&quot;: {&quot;text&quot;: &quot;&#36;&#92;&#92;alpha_{1c} = 352 &#92;&#92;pm 11 &#92;&#92;text{ km s}^{-1}&#36;&quot;}, &quot;dragmode&quot;: &quot;zoom&quot;
```

which, I think `mathjax` can't recognize as valid latex

---

In the plotly formatter, `build_stateless_plugin` is evaluated to build the html plugin

https://github.com/marimo-team/marimo/blob/995cd935473ef56c2c7194936eb884e80b7dcc4e/marimo/_output/formatters/plotly_formatters.py#L56-L73

and `build_stateless_plugin` calls `_build_attr`

https://github.com/marimo-team/marimo/blob/c461eb592df52917cc7bf3981a16f34e392b86dd/marimo/_plugins/core/web_component.py#L101-L119

**Comment by Light2Dark** [comment]
hmm, I thought the issue was the mathjax library is missing, if I return this in `plotly_formatters.py:68`, the script wouldn't be executed.

```plotly_formatters.py
return Html(
    '<script>console.log("Hello!")</script>' +
    build_stateless_plugin(
        component_name="marimo-plotly",
        args={"figure": json, "config": resolved_config},
    )
)
```

If you added this line to `marimo/frontend/index.html`, it would work.
```
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```

Update: this works (`plotly_formatters.py:68`)
```.py
return Html(
    h.iframe(src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML') +
    build_stateless_plugin(
        component_name="marimo-plotly",
        args={"figure": json, "config": resolved_config},
    )
)
```

**Comment by metaboulie** [comment]
@Light2Dark 

Yeah, adding that line to `marimo/frontend/index.html` resolves the problem.
Maybe you should make a PR for this solution

**Comment by Light2Dark** [comment]
I'm not so keen on adding a script tag to index.html, it will add another dependency that's only needed for some use cases imo. Ideally the script would be added in `plotly_formatters` when LaTeX code is detected. If you know of any examples where the Python returns a script that's executed, maybe that could help.

In any case, this is a workaround
```.py
import marimo as mo
import plotly.express as px

script = '<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML"></script>'

fig_html = px.line(
    x=[1, 2, 3, 4],
    y=[1, 4, 9, 16],
    title=r"$\alpha_{1c} = 352 \pm 11 \text{ km s}^{-1}$",
).update_layout(
    xaxis_title=r"$\sqrt{(n_\text{c}(t|{T_\text{early}}))}$",
    yaxis_title=r"$d, r \text{ (solar radius)}$",
).to_html()

mo.iframe(script + fig_html)
```

**Comment by metaboulie** [comment]
Maybe you can add this workaround to the doc 

https://docs.marimo.io/guides/working_with_data/plotting.html#plotly

Albeit this is the doc for `mo.ui.plotly`

**Comment by Light2Dark** [comment]
good idea, let me work on that :)

**Comment by Asuranceturix** [comment]
Hi, I don't quite get how to use this. I have written code to generate a Plotly figure, but if I write a `$...$` label, it appears literally with the dollar signs. I have tried to wrap it in mo.ui.plotly and mo.iframe(script + figure.to_html()) but none of them work for me. Can someone please point me in the right direction? Thanks!

**Comment by Light2Dark** [comment]
You could share your code (in a new issue preferably).

Have you enclosed the string with `r`? It's an r string.
```python
import plotly.express as px

px.line(
    x=[1, 2, 3, 4],
    y=[1, 4, 9, 16],
    title=r"$\alpha_{1c} = 352 \pm 11 \text{ km s}^{-1}$",
).update_layout(
    xaxis_title=r"$\sqrt{(n_\text{c}(t|{T_\text{early}}))}$",
    yaxis_title=r"$d, r \text{ (solar radius)}$",
)
```

**Comment by Asuranceturix** [comment]
Thanks for your quick answer. It appears in the end it was a quirk of Scatter3d text traces. It does work when using annotations.
