### ISSUE TITLE
Some Firefox keyboard shortcuts are captured, while some not

### ISSUE THREAD

**Issue by robaki** [marimo-team/marimo#2081]
### Describe the bug

The default Ctrl+Shift+... shortcuts for creating new cells, when using marimo in Firefox, are not captured by marimo and trigger whatever they do in Firefox. At the same time ctrl+B is captured by marimo (in editor), so it seems like something could be done about that.

The desired behaviour is to capture all shortcuts defined in marimo config.

### Environment

{
  "marimo": "0.8.0",
  "OS": "Linux",
  "OS Version": "5.15.0-118-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.0.3",
    "importlib-resources": "missing",
    "jedi": "0.18.0",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.6.1"
  }
}

Firefox version: 129.0 (64-bit) (for linux mint)

### Code to reproduce

No code needed - just open marimo editor in firefox and do Ctrl+Shift+P (this will open a new private window). For comparison, do Ctrl+B in marimo editor (nothing will happen) and some other website (bookmarks menu will open).

**Comment by mscolnick** [comment]
Hi - yes, Firefox and Safari may capture some shortcuts. They unfortunately won't let the page capture these at all - so there are just some shortcuts we cannot use.

 We have added custom configuration for this though. We would like to change the defaults, but is it breaking change that we don't want to do (just yet)

**Comment by mscolnick** [comment]
`Ctrl+Shift+P` is not a default shortcut. Are you setting that? If its not set, it will fallback to the browser.

`Ctrl+B` will bold (when the editor is in markdown mode)

**Comment by mscolnick** [comment]
Sorry, you are right. `Ctrl+Shift+P` is a default and you are correct that it does not work with Firefox. 

Still the same answer: there is nothing we can do in Firefox to _keep_ that shortcut. It has to be changed, unfortunately, but you can customize that. Or you can use Chrome.

I am going to close this since there isn't anything we can do with Firefox.
