### ISSUE TITLE
showing a polars dataframe with array column is slow

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#2090]
### Describe the bug

I regularly use polars dataframe with array columns with a significant amount of data in them. Showing them in marimo results in long cell evaluations, for example the cell showing `df` below takes 2 s for me. In real use cases I'm regularly seeing 4 s. Whereas printing them with the polars representation is basically instantaneous.  

### Environment

{
  "marimo": "0.8.0",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "127.0.6533.120",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.8.1",
    "pygments": "2.16.1",
    "tomlkit": "0.12.5",
    "uvicorn": "0.30.1",
    "starlette": "0.37.2",
    "websockets": "12.0",
    "typing-extensions": "4.7.1",
    "ruff": "0.5.5"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.8.0"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import polars as pl
    import numpy as np
    return mo, np, pl


@app.cell
def __(np, pl):
    df = pl.DataFrame(
        {"a": np.arange(10000000.0).reshape(-1, 1000)},
        schema={"a": pl.Array(pl.Float64, 1000)},
    )
    return df,


@app.cell
def __(df):
    # 2 s
    df
    return


@app.cell
def __(df):
    # 200 ms
    str(df)
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
This is because we need to flatten the df before sending it to the frontend, and we send a lot of data and handle pagination on the frontend. 

We should instead handle pagination on the backend

**Comment by akshayka** [comment]
Thanks for reporting @ggggggggg ; we'll fix this.

**Comment by mscolnick** [comment]
Closed by https://github.com/marimo-team/marimo/pull/2115
