### ISSUE TITLE
Show Python results in Python notation

### ISSUE THREAD

**Issue by odanoburu** [marimo-team/marimo#2101]
### Description

When a cell has multiple results, such as the last statement (and expression) on a cell is `True, False`, the output seems to be JSON output similar to `json.dumps((True, False))`, which thus uses JS syntax for True/False. 

This can be confusing to Python newcomers, like the students I teach to. I understand if there's a reason for this (like interfacing with JS libraries in the frontend), but if there is a solution it would be appreciated. 

### Suggested solution

Maybe it's possible to use something like [ast.unparse](https://docs.python.org/3/library/ast.html#ast.unparse), although that's not a pretty-printer.

### Alternative

There is also a workaround for this 'problem', which is to write `print(True, False)`.

**Comment by mscolnick** [comment]
Just for reference, this is what it currently looks like:

<img width="499" alt="image" src="https://github.com/user-attachments/assets/56024e47-6e97-46c2-a219-6d75efeda6db">

[Playground](https://marimo.app/#code/JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoAODgJhbSIwYJgmSoOAQWEAKGuXqMWICsACuIFgEoMaAAJCwHAMZ4ANmbTk8AMzjYZWgFxo4buABUoavK-dQ8GDUoAl0DYRNzS2s7B2c-NwAxRDMAZ193OACgkLDDSIsrW3tMRxdMgG8vHwAaOGS0vABfBKzA4NCMcKNTQpiSstaAbWq8Oob0gF1W7I68iN7o4rjy91HxlPSZ9tyMYFjMAkQVbCZmFmwkYAJsFlW3fO8CRyA)

**Comment by akshayka** [comment]
@odanoburu , thanks for opening this issue and helping us improve marimo! Version 0.8.3, which should be available on PyPI shortly, contains a fix.

<img width="435" alt="image" src="https://github.com/user-attachments/assets/9a46c50e-6dcd-4af6-8dc1-a805e96367d1">
