### ISSUE TITLE
"no module named pandas" when plotting Polars DataFrame with Altair

### ISSUE THREAD

**Issue by MarcoGorelli** [marimo-team/marimo#2107]
### Describe the bug

Trying to plot a polars dataframe raises because pandas isn't found

### Environment

{
  "marimo": "0.8.2",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.11.9",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.16.0"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "6.4.3",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.5.7"
  }
}

### Code to reproduce

Here's my notebook:
```python
import marimo

__generated_with = "0.8.2"
app = marimo.App(width="medium")


@app.cell
def __():
    import polars as pl
    import altair as alt
    import marimo as mo
    return alt, mo, pl


@app.cell
def __(pl):
    df = pl.DataFrame({'a': [1,2,3], 'b': [4, 5, 6]})
    return df,


@app.cell
def __(alt, df, mo):
    mo.ui.altair_chart(alt.Chart(df).mark_point().encode(x='a', y='b'))
    return


@app.cell
def __():
    return


if __name__ == "__main__":
    app.run()
```

**Comment by MarcoGorelli** [comment]
I'm hoping that the solution here can be to support charts made starting from Polars, rather than to add pandas as a dependency 🤞

**Comment by mscolnick** [comment]
Thanks for reporting, I can fix this. Up until recently, Altair only supported pandas so the requirement was necessary. I can make an update to use whichever is installed
