### ISSUE TITLE
ability to disable `import *` error

### ISSUE THREAD

**Issue by Zaf4** [marimo-team/marimo#2113]
### Description

I know it is is well thought out decision by the team wtih some good reason, but in some cases it is not convenient at all name all the imports.
for example when I use the plotting library [lets_plot](https://github.com/JetBrains/lets-plot) I need to have something like this for  simple plots.

```python
from lets_plot import (ggplot,aes,geom_point, LetsPlot, scale_color_brewer,geom_boxplot, scale_fill_hue, scale_y_log10, theme)
```
... and this goes to >20 functions in most cases 

and I every time I need to use a another function, I need to go up and add the import which is not very convenient and this is the best practice for this library by jetbrains.

### Suggested solution

there can be a configuration option to disable this error or to make it a warning.

**Comment by akshayka** [comment]
Unfortunately we won't be able to support this request. marimo needs to know what names are defined statically, but import `*` defines a bunch of names in a way we can't figure out by just reading the source code.

Is it not possible to use the same convention as other Python libraries? For example, it's conventional to write `import numpy as np`; can you similarly do `import lets_plot as lp`?

**Comment by Zaf4** [comment]
Unfortunately, importing it as lp make the syntax much more convoluted and it is against the accepted practice for this library. I understand your decision as this is a unique case.
