### ISSUE TITLE
Realtime Markdown Cell Result?

### ISSUE THREAD

**Issue by atticus-lv** [marimo-team/marimo#2137]
### Description

Lots of editors can render markdown directly, they may have sider panel to show the result ( vscode, Pycharm) or just make a toggle mode between the markdown code and the render ( Typora, ext)
So I think when the markdown cell is only use for description, it should have this feature for a quick edit feedback

### Suggested solution

When a markdown cell is pure text, the markdown cell should render the result when there is any changes. 
When detect python vars in it,  user should run it manually

**Comment by wasimsandhu** [comment]
I like this idea, will pick it up if the team approves.

**Comment by mscolnick** [comment]
hey @wasimsandhu, go for it!

**Comment by mscolnick** [comment]
@wasimsandhu - we don't render f'strings using with the markdown editor anymore, those stay as python editors, so i think as long as the `languageAdapter` is the `MarkdownLanguage` adapter, we can just automatically call "run".

I think the place to look is `MarkdownLanguageAdapter.getExtension` and use `movementCallbacks: MovementCallbacks`, which is part of the `LanguageAdapter` interface.

and you can create a codemirror extension that onChange, just calls `movementCallbacks.onRun` 

(i think)

**Comment by akshayka** [comment]
@atticus-lv , this will be available in the next release. Thanks for the feature request!
