### ISSUE TITLE
Disable heading detection for mo.carousel

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2139]
### Describe the bug

I'm doing a web scraping (on marimo blogs) and using mo.carousel to display the scraped content.
The content is formatted as markdown. And the outline is augmented by these contents.

<img width="1440" alt="Screenshot 2024-08-28 at 11 37 07" src="https://github.com/user-attachments/assets/884307ef-a37d-4514-920f-6a2daf6f2e3b">

### Environment

Disable heading detection for `mo.carousel`, or add an arg like `disable_heading: bool = True` to optionally disable heading detection for carousel.

**Comment by metaboulie** [comment]
Also, if `disable_heading` is False, i.e., enable heading detection for carousel, then click on the outline should navigate user to the corresponding part.

**Comment by mscolnick** [comment]
I think for now, we can just disable it always - i think the logic for paginating to the header is difficult and can be confusing. 

we have the logic in `getOutline`, we can also just stop/terminate once we hit certain tags, like `marimo-carousel`
