### ISSUE TITLE
Claude ai supports.

### ISSUE THREAD

**Issue by hongyi-zhao** [marimo-team/marimo#2141]
Dear Marimo Development Team,

Does this tool support [Claude ai](https://claude.ai/) as its [AI assistant](https://docs.marimo.io/guides/editor_features/ai_completion.html#using-other-ai-providers)?

Regards,
Zhao

**Comment by mscolnick** [comment]
@hongyi-zhao, does claude support the OpenAI spec. we allow changing the base-url, similar to how we support Ollama. 

If not, we would accept a contribution to directly use the Caude Python SDK in our completions endpoint.
