### ISSUE TITLE
Replace all occurrences of something in a cell or all cells at once.

### ISSUE THREAD

**Issue by hongyi-zhao** [marimo-team/marimo#2142]
Hi there,

In marimo, can I replace all occurrences of something in a cell or all cells with the one I wanted at once?

Regards,
Zhao

**Comment by mscolnick** [comment]
Do you mean like find/replace and find/replace-all?

We do support this with Ctrl-F

**Comment by hongyi-zhao** [comment]
Yes. Thank you for your tip.
