### ISSUE TITLE
Weird center alignment in accordions summary

### ISSUE THREAD

**Issue by rgouveiamendes** [marimo-team/marimo#2173]
### Description

I am using Marimo Notebooks for teaching.
I like to use accordions in exercises, hiding the answer while letting the students go through the problem.
Since the questions can occupy several lines, I notice that the default alignment of the summary in an accordion is centered. Moreover, it has a fixed width, as shown here:
![image](https://github.com/user-attachments/assets/cefc4f2a-8b0f-4f3f-a8d0-1ac7bc95ed6a)

### Suggested solution

I think the best would be to have the inherent alignment of the body in the summary of an accordion and let it expand through the entire width of the block.

**Comment by mscolnick** [comment]
can you wrap the title in an `mo.md()` and style that? `mo.md().center()/mo.md().left()/mo.md().right()`

**Comment by rgouveiamendes** [comment]
No. It gives this error:
![image](https://github.com/user-attachments/assets/d88b3faa-b3ed-42ca-8a99-ad42e6c41056)

Here is the code:
```python
mo.accordion(
    {
        mo.md("""**e)** Diria que o trabalho, a educação e a idade explicam muita da variação no sono? Que outros fatores poderiam afetar o tempo passado a dormir? Estarão esses fatores provavelmente correlacionados com o trabalho?""").left(): """
    - O $R^2 = 0.113$ é reduzido
    - Só 11.3% da variabilidade do sono é explicada pelas variáveis explicativas escolhidas para o modelo
    - Há fatores que ficaram de fora do modelo que podem influenciar o sono. Exemplos:
        - _Stress_
        - Idade dos filhos
        - Profissão
    - Vários destes fatores podem estar relacionado com o número de horas de trabalho, o que compromete o pressuposto $\mathbb{E}(u|trab)=0$ e, assim, coloca em causa a validade do modelo.
    """
    }
)
```

**Comment by mscolnick** [comment]
@rgouveiamendes I have a fix out on our end, will be in the next release
