### ISSUE TITLE
Using holoviews tries to load plotly even if it is not installed

### ISSUE THREAD

**Issue by mb-915** [marimo-team/marimo#2198]
### Describe the bug

When I import `holoviews`, there is an error, marimo seems to be calling `hv.renderer` that tries to import `plotly` even if it is neither installed nor used.

```
Could not find a 'plotly' renderer, available renderers are: 'bokeh'.'
```

The error seem to be located here : 

https://github.com/marimo-team/marimo/blob/e634a8dd5ee3dd1ed9af38b654bf9d6ae4274339/marimo/_output/formatters/holoviews_formatters.py#L61-L66

I wrote a patch that I currently use (it is working for me):
https://github.com/mb-915/marimo/commit/5c2e324936703146bb01c6db4ed817b23701b06e
but I couldn't get the tests to pass and I’m not sure if adding `bokeh` in `DependencyManager` is right. Therefore, I'm not opening a PR for now.

### Environment

```
{
  "marimo": "0.8.7",
  "OS": "Linux",
  "OS Version": "6.9.8-zen1",
  "Processor": "",
  "Python Version": "3.11.8",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.5.2",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.17.2",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.4",
    "websockets": "12.0",
    "typing-extensions": "4.10.0",
    "ruff": "0.5.7"
  }
}
```

### Code to reproduce

(in an environment without `plotly`)

```
import marimo as mo
import holoviews as hv
```

**Comment by mscolnick** [comment]
thank you for filing @mb-915! the patch looks correct (not sure why the tests would not pass). do you want to open a PR with that patch or would you like me to? I can look at the test failure reasons, if it does end up failing.

**Comment by mb-915** [comment]
i opened a PR #2199 

The failing tests do not seem to be linked to the modification. There might be something in my dev environment.
