### ISSUE TITLE
Custom.css not found

### ISSUE THREAD

**Issue by pyinstallerbaggins** [marimo-team/marimo#2202]
### Describe the bug

I added the sample custom.css provided in Theming from the documentation

I used the Application Config option in the settings and pasted the relative path as directed.

C:\vault\ForageReportingAndServices\custom.css

### Environment

![marimo theme issue](https://github.com/user-attachments/assets/c471ca87-fb80-4705-8c44-50c0f87f4a41)

**Comment by pyinstallerbaggins** [comment]
I got it to work by editing directly in my IDE

Had to revert to the old python string validation tricks by replacing "\" with "//" in the relative filepath. I thought marimo would have accounted for that.

Is there another way to set it up in the app config setting that im missing?

![image](https://github.com/user-attachments/assets/903a4780-59be-4dfb-87fa-8c22dada94d8)

**Comment by mscolnick** [comment]
what was the original path you were putting in? I would assume `custom.css` should be just fine

we aren't doing anything fancy with the paths. we are just using the built-in python libs:

```python
def read_css_file(css_file: str, filename: Optional[str]) -> Optional[str]:
    if not css_file or not filename:
        return None

    app_dir = os.path.dirname(filename)
    filepath = os.path.join(app_dir, css_file)
    if not os.path.exists(filepath):
        LOGGER.error("CSS file %s does not exist", css_file)
        return None
    try:
        with open(filepath) as f:
            return f.read()
    except OSError as e:
        LOGGER.warning(
            "Failed to open custom CSS file %s for reading: %s",
            filepath,
            str(e),
        )
        return None
```

I am not sure what the best way to handle this on windows
