### ISSUE TITLE
Please show dtypes for Polars dataframes

### ISSUE THREAD

**Issue by MarcoGorelli** [marimo-team/marimo#2221]
![image](https://github.com/user-attachments/assets/d2b8cca6-120c-4326-943e-f47799f433b1)

`print(df)` is more informative here as it shows the dtypes, rather than just the values and column names

**Comment by mscolnick** [comment]
We show them in the dropdown of the header. We can think about displaying it upfront. 

If you want, you can also turn off automatic fancy dataframes in the top right settings.

**Comment by MarcoGorelli** [comment]
> We can think about displaying it upfront.

that would be amazing if possible, thanks, somewhat surprisingly it's one of Polars' features that users appreciate the most
