### ISSUE TITLE
auto apply_theme to mo.ui.data_explorer based on the notebook display theme

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2228]
### Description

The figures in `mo.ui.data_explorer` are always light.

<img width="1139" alt="Screenshot 2024-09-05 at 16 27 28" src="https://github.com/user-attachments/assets/8a600b17-8487-4eaa-a448-1dbc8a05f355">

### Suggested solution

Change the plotting theme to dark when the display theme is dark

**Comment by mscolnick** [comment]
hey @metaboulie - i agree, we can make this darktheme compat. should be 2 lines to change, and only in the frontend.

**Comment by mscolnick** [comment]
ill see if GitHub Copilot Workspace can actually fix this
