### ISSUE TITLE
light & dark custom css and remember custom css config

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2255]
### Description

<img width="279" alt="Screenshot 2024-09-07 at 16 17 42" src="https://github.com/user-attachments/assets/71495e45-d3b1-4fa0-8f90-b1be1280f418">

In the `Custom CSS` section, add 2 text input, one for **light theme** and one for **dark theme**.

And if the notebook display theme is light, use the custom css in the light option; if the display theme is dark, then use the custom css in the dark option.

Also, it would be great to to able to remember the custom css setting.

### Suggested solution

Add a CLI like `marimo theme` to use custom theme.

- `marimo theme --dark=dark.css`
- `marimo theme --light=light.css`

**Comment by mscolnick** [comment]
In each light and dark mode, we set the `color-scheme` - so you can add support for light/dark in the same css file using just css features.

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
