### ISSUE TITLE
Local Image in Markdown Cell?

### ISSUE THREAD

**Issue by atticus-lv** [marimo-team/marimo#2256]
### Description

Now the markdown cell only support web url image, but not local image(relative path to folder or abs path )

work `![web url](https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png)`

not work `![](local/path/to/image)`

Also, `mo.md()` and `mo.image()` can not work together in one cell

Though now we can use python mo.image to load an local image, but sometimes we need some description text with images in it in one markdown cell, not separate them into different cell, which break the continuity of the whole text

### Suggested solution

I think the markdown cell should support local image `![](local/path/to/image)`, and provide a simple size control method

**Comment by akshayka** [comment]
`mo.md` and `mo.image` can readily work together in one cell. Here are three ways of combining them in the same cell:

https://marimo.app/l/ce3anh

I encourage you to run `marimo tutorial markdown` for more tips on how to combine objects into markdown.`

I'm not sure why markdown links to local images are not working

**Comment by akshayka** [comment]
I think the browser just can't read local images due to security restrictions, so using the markdown link syntax for local images won't work. With the example notebook I provided, `mo.image` should get the job done. Let me know if you still run into issues.

**Comment by atticus-lv** [comment]
This seems strange, and it can not be run again @akshayka 

Init

![image](https://github.com/user-attachments/assets/943d40ca-a7ac-443e-af13-2a1221d1ac5e)

Run again

![image](https://github.com/user-attachments/assets/1aef4ccf-0daf-4b8b-aa3e-248530361ffd)

**Comment by akshayka** [comment]
Thanks so much for letting me know, that's actually a bug in marimo. It should be

mo.md("another way to ..."), mo.image("...")

but the code got corrupted. I will open another issue

**Comment by atticus-lv** [comment]
I think so, change the code still not work. Something breaks it. Thanks for your work, waiting for fixing
![image](https://github.com/user-attachments/assets/6388763d-52e1-463a-b305-b51e8d7da530)
