### ISSUE TITLE
marimo darkmode saves plots in darkmode

### ISSUE THREAD

**Issue by VivaldoMendes** [marimo-team/marimo#2260]
Hi,

In the latest versions of marimo, there was a change that has a good side, but also a problem that I need help solving. In marimo's dark mode, most plotting also comes out in dark mode, even if we use the default templates and themes of the packages I tested (Plotly, Altair, Seaborn). Apparently, the only plotting package that continues to render the plots according to its default templates and themes is Lets-plot.py. 

This novelty charms my eyes (the user) because I employ dark mode everywhere in my work, and I appreciate it. However, there is a lateral problem that I do not know how to deal with. If I save a plot as a PDF, PNG, or SVG, the saved plots also come out in dark mode. This problem is complicated if one needs to use the saved plots in a paper or a presentation. 

For example, the image below is an SVG file produced by the default theme of Plotly. Thanks.
![fig6](https://github.com/user-attachments/assets/7cfd402a-57b0-4559-8b9a-40ba5d261fcc)

**Comment by akshayka** [comment]
>  However, there is a lateral problem that I do not know how to deal with. If I save a plot as a PDF, PNG, or SVG, the saved plots also come out in dark mode.

That's a good point ... it makes sense for automatic theming to apply only to rendering in the frontend, but not to exporting.

I believe we apply the themes globally. Instead we should just apply the theme before formatting the output for the frontend, and then restore the original theme after formatting.

**Comment by akshayka** [comment]
In the meantime, you can manually set the plotting library themes. For example to restore the Plotly light theme:

```python
import plotly.io as pio 

pio.templates.default = "plotly"
```

Sample code for changing the themes of other libraries can be found in this directory:

https://github.com/marimo-team/marimo/tree/64762eb92b5c8203200cac89f8e564d3fbae308d/marimo/_output/formatters

**Comment by VivaldoMendes** [comment]
Hi @akshayka, Thanks for the quick response. Yes, your code indeed restores the default plotly theme. Wonderful. With the humble cost of two simple code lines, I have both worlds at my disposal. Thanks a lot.

**Comment by zkkv** [comment]
I think this can be reopened because it would make more sense to not change the plot theme by default, even in notebook itself.

**Comment by jonwzheng** [comment]
i second re-opening; using dark mode while exporting to light mode should at least be a user/notebook setting

**Comment by chicolucio** [comment]
Yes, this should definitely be reopened. There should be an option to choose whether the theme is applied to plots or not. I'm having issues with maplotlib plots that should be light theme in the notebook itself and exported.

**Comment by FilipSchymik** [comment]
I agree that this would be easier as an option in the settings. 

For anyone still looking, to make matplotlib display and save plots in default (white) mode you can use:

```
import matplotlib.style

matplotlib.style.use(
    "default"
)
```

**Comment by JVikoren** [comment]
Just flagging that this is still worth reopening. The default behavior should be to use... the default. :D

matplotlib.style.use(
    "default"
)
