### ISSUE TITLE
Limit number of rows in mo.ui.dataframe as preview for Ibis

### ISSUE THREAD

**Issue by szst11** [marimo-team/marimo#2269]
### Description

I am having a big dataset and want to filter it with mo.ui.dataframe, then all *illions of datapoints are loaded into the table.

### Suggested solution

would it be possible to add a limit(head in pandas) feature to the class marimo.ui.dataframe, which loads only, if a value is given, number of rows as a preview. But the resulting dataframe should be without the limit.

**Comment by mscolnick** [comment]
@szst11 we only show 5 rows in `mo.ui.dataframe` and we only load that many in the frontend. Are you seeing something different? What version are you on?

**Comment by szst11** [comment]
@mscolnick right, only 5 rows are shown, as configurable with the page_size argument. But the full dataset seems to be available, when going to the other pages of the table and the length of the dataset is known. If using Ibis I also checked the query, where is no limit statement. (Version just updated to 0.8.14)

**Comment by mscolnick** [comment]
I think what you are seeing is that the full ibis table is being loaded into python memory, but not the frontend. 

I am guessing that is still not desirable? We do only load 5 at a time, but maybe by loading `total_rows` we are triggering a full load for ibis. 

Do you prefer the length to be unknown and not be able to jump to particular pages (just left/right)?

**Comment by szst11** [comment]
@mscolnick with the Ibis integration, you are now able to access and explore tables in big databases. So it would be necessary to avoid the loading of a full table, before filtering. The limit should be set in Python to the dataframe and then the length of the table would be the amount of available rows. Jumping pages would only be possible within that limited number of rows. Maybe a warning could be shown that a limit is active..

**Comment by mscolnick** [comment]
Got it - this makes sense. I can look into making Ibis more lazy, is it specifically retrieving the number of rows? or is there anything else that causes Ibis to load everything into memory?

**Comment by szst11** [comment]
If a datasource is large and some transformation are already in place, already a row count could need some resources on the database and may take a while. So I would suggest to limit the query after the applied transformations to get some of the expected results. But keep the output dataframe without the limit, as this should still be lazy. 
The limit behaviour might also be useful for Polars, as it can also handle large datasources in a lazy manner.

**Comment by mscolnick** [comment]
@szst11 - let me know if this is sufficient. you can now pass `row_limit` in `mo.ui.dataframe(row_limit=100)` (via https://github.com/marimo-team/marimo/pull/2312) (after the next release)

For now, it is omitted and has no limit, but in future, we may add some sane defaults (but can be undone by passing `None`). Let me know if you have thoughts on these defaults.

**Comment by szst11** [comment]
@mscolnick it works great! many thanks (beside: you took limit as key, not row_limit)
I am not sure, if a default limit has to be set. In most cases probably local data is used and then it is ok.

**Comment by mscolnick** [comment]
Ah, thanks for the correction, yes, `limit`.

We would set it in user-config or app-config or env variables. Something we can consider later, based on usage and feedback. For now, we can just let the user put it in the `mo.ui.dataframe`
