### ISSUE TITLE
unable to run sql even in the sql tutorial

### ISSUE THREAD

**Issue by th1nk1ng0utl0ud** [marimo-team/marimo#2277]
### Describe the bug

just trying to run the marimo sql tutorial doesn't work, I have already install the requirements as pip install 'marimo[sql]', In one of the first cells the notebook says the installation is correct. but its unable to run the tutorial for sql

<img width="834" alt="Screenshot 2024-09-09 at 15 02 46" src="https://github.com/user-attachments/assets/1c93ac81-3896-416e-9652-c43facd9caae">

<img width="897" alt="Screenshot 2024-09-09 at 15 03 19" src="https://github.com/user-attachments/assets/af685f0a-f712-48eb-899a-2bbf7009ebe2">

don't really know what is the problem, I tried by myself as the documentation indicates and gives me the exact same error.

```
CatalogException

This cell raised an exception: CatalogException('Catalog Error: Table with name df does not exist! Did you mean "pg_depend"?')
See the console area for a traceback.
Traceback (most recent call last):
  File "/Users/danielluque/anaconda3/lib/python3.11/site-packages/marimo/_runtime/executor.py", line 170, in execute_cell
    exec(cell.body, glbls)
  Cell marimo:///var/folders/rp/__ndnbkj7d364mdw_r8l25m80000gn/T/tmp5in93ni2/sql.py#cell=cell-9, line 1, in <module>
    _df = mo.sql(
          ^^^^^^^
  File "/Users/danielluque/anaconda3/lib/python3.11/site-packages/marimo/_sql/sql.py", line 40, in sql
    relation = duckdb.sql(query=query)
               ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "pg_depend"?
```

### Environment

{
  "marimo": "0.8.13",
  "OS": "Darwin",
  "OS Version": "22.5.0",
  "Processor": "arm",
  "Python Version": "3.11.3",
  "Binaries": {
    "Browser": "128.0.6613.120",
    "Node": "v22.2.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.18.1",
    "markdown": "3.7",
    "pygments": "2.15.1",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.4",
    "starlette": "0.33.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.5.0",
    "uvicorn": "0.24.0.post1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.3.0",
    "duckdb": "1.1.0",
    "pandas": "2.1.1",
    "pyarrow": "11.0.0"
  }
}

### Code to reproduce

marimo tutorial sql

**Comment by mscolnick** [comment]
it looks like the latest release of `duckdb` today (1.1.0) broke our integration. 

can you re-install version `1.0.0`. e.g `uv pip install -U duckdb==1.0.0` or `pip install -U duckdb==1.0.0`

**Comment by th1nk1ng0utl0ud** [comment]
awesome!, it was indeed the new version of duckdb, thanks!
