### ISSUE TITLE
MkDocs/Sphinx integration (a la `mknotebooks`)

### ISSUE THREAD

**Issue by patrick-kidger** [marimo-team/marimo#2287]
### Description

A very frequent use case for notebooks is to writing examples for software libraries.

Pulling an example from one of my own libraries, [this example](https://docs.kidger.site/equinox/examples/score_based_diffusion/) is produced by creating it in a Jupyter notebook, and then using [mknotebooks](https://github.com/greenape/mknotebooks) to convert it into a MkDocs-compatible webpage.

Anecodatally, most other Python software I see generates substantial portions of their own documentation in the same way.

Now conveniently, Marimo already supports export to HTML! The only thing that is missing is the ability to make this part of documentation generation.

The main two documentation generators seem to [MkDocs](https://github.com/mkdocs/mkdocs) + [mkdocs-material](https://github.com/squidfunk/mkdocs-material) (usually newer software libraries) or [Sphinx](https://github.com/sphinx-doc/sphinx) (usually older software libraries).

It'd be awesome if there was a tool similar to mknotebooks (or whatever Sphinx uses that's similar) to ease adopting Marimo for such use-cases.

### Suggested solution

-

### Alternative

Continue to use Jupyter instead of Marimo.

**Comment by dmadisetti** [comment]
Nice! I use [mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter). But marimo with mkdocs is something I've been playing around with for a second.

So just pushed what I have locally up:
  - very messy, just playing around: https://github.com/dmadisetti/mkmarimo
  - utilizing the quarto base: https://github.com/dmadisetti/quarto-marimo
to increase code reusage.

I know this is definitely in marimo's plans to make notebooks more portable.
I'm a full time PhD student, but here' the timeline as I see contributing to marimo:

 1. Polish off and migrate the quarto/ pandoc plugin to marimo-team/mo-quarto for embedded markdown exports
     - Using this with my own notebooks, but ideally should be in a place to share with others
 2. Get native save / caching working
      - I'd like to have some pretty heavy notebooks in a sharable form. Leveraging aggressive caching or save outputs means that compute heavy notebooks can be quickly executed, and still technically having the notebook run in browser, and make it interactive.
 3. Polish and publish the MkDocs plugin
      - MkDocs is also my preference of choice, but having quarto means that it can potentially be embedded anywhere.

 Some action items that have already been crossed off!
 - native markdown format (e.g. https://github.com/marimo-team/marimo/blob/main/marimo/_tutorials/markdown_format.md)
 
 Relevant issue (your choice to mark as dupe):
  - https://github.com/marimo-team/marimo/issues/1882
  
  Also publishing to Observable:
   - https://github.com/marimo-team/marimo/discussions/962

**Comment by mscolnick** [comment]
FYI: We, alongside a few contributors, are working on a mkdocs plugin.

**Comment by AdamRJensen** [comment]
Note, Jupyterbooks are built using Sphinx and Sphinx seems to be more extensible than MkDocs which would be one argument for heading the Sphinx way.

**Comment by Haleshot** [comment]
Wanted to drop by to post the marimo-mkdocs plugin repo here - https://github.com/marimo-team/mkdocs-marimo
_CC: @patrick-kidger_

**Comment by patrick-kidger** [comment]
Oh, super interesting! Thank you.

I've just taken a look at it -- if I understand correctly this isn't a way to transform a Marimo notebook, but is essentially a competing serialization format to the current `.py` files? (It's still executable, just now it's in `.md` format instead.)

I'm guessing the reactivity comes with some heavy extra extensions. I expect static web pages to be my 99% use-case -- if I set `is_reactive: false` will these not be loaded?

**Comment by Haleshot** [comment]
> I'm guessing the reactivity comes with some heavy extra extensions. I expect static web pages to be my 99% use-case -- if I set `is_reactive: false` will these not be loaded?

From this link - https://marimo-team.github.io/mkdocs-marimo/getting-started/configuration/#code-fence-options, it shows how setting `is_reactive=false` just shows a static output:
![Image](https://github.com/user-attachments/assets/cee881c7-7eef-404e-9b59-d61124e09b29)

By default `is_reactive=true`. If your primary usecase involves graphs/plots/visualizations to be static, setting this parameter to be false would make sense.

**Comment by mscolnick** [comment]
As @Haleshot mentioned, we've created https://github.com/marimo-team/mkdocs-marimo

It is early so please provide feedback (and recommend to use the latest marimo with it).

@patrick-kidger you can disable reactivity globally and locally, you can find [the configuration options here](https://marimo-team.github.io/mkdocs-marimo/getting-started/configuration/#global-configuration).

**Comment by patrick-kidger** [comment]
Thanks! Unfortunately I don't think this is quite what the original issue was about: this is a way to write cells directly into markdown, not a way to take an existing `.py` file and host it through mkdocs.

As for reactivity, indeed, I already found the relevant part of the documentation. What I didn't see was a guarantee that doing this would result in skipping what I assume is otherwise a very large JS download.

**Comment by mscolnick** [comment]
> not a way to take an existing .py file and host it through mkdocs.

@patrick-kidger - this plugin does allow that too (just not documented on the readme yet). Let me know if i am understanding the request correctly. 

You can, do:

```markdown
# Some document 

This will inline my notebook

!marimo_file notebook.py
```

Or you can reference a `.py` file in your nav:

```yaml
nav:
  - Overview: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Notebooks in Navigation: getting-started/nav_notebook.py  # <- this is a marimo file
```

Both above may only exist reactively, so it will likely need some additional work for your use-case. 

> What I didn't see was a guarantee that doing this would result in skipping what I assume is otherwise a very large JS download.

Right now our UI elements heavily use web-components which require downloading our JS and CSS. I don't think we will avoid downloading the JS anytime soon. We do lazy-load a lot of our javascript, but we be more aggressive about this.

**Comment by patrick-kidger** [comment]
> just not documented on the readme yet

Ah, that's why! I took a look through the rest of the docs too but it wasn't clear that this was possible.

> Right now our UI elements heavily use web-components which require downloading our JS and CSS. I don't think we will avoid downloading the JS anytime soon.

Ah, that's a shame! I'll stick to Jupyter for the standard display some code + display it's text output for now, and give this a try when I need something more heavyweight. (As another open source maintainer, I totally understand wanting to focus on other priorities. :) )

**Comment by mscolnick** [comment]
I appreciate the help and feedback @patrick-kidger. I will let you know if we end getting the outputs more light-weight.

**Comment by bramth** [comment]
Wanted to drop that one of the marimo devs published this plugin: https://github.com/koaning/sphinx-marimo (in my experience its quite stable).

I guess in hindsight going for mkdocs was not the best decision: https://fpgmaas.com/blog/collapse-of-mkdocs/
