### ISSUE TITLE
Column-specific filtering includes null values

### ISSUE THREAD

**Issue by delennc** [marimo-team/marimo#2299]
### Describe the bug

Filtering for a value in a column also includes the rows where the column value is null

### Environment

0.8.11

### Code to reproduce

![Screenshot 2024-09-11 at 5 09 54 PM](https://github.com/user-attachments/assets/843ed8ed-9dbb-488a-9cfe-69d4fb779065)

**Comment by mscolnick** [comment]
pandas 😢

**Comment by mscolnick** [comment]
This will be fixed by https://github.com/marimo-team/marimo/pull/2300
