### ISSUE TITLE
Customizing the actions links in the Altair charts

### ISSUE THREAD

**Issue by sgsfak** [marimo-team/marimo#2302]
### Describe the bug

It seems that disabling the actions links in the Altair charts using `altair.renderers.set_embed_options(actions=False)` does not work. I am not sure whether it's marimo's or altair's issue. It's probably the latter since the same problem  has been reported for [streamlit](https://github.com/streamlit/streamlit/issues/3258).

The workaround proposed in the Streamlit's discussion [here](https://discuss.streamlit.io/t/does-altairs-set-embed-options-work-with-streamlit/1675/10) is to do the following per chart:
```python
chart["usermeta"] = {
    "embedOptions": {
        "actions": False,
    }
}
```

### Environment

```json
{
  "marimo": "0.8.13",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "i386",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "128.0.6613.121",
    "Node": "v18.17.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.4",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "duckdb": "1.0.0",
    "pandas": "2.2.2",
    "pyarrow": "17.0.0"
  }
}
```

### Code to reproduce

```python
import marimo as mo
import pandas as pd
import altair as alt

alt.renderers.set_embed_options(actions=False)

df = pd.DataFrame({"x": [1,2,3], "y": [10,20,30]})

chart = alt.Chart(df).mark_point().encode(x="x", y="y")
mo.ui.altair_chart(chart)

## However, using the following per chart works:

chart["usermeta"] = {
   "embedOptions": {
       "actions": False,
    }
}

mo.ui.altair_chart(chart)
```

**Comment by mscolnick** [comment]
Thanks for the detailed issue. I am surprised that altair does not handle this internally, but using your workaround, I can make this embedOptions set globally are always set on all charts. 

PR here: https://github.com/marimo-team/marimo/pull/2303
