### ISSUE TITLE
[CI] BE only changes don't trigger required FE tests

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#2317]
### Describe the bug

As seen in #1993 and #2316

Backend changes that do not touch any FE code, do not trigger the FE tests and as such are blocking

You can change the required checks in Settings -> branches -> Branch protection rules
or maybe figure out how to make it skip?

### Environment

head

**Comment by mscolnick** [comment]
This is a limitation of GitHub. And they force you to create no-op test suites with the same name, which is worse in my opinion. 

I'd rather just force merge in this case

**Comment by dmadisetti** [comment]
Fair, but also doesn't have to be a no-op. What tests ensure a consistent `openapi` export?

**Comment by mscolnick** [comment]
We dont test schema drift in the open api schema but something we should definitely test for
