### ISSUE TITLE
mo.ui.number rendered wrongly (.value != displayed one)

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#2327]
### Describe the bug

I'm trying to create a table where I can add rows, while preserving the values of existing rows. This is done using states and some on_change handlers. For some reason, when I add a row, the updated elements of the table (mo.ui.number), is displayed wrongly.

### Environment

{
  "marimo": "0.8.15",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "125.0.6422.142",
    "Node": "v20.14.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "ruff": "0.5.2",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.9.0",
    "uvicorn": "0.29.0",
    "websockets": "11.0.3"
  },
  "Optional Dependencies": {
    "pandas": "2.2.2"
  }
}

### Code to reproduce

here's a minimum reproducible example. I'm running things in marimo edit mode.

To trigger the bug, enter some value into the initial table, and then press "add row". Notice, how the table is now apparently reset back to the initial value. Notice, that the states are updated (get_data) correctly, and that the table_list that contains the dict which has elements of the table, also has the correct .value property of the mo.ui.number item.

```python

import marimo

__generated_with = "0.8.14"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import datetime
    return datetime, mo


@app.cell
def __():
    initial_data = [{"x": 1, "y": -1}]
    return initial_data,


@app.cell
def __(initial_data, mo):
    get_data, set_data = mo.state(initial_data)
    return get_data, set_data


@app.cell
def __(datetime, get_data, mo, set_data):
    _data = get_data()
    print("Creating new table list", datetime.datetime.utcnow())
    def on_change_wrapper(i, k):    
        def on_change(value):
            print("setting")
            _data = get_data()
            _data[i][k] = value
            set_data(_data)
        return on_change

    table_list = [{k: mo.ui.number(value=v, start=-100, stop=100, on_change=on_change_wrapper(i, k)) for k, v in d.items()} for i, d in enumerate(_data)]
    return on_change_wrapper, table_list


@app.cell
def __(mo, table_list):
    table = mo.ui.table(table_list)
    return table,


@app.cell
def __(get_data, mo, set_data):
    def on_click(*value):
        rows = get_data()
        rows.append({"x": 0, "y": 0})
        set_data(rows)



    add_row = mo.ui.button(label="add row", on_click=on_click)
    return add_row, on_click


@app.cell
def __(add_row, mo, table):
    mo.vstack([table, add_row])
    return


@app.cell
def __(get_data):
    get_data()
    return


@app.cell
def __(table_list):
    table_list[0]["x"].value
    return


if __name__ == "__main__":
    app.run()

**Comment by mrdobalina2k** [comment]
I'd like to add a comment: if the output of cell defined here is added:

 ```python

@app.cell
def __(datetime, get_data, mo, set_data):
    _data = get_data()
    print("Creating new table list", datetime.datetime.utcnow())
    def on_change_wrapper(i, k):    
        def on_change(value):
            print("setting")
            _data = get_data()
            _data[i][k] = value
            set_data(_data)
        return on_change

    table_list = [{k: mo.ui.number(value=v, start=-100, stop=100, on_change=on_change_wrapper(i, k)) for k, v in d.items()} for i, d in enumerate(_data)]
    table_list
    return on_change_wrapper, table_list

then this issue disappears. I have no idea why, but can only assume it's not the intended effect.

**Comment by akshayka** [comment]
Thanks for reporting. I just wanted to write back that I've started debugging but haven't made progress yet, but your reproduction and additional comment are helpful.
