### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by epicycloids** [marimo-team/marimo#2332]
### Describe the bug

See the attached screenshots. If I assign a large numpy array to a cell-scoped variable, then after the cell is done running the memory is still occupied (about 7.5 GB). If I rename the cell-scoped variable and rerun, then the old memory still remains occupied and a new, large chunk of memory is allocated (so now taking about 15 GB).

![run1](https://github.com/user-attachments/assets/2fdcee76-d7db-4bec-bd13-01bbb4ed88af)
![run2](https://github.com/user-attachments/assets/ca3d8f20-100f-4dbb-8140-5de3780cd414)

(Note that I am running Linux, but the issue first occurred to me on my work MacBook.)

### Environment

```
{
  "marimo": "0.8.15",
  "OS": "Linux",
  "OS Version": "6.9.3-76060903-generic",
  "Processor": "x86_64",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "ruff": "0.5.7",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.3.0",
    "pandas": "2.2.2",
    "pyarrow": "15.0.2"
  }
}
```

### Code to reproduce

```
import marimo

__generated_with = "0.8.15"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import numpy as np
    return mo, np


@app.cell
def __(np):
    _test = np.ones((10_000, 100_000))
    return


if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
Thanks, we'll fix this.
