### ISSUE TITLE
px.scatter_map does not display

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#2337]
### Describe the bug

From Discord.

"I am attempting to use a Plotly Scatter Map. When I render it, it shows a basic blank chart. I tried to follow the official Plotly tutorial and it does the same thing. I'll put a screenshot below shortly.

This is the code from the "Basic example with Plotly Express" https://plotly.com/python/tile-scatter-maps/"

![image](https://github.com/user-attachments/assets/5b93cef2-8640-4827-a9ab-b38b279c1b9c)

### Environment

HEAD

### Code to reproduce

```
import pandas as pd
import plotly.express as px
df = px.data.carshare()
fig = px.scatter_map(df, lat="centroid_lat", lon="centroid_lon",     color="peak_hour", size="car_hours",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10)
fig
```

**Comment by Light2Dark** [comment]
hey, this is actually due to plotly migrating from mapbox to maplibre. https://plotly.com/javascript/maplibre-migration/

I’ve verified that upgrading `plotly.js` to the latest version resolves this issue. Would you like me to open a PR for this?

**Comment by mscolnick** [comment]
hey @Light2Dark, thank would be awesome / very much appreciated, thank you!
