### ISSUE TITLE
`marimo run` should have an option to stop once the notebook has finished running

### ISSUE THREAD

**Issue by patrick-kidger** [marimo-team/marimo#2341]
### Description

I'm in a scenario where I have code in a Marimo notebook, which I need to run through the CLI -- and once it has completed, move on to other things. (Specifically, I'm writing a test suite, and I'd checking that the library I'm writing is compatible with Marimo notebooks.)

Right now there doesn't seem to be a way to do this. `marimo run some_notebook.py` runs indefinitely, and I think the only way I'll be able to halt it is by fiddling around to run it in a separate thread.

### Suggested solution

`marimo run --until-done some_notebook.py`

**Comment by mscolnick** [comment]
does `python some_notebook.py` work? that seems like the use case you are describing

**Comment by akshayka** [comment]
> (Specifically, I'm writing a test suite, and I'd checking that the library I'm writing is compatible with Marimo notebooks.)

First of all, awesome!

Depending on your use case, perhaps what Myles has recommended is sufficient. If so, awesome and we can close.

If not, here are a couple options.

If you really need to test the `marimo run` command in particular in testing, and if you can edit the notebook source, you can add a call to `os._exit`:

```python
import marimo

__generated_with = "0.8.15"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import os
    return mo, os


@app.cell
def __(mo):
    for i in mo.status.progress_bar(range(10)):
        import time
        time.sleep(0.1)
        
    FINISHED = True
    return FINISHED, i, time


@app.cell
def __(FINISHED, os):
    if FINISHED:
        os._exit(0)
    return


if __name__ == "__main__":
    app.run()
```

Alternatively, maybe for your use case testing `marimo export html notebook.py` returns a status code of `0` might suffice?

**Comment by patrick-kidger** [comment]
Aha, wonderful -- `marimo export html notebook.py` did the trick perfectly. Thank you for that suggestion.

For completeness, on the other approaches:
- `python notebook.py` does not set the `__marimo__` variable, which I'm looking for to determine the Marimo-ness of a file.
- `marimo run notebook.py` with `os._exit(0)` works, but opens a web browser.
- `marimo run --headless notebook.py` with `os._exit(0)` does not work, and hangs in the same infinite loop as my original issue.

(To add some details on what I'm doing -- the library I'm writing involves manipulating source code. This means needing to detect Marimo-ness of a runtime environment, and then converting the source code using `marimo export script`.)
