### ISSUE TITLE
Hash source code to check whether exported HTML is up-to-date

### ISSUE THREAD

**Issue by patrick-kidger** [marimo-team/marimo#2346]
### Description

Feature request: for the source code of the `.py` file to be hashed and stored in the `.html` file it is exported to. This makes it possible to write a pre-commit check that validates that the HTML file is up-to-date with the `.py` file that generated it. It should be possible to manually compute this hash, and then manually edit this hash. (If I want to be sneaky and avoid running my notebook again.)

The use-case for this is to make this a pre-commit check. The use of auto-export (#2290) makes passing this check low-friction, but it doesn't offer a way for CI processes to verify that this has happened.

Right now this is one of the things that Jupyter noticeably falls over on -- I can run my notebook, and *then* edit my source code afterwards.

### Suggested solution

As above.

**Comment by mscolnick** [comment]
@patrick-kidger, if you run `marimo export html nb.py --include-code`, this includes the code in the html export.

this is meant to let you run the code yourself from an export, but you should be able to use it for your usecase

**Comment by patrick-kidger** [comment]
I might not want the code to appear in the generated HTML, however?

**Comment by mscolnick** [comment]
Got it. And is this for caching mainly (compute intensive workflows)? or do some integrity? 

What's wrong with putting the all the code in there (instead of the hash)? Do you want the code obfuscated or just a smaller footprint?

**Comment by dmadisetti** [comment]
Hashes also aren't reversible- so providing a hash doesn't mean you'll be able to associate it with the generating notebook. Works as a checksum, but you could also just look at modification timestamps.

How about dumping the git head hash of the notebook folder into the HTML, with a `dirty` flag if there are uncommitted changes? Also, prompts the good practice of committing early and frequently

**Comment by mscolnick** [comment]
Adding this in https://github.com/marimo-team/marimo/pull/2359

**Comment by patrick-kidger** [comment]
Awesome!
You guys are adding feature requests very rapidly, I look forward to the day when I can completely replace my Jupyter notebooks :)

For this one I think it's best paired with a pre-commit check. I can write one myself that does the introspection, but for broader use I'll make a follow-up feature request for providing that out-of-the-box.

**Comment by mscolnick** [comment]
Thanks @patrick-kidger, that'd be great. We can happily house it in the marimo-team org if you want help maintaining it and increasing discoverability.
