### ISSUE TITLE
Multiple for loops with the same iterator causes error

### ISSUE THREAD

**Issue by jr-leary7** [marimo-team/marimo#2347]
### Describe the bug

I'm writing a document in which I use the same style of for loop a couple times. I would like to use the same iterator, `i`, to be consistent. However, doing so more than once leads to an error in the DAG due to `i` being defined in multiple cells. I understand why this happens, as `marimo` tracks which variables are defined in which cells to create the DAG. However, `i` is a "temporary" variable that is only defined in the context of the for loop -- so in my mind, it doesn't make sense for it to be part of the DAG between cells. In addition, it's rather clunky to have to instead use different versions of `_i`, `ii`, etc. just to write a different loop. 

Is it possible to work around this somehow by having the DAG only include variables that are not defined in temporary contexts such as iterators ? I looked through prior issues / the discussions page / the docs but couldn't find anything related. 

### Environment

```
{
  "marimo": "0.8.15",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "i386",
  "Python Version": "3.12.5",
  "Binaries": {
    "Browser": "114.0.5735.198",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.5",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "pandas": "2.2.2"
  }
}
```

### Code to reproduce

```
# libraries
import pandas as pd
import marimo as mo
```

```
# some example data 
df = pd.DataFrame({
    'gene': ['gene1', 'gene2', 'gene3', 'gene4'], 
    'status': ['a', 'a', 'b', 'b'], 
    'mean': [1, 2, 3, 4]
})
```

```
# first loop 
for i, status in enumerate(df['status'].unique()): 
    sub_df = df[df['status'] == status]
    # create a plot, etc. 
```

```
# second loop -- this is where the error occurs 
for i, status in enumerate(df['status'].unique()): 
    sub_df = df[df['status'] == status]
    # create a different, but also necessary, plot
```

**Comment by mscolnick** [comment]
>  However, i is a "temporary" variable that is only defined in the context of the for loop 

This is[ actually a Python language feature](https://eli.thegreenplace.net/2015/the-scope-of-index-variables-in-pythons-for-loops/) (personally, I don't like it), but it keeps the variable assignments in scope, in case you wanted to use it later (for example, if you had a `break`).

We don't want to diverge from this spec (otherwise if you ran the code with just python `python nb.py`, since you can do this in marimo), you could get an inconsistent result.

We recommend making your variable **private**, by adding an underscore `_i`

**Comment by jr-leary7** [comment]
Ahhhh gotcha, I think I misunderstood what adding the _ to the variable name did. Thanks for the prompt response -- I love the tool you all have developed and have been evangelizing it at my work !
