### ISSUE TITLE
No new line when copying from Marimo NB output

### ISSUE THREAD

**Issue by muffin-rice** [marimo-team/marimo#2354]
### Describe the bug

Spaces replace newlines in Marimo output.

### Environment

 $ marimo env
{
  "marimo": "0.8.15",
  "OS": "Darwin",
  "OS Version": "23.5.0",
  "Processor": "arm",
  "Python Version": "3.12.6",
  "Binaries": {
    "Browser": "128.0.6613.138",
    "Node": "v20.17.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.1",
    "starlette": "0.38.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "pandas": "2.2.2",
    "pyarrow": "17.0.0"
  }
}

### Code to reproduce

print('Testing\nHello')

After copy pasting from cell output, I get `Testing Hello`

**Comment by mscolnick** [comment]
I cannot reproduce this - what browser are you using? can you include a short video

**Comment by muffin-rice** [comment]
I am using Firefox

Huh, trying again, I'm not sure if this is a bug with Marimo or differences in individual applications handling paste, but it's weird that this is the first time I've noticed this issue.

Pasting back in Marimo editor cell works as expected, Vim works, Github comment box works. 

However, pasting in Apple Notes and Google docs fails (replaces newline with space).

Are you able to reproduce in Google docs, or Notes if you are on a Mac?

**Comment by akshayka** [comment]
I can reproduce when copying from Firefox and pasting into Apple Notes. Copying from Chrome works. Curious ...

**Comment by akshayka** [comment]
If you paste without formatting — `cmd-shift-v` — in Google Docs, the newline is preserved.

**Comment by mscolnick** [comment]
Going to close as this issue seems to be outside marimo
