### ISSUE TITLE
Sorting a table with mixed values and ui elements leads to ui elements not rendered

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#2357]
### Describe the bug

I have table that I want to sort for a specific column which shows a score. The table also has a column that contains buttons that let me download some data. When I sort the numeric column, the column that contains the UI elements is not rendered.

### Environment

{
  "marimo": "0.8.17",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "125.0.6422.142",
    "Node": "v20.14.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "ruff": "0.5.2",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.9.0",
    "uvicorn": "0.29.0",
    "websockets": "11.0.3"
  },
  "Optional Dependencies": {
    "pandas": "2.2.2"
  }
}

### Code to reproduce

Here's a simple code to reproduce. Try to sort the columns "x" or "y", then column "c" disappears.

```python
import marimo

__generated_with = "0.8.17"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    data = [{"x": 1, "y": "a", "c": mo.ui.button(label="hello")}, {"x": 2, "y": "b", "c": mo.ui.button(label="world")}]
    return data,


@app.cell
def __(data, mo):
    mo.ui.table(data)
    return


if __name__ == "__main__":
    app.run()

**Comment by mscolnick** [comment]
Thanks for finding this @mrdobalina2k  - i have a fix out (https://github.com/marimo-team/marimo/pull/2358), should land soon
