### ISSUE TITLE
Marks for updated code since the last run of a cell

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2363]
### Description

With git, it's easy to visualize updated code since the last commit:

<img width="245" alt="Screenshot 2024-09-20 at 19 32 18" src="https://github.com/user-attachments/assets/6406ff7f-da93-47aa-a32c-579599fd8d16">

I suggest add similar marks for each cell. 
Specifically, show marks for updated code since the last run of a cell

**Comment by mscolnick** [comment]
This would be a great codemirror plugin as well. We have a lot of plugins that would be great to contribute back to
