### ISSUE TITLE
`alert` arg for  `marimo.status.progress_bar`

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2364]
### Description

Add an `alert` arg to `marimo.status.progress_bar`, alert completion message when progress is completed

---

Besides, 

A tiny doc issue [here](https://docs.marimo.io/api/status.html#progress-bar)

in the **Args** part, add description for `disabled` 

---

why this is valuable:

If I'm training a neural network and editing some other parts of the notebook, I'd like a notification when the training is done

**Comment by metaboulie** [comment]
I can implement this and fix the doc error if it's valuable

**Comment by mscolnick** [comment]
i like this idea. metaboulie, maybe for better composition, **what about an `mo.alert()`**? then you can place the alert after spinner too or before the progress. we also also had more arguments like title/description

**Comment by metaboulie** [comment]
Do you mean something like:
```python
for _ in mo.status.progress_bar(range(100)):
    await asyncio.sleep(0.5)
mo.toast("Finished.")
```

**Comment by metaboulie** [comment]
Should we put it inside Control flow or Status?

**Comment by mscolnick** [comment]
oh status is good - maybe `mo.status.toast()`
