### ISSUE TITLE
marimo edit not working

### ISSUE THREAD

**Issue by Elfrunner28** [marimo-team/marimo#2370]
### Describe the bug

I type marimo edit on my command prompt and it just takes me to a new notebook that is loading forever. and then when trying to quit, it doesn't let me

### Environment

{
  "marimo": "0.8.15",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 140 Stepping 2, GenuineIntel",
  "Python Version": "3.12.5",
  "Binaries": {
    "Browser": "128.0.6613.138",
    "Node": "v20.14.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.5",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}

### Code to reproduce

marimo edit

**Comment by mscolnick** [comment]
can you try re-installing it?

can you try `uvx marimo edit` and see if that works (need to install [uv](https://docs.astral.sh/uv/))

**Comment by akshayka** [comment]
@Elfrunner28 if reinstalling doesn't work, can you try creating a new directory, and running `marimo edit` from inside that new (empty) directory? I am curious if that works. If so that will help me narrow in on the bug.

**Comment by Elfrunner28** [comment]
> can you try re-installing it?
> 
> can you try `uvx marimo edit` and see if that works (need to install [uv](https://docs.astral.sh/uv/))

I re-installed and it worked just fine :)
