### ISSUE TITLE
download pdf gives totally blank preview, possibly only on windows

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#2376]
### Describe the bug

I worked on a notebook and wanted to share it, I used "download pdf" and looked at the print preview. It is totally blank. The pdf is also blank.

Here is a screenshot of the print preview
![image](https://github.com/user-attachments/assets/1054f893-d508-427f-9b92-812e90589f64)

And the pdf I generated:
[new notebook.py.pdf](https://github.com/user-attachments/files/17081428/new.notebook.py.pdf)

### Environment

{
  "marimo": "0.8.17",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "128.0.6613.85",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pygments": "2.16.1",
    "pymdown-extensions": "10.8.1",
    "ruff": "0.5.5",
    "starlette": "0.37.2",
    "tomlkit": "0.12.5",
    "typing-extensions": "4.7.1",
    "uvicorn": "0.30.1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.3.0",
    "pandas": "2.1.0",
    "polars": "1.2.1",
    "pyarrow": "16.1.0"
  }
}

### Code to reproduce

```
import marimo

__generated_with = "0.8.17"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import pylab as plt
    import numpy as np
    return mo, np, plt


@app.cell
def __(mo):
    mo.md(r"""hi I am testing export options""")
    return


@app.cell
def __(np, plt):
    plt.plot(np.arange(10))
    return


@app.cell
def __(mo, np, plt):
    plt.plot(np.arange(10))
    mo.mpl.interactive(plt.gcf())
    return


if __name__ == "__main__":
    app.run()
```
Then go to the hamburger menu and choose "download->pdf".

**Comment by mscolnick** [comment]
This could be a timing issue or windows issue. Can you retry this when toggling "app mode"?

**Comment by michaelnt** [comment]
I think I have the same problem (Windows, Chrome or Edge).

If I toggle app view, under "Present as", it works and I can save as pdf.

**Comment by ggggggggg** [comment]
Sounds like a good move. I was exporting from edit mode, I'll try from app mode when I'm back I. The office.
