### ISSUE TITLE
download as html missing markdown cell, and includes no outputs

### ISSUE THREAD

**Issue by ggggggggg** [marimo-team/marimo#2377]
### Describe the bug

I tried to download a notebook at HTML to share it with a colleague. I was hoping Pluto.jl level awesome, where you can actually download a notebook with interactive plots still working. I was expecting the interactive plots to embed as static images. What I got included no outputs, and was missing one markdown cell completely. 

Here is an image of what I see when opening the downloaded HTML:
![image](https://github.com/user-attachments/assets/a6f861f1-fbba-49bf-9008-325b6e45b9fa)

The main bug is the total lack of a markdown cell, though I also would really like it if it showed the static images corresponding to the plots.

Here is a link to the downloaded html in a gist: https://gist.github.com/ggggggggg/8158b6ef24f302c44d898fafaea13d80

### Environment

{
  "marimo": "0.8.17",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 85 Stepping 4, GenuineIntel",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "128.0.6613.85",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pygments": "2.16.1",
    "pymdown-extensions": "10.8.1",
    "ruff": "0.5.5",
    "starlette": "0.37.2",
    "tomlkit": "0.12.5",
    "typing-extensions": "4.7.1",
    "uvicorn": "0.30.1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.3.0",
    "pandas": "2.1.0",
    "polars": "1.2.1",
    "pyarrow": "16.1.0"
  }
}

### Code to reproduce

import marimo

__generated_with = "0.8.17"
app = marimo.App(width="medium")

@app.cell
def __():
    import marimo as mo
    import pylab as plt
    import numpy as np
    return mo, np, plt

@app.cell
def __(mo):
    mo.md(r"""hi I am testing export options""")
    return

@app.cell
def __(np, plt):
    plt.plot(np.arange(10))
    return

@app.cell
def __(mo, np, plt):
    plt.plot(np.arange(10))
    mo.mpl.interactive(plt.gcf())
    return

if __name__ == "__main__":
    app.run()

**Comment by akshayka** [comment]
Thanks for reporting — we'll look into this.

Strangely I can't reproduce this when I save as HTML on my machine, but I can verify that the HTML you got doesn't include outputs. @mscolnick could this be a timing issue on the frontend?

Static images for plots will work (once this bug is resolved). `mo.mpl.interactive()` plots won't work, but plots made with plotly or altair may retain limited interactivity.

**Comment by mscolnick** [comment]
Likely not a timing issue - possibly a windows issue. 

@ggggggggg could you share the html download with us (or a different one)

**Comment by ggggggggg** [comment]
There is a link to the generated html in my first post.

**Comment by mscolnick** [comment]
@ggggggggg, sorry i missed that. looking at it now, it looks like the outputs are not all being included. 

Can you consistently reproduce this? What steps are you taking to export this? Are you using `marimo edit` or `marimo run`?

**Comment by akshayka** [comment]
@ggggggggg , any help you can give to reproduce this issue would be very much appreciated. We'd love to solve this for you but can't reproduce.

**Comment by ggggggggg** [comment]
I ran `pip install --upgrade marimo` and went from 0.8.17 to 0.8.19 and tried to reproduce this today. I got all output in the html, including the `mo.mpl.interactive` plot being somewhat interactive. It had some glitches, but that's not the issue at hand.  

So I guess I'll close this, perhaps it was fixed by the update, or I'll re-open if I run into it again.
