### ISSUE TITLE
Hide markdown duplication in 'edit' view.

### ISSUE THREAD

**Issue by patrick-kidger** [marimo-team/marimo#2389]
### Description

I did a search but surprisingly could not see an existing issue for this. When editing a notebook, it would be nice to not see all of the markdown written out twice.

(This is kind of detail that makes Marimo a hard sell to my coworkers.)

I appreciate that you're getting bombarded with a lot of options for when to show/hide each individual widget in each mode. I'm sorry to be adding to that! :D

### Suggested solution

A Jupyter-like solution in which the display switches between the underlying markdown and the rendered HTML, when you click on it to edit it.

I appreciate that Marimo is a bit unusual in that it has *three* representations of Markdown (the underlying Python), which may complicate this further. I think the underlying Python is kind of an implementation detail of the serialization format though, maybe no-one ever needs to worry about that...

**Comment by akshayka** [comment]
We've talked about making the "markdown cells" WYSIWYG (like Colab for example), but it hasn't been a priority.

I'm surprised that the duplication makes it a hard sell, but that's good to know — thanks for letting us know.

>  I think the underlying Python is kind of an implementation detail of the serialization format though, maybe no-one ever needs to worry about that

The Python API of `mo.md()` is required for interpolating Python values (which requires using `mo.md(f"")`, including markdown in layouts, and conditionally writing markdown, all of which are not uncommon use cases. But you're totally right for pure markdown, `mo.md` is boilerplate.

**Comment by ngbrown** [comment]
I hope the issue with the PR is resolved and this comes back.
