### ISSUE TITLE
Multiple text boxes display bug

### ISSUE THREAD

**Issue by niv-gv** [marimo-team/marimo#2403]
### Describe the bug

I created a button that triggers a cell which creates some text boxes with default text. 
When adding an additional text box with an empty default text, it fetches the text from the other shown text box. 
After clicking the button again, it fixes the value, but it requires a second click to show the correct value. 

Also another weird thing - when checking any checkbox among the checkboxes, I need to click on the button / or run the relevant cell for it to run, although it depends on the checkbox's value. 

For reproduction:

1. Check box number 4
2. Click "Choose Experiments" button
3. Check box number 2
4. Click "Choose Experiments" button (here you'll see the wrong values in the new text box)
5. Click "Choose Experiments" button again (now you'll see the correct values)

### Environment

{
  "marimo": "0.8.19",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.3",
    "starlette": "0.38.4",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "pandas": "2.1.4",
    "polars": "1.6.0",
    "pyarrow": "15.0.2"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.8.19"
app = marimo.App(width="full")


@app.cell
def __():
    import marimo as mo
    return (mo,)


@app.cell
def __():
    exp_keys = range(1, 5)
    sub_exp_keys = range(1, 4)
    sub_exp_text = 'abc'

    experiments = {_k: {_s_k: sub_exp_text if _k > len(exp_keys) // 2 else '' for _s_k in sub_exp_keys} for _k in exp_keys}
    experiments
    return exp_keys, experiments, sub_exp_keys, sub_exp_text


@app.cell
def stack(exp_keys, mo):
    experiment_checkboxes = {_exp_number: mo.ui.checkbox(value=False, label=str(_exp_number)) for _exp_number in exp_keys}
    experiment_checkboxes_stack = mo.hstack(experiment_checkboxes.values(), wrap=True)
    experiment_checkboxes_stack
    return experiment_checkboxes, experiment_checkboxes_stack


@app.cell
def button(mo):
    trigger_button_update_experiments = mo.ui.button(
        on_click=lambda value: not value,
        value=True,
        label='Choose Experiments'
    )
    trigger_button_update_experiments
    return (trigger_button_update_experiments,)


@app.cell
def display(
    experiment_checkboxes,
    experiments,
    mo,
    trigger_button_update_experiments,
):
    _trigger = trigger_button_update_experiments.value
    experiments_to_show = [_exp_number for _exp_number, _checkbox in experiment_checkboxes.items() if _checkbox.value]
    print(experiments_to_show)

    mo_table = {
        str(_exp_number): mo.ui.table(
            {str(_sub_exp_number): mo.ui.text(
                value=experiments[_exp_number][_sub_exp_number]
            ) for _sub_exp_number in experiments[_exp_number].keys()}
        ) for _exp_number in experiments_to_show
    }

    mo_dict = mo.ui.dictionary(mo_table)

    mo_hstack = mo.hstack([mo_dict], wrap=True)
    mo_hstack
    return experiments_to_show, mo_dict, mo_hstack, mo_table


if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
Thanks for reporting. I think this is related to https://github.com/marimo-team/marimo/issues/2327. We'll dig deeper.
