### ISSUE TITLE
matplotlib: rc file not work

### ISSUE THREAD

**Issue by YDX-2147483647** [marimo-team/marimo#2404]
### Describe the bug

[Matplotlib uses `matplotlibrc` configuration files to customize properties.](https://matplotlib.org/stable/users/explain/customizing.html#the-matplotlibrc-file) For example, you can add `mathtext.fontset: cm` into the file `matplotlibrc`, and all math texts in plots will now in Computer Modern.

However, if you matplotlib in a marimo cell, the rc file takes no effect.

### Environment

```json
{
  "marimo": "0.8.19",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 166 Stepping 0, GenuineIntel",
  "Python Version": "3.12.5",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.10.1",
    "ruff": "0.6.7",
    "starlette": "0.39.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

Matplotlib version: 3.9.2

### Code to reproduce

`matplotlibrc`:

```yaml
mathtext.fontset: cm

This is an invalid line on purpose.
```

`test.py`:
```python
def foo():
    from matplotlib import rcParams, matplotlib_fname

    print("Outside:", rcParams["mathtext.fontset"], matplotlib_fname())


foo()

import marimo

app = marimo.App()


@app.cell
def __():
    from matplotlib import rcParams, matplotlib_fname

    print("In app:", rcParams["mathtext.fontset"], matplotlib_fname())


app.run()

foo()
```

`python test.py`:

```log
Missing colon in file 'matplotlibrc', line 3 ('This is an invalid line on purpose.')   ✅ expected
Outside cm matplotlibrc                ✅ expected
In app: dejavusans matplotlibrc     😖 it should be `cm`
Outside: dejavusans matplotlibrc   ❓ side effect?
```

### Question

Is it by design for reproducibility? I have found nothing in the doc or discord…

### Workaround

Set `rcParams["mathtext.fontset"] = 'cm'` dynamically in the cell.

[Runtime rc settings — Customizing Matplotlib with style sheets and rcParams — Matplotlib 3.9.2 documentation](https://matplotlib.org/stable/users/explain/customizing.html#runtime-rc-settings)

**Comment by YDX-2147483647** [comment]
Wow, thanks for showing the way.

I add `if key == 'mathtext.fontset': print(f"{key} = {val}")` in `RcParams._set(self, key, val)` https://github.com/matplotlib/matplotlib/blob/a254b687df97cda8c6affa37a1dfcf213f8e6c3a/lib/matplotlib/__init__.py#L692, and find something weird: `rcParams` is set three times! And marimo somehow changes the order…

```python
def foo():
    print("Outside:")
    from matplotlib import rcParams, matplotlib_fname


foo()

import marimo

app = marimo.App()


@app.cell
def __():
    print("Before import?")
    from matplotlib import rcParams, matplotlib_fname


print("In app:")
app.run()
```

```log
Outside:
mathtext.fontset = dejavusans
mathtext.fontset = cm
mathtext.fontset = cm
In app:
mathtext.fontset = cm
mathtext.fontset = cm
mathtext.fontset = dejavusans
Before import?
```

**Comment by akshayka** [comment]
Thank you for investigating! So it looks like `apply_theme`, specifically `matplotlib.style.use`, is causing the rcParams to be reset?

**Comment by YDX-2147483647** [comment]
`matplotlib.style.use("dark_background")` is OK, but `matplotlib.style.use("default")` overrides the rc file. Change `apply_theme(self, theme: Theme)` to the following would fix the issue.

```python
if theme == "dark":
        matplotlib.style.use("dark_background")
```

But if `apply_theme` multiple times, first dark then light, it won't change.

**Comment by akshayka** [comment]
Awesome, thank you so much for looking into this! I will make a PR with a fix.

**Comment by YDX-2147483647** [comment]
Wait! If `apply_theme` is called multiple times, the “fix” might break things.

**Comment by akshayka** [comment]
Thanks! I can test. Or, if you'd like to make the PR yourself (you're more than welcome to!), I can hold off and leave this for you. Either works 🙂

**Comment by YDX-2147483647** [comment]
It’s nice of you, please go ahead and get it fixed. It looks like that you are more familiar with the code base, and therefore more capable of it.
