### ISSUE TITLE
import yaml not found while present (only import with issue)

### ISSUE THREAD

**Issue by shuther** [marimo-team/marimo#2413]
### Describe the bug

I am using pipx to install the packages, such as:
`pipx inject marimo itables`

It is working well, except for PyYAML; pipx is saying already present. I even tried to force it:
`pipx inject marimo pyaml`
I even restarted marimo.

However in the notebook, marimo complains for:
`import pyyaml`
It was proposing to install it using pip. It seems it completed the work (no complain on the frontend), but I had the error below in the server console (not using if they are from pip or marimo):
```
WARNING: Error parsing dependencies of send2trash: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    sys-platform (=="darwin") ; extra == 'objc'
                 ~^
WARNING: Error parsing dependencies of shredder: Invalid version: '2.9.0.Odd.Olm'
WARNING: Error parsing dependencies of devscripts: Invalid version: '2.22.1ubuntu1'
```

Still, the import is not recognized by marimo and I don't have the option the reinstall it using a different package manager.
I was able to create a new notebook to test it further, but the other ones were not successful as expected.

Error: 
`ModuleNotFoundError: No module named 'pyyaml'`

### Environment

{
  "marimo": "0.8.20",
  "OS": "Linux",
  "OS Version": "6.10.10-zabbly+",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "129.0.6668.58",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "6.4.4",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.4",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "anywidget": "0.9.13",
    "duckdb": "1.0.0",
    "pandas": "2.2.2",
    "polars": "1.6.0",
    "pyarrow": "17.0.0"
  }
}

### Code to reproduce

import pyyaml

**Comment by mscolnick** [comment]
Looking at pyaml's docs, I think it should be `import yaml` not `import pyaml`

https://pyyaml.org/wiki/PyYAMLDocumentation
