### ISSUE TITLE
Run apps in sandbox by default

### ISSUE THREAD

**Issue by martimlobao** [marimo-team/marimo#2414]
### Description

I just came across marimo and am really enjoying using it! I especially love how it uses `uv` to build the requirements incredibly fast, making it very easy to boot up a notebook without having to think about activating any virtual environments.

One thing that struck me as unexpected is how `marimo run` didn't create a standalone environment for the app automatically and instead gave an error about missing packages. My expectation would be that when running this as an app, a user likely just wants to run the app and have it handle everything automatically, without needing to pass in any extra arguments.

### Suggested solution

Instead of having a `--sandbox` argument when running `marimo run`, it would seem like it might even be smarter to have the sandbox enabled by default and possibly having a `--no-sandbox` argument if the user didn't wish to use the sandbox.

### Alternative

Although I believe the use cases are different, it's possible to make the argument that this causes some inconsistency in using `edit` vs using `run`. One alternative solution might be to have everything _always_ run in a sandbox by default.

**Comment by mscolnick** [comment]
This is a great idea and we are doing something for this (already in a pr! https://github.com/marimo-team/marimo/pull/2412)

We don't want to enforce people to install `uv` and other users may use marimo in a larger project where their environments are already set up - so in the meantime, we will ask user's if they would like to if one can be created for them.
