### ISSUE TITLE
Failed to format with ruff

### ISSUE THREAD

**Issue by shuther** [marimo-team/marimo#2424]
### Describe the bug

Error server side with log level=debug when forcing the format the code:
```
[E 240927 08:55:25 formatter:74] Failed to format code with ruff
[D 240927 08:55:25 formatter:75] Command '['ruff', 'format', '--line-length', '79', '-']' returned non-zero exit status 1.
```

Expectation:
- configure the formatting / --line-length(maybe using a 
- (.)ruff.toml?) so some rules could be added/removed as needed?
- better debug log (debug log request should cascade to ruff?)

### Environment

{
  "marimo": "0.8.20",
  "OS": "Linux",
  "OS Version": "6.10.10-zabbly+",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "129.0.6668.58",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "6.4.4",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.4",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "anywidget": "0.9.13",
    "duckdb": "1.0.0",
    "pandas": "2.2.2",
    "polars": "1.6.0",
    "pyarrow": "17.0.0"
  }
}

### Code to reproduce

not sure which line brings the problem (would be a nice addition) and if it relates to ruff error E501.

**Comment by mscolnick** [comment]
@shuther - this error is a correct error if you python code is not formattable. this can be the case if its not valid code (which can happen as you write it)

can you confirm is this error happens all the time or just when it is invalid code?
for example, can you format with:
```
[1, 2,]
```
and also format with
```
[1, 2,]]
```
the second should fail

**Comment by mscolnick** [comment]
@shuther - also ruff should pick up your ruff.toml or ruff config in pyproject.toml already
