### ISSUE TITLE
mo.ui.number with infinite bounds set values to None when changed

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#2426]
### Describe the bug

I want to create a number component, but I dont want to set an upper or lower limit, so I simply used numpys infinity representation. Unfortunately, if I do that and I change the values using the up or down arrows, the value of the number field is set to None. I would expect that I could set open limits like this, where I don't want to limit the user.

### Environment

{
  "marimo": "0.8.20",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "125.0.6422.142",
    "Node": "v20.14.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "ruff": "0.5.2",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.9.0",
    "uvicorn": "0.29.0",
    "websockets": "11.0.3"
  },
  "Optional Dependencies": {
    "pandas": "2.2.2"
  }
}

### Code to reproduce

Here's a code that creates two number objects. The first uses very large values (integer) manually set (+/- 1e255) to set the boundaries. This works if you change the value using the arrows. The second uses numpy s "inf" value is the floating point representation of infinity as pr IEEE754.

```python

import marimo

__generated_with = "0.8.20"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import numpy as np
    return mo, np


@app.cell
def __(mo):
    def _on_change(new_value):
        print(new_value)
    number = mo.ui.number(start=-1e255, stop=1e255, value=5, on_change=_on_change)
    number
    return (number,)


@app.cell
def __(mo, np):
    def _on_change(new_value):
        print(new_value)
    number2 = mo.ui.number(start=-np.inf, stop=np.inf, value=5, on_change=_on_change)
    number2
    return (number2,)


if __name__ == "__main__":
    app.run()

**Comment by mscolnick** [comment]
I am pretty sure those numbers will overflow in the frontend (javascript limitation). We probably do most of these:
1) should warn on the backend
2) support BigInt numbers
3) make the bounds optional

**Comment by mrdobalina2k** [comment]
I think bounds as optional is just as good. But for now the workaround I found was to chose something unrealistically high. It didn't overflow on my end however.
