### ISSUE TITLE
multiselect : select / unselect all is painful

### ISSUE THREAD

**Issue by sebvey** [marimo-team/marimo#2432]
### Description

When more than 2O options are available on a mo.ui.multiselect component, it's really painful to select/unselect  all options.

### Suggested solution

Add a 'select all' and a 'unselect all' button

### Additional context

Thanks guys, I love marimo !

**Comment by mscolnick** [comment]
Thanks for the feedback, i have a fix for this https://github.com/marimo-team/marimo/pull/2433
