### ISSUE TITLE
S3 integration doesn't allow empty credentials

### ISSUE THREAD

**Issue by tmchartrand** [marimo-team/marimo#2438]
### Describe the bug

The AWS S3 integration panel on marimo.io states "Leave empty if the bucket is public." for the credentials fields, but doesn't actually allow empty input!

### Environment

marimo.io

**Comment by mscolnick** [comment]
Thanks for flagging. Does fake credentials work in the meantime?

**Comment by tmchartrand** [comment]
I tried a random string and it didn't work, but maybe a more realistic-looking fake would (ie the correct lengths)?

**Comment by mscolnick** [comment]
@tmchartrand I relaxed the constrain on the field being required. Can you give it another try?

**Comment by tmchartrand** [comment]
Thanks! tried it out, but it now seems to be creating the mount point but failing to actually mount (empty directory)

**Comment by mscolnick** [comment]
sorry @tmchartrand, i didn't quite test all the way through that empty credentials were ok by the S3 client. i made another fix to allow the S3 client to work with public bucket.

let me know how it works for you!

**Comment by tmchartrand** [comment]
loooks good to me, thanks for the quick fix!
