### ISSUE TITLE
Reactive plots don't work with Plotly Treemaps

### ISSUE THREAD

**Issue by dboeke** [marimo-team/marimo#2457]
### Describe the bug

I am following this guide:  https://docs.marimo.io/guides/plotting.html#plotly  

According to the docs, using mo.ui.plotly(_fig) should return a plot and a list of dictionaries representing the selected data.

When using the [treemap chart type](https://plotly.com/python/treemaps/), this interactivity does not work.  `value` returns an empty dictionary and interacting with the chart has no impact on the results.

### Environment

{
  "marimo": "0.8.15",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "arm",
  "Python Version": "3.12.6",
  "Binaries": {
    "Browser": "--",
    "Node": "v22.8.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.9",
    "ruff": "0.6.5",
    "starlette": "0.38.5",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "duckdb": "1.1.0",
    "pandas": "2.2.2"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.8.15"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import plotly.express as px

    mo.md("# Testing Plotly Issue")
    return mo, px


@app.cell
def __(mo, px):
    _df = px.data.tips()
    _fig = px.treemap(_df, path=[px.Constant("all"), 'day', 'time', 'sex'], values='total_bill')

    plot = mo.ui.plotly(_fig)
    return plot,


@app.cell
def __(mo, plot):
    mo.vstack([plot, plot.value], align="stretch")
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
ah - we don't support treemaps. I can look into supporting this. Just at a glance, it seems like tree-plots don't emit "selection" like plotly scatter plots do, but maybe there is another param we can hook into.

**Comment by dboeke** [comment]
Ah!  I guess change to a feature request then.  Treemaps return a dict when you select leafs:

```python
{'points': [{'curveNumber': 0, 'pointNumber': 5, 'currentPath': 'Root/A/', 'root': 'Root', 'entry': 'Root', 'percentRoot': 0.2, 'percentEntry': 0.2, 'percentParent': 0.5, 'parent': 'A', 'label': 'A2'}]}
```

Example using dash:  

```python
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output

# Sample data for treemap
labels = ["Root", "A", "B", "C", "A1", "A2", "B1", "B2", "C1"]
parents = ["", "Root", "Root", "Root", "A", "A", "B", "B", "C"]

# Create treemap figure
fig = go.Figure(go.Treemap(
    labels=labels,
    parents=parents
))

# Create Dash app to capture the selection
app = Dash(__name__)

app.layout = html.Div([
    dcc.Graph(id="treemap", figure=fig),
    html.Pre(id="output", style={"whiteSpace": "pre-wrap"})
])

# Callback to handle click data
@app.callback(
    Output("output", "children"),
    Input("treemap", "clickData")
)
def display_click_data(clickData):
    return str(clickData)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by mscolnick** [comment]
I was able to patch the library we use under the hood to make this work as expected. Should be fixed in the next PR: https://github.com/marimo-team/marimo/pull/2463
