### ISSUE TITLE
LaTeX rendering in Markdown doesn't seems to support correctly superscript

### ISSUE THREAD

**Issue by scls19fr** [marimo-team/marimo#2459]
### Describe the bug

![image](https://github.com/user-attachments/assets/8fb6899b-60cc-4e8a-ae9b-8668f1236529)

### Environment

    {
      "marimo": "0.8.22",
      "OS": "Windows",
      "OS Version": "11",
      "Processor": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
      "Python Version": "3.11.7",
      "Binaries": {
        "Browser": "128.0.6613.138",
        "Node": "v22.4.0"
      },
      "Dependencies": {
        "click": "8.1.7",
        "importlib-resources": "missing",
        "jedi": "0.18.1",
        "markdown": "3.6",
        "pygments": "2.15.1",
        "pymdown-extensions": "10.8.1",
        "ruff": "0.3.5",
        "starlette": "0.37.2",
        "tomlkit": "0.12.5",
        "typing-extensions": "4.9.0",
        "uvicorn": "0.30.1",
        "websockets": "12.0"
      },
      "Optional Dependencies": {
        "altair": "5.0.1",
        "pandas": "2.1.4",
        "pyarrow": "14.0.2"
      }
    }

### Code to reproduce

Hello,

    import marimo
    g = 9.81
    mo.md(f"""$g = {g} m.s^{-2}$""")

doesn't print superscript correctly

but

    mo.md("""$$g = 9.81 m.s^{-2}$$""")

does

what is the most appropriate way to mix LaTeX and f-string in Marimo Mardown output ?

Kind regards

**Comment by mscolnick** [comment]
Hi @scls19fr, you need to escape backets `{}` if you are using f-strings, to do so, you just need to double-backet:

```python
mo.md(f"""$g = {g} m.s^{{-2}}$""")
```

**Comment by scls19fr** [comment]
Thanks @mscolnick 
Maybe it should be somewhere in docs... probably https://docs.marimo.io/api/markdown.html

**Comment by mscolnick** [comment]
I agree @scls19fr, it can be a common gotcha, and would be great to document. Would you be open to making the contribution?

**Comment by scls19fr** [comment]
Sorry I'm quite busy currently and can't provide such a contribution
