### ISSUE TITLE
Amend runtime uv package management

### ISSUE THREAD

**Issue by liquidcarbon** [marimo-team/marimo#2465]
https://github.com/marimo-team/marimo/blob/218870cee12faf5fe6b14c60cd0a640267508e48/marimo/_runtime/packages/pypi_package_manager.py#L106

Would it be possible to amend this to include the python executable, from the same environment from which marimo was launched?  Otherwise uv can install things into wrong place, and the runtime won't "see" the new packages.

Basically, the command needs one more argument `-p {Path(".venv/bin/marimo").parent / "python"}`
happy to put in a PR if the idea makes sense.

PS super impressive that you're supporting ALL the package mangers 🤯

**Comment by akshayka** [comment]
> Would it be possible to amend this to include the python executable, from the same environment from which marimo was launched? Otherwise uv can install things into wrong place, and the runtime won't "see" the new packages.

Oh interesting. Yea we can. 

> Basically, the command needs one more argument `-p {Path(".venv/bin/marimo").parent / "python"}`

Let me see if there is a more reliable way to get the current Python executable. I think the current directory where marimo is running may not necessarily be where the `venv` is stored

> PS super impressive that you're supporting ALL the package mangers 🤯

We're trying! :)

**Comment by liquidcarbon** [comment]
If this helps, this is how I handle paths in puppy: https://github.com/liquidcarbon/puppy/blob/main/pup.py#L22-L25

And then
```
    cmd = f"{PUP_UV} venv {PUP_HOME / where}/.venv -p {PUP_PYTHON}"
    tee(cmd)
    subprocess.run(cmd.split())
```

**Comment by liquidcarbon** [comment]
Alternative (a bit dirty): figure out where the newly installed packages went, and quietly append to sys.path

**Comment by akshayka** [comment]
Can we just do: `-p {sys.executable}`?

**Comment by liquidcarbon** [comment]
Yeah! The same thing will work for pip, too.
