### ISSUE TITLE
[UX] Cmd+Shift+P/O should yank selected text into new cell

### ISSUE THREAD

**Issue by mholub** [marimo-team/marimo#2474]
### Description

It feels like it improves UX slightly

most common case when I want to do it - I write code in one cell and then I want to split piece of it into another cell, happens a lot with marimo.ui elements cause they want to be in separate cells anyway to work - you can't use value in the same cell

But I think it is generally useful and follows principle of least surprise

### Suggested solution

So if you have text selected inside cell source code and press Cmd+Shift+P - it appends new cell (like now) and automatically fills it with selected text (and edits current cell)

**Comment by wasimsandhu** [comment]
Should highlighting text and creating a new cell with the keyboard shortcuts cut and paste that code into the new cell? I implemented this fairly quickly but think this deserves more discussion because the UX feels a little funny to me. I'll open a PR so we can play around with it.

**Comment by wasimsandhu** [comment]
Never mind I like it 👍🏽
