### ISSUE TITLE
Ploty figures can't be displayed

### ISSUE THREAD

**Issue by proItheus** [marimo-team/marimo#248]
### Describe the bug

![Screenshot_20231025_195155](https://github.com/marimo-team/marimo/assets/50539150/707fccf2-d66a-4c80-94cc-9b09da03c715)

As the screenshot says.

### Version

0.1.36

### Code to reproduce

```python
import marimo

__generated_with = "0.1.36"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    from plotly import express as px
    import numpy as np
    return mo, np, px


@app.cell
def __(np):
    x = np.linspace(0, 1, 50)
    return x,


@app.cell
def __(px, x):
    px.line(x, x)
    return


if __name__ == "__main__":
    app.run()
```

**Comment by akshayka** [comment]
@proItheus, we've cut a new release with a fix, version 0.1.37. Feel free to re-open this issue if you're still having problems.
