### ISSUE TITLE
Altair Charts fail to adapt to dark mode

### ISSUE THREAD

**Issue by ngriffiths13** [marimo-team/marimo#2483]
### Describe the bug

When switched to dark mode, altair charts don't switch correctly. Instead the text disappears and only the chart lines are left.
<img width="1069" alt="Screenshot 2024-10-02 at 9 39 20 PM" src="https://github.com/user-attachments/assets/6ce3e1e8-539e-4cd5-9237-7805a5f734fa">

### Environment

```
{
  "marimo": "0.8.22",
  "OS": "Darwin",
  "OS Version": "23.2.0",
  "Processor": "arm",
  "Python Version": "3.11.9",
  "Binaries": {
    "Browser": "129.0.6668.72",
    "Node": "v22.6.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "6.4.5",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "ruff": "0.6.8",
    "starlette": "0.37.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "pandas": "2.2.3",
    "polars": "1.9.0",
    "pyarrow": "17.0.0"
  }
}
```

**Comment by mscolnick** [comment]
@ngriffiths13 - i cannot reproduce this. any chance you can include some code with a reproduction?

**Comment by ngriffiths13** [comment]
@mscolnick I am struggling to reproduce it. In some notebooks I am seeing it works and in some it doesnt in the same environment. Working my way towards and MRE.

**Comment by wasimsandhu** [comment]
Busted!

![Screenshot 2024-10-07 at 8 00 48 PM](https://github.com/user-attachments/assets/d0aa08ca-ebc6-44ea-9ac0-6a7646e24be2)
