### ISSUE TITLE
Add support for `pygwalker` data visualization tool

### ISSUE THREAD

**Issue by Haleshot** [marimo-team/marimo#2486]
### Describe the bug

Tried a very sample demo with a sample code from the [pygwalker repo](https://github.com/Kanaries/pygwalker); it resulted in:
```
Unsupported mimetype: application/vnd.jupyter.widget-view+json
```
being displayed on top of the cell block.

Would having this data visualization tool integrated into marimo be encouraged?

Some screenshots to support:

In marimo:
![marimo-demo](https://github.com/user-attachments/assets/2ec9d5c7-e667-4559-bc8c-410272dd9818)

In Jupyter labs (from pygwalker repo):
![](https://docs-us.oss-us-west-1.aliyuncs.com/img/pygwalker/travel-ani-0-light.gif)

### Environment

```json
{
  "marimo": "0.8.19",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "128.0.6613.120",
    "Node": "v18.17.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "6.4.5",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.8.1",
    "ruff": "0.6.0",
    "starlette": "0.37.2",
    "tomlkit": "0.12.5",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "duckdb": "1.1.1",
    "pandas": "2.2.2",
    "pyarrow": "17.0.0"
  }
}
```

### Code to reproduce

Import pygwalker and pandas to your Jupyter Notebook to get started.

```python    
import pandas as pd
import pygwalker as pyg
```

You can use pygwalker without breaking your existing workflow. For example, you can call up PyGWalker with the dataframe loaded in this way:

```python
df = pd.read_csv('filename.csv')
walker = pyg.walk(df)
```

**Comment by Haleshot** [comment]
Would like to ask how this issue can be tackled; something to do solely with adding/handling [mimetypes ](https://github.com/marimo-team/marimo/blob/main/marimo/_output/mime.py)in marimo.

**Comment by mscolnick** [comment]
@Haleshot, quick solution is we can by outputting the HTML

```python
import pygwalker as pyg
import marimo as mo
from vega_datasets import data

walker = pyg.walk(data.iris())
mo.iframe(walker.to_html_without_iframe())
```

It should return a mime type of HTML as well, but looks like it doesn't. I can look if we can support this though.

**Comment by mscolnick** [comment]
@Haleshot could you actually file a feature request on the pywalker repo so that `pygwalker.api.pygwalker.PygWalker` could implement a `_repr_html_` or `_mime_` ([see docs](https://docs.marimo.io/guides/integrating_with_marimo/displaying_objects.html))

**Comment by Haleshot** [comment]
> @Haleshot, quick solution is we can by outputting the HTML
> 
> ```python
> import pygwalker as pyg
> import marimo as mo
> from vega_datasets import data
> 
> walker = pyg.walk(data.iris())
> mo.iframe(walker.to_html_without_iframe())
> ```
> 
> It should return a mime type of HTML as well, but looks like it doesn't. I can look if we can support this though.

When trying this; I thought doing something relating to anywidget might lead to a successful output.

**Comment by Haleshot** [comment]
> @Haleshot could you actually file a feature request on the pywalker repo so that `pygwalker.api.pygwalker.PygWalker` could implement a `_repr_html_` or `_mime_` ([see docs](https://docs.marimo.io/guides/integrating_with_marimo/displaying_objects.html)), otherwise looks like this:
> 
> ![image](https://private-user-images.githubusercontent.com/2753772/373273099-3a078cb9-a0c1-4d5e-881d-9ad374f16dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjI4NTAsIm5iZiI6MTcyNzk2MjU1MCwicGF0aCI6Ii8yNzUzNzcyLzM3MzI3MzA5OS0zYTA3OGNiOS1hMGMxLTRkNWUtODgxZC05YWQzNzRmMTZkZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTMzNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDlhN2MwNDMxYTY4M2EwOWUyOGJhOTM5ZTk4ZmQ2ZGQ4MjU3ZTgyYWM4YmQ0NjMxZjQ1MDg5OTY4ZmFkZjZmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wp0EaAPhmPm0GcPhUtqn-4ge4vK16zU1PzfseNUNEQA)

Sure, will check this out and raise a feature request there!

**Comment by Haleshot** [comment]
Linking the relevant issue request here - https://github.com/Kanaries/pygwalker/issues/638

**Comment by Haleshot** [comment]
Closing this issue as pygwalker support was added to marimo!

Relevant links:
1) https://github.com/Kanaries/pygwalker/issues/638
2) https://github.com/Kanaries/pygwalker/pull/647
3) https://github.com/Kanaries/pygwalker/pull/649

Thanks to everyone who helped in this integration.

_Relevant SS:_
<details>

![image](https://github.com/user-attachments/assets/8419779e-e4cf-479e-ba1a-56c8167d6ccd)
</details>


Sample code for anyone who wants to try:
<details>

```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "marimo",
#     "pandas==2.2.3",
#     "pygwalker==0.4.9.12",
#     "openai==1.52.2",
#     "polars==1.12.0",
# ]
# ///

import marimo

__generated_with = "0.9.14"
app = marimo.App(width="medium")


@app.cell
def __(pd, walk):
    _df = pd.read_csv("../Exploratory-Data-Analysis/assets/books_enriched.csv")

    walk(_df, spec="spec.json")
    return


@app.cell
def __(pd, pyg):
    _df = pd.read_csv("../Exploratory-Data-Analysis/assets/books_enriched.csv")
    pyg.walk(_df, spec="spec.json")
    return


@app.cell(hide_code=True)
def __():
    # import libraries
    import marimo as mo
    import pandas as pd
    from pygwalker.api.marimo import walk
    import pygwalker.api.marimo as pyg
    return mo, pd, pyg, walk


if __name__ == "__main__":
    app.run()
```
</details>
