### ISSUE TITLE
cache decoraor not found in latest Pypi version

### ISSUE THREAD

**Issue by Auric-Manteo** [marimo-team/marimo#2487]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

Hi,

I followed the documentation to use the cache decorator and got the following error:
![image](https://github.com/user-attachments/assets/0c114350-78e0-4ed6-ac4a-e4a91aa92abc)

### Your Suggestion for Changes

The documentation should be valid for the latest pypi version. Not sure if this is a bug or if I am using the wrong version, but it would improve the user experience if there was some easy way to determine if the documented feature has not been published.

**Comment by mscolnick** [comment]
Sorry our docs are a bit ahead of the release, since the release got delayed with a few bugs that have popped up. 

We can look into releasing docs just on library releases.

**Comment by akshayka** [comment]
@Auric-Manteo , the latest version of marimo is now consistent with the docs.

**Comment by Auric-Manteo** [comment]
awesome, thanks!
