### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'model')

### ISSUE THREAD

**Issue by bmuckianupgrade** [marimo-team/marimo#2497]
### Describe the bug

Seeing an error at the bottom of the UI/page which reads: Something went wrong along with "Cannot read properties of undefined (reading 'model')"; how to overcome/avoid?

### Environment

{
  "marimo": "0.9.0",
  "OS": "Linux",
  "OS Version": "6.6.26-linuxkit",
  "Processor": "",
  "Python Version": "3.10.14",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "ruff": "0.6.9",
    "starlette": "0.39.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.1",
    "uvicorn": "0.30.1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "duckdb": "1.1.1",
    "pandas": "2.2.3",
    "polars": "1.9.0",
    "pyarrow": "17.0.0"
  }
}

### Code to reproduce

<img width="412" alt="Screenshot 2024-10-04 at 11 38 23 AM" src="https://github.com/user-attachments/assets/ddc52fb8-cb06-44f9-9050-0d3f644244ac">

[0.0.0.0-1728067234243.log](https://github.com/user-attachments/files/17262623/0.0.0.0-1728067234243.log)

**Comment by akshayka** [comment]
Can you try upgrading? We just released a patch

**Comment by mscolnick** [comment]
This should be fixed on latest, can you upgrade?
