### ISSUE TITLE
Magic module installation does not use same virtual environment as Marimo

### ISSUE THREAD

**Issue by simonw** [marimo-team/marimo#2498]
### Describe the bug

I tried running this:
```python
import llm
```
And then clicking the "install module" button. The first time I tried it this seemed to work but then I could not import the module. I think it was installed in the wrong virtual environment.

Worth noting that I had started Marimo using `uvx marimo new`, so it was not running in my system's default environment.

### Environment

I ran `uvx marimo env`:
```json
{
  "marimo": "0.9.1",
  "OS": "Darwin",
  "OS Version": "24.0.0",
  "Processor": "arm",
  "Python Version": "3.12.0",
  "Binaries": {
    "Browser": "129.0.6668.90",
    "Node": "v22.4.1"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "ruff": "0.6.9",
    "starlette": "0.39.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.31.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

### Code to reproduce

Run this:
```bash
uvx marimo new
```
Then this:
```python
import llm
```

**Comment by simonw** [comment]
When I'm working with Jupyter notebooks I always install packages like this:
```
%pip install llm
```
Because that way it is guaranteed to use a `pip` that is running in the same environment as the notebook itself, which means I don't have to even think about what virtual environment that might be.

**Comment by akshayka** [comment]
Thanks for reporting; we'll fix this

**Comment by mscolnick** [comment]
@simonw what version of `uv` are you using? this works for me, and I reported this before for `uv run` and they fixed it: https://github.com/astral-sh/uv/pull/6543

**Comment by simonw** [comment]
```bash
uv --version
```
```
uv 0.4.1 (823f23e22 2024-08-30)
```
I'm upgrading it now:
```bash
uv pip install -U uv
uv --version
```
```
uv 0.4.18 (7b55e9790 2024-10-01)
```
And now:
```bash
uvx marimo new
```
Then:
```python
import llm
```
![CleanShot 2024-10-04 at 12 53 13@2x](https://github.com/user-attachments/assets/8079d352-a2a5-4a06-bea3-4f236f81618e)

That default `pip` option gave me the same problem. I tried again and this time switched to `uv` in that menu:

![CleanShot 2024-10-04 at 12 53 13@2x](https://github.com/user-attachments/assets/5a207edf-3142-4c5d-a741-5db2ef7e3ed7)

And that worked!

So there's still a problem here with the default option to use "pip", I think.

**Comment by simonw** [comment]
... and now I can't replicate the problem I had with `pip`. I tried this:

```bash
rm -rf ~/.local/share/uv/tools/marimo/
uvx marimo new
```
And this time when I did the `import llm` and then click install dance it worked as it should.

So maybe there was something broken in my `uvx marimo` environment which I fixed by deleting that directory in order to recreate it?

**Comment by akshayka** [comment]
Cool, thanks for reporting back; good to hear that it's at least working now, though like the other issue, I'm not sure how it would have become broken in the first place.

I will close this issue for now, but if it shows up again let us know?

**Comment by mscolnick** [comment]
You probably can't install with pip if you are running in a uv venv. Maybe we could figure that out and warn you.
