### ISSUE TITLE
Problem with image binary data in marimo+anywidget

### ISSUE THREAD

**Issue by gereleth** [marimo-team/marimo#2506]
### Describe the bug

I got a [report](https://github.com/gereleth/jupyter-bbox-widget/issues/31)  of my anywidget-based widget not working in `marimo`. The widget works with images and I use a `traitlets.Bytes` trait for the image's binary data in order to display it.

For a minimal reproduction let's examine this tiny widget with a binary data trait. It displays `true` if we successfully get the binary data to the frontend. Example is adapted from issue #2366 .

```python
import anywidget
import traitlets
import numpy as np
from pathlib import Path

class BytesWidget(anywidget.AnyWidget):
    _esm = """
    function render({ model, el }) {
      let value = model.get("value");
      el.innerText = value instanceof DataView;
    }
    export default { render };
    """
    value = traitlets.Bytes().tag(sync=True)
```

Issue #2366 showed a similar widget with binary data coming from a numpy array and it works and displays `true` as expected.

```python
# displays true
BytesWidget(value=np.array([1,2,3]).tobytes())
```

But if the bytes come from reading in an image file instead then suddenly we get `false` in `marimo`. In Jupyter both examples display `true`.

```python
# displays false in marimo, true in Jupyter
BytesWidget(value=Path('test.png').read_bytes())
```

I'm pretty puzzled about where the difference might be coming from. Is this a bug in handling binary data in `marimo`?

### Environment

    {
      "marimo": "0.9.1",
      "OS": "Linux",
      "OS Version": "6.0.12-100.fc35.x86_64",
      "Processor": "x86_64",
      "Python Version": "3.10.8",
      "Binaries": {
        "Browser": "--",
        "Node": "v22.3.0"
      },
      "Dependencies": {
        "click": "8.1.7",
        "importlib-resources": "missing",
        "jedi": "0.19.1",
        "markdown": "3.7",
        "pygments": "2.18.0",
        "pymdown-extensions": "10.11.2",
        "ruff": "0.6.9",
        "starlette": "0.39.2",
        "tomlkit": "0.13.2",
        "typing-extensions": "4.12.2",
        "uvicorn": "0.31.0",
        "websockets": "12.0"
      },
      "Optional Dependencies": {
        "anywidget": "0.9.13"
      }
    }

### Code to reproduce

```python
import anywidget
import traitlets

class BytesWidget(anywidget.AnyWidget):
    _esm = """
    function render({ model, el }) {
      let value = model.get("value");
      el.innerText = value instanceof DataView;
    }
    export default { render };
    """
    value = traitlets.Bytes().tag(sync=True)

# displays false, I expected true
# binary data is a png image of a small purple square
BytesWidget(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x14\x00\x00\x00\x14\x08\x02\x00\x00\x00\x02\xeb\x8aZ\x00\x00\x00\tpHYs\x00\x00.#\x00\x00.#\x01x\xa5?v\x00\x00\x00\x1dIDAT8\xcbc\xac\x11\xa9g \x1701P\x00F5\x8fj\x1e\xd5<\xaa\x99r\xcd\x00m\xba\x017\xd3\x00\xdf\xcb\x00\x00\x00\x00IEND\xaeB`\x82')
```

**Comment by mscolnick** [comment]
Thanks for the repro, I'm guessing a bug in marimo. I'll take a look today.

**Comment by gereleth** [comment]
Thanks for the quick reaction! With `marimo 0.9.3` the image shows up successfully :tada:

But I'm still having problems as soon as I try to change any other widget traits:

```python
import anywidget
import traitlets

purple_square = b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x14\x00\x00\x00\x14\x08\x02\x00\x00\x00\x02\xeb\x8aZ\x00\x00\x00\tpHYs\x00\x00.#\x00\x00.#\x01x\xa5?v\x00\x00\x00\x1dIDAT8\xcbc\xac\x11\xa9g \x1701P\x00F5\x8fj\x1e\xd5<\xaa\x99r\xcd\x00m\xba\x017\xd3\x00\xdf\xcb\x00\x00\x00\x00IEND\xaeB`\x82'

class BytesWidget(anywidget.AnyWidget):
    _esm = """
    function render({ model, el }) {
      model.set("other_value", 42)
      model.save_changes()
    }
    export default { render };
    """
    value = traitlets.Bytes().tag(sync=True)
    other_value = traitlets.Integer(0).tag(sync=True)

# raises a TraitError
BytesWidget(value=purple_square)
```

I immediately see this error: `traitlets.traitlets.TraitError: The 'value' trait of a BytesWidget instance expected a bytes object, not the dict {}.`. Full stack trace below.

```
An exception was raised by a UIElement's on_change handler:
Traceback (most recent call last):
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/marimo/_runtime/runtime.py", line 1465, in set_ui_element_value
    component._update(value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/marimo/_plugins/ui/_core/ui_element.py", line 454, in _update
    self._on_change(self._value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/marimo/_plugins/ui/_impl/from_anywidget.py", line 127, in on_change
    widget.set_trait(key, value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/traitlets/traitlets.py", line 1764, in set_trait
    getattr(cls, name).set(self, value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/traitlets/traitlets.py", line 690, in set
    new_value = self._validate(obj, value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/traitlets/traitlets.py", line 722, in _validate
    value = self.validate(obj, value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/traitlets/traitlets.py", line 2859, in validate
    self.error(obj, value)
  File "/home/daria/marimo/venv/lib64/python3.10/site-packages/traitlets/traitlets.py", line 831, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'value' trait of a BytesWidget instance expected a bytes object, not the dict {}.
```
