### ISSUE TITLE
Cell undo does not preserve cell language 

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#2509]
### Describe the bug

We have a bug in which the undo delete cell operation brings doesn't preserve the cell language.

1. Create a "markdown" cell
2. Delete the markdown cell
3. Undo the deletion

Today, after 3., the cell is incorrectly brought back as a Python cell, but it should be a markdown cell. Here is an example of an incorrect cell being brought back after undo:

<img width="873" alt="image" src="https://github.com/user-attachments/assets/509748a6-1274-4268-9032-854d604fdc52">

SQL cells have the same problem.

Possible fixes:

1. Preserve the cell language in the undo/redo stack.
2. Only keep track of the underlying Python code in the undo/redo stack (in which case it would be okay to bring any cell back as a Python cell).

### Environment

HEAD

**Comment by mscolnick** [comment]
We should do number #2. It should be a one line change, with probably a 20 line unit test.

**Comment by wasimsandhu** [comment]
Sorry @mscolnick I missed your comment before I started on #1. Wasn't a big change so I don't mind if we do #2 instead.

**Comment by mscolnick** [comment]
Let's go with 2 - since with 1, we don't actually preserve all the state (like dataframe name or quote type) which exist in the language adapters. So by converting to Python, we actually can encode this

**Comment by wasimsandhu** [comment]
Ah okay! I didn't think about that
