### ISSUE TITLE
Blinking of `altair` plots when value changes

### ISSUE THREAD

**Issue by proItheus** [marimo-team/marimo#251]
### Describe the bug

[plot.webm](https://github.com/marimo-team/marimo/assets/50539150/c14148fe-feac-4b89-965a-fce7354aa710)

There is unpleasant visual blinking for the `altair` plot, but not for `matplotlib` and `seaborn` plot.

Confirmed blinking using either plain `altair` chart and `marimo.ui.altair_chart`.

### Version

0.1.36

**Comment by akshayka** [comment]
Thanks for reporting, we can repro, looking into it.

**Comment by mscolnick** [comment]
@proItheus we have a fix for this in https://github.com/marimo-team/marimo/pull/254

this will fix `marimo.ui.altair_chart`. 

it won't fix vanilla altair at the moment since we embed that in an iframe and the iframe must reload. there is a solution though that we can followup with
