### ISSUE TITLE
`mo.mpl.interactive` doesn't work

### ISSUE THREAD

**Issue by proItheus** [marimo-team/marimo#252]
### Describe the bug

It's just blank.
![Screenshot_20231026_000211](https://github.com/marimo-team/marimo/assets/50539150/6a6a9bd1-53d8-4e4c-ba3e-941817c889a6)

### Version

0.1.36

### Code to reproduce

```python
import marimo

__generated_with = "0.1.36"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    import numpy as np
    from matplotlib import pyplot as plt
    return mo, np, plt


@app.cell
def __(np):
    x=np.linspace(0,1,20)
    return x,


@app.cell
def __(plt, x):
    plt.plot(x,x)
    return


@app.cell
def __(mo, plt):
    mo.mpl.interactive(plt.gcf())
    return


if __name__ == "__main__":
    app.run()


```

**Comment by proItheus** [comment]
Well, not exactly. It is no longer blank, but still have some weird behavior.
[plot.webm](https://github.com/marimo-team/marimo/assets/50539150/f1d726e6-131e-4b3e-a452-5953ff7a0e5d)

**Comment by akshayka** [comment]
Oh weird. @mscolnick could this have to do with iframe resizing?

**Comment by mscolnick** [comment]
@proItheus, i am unable to reproduce it. on my computer the interactive plot takes up the full size it is given.

couple questions that could help us:
* what browser are you using
* what version of matplotlib

thanks

**Comment by proItheus** [comment]
Well, I realized I have enabled `privacy.resistFingerprinting` in firefox. When this switch is  turned off, it works fine.
