### ISSUE TITLE
GitHub Copilot fails to connect in Marimo (v0.9.3) using asdf with missing _lsp directory

### ISSUE THREAD

**Issue by vangberg** [marimo-team/marimo#2536]
### Describe the bug

GitHub Copilot fails to connect when running Marimo (v0.9.3) with Python 3.12.6 managed by `asdf`. The issue seems related to the Language Server Protocol (LSP) setup, as Marimo expects an `_lsp` directory, which does not exist. The console logs show failed attempts to connect to the websocket for Copilot (`ws://localhost:27180/copilot`). 

Here is the key error in the browser console:  
```
Uncaught (in promise) Error: Failed to connect to ws://localhost:27180/copilot
    connect http://localhost:2718/assets/tree-CSVguZWm.js:13
```

The Marimo logs also show an `_lsp` folder:
```
% marimo -l debug edit eulers-method.py
[D 241008 12:35:47 file_router:43] Routing to file eulers-method.py
[D 241008 12:35:47 utils:133] Using config at /Users/harryvangberg/.marimo.toml
[D 241008 12:35:47 lifespans:56] Setup: lsp
[D 241008 12:35:47 lifespans:73] GitHub Copilot is enabled
[D 241008 12:35:47 sessions:938] Starting LSP server at port 27180...
[D 241008 12:35:47 sessions:944] ... running command: node /Users/harryvangberg/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/marimo/_lsp/index.js --port 27180
[D 241008 12:35:47 sessions:951] ... node process return code (`None` means success): None
[D 241008 12:35:47 sessions:955] Started LSP server at port 27180
[D 241008 12:35:47 lifespans:56] Setup: watcher
[D 241008 12:35:47 lifespans:56] Setup: etc
[D 241008 12:35:47 lifespans:56] Setup: signal_handler
[D 241008 12:35:47 lifespans:56] Setup: logging

        Edit eulers-method.py in your browser 📝

        URL: http://localhost:2718?access_token=7UqbLHu5950abNIvm6nF9g

[D 241008 12:35:47 lifespans:56] Setup: open_browser
```

However, the `_lsp` folder is missing from the installation directory:
```
% ls /Users/harryvangberg/.asdf/installs/python/3.12.6/lib/python3.12/site-packages/marimo/
__init__.py	_ast		_convert	_islands	_output		_runtime	_snippets	_tracer.py	py.typed
__main__.py	_cli		_data		_loggers.py	_plugins	_save		_sql		_tutorials
__pycache__	_config		_dependencies	_messaging	_pyodide	_server		_static		_utils
```

### Environment

{
  "marimo": "0.9.3",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.6",
  "Binaries": {
    "Browser": "129.0.6668.90",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.10.1",
    "ruff": "0.6.7",
    "starlette": "0.39.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}

**Comment by mscolnick** [comment]
Thanks for bringing this up - it looks like I dropped the `_lsp` directory when moving to `hatch`, we will fix this today and cut a release
