### ISSUE TITLE
Error when performing table search on polars dataframe

### ISSUE THREAD

**Issue by andrewhill157** [marimo-team/marimo#2550]
### Describe the bug

The search in bottom left of `mo.ui.table` seems to not like polars dataframes with mixed datatypes.
![image](https://github.com/user-attachments/assets/592eae4b-d7d1-4036-b5dc-673a66a0d10a)

### Environment

```
{
  "marimo": "0.9.4",
  "OS": "Darwin",
  "OS Version": "23.5.0",
  "Processor": "arm",
  "Python Version": "3.10.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v21.7.1"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.5.2",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7",
    "ruff": "0.6.7",
    "starlette": "0.37.2",
    "tomlkit": "0.12.3",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "pandas": "2.2.2",
    "polars": "1.7.1",
    "pyarrow": "17.0.0"
  }
}
```

### Code to reproduce

```
import marimo

__generated_with = "0.8.19"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    import polars as pl
    import pandas
    return mo, pandas, pl


@app.cell
def __(mo, pl):
    mo.ui.table(pl.DataFrame({"A": ["A", "B", "C"], "B": [1, 2, 3]}).to_pandas())
    return


@app.cell
def __(mo, pl):
    mo.ui.table(pl.DataFrame({"A": ["A", "B", "C"], "B": [1, 2, 3]}))
    return


if __name__ == "__main__":
    app.run()

```

**Comment by mscolnick** [comment]
I cannot reproduce with `polars==1.5.0`, but I can with `1.7.0` and `1.9.0`. 

Looking into this now.

**Comment by andrewhill157** [comment]
@mscolnick I no longer see the error above but searches like "A" that should pull up a row don't seem to at least with polars `1.17.1` btw (with `0.9.34` and various other  versions of polars including the ones you referenced above). Not sure if is related but the same example should reproduce this. I can open a different issue if you'd prefer though.

**Comment by mscolnick** [comment]
@andrewhill157, that might be moving our search to narwhals. which had a bit different semantics (i think just for searching nested arrays). a new issue would be great, thanks
