### ISSUE TITLE
Cell with hide enabled is hidden when returning to tab, although cell is still focused

### ISSUE THREAD

**Issue by vangberg** [marimo-team/marimo#2572]
### Describe the bug

When I am editing a Markdown cell, I often change to another browser tab, using keyboard shortcuts, to look up some information. When I tab back to Marimo, the cell has been hidden, but it is still focused, i.e. I can still write in the cell.

As it is now, the behavior is inconsistent: either the cell should be hidden and focus removed, or the cell should not be hidden, and focus kept. I would prefer the second option, which seems least disruptive to my flow.

https://github.com/user-attachments/assets/3d86143c-1d80-4090-8f5c-293123ec7751

### Environment

{
  "marimo": "0.9.4",
  "OS": "Darwin",
  "OS Version": "22.3.0",
  "Processor": "arm",
  "Python Version": "3.12.6",
  "Binaries": {
    "Browser": "129.0.6668.91",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.10.1",
    "ruff": "0.6.7",
    "starlette": "0.39.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.30.6",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}

**Comment by mscolnick** [comment]
I was fixing another bug introduced by https://github.com/marimo-team/marimo/pull/2523, it is possible this PR (https://github.com/marimo-team/marimo/pull/2575) fixes your bug as well.

**Comment by akshayka** [comment]
@vangberg this should be fixed on 0.9.6 (just released). I can no longer repro on that version. Please reopen if you're still experiencing this issue.

**Comment by vangberg** [comment]
It works as expected now. Thank you!
