### ISSUE TITLE
Convenient way to locate one cell's dependency

### ISSUE THREAD

**Issue by switchball** [marimo-team/marimo#2576]
### Description

Sometimes I need to modify a cell code that has dependency (also with some large computation) , the best way for me is to open the dependency tab and find it. (and its predecessor)

But if there are many cell in the notebook, finding that cell in the messy dependency graph is not an easy job.

I hope there is a way to locate cell in the dependency. 

### Suggested solution

The first idea is to add in right-click menu, such as "View in Dependency". but this may not be used very often.

Since double-click one cell in the dependency graph, will highlight related cell in the main notebook.  From this we can think of a reverse approach, i.e. 
![20241010_221549](https://github.com/user-attachments/assets/0bbca363-89ff-4b8e-9e8e-65fb1f2e26b4)

double-click the cell in the main notebook, the related cell will be selected (with the dependency tab already open).

I personally prefer the second idea, and welcome others.

**Comment by mscolnick** [comment]
@switchball - would this work? https://github.com/marimo-team/marimo/pull/2578
