### ISSUE TITLE
The user denied permission to access the database.

### ISSUE THREAD

**Issue by vitorhirota** [marimo-team/marimo#2596]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

It seems every example in the docs are throwing this error.

Main culprit seems to be a CORS issue from docs.marimo.io to marimo.app

> Access to internal resource at 'https://marimo.io/site.webmanifest' from origin 'https://marimo.app' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

### Your Suggestion for Changes

Enable CORS

**Comment by akshayka** [comment]
Thanks for reporting. Can I ask which browser you are using? I don't currently see this on my end

**Comment by vitorhirota** [comment]
I'm on brave

**Comment by mscolnick** [comment]
This seems like a quirk with brave and we target the 4 main browsers for our web assembly. 

I'm going to close this as an issue upstream with brave. Please reopen if there is something we can do.
