### ISSUE TITLE
"marimo config show" wording

### ISSUE THREAD

**Issue by koaning** [marimo-team/marimo#2600]
### Describe the bug

I ran into these steps: 

1. I ran `marimo config show`
2. I copied the filepath that I saw which in my case was `/Users/vincentwarmerdam/.config/marimo/marimo.toml` and figured I might explore it.
3. This filepath was empty. 

This was confusing because `marimo config show` did show me some config. So it might be a nice QOL to add the default config in that file instead. 

There is a relevant thread [on Discord](https://discord.com/channels/1059888774789730424/1294384650134753400).

### Environment

```
{
  "marimo": "0.9.7",
  "OS": "Darwin",
  "OS Version": "23.4.0",
  "Processor": "arm",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "129.0.6668.100",
    "Node": "v11.0.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "ruff": "0.6.9",
    "starlette": "0.39.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.9.0",
    "uvicorn": "0.31.1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

**Comment by mscolnick** [comment]
it would be nice to not add the default config as is - but rather just the changes. It would be nice to be able to update the default config (for best practices) and let users get those for free.

**Comment by koaning** [comment]
I guess that could work as well, but then the message should differ. 

```
> marimo config show
User config from /Users/vincentwarmerdam/.config/marimo/marimo.toml

[formatting]
line_length = 79

[keymap]
preset = "default"

[keymap.overrides]

[server]
browser = "default"
follow_symlink = false

[experimental]
multi_column = true

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[package_management]
manager = "pip"

[completion]
activate_on_typing = true
copilot = false

[runtime]
auto_instantiate = true
auto_reload = "off"
on_cell_change = "autorun"

[display]
theme = "light"
code_editor_font_size = 14
cell_output = "above"
default_width = "medium"
dataframes = "rich"
```

Reading this, it does seem suggested like there is a config being loaded from that file.

**Comment by mscolnick** [comment]
Possibly that wording can be changed to be less confusing
