### ISSUE TITLE
Escape characters in strings

### ISSUE THREAD

**Issue by liquidcarbon** [marimo-team/marimo#2601]
### Describe the bug

![image](https://github.com/user-attachments/assets/092c8d2f-2066-4a58-99df-a980155dd8de)

in terminal: `<unknown>:2: SyntaxWarning: invalid escape sequence '\L'`

### Environment

```
{
  "marimo": "0.9.1",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel",
  "Python Version": "3.12.7",
  "Binaries": {
    "Browser": "129.0.6668.59",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "ruff": "0.6.9",
    "starlette": "0.39.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.31.1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

**Comment by akshayka** [comment]
I think this is just Python, not marimo. You can replace double quotes with single quotes, or escape your backslash

![image](https://github.com/user-attachments/assets/ce4127ca-d780-46e4-8b9d-d91344578eda)

Feel free to reopen if I misunderstood.

**Comment by liquidcarbon** [comment]
I could've sworn python is not tripped up by this, but you are right.  My bad.
