### ISSUE TITLE
command palette action and keyboard shortcut for terminal

### ISSUE THREAD

**Issue by aidanmontare-fed** [marimo-team/marimo#2608]
### Description

I'd like to be able to open and close the integrated terminal with the keyboard. Also, I noticed this doesn't have a command palette action, which would help if I forget the shortcut key.

### Suggested solution

Maybe something like CTRL-`, the default in vscode?

**Comment by mscolnick** [comment]
Great suggestion, we can add this!

**Comment by wasimsandhu** [comment]
I was just about to request this, great timing
