### ISSUE TITLE
FastAPI example in documentation does not run

### ISSUE THREAD

**Issue by aidanmontare-fed** [marimo-team/marimo#2638]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [x] Confusing
- [x] Not sure?

### Explain in Detail

The example code provided on https://docs.marimo.io/guides/deploying/programmatically.html won't run, and seems to be missing some bits? I.e. there is the line `app.add_middleware(auth_middleware)`, but the variable `auth_middleware` isn't defined.

### Your Suggestion for Changes

A working example would be lovely, I'd like to try this!

**Comment by mscolnick** [comment]
Hi @aidanmontare-fed - you should be able to find a (hopefully) running example here: https://github.com/marimo-team/marimo/blob/b0cd2d03c2b83ee86e14a8c076f9f25f47796382/marimo/_smoke_tests/custom_server/my_server.py
