### ISSUE TITLE
ui.dataframe for Ibis fails if backend does not support SQL

### ISSUE THREAD

**Issue by szst11** [marimo-team/marimo#2646]
### Describe the bug

If I use the Polars Backend with Ibis, the ui.dataframe fails with an exception, as Polars does not support SQL.
A solution could be an exception handling when invoking ibis.to_sql().

### Environment

marimo 0.9.10

### Code to reproduce

```
import marimo as mo
import ibis
ibis.set_backend('polars')

data = {
    'a': [1, 2, 3],
    'b': [22.5, 23.0, 21.5],
}
memtable = ibis.memtable(data)
mo.ui.dataframe(memtable)
```

**Comment by mscolnick** [comment]
Thanks for reporting, fix incoming
