### ISSUE TITLE
ui.file_browser is not responsive on initial_path from ui.text

### ISSUE THREAD

**Issue by szst11** [marimo-team/marimo#2648]
### Describe the bug

If I take the inital_path from ui.text() response, the file_browser is not reset to that new location. E.g. if I put another Drive letter to the text-input.

### Environment

marimo 0.9.9

### Code to reproduce

```
import marimo as mo
```

```
source = mo.ui.text()
source
```

```
mo.ui.file_browser(initial_path=source.value)
```

**Comment by mscolnick** [comment]
Thanks for reporting. we already have a fix out for this (https://github.com/marimo-team/marimo/pull/2623) thanks to @wasimsandhu
