### ISSUE TITLE
Click to edit markdown cell

### ISSUE THREAD

**Issue by odanoburu** [marimo-team/marimo#2678]
### Description

I [previously requested](https://github.com/marimo-team/marimo/issues/1975) that the markdown rendering be more similar to the jupyter one, with the user having to click twice to edit it. I'm creating this issue to track this proposal separately.

The motivation is to not have the distracting markdown source appear. Even if the cell is hidden, it still shows the first line of the markdown:

![Image](https://github.com/user-attachments/assets/4778bfa4-610e-4c2a-8834-d1b609e6bdaa)

I tried leaving a blank line as the first line, which makes it less distracting, but marimo seems to normalize the notebook contents (removing the blank line) so this is not a viable workaround.

### Suggested solution

Show only the rendered markdown, with a double-click (or a button) showing the markdown source. I would settle for a hidden cell that shows no preview too, although I would still prefer the jupyter behaviour.

**Comment by Light2Dark** [comment]
/assign-me, haha. Anyways, have an idea of how to make this work. One design consideration is how to make it clear that the markdown is editable when the code is hidden.

Thinking of bringing up the show code icon (eyeball) with a tooltip to show the shortcuts. Will work on it!

**Comment by Light2Dark** [comment]
hi @odanoburu, I've attached a video in the PR, let me know if you have any feedback :)

(I did not add the tooltip to maintain consistency, but the shortcuts work)

**Comment by odanoburu** [comment]
Looks great, I'm excited for this!!
