### ISSUE TITLE
Issue plotting with 'marimo_csv'

### ISSUE THREAD

**Issue by AdrienDart** [marimo-team/marimo#2702]
### Describe the bug

Hi team,

I'm trying to plot a line with polars but the plot is empty when using alt.data_transformers.enable('marimo_csv')

### Environment

0.9.11

### Code to reproduce

```python
from datetime import date
import polars as pl 
import altair as alt
alt.data_transformers.enable('marimo_csv') 
df = pl.DataFrame(
    {
        "date": [date(2020, 1, 2), date(2020, 1, 3), date(2020, 1, 4)] * 2,
        "price": [1, 4, 6, 1, 5, 2],
        "stock": ["a", "a", "a", "b", "b", "b"],
    }
)
df.plot.line(x="date", y="price", color="stock")  
```

**Comment by mscolnick** [comment]
Thanks for filing this issue. There is indeed a subtle bug. In the meantime, it should work if you add `mo.ui.altair_chart(df.plot.line(x="date", y="price", color="stock"))` which does correctly handle some parsing
