### ISSUE TITLE
Add time range to datetime filter on Dataframe Transformer

### ISSUE THREAD

**Issue by lovuikeng** [marimo-team/marimo#2709]
### Description

Currently there's only date range of datetime filter on Transformer table, would be helpful if time range also be available as part of the datetime filter 

![Image](https://github.com/user-attachments/assets/a61e911c-5fd8-4bcf-a069-a8a1d96f762b)

### Suggested solution

Sample datetime select widget as on Kibana
![Image](https://github.com/user-attachments/assets/f936daaf-d82f-44ae-aeb5-e865054bb9c0)

**Comment by mscolnick** [comment]
I am working on this
