### ISSUE TITLE
Create WebAssembly link does not work in Safari

### ISSUE THREAD

**Issue by ndrezn** [marimo-team/marimo#2729]
### Describe the bug

Clicking "Create WebAssembly Link" does not work in Safari: ![Image](https://github.com/user-attachments/assets/a375b32e-d5d0-427e-bbda-012e5b0c764c)

Seems like nothing is copied.

### Environment

{
  "marimo": "0.9.14",
  "OS": "Darwin",
  "OS Version": "24.0.0",
  "Processor": "arm",
  "Python Version": "3.12.5",
  "Binaries": {
    "Browser": "130.0.6723.70",
    "Node": "v22.7.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "narwhals": "1.10.0",
    "packaging": "24.1",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "pyyaml": "6.0.2",
    "ruff": "0.7.0",
    "starlette": "0.41.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "anywidget": "0.9.13",
    "pandas": "2.2.3"
  }
}

### Code to reproduce

N/A

**Comment by mscolnick** [comment]
Looks like safari does not support the clipboard API on localhost (as a security gate). I am providing a fallback to show a prompt so you can copy it yourself.
