### ISSUE TITLE
Plotly figures with `fig.show()` do not appear in app editor

### ISSUE THREAD

**Issue by ndrezn** [marimo-team/marimo#2734]
### Describe the bug

When adding a Plotly figure to Marimo, it's possible to preview with e.g.:
```python
import plotly.express
fig = px.line(x=[1,2,3], y=[5,3,2])
fig.show()
```

This will preview the figure _under_ the cell and the resulting figure will not appear in the app editor.

### Environment
```
"marimo",
"plotly>=5.24.1",
"pandas>=2.2.3",
```

**Comment by VivaldoMendes** [comment]
I can not replicate your problem. Notice that you have to call the plot without `show()`:

![Image](https://github.com/user-attachments/assets/383067b8-d098-4062-b747-2288db395f6e)

**Comment by mscolnick** [comment]
`fig.show()` puts this in the console. this is so you can imperatively print to the console, e.g. if you are in a for-loop and want to print many different plots. 

Returning `fig` as the last line will make it appear in the regular outputs. This is currently how we also handle `matplotib` plots. 

I am going to close this as expected. This is [in the docs](https://docs.marimo.io/guides/working_with_data/plotting.html#matplotlib), albeit for a very small part.
