### ISSUE TITLE
Mermaid diagrams color change in light and dark mode

### ISSUE THREAD

**Issue by robmck1995** [marimo-team/marimo#2746]
### Describe the bug

Mermaid diagrams don't seem to adjust for dark mode correctly. I created a diagram with some custom styling (thanks claude) and it has some odd behavior. Here's what happens:

Run the script in light mode, looks great
![Image](https://github.com/user-attachments/assets/3cb7cce2-9e7b-4a82-9503-096be38bee5b)

Change to dark mode, still looks great
![Image](https://github.com/user-attachments/assets/a9655eaf-48b2-433d-b2af-ecd84de46fe5)

Restart the kernel, colors are off
![Image](https://github.com/user-attachments/assets/0432572d-3795-43cd-9506-a0b8991f7f8b)

I'm sure this has something to do with the custom styling, I'm admittedly a mermaid novice so not sure what the expected behavior should be here.

### Environment

```
{
  "marimo": "0.9.13",
  "OS": "Darwin",
  "OS Version": "23.3.0",
  "Processor": "arm",
  "Python Version": "3.10.11",
  "Binaries": {
    "Browser": "130.0.6723.91",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "narwhals": "1.12.1",
    "packaging": "24.1",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.7.1",
    "starlette": "0.41.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

### Code to reproduce

```
import marimo as mo

node_names = {'main_node': 'A', 'ref_node': 'B', 'end_node': 'C'}  # example node names

mermaid_diagram = '''graph TD
    A[Start] --> B[Process]
    B --> C[End]

    %% Styling
    classDef default fill:#f9f9f9,stroke:#333,stroke-width:2px
    classDef source fill:#e1f5fe,stroke:#0277bd,stroke-width:2px
    classDef reference fill:#e8e7ff,stroke:#6b69d6,stroke-width:2px
    class A source'''

mo.mermaid(mermaid_diagram)
```

**Comment by mscolnick** [comment]
It looks like marimo/mermaid is already handling the styling for you (setting the default theme for dark mode). If you want to override the colors, you will need to override ALL of it (including the text color), otherwise the text color will default to the dark text color in dark mode.

If you do need access to the theme, you can use this snippet:
```
import marimo as mo
mo.app_meta().theme
```
