### ISSUE TITLE
Tutorial on UI elements contains error

### ISSUE THREAD

**Issue by chopin57otu** [marimo-team/marimo#2750]
### Describe the bug

[**https://marimo.app/?slug=0ue871#code/**](https://marimo.app/?slug=0ue871#code/)

![Image](https://github.com/user-attachments/assets/67d0478c-60bd-43b6-a49b-9cf838ad241f)

### Environment

On Win 10 Chrome Version 130.0.6723.92 (Official Build) (64-bit)

### Code to reproduce

N/A

**Comment by akshayka** [comment]
Thanks for reporting! I have updated the link to the UI tutorial to point to an updated version without the error, and that should be reflected online soon. In the meantime, after installing marimo locally, use can run `marimo tutorial ui` to use a version without this error
