### ISSUE TITLE
Marimo sporadically asking me to login

### ISSUE THREAD

**Issue by MarcoGorelli** [marimo-team/marimo#2771]
### Describe the bug

I ran
```
marimo edit untitled.py
```
and then opened
```
 http://localhost:2718?access_token=OgDWC8JChJVQKNxF3JC2cQ
```
in the browser

I write a bit of code, and then

![Image](https://github.com/user-attachments/assets/d86efa5f-ca53-4e5e-a8a4-82adc58d8be3)

appears

this seems to be quite sporadic and happen randomly

If I opened the link which includes the access token, then why am I being asked to log in?

### Environment

{
  "marimo": "0.9.14",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.11.10",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.16.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "narwhals": "1.12.1",
    "packaging": "24.1",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.7.2",
    "starlette": "0.41.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "duckdb": "1.1.2",
    "pandas": "1.5.3",
    "polars": "1.11.0",
    "pyarrow": "17.0.0"
  }
}

**Comment by Abhijeet213** [comment]
This Issue Is On Your Machine Because This Is Working Fine On My Side

And If Issue Persists 

- This Issue Is Mainly Caused by Entering Wrong Access Token Or Sudden Restart Of Your Marimo

- Try Changing Browser To Chrome 

And Comment Again If Issue Is Still on Your Machine

**Comment by mscolnick** [comment]
@MarcoGorelli which browser are you using? Do you have an extension that will remove cookies? Anything else that could be different about your setup?

If you want in the meantime, you can do `--no-token` to remove this.

**Comment by MarcoGorelli** [comment]
i'm using firefox, and do have an adblock - perhaps it's that?

i'll use --no-token or chrome then, thanks! 🙏

**Comment by OrionYeung** [comment]
I am also on Firefox and this issue didn't appear for me until I started using Ubuntu 24.04 for my WSL distro - I did this specifically to upgrade glibc. I don't know if it's relevant, but figured I could share.

**Comment by safesintesi** [comment]
Same issue with Edge, no ad-block. If it's worth something, I use it with WSL Ubuntu 22.04.

To be clear, this also happens when starting from fresh and often. It's kinda disturbing the workflow.

**Comment by mscolnick** [comment]
@safesintesi what version of Edge? Works ok in Chrome as well?

**Comment by safesintesi** [comment]
Version 138.0.3351.109 (64 bit).
Updated to Version 139.0.3405.102 (64 bit) and is no longer a problem.
