### ISSUE TITLE
marimo-user-config tag not found

### ISSUE THREAD

**Issue by Light2Dark** [marimo-team/marimo#2775]
### Describe the bug

I was setting up the local environment and ran the following commands:
```
make fe
hatch shell

cd frontend
pnpm dev
```

After running pnpm dev, the console displays the following:
```
Element base not found.
Element title not found.
Element marimo-filename not found.
```
And localhost:3000 shows a blank page with some errors like 
`Logger.ts:34 Marimo got an unexpected value in the configuration file: Error: internal-error: marimo-user-config tag not found`

![Image](https://github.com/user-attachments/assets/916d426b-88c5-4cda-8e80-4a34f2b7080c)

Am I missing a config somewhere?

### Environment

```
{
  "marimo": "0.9.14",
  "OS": "Darwin",
  "OS Version": "23.6.0",
  "Processor": "arm",
  "Python Version": "3.12.7",
  "Binaries": {
    "Browser": "130.0.6723.92",
    "Node": "v20.11.0"
  },
  "Dependencies": {
    "click": "8.1.3",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "narwhals": "1.12.1",
    "packaging": "24.1",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.6.9",
    "starlette": "0.41.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "duckdb": "1.1.2"
  }
}
```

**Comment by mscolnick** [comment]
@Light2Dark - you will need to run an app in headless mode alongside running "pnpm dev"

```
marimo edit nb.py --headless --no-token
```

**Comment by Light2Dark** [comment]
hmm, I get the same errors unfortunately 🤔.

The backend works fine. Ran `marimo edit nb.py --headless --no-token` and localhost:2723 will display the notebook.

As an alternative, if I run `pnpm build:watch` as per CONTRIBUTING.md, do I serve the build using vite preview? It's not clear in the docs.

**Comment by mscolnick** [comment]
Can you get the notebook to run on localhost:2718?

**Comment by Light2Dark** [comment]
ohh, yes it works now. There were some processes running on localhost:2718 that I killed then ran marimo again.
Tqsm!

**Comment by mscolnick** [comment]
No problem - I leave this ticket open, I can add a small improvement to the dev server to warn/help you.
