### ISSUE TITLE
`marimo.app_meta().mode` Detection for Notebook Modes

### ISSUE THREAD

**Issue by metaboulie** [marimo-team/marimo#2776]
### Description

Add a `marimo.app_meta().mode` attribute to detect the notebook mode, providing values like `Literal["edit", "app"]`.

This feature would allow notebooks to dynamically detect their operating mode—`edit`, `app`, etc—enabling more adaptable behavior and tailored displays based on the context. 

For example, users may want some contents to be displayed only in `edit` mode or `app` mode.

### Suggested solution

Add the `marimo.app_meta().mode` attribute.

**Comment by mscolnick** [comment]
This makes sense to me. We also have "script" as a mode. I think we can infer this from the response of `get_context_manager`

**Comment by metaboulie** [comment]
I just found these modes, 
https://github.com/marimo-team/marimo/blob/71475b4a818697f95e49d7832f28a4f0f990cbe5/frontend/src/core/mode.ts#L16
and I can't infer the modes from `RuntimeContext`, which is the response of `get_context()` 
https://github.com/marimo-team/marimo/blob/ddd11e2203bef2c700d7dda42f79c981b74a8a68/marimo/_runtime/context/types.py#L65
should we infer the mode from `AppMode` or from `RuntimeContext` somehow?

**Comment by mscolnick** [comment]
@metaboulie - for the backend, you'll want to use `SessionMode`. I think for runtime context, you could do something like this (untested, unfinished)

```python
def get_mode():
    try:
        context = get_context()
        if isinstance(context, KernelRuntimeContext):
           return context.session_mode;
        if isinstance(context, ScriptRuntimeContext):
           return "script"
    except:
        return "unknown"
```

We will need to add `session_mode` to `KernelRuntimeContext`
