### ISSUE TITLE
mo.ui.table: flip between pages does not work with pyarrow table

### ISSUE THREAD

**Issue by szst11** [marimo-team/marimo#2786]
### Describe the bug

if I show a pandas dataframe as a mo.ui.table I can swicht between the pages and see the new data. That does actually not work with pyarrow tables. see the example code.

### Environment

marimo 0.9.14 on Python 3.11

### Code to reproduce

```Python
import marimo as mo
```

this works:
```Python
import pandas as pd
import numpy as np

df = pd.DataFrame((np.linspace(0, 2 * np.pi, 256)), columns=['sine'])
mo.ui.table(df)
```

this not:
```Python
import pyarrow as pa

mo.ui.table(pa.Table.from_pandas(df))
```

**Comment by mscolnick** [comment]
This might be fixed on main now, since moving to narwhals - as it does seem to work for me on main. I'll let you know when we release (hopefully today) and let you know.

**Comment by szst11** [comment]
runs again with 0.9.15
