### ISSUE TITLE
Make the output of markdown cells expanded by default

### ISSUE THREAD

**Issue by odanoburu** [marimo-team/marimo#2804]
### Description

Specially for markdown cells, it is undesirable to have the output be collapsed by default, it should be expanded by default. When I write something, I don't want the reader to have to scroll the cell to read it.

![](https://private-user-images.githubusercontent.com/19347395/382295069-8f0a70f9-4307-4f3a-b22f-13d2812f3c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDc4NzEsIm5iZiI6MTczMDg0NzU3MSwicGF0aCI6Ii8xOTM0NzM5NS8zODIyOTUwNjktOGYwYTcwZjktNDMwNy00ZjNhLWIyMmYtMTNkMjgxMmYzYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDIyNTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZjRkMjc3NTQzYzI2MzFmYjNkOGI5YzgzNzczOTMwM2ZiZDVlNTYwOGQzMDRiYjA5YzU1Njc3MzJkODczMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yXzYLfjojmSH0Kx9ci__uhGusublahvmg65Mec2rdT0)

### Suggested solution

Make the output of the markdown cells expanded by default. For other kinds of cells, it might be useful to have a way of specifying that we want the output of the cell to be expanded or collapsed by default.

### Additional context

Related discussion: https://github.com/marimo-team/marimo/discussions/2765.

**Comment by akshayka** [comment]
Expanding pure markdown makes sense to me, thanks for the suggestion!

I'm hesitant to add configuration for other kinds of cells; seems less helpful, and adds more configuration/UI complexity.

**Comment by odanoburu** [comment]
I'm more than happy with just that, thank you :)
