### ISSUE TITLE
app.embed is broken for some notebooks, unable to interact with embedded notebook

### ISSUE THREAD

**Issue by latifboubyan** [marimo-team/marimo#2833]
### Describe the bug

Hello, I'm trying to use the `app.embed()` feature but it is somewhat broken. I am using the fastapi integration to serve a notebook, which embeds other notebooks. I can see the embedded notebooks rendered, but it's not interactive. I'm using the latest Marimo version (0.9.17).

# Minimum Example 
Here is the minimum to recreate it. You need two notebooks. One is the example you guys provide `ui/task_list.py` and the other one will embed the previous one:

**task_list.py**
code from your examples folder: [task_list.py](https://github.com/marimo-team/marimo/blob/c9f6ab5b748b9a74e7d8cefdce3bd851499540f0/examples/ui/task_list.py)

**test.py** (in a notebook cell)
```python
from task_list import app 
result = await app.embed()
result.output
```

This renders the `task_list` notebook, but I can't interact with it. Clicking the add button, doesn't add the task. But as a standalone the `task_list.py` notebook works fine, so something in the embedding process breaks. 

 ## Conditions in which it works

Here's the strangest part. I found a way to make it work. You have add another cell:

```
result2 = await app.embed()
result2.output
```

And it'll kinda work. What will happen is that now you can add tasks. (Although adding a task to the first embedded notebook will actually reflect in the second embedded notebook, not the first one).

In the editor:

![Image](https://github.com/user-attachments/assets/aee402a8-df41-46cc-bbf1-7a9b1b72c11d)

Served by fastapi:

![Image](https://github.com/user-attachments/assets/c31b80ea-d47d-4088-9d2d-908ac22c19ed)

### Environment

{
  "marimo": "0.9.17",
  "OS": "Linux",
  "OS Version": "5.15.153.1-microsoft-standard-WSL2",
  "Processor": "",
  "Python Version": "3.11.9",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "narwhals": "1.13.2",
    "packaging": "24.1",
    "psutil": "6.0.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.11.2",
    "pyyaml": "6.0.2",
    "ruff": "0.6.9",
    "starlette": "0.40.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "duckdb": "1.1.2",
    "pandas": "2.2.3"
  }
}

### Code to reproduce

```python
from task_list import app 
result = await app.embed()
result.output
```

**Comment by akshayka** [comment]
Thanks for reporting. I can take a look into this, but likely not this week. Are you blocked on this, or can you work around it?

**Comment by latifboubyan** [comment]
To be frank, I'm pushing for Marimo adoption in my company. I'm not sure how much of a time window I have. 

I want to show that we can use Marimo as a comprehensive solution, the ability to embed notebooks means you don't have to write frontend code for these mini data applications. It worked perfectly except for this last crucial part, actual usable input. So I would say I am blocked on this for my main use case.

This is what I ended up with btw:
![Image](https://github.com/user-attachments/assets/697b124d-3e5e-42f2-8c34-777c48f28bc3)

**Comment by akshayka** [comment]
Thanks for the context. 

After the fold, I have an example of how to use `app.embed()`. But I do want to note that it's possible to use the FastAPI integration (`create_asgi_app()`) to serve multiple marimo apps, without using `app.embed()`. I don't know your exact use case, but if all you want to do deploy an app that in turn provides access to additional apps, I think this is the most straightforward solution.

Full example: https://github.com/marimo-team/marimo/tree/main/examples. If you run it, at the login page, the username is "admin" and the password is "password123":

![Image](https://github.com/user-attachments/assets/20a83c88-7f30-425e-993c-bd13bfb84585)

****

I believe `app.embed()` should work if you use the following pattern, :

1. Import the app object in one cell

```python
from task_list import app
```

2. In **another** cell, embed the app and visualize its output:

```python
result = await app.embed()
result.output
```

This is due to a limitation in the app reactivity — similar to how interacting with a UI element doesn't re-run the cell where the element is defined, interacting with an app output doesn't re-run the cell in which the `app` was imported. This evidently is not documented (sorry!), which I can fix.

Can you see if following this pattern solves the issue for you? Here is a video example

https://github.com/user-attachments/assets/c85ed61c-9a63-48f9-9269-897965fc51d4

Full source:

```python
import marimo

__generated_with = "0.9.17"
app = marimo.App()


@app.cell
def __():
    from task_list import app
    return (app,)


@app.cell
async def __(app):
    result = await app.embed()
    result.output
    return (result,)


if __name__ == "__main__":
    app.run()
```

P.S. Cool example using the sidebar!

**Comment by latifboubyan** [comment]
Ah that clears up the root of the issue, thanks so much for responding. I'm still having an issue, but maybe it's particular for my use case, I iterate over a directory of notebooks, import them one by one, and then set them up in the sidebar. Something like this:

Cell 1:
```python
def preimport(root_dir: Path):
    apps = {}
    for path in root_dir.rglob("*.py"):
        if path.stem == "__init__":
            continue
        path = path.relative_to(root_dir)
        if len(path.parts) == 1:
            app =__import__(path.stem).app
        elif len(path.parts) == 2:
            package = __import__(str(path).replace("/",".").removesuffix(".py"))
            app = getattr(package, path.stem).app
        else:
            print("Should not have files with more than one leve of nesting.")
            continue 
        apps[str(path)] = app
    return apps 

apps = preimport(current_dir)
```

Cell 2:
```python
async def render(path: Path, root_dir: Path):
    path = Path(path).relative_to(root_dir)
    result = await apps[str(path)].embed()
    return result.output

async def build_routes(paths, root_dir: Path):

    d = {}

    for path in paths:
        relative = path.relative_to(root_dir)
        #print(relative.parts)
        d[f"#{relative}"] = partial(render, path, root_dir)

    return mo.routes(d)

routes = await build_routes(python_files, current_file.parent)
```

And finally Cell 3
```
routes
```

There is more code for the sidebar itself, but I don't think it's part of the core issue. Now the part that I'm a bit confused about, is that I pre-import all the notebooks in the first cell. And when a route is entered, I render that notebook. But I still don't get reactive inputs even though they're in separate cells.

**Comment by lateef-k** [comment]
I'm gonna go ahead and close this issue, I've decided to use an html template that links to all of the notebooks available and embeds an iframe for notebooks served by the fastapi server.

**Comment by latifboubyan** [comment]
Okay that makes sense. I actually ended up creating something similar to your approach. A jinja template served by FastAPI that lists all the available notebooks. Works pretty well so far. 

Thanks a lot for your help, I'm going to go ahead and close this issue.
