### ISSUE TITLE
devtools dependency not added to embedded deps when running in sandbox

### ISSUE THREAD

**Issue by gabrielgrant** [marimo-team/marimo#2844]
### Describe the bug

I have a notebook that has embedded deps:

```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "anyio==4.6.2.post1",
#     "diskcache==5.6.3",
#     "google-api-python-client==2.151.0",
#     "google-cloud-storage==2.18.2",
#     "marimo",
#     "openai==1.52.2",
#     "pandas==2.2.3",
#     "pillow==11.0.0",
#     "psycopg2-binary==2.9.10",
#     "pydantic==2.9.2",
#     "record-type==2023.1.post1",
#     "requests==2.32.3",
# ]
# ///

import marimo

__generated_with = "0.9.17"
app = marimo.App(
    width="medium",
    app_title="...
)
```

Starts fine, and installs the deps listed.

```
 marimo edit --sandbox my_notebook.py
Running in a sandbox: uv run --isolated --no-project --with-requirements /tmp/tmpgna8fd1z.txt marimo edit my_notebook.py
Installed 64 packages in 60ms

        Edit my_notebook.py in your browser 📝

        URL: http://localhost:2718?access_token=XXXXX
```

 In the notebook, I'm using python-devtools (the `devtools` package) to pretty-print a Pydantic model, though, and this dep doesn't seem to be captured. marimo offers to install the wrong package (a turbogears devtools package):

![Image](https://github.com/user-attachments/assets/f775b30d-35b5-4223-9e38-ed0b01c9ea6c)

I cancel that and adding the proper `devtools` package manually through the marimo packages interface:

![Image](https://github.com/user-attachments/assets/6005e9ac-fb39-476a-9d60-bb72bf1dccfc)

this seems to work:

![Image](https://github.com/user-attachments/assets/b65fb026-0ce0-47cd-87c6-d4134cd9bfd5)

![Image](https://github.com/user-attachments/assets/eaba40cc-6e70-4650-b00d-154880887071)

but it still isn't added to the `dependencies` list in the file header, so have to go through the process again next time the notebook is opened.

1. Why is the `devtools` import matching to the wrong package?
2. Why does the manually-added package show up in the interface's package list but not get added to the file's dep list?

FWIW there seem to be a lot more deps in the marimo interface than in the file. Is that expected? Where does the list in the interface come from? It doesn't seem to match up with the list returned from `pip freeze` either (neither the list returned by my global python/pip, nor with that from the virtualenv in which i have marimo installed)

### Environment

```shell
$ marimo env
{
  "marimo": "0.9.17",
  "OS": "Linux",
  "OS Version": "5.10.102.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.11.5",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.18.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "narwhals": "1.13.3",
    "packaging": "24.0",
    "psutil": "5.9.8",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.8.1",
    "pyyaml": "6.0.1",
    "ruff": "0.7.1",
    "starlette": "0.37.2",
    "tomlkit": "0.12.5",
    "typing-extensions": "missing",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {}
}
```

### Code to reproduce

Start a fresh notebook:

`$ marimo edit --sandbox marimo-devtools-test.py`

Add a single cell:

`import devtools`

![Image](https://github.com/user-attachments/assets/923567f2-62d9-4200-87bf-9e16ff711a22)

**Comment by mscolnick** [comment]
The reason it resolves to `tg.devtools` is because we have some logic (i.e. hard-coded mappings) to get the correct packages for common imports. This list was bootstrapped from another registry. I've updated the package to point to this [devtools](https://github.com/samuelcolvin/python-devtools).

This mapping is also the reason that installing from the sidebar doesn't add it either, but that is a bug that I am looking into.

**Comment by gabrielgrant** [comment]
Gotcha. Thanks for looking in to this!
