### ISSUE TITLE
Inserting an SQL cell in the middle of a notebook

### ISSUE THREAD

**Issue by Light2Dark** [marimo-team/marimo#2876]
### Description

It's not possible to insert a SQL cell in the middle of a notebook. You would have to create one at the end and then drag it to wherever you want. It gets painful when notebooks are long.

### Suggested solution

1. Add a toggle to switch between markdown, python & sql.
![Image](https://github.com/user-attachments/assets/06332640-1b89-49a8-a7cb-1251c2e6a351)

- Currently this toggle changes between markdown view & python view / if an SQL cell, changes between sql & python. A proposal is to allow a cell to be changed between all 3 states. Even if there's an error in 1 state.

2. Add extra bubbles upon hovering the + bubble
![Image](https://github.com/user-attachments/assets/dfc7ac66-6d58-4b84-b907-0b85e415335b)

I'm sure there are more designs possible. Need some brainstorming 😶‍🌫️

**Comment by mscolnick** [comment]
@Light2Dark thanks for the suggestions

1) you can get a menu of cell types by right-clicking, but its not super discoverable. i would be open to always making it a menu like we have today
2) i will will explore adding another toggle to go to SQL from python

**Comment by Light2Dark** [comment]
Ahh, I see why I didn't discover num 1 earlier.

You can only **View as SQL** once you run an empty cell. If you don't run it, it will only show **View as Markdown**

**Comment by mscolnick** [comment]
@Light2Dark - i made some fixes on this PR https://github.com/marimo-team/marimo/pull/2878, if you'd like to try it out and let me know if you have any suggestions. Also open to more improvements if you have ideas.
