### ISSUE TITLE
Support for websockets > 13.0

### ISSUE THREAD

**Issue by johnhelt** [marimo-team/marimo#2890]
### Description

Marimo caps the requirement for websockets to < 13.0. A new API was introduced with version 11, and since version 14 it is now the default, and the old api is deprecated. It would be great if marimo doesn't limit which websockets to use.

### Suggested solution

Support versions > 13.0.

**Comment by mscolnick** [comment]
Thanks for flagging this. I'll see if i can remove the upperbound : https://github.com/marimo-team/marimo/pull/2892
