### ISSUE TITLE
Display cell run history

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#2898]
### Description

I'm working with a large dataset and occasionally running into OOM errors. When the process is killed, there no way on the frontend to determine the last run cell (or cell that was running before OOM)

### Suggested solution

![Image](https://github.com/user-attachments/assets/eae3dd34-e710-4101-bd06-16c8ebbe4a4e)

 - Clicking the broken link scrolls to the last cell
 - Some styling on the broken cell (just the red error might be fine)

### Additional context

Happy to put this in myself, just leaving a bookmark. Small QOL improvement

**Comment by mscolnick** [comment]
I've wanted to add another helper panel that just lists out a history of all the cell executions and their times and status (success/failure) in a list. That might help solve this as well?

**Comment by dmadisetti** [comment]
That absolutely works. LMK if there's an existing issue so I can merge it

**Comment by mscolnick** [comment]
I haven't seen one, but this relates: https://github.com/marimo-team/marimo/issues/974.

I am unsure if its a stack/history of runs or a flame graph (or both).

**Comment by mscolnick** [comment]
@Light2Dark i agree the top one is better. i could imagine each run being closed by default (except maybe the top one) and you can expand to see the cell that were run, times, and result (just like you have designed). 

for the chart, I am not sure what libraries out there exist/would be good for this, but we do already use vega-lite internally. you could maybe create a chart using the vega spec. here is a [sample chart](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QUOQFtMKEPMUBaAOwAOACxz9mY+YCsAIxvmWATivGwMGGxeGWYFlcdgxiAyIGpyAE4A1sqEAJ4ADprIIDYRwdyYUJB0JEioIAAeyvCYADZ0WpSK4eLccYlaAI6kckRwisRomiEFAEzFWOVamRUhsQNlFcmKlNF1CUkqEGokcqXBIQAklGCMmGFaYoTxlMgA9GddCHIAdAjtjKQ2N3AQZzt7YZeY17ql7ZhLlYbr02DcAIw3ABWlGgIFkCjklEwhEoyh0cgMJjMFmsdgczlc7k8xm8vn8gRQAG1QDNoskAILwkBVCLiZDgjJQKYsGS0pH0kAAIWZrJqrC5U0MfJAdK0AGFRdV2YZJShwWxJABdaRAA)
the keywords to look are little gantt chart or timeline chart.

in future, we could add zooming on the chart and panning to filter the list of cells.

**Comment by Light2Dark** [comment]
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/85f83a2c-7975-44c8-9769-2007ded7961e" />

The lib is good! Although the chart has to be built separately and then placed side-by-side to the trace rows. Can't really build it row by row like a react component afaik.

**Comment by mscolnick** [comment]
wow that looks great. i wonder if its would be better to stack them. it wouldn't be aligned then, but you would get:
* you can pan and zoom the full graph to filter the individual cells below it.
* scales way better, e.g. past 20 cells
* more horizontal realstate for the chart itself. (we are rich on vertical realestate

You can also add higlight-on-hover synced when hovered over a bar or the cell summary

**Comment by mscolnick** [comment]
I was thinking the browser network tab is good inspo, which does both above and to the right. The above allows for pan/zoom. But i find the right-side is easier to parse (as you've done)

![Image](https://github.com/user-attachments/assets/88e32ec1-643b-4714-9fe3-dd2b86f5b132)

So maybe we do both, eventually, but start with one for now.

**Comment by Light2Dark** [comment]
cool! I think it's similar to what I've done actly, since they clamp the total width.

**Comment by mscolnick** [comment]
thats great! sounds good

> I found a very nice gantt chart that does a lot of what we want

Wow i can't believe this was all done with vega. thats pretty impressive. We should definitely use some of it if we can. We may end up hitting a roadblock when wanting to integrate it with some of our React components (tooltips, anchors, icons)
