### ISSUE TITLE
Cell update bug with tables and mo.ui.run_button (race condition?)

### ISSUE THREAD

**Issue by psymonryan** [marimo-team/marimo#2913]
### Describe the bug

When mo.ui.run_button is used to create a list of dict, any cells referencing this list show the table empty of values.
However, when the output is triggered by a state change, the table display works correctly.

![Image](https://github.com/user-attachments/assets/6f8a0022-6d62-4e98-a5dd-f746282475a5)

This bug first appeared in marimo version "0.9.15"

### Environment

{
  "marimo": "0.9.20",
  "OS": "Linux",
  "OS Version": "6.10.14-linuxkit",
  "Processor": "aarch64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.14.1",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.7.4",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "pandas": "2.2.3"
  }
}

### Code to reproduce

```python
import marimo

__generated_with = "0.9.20"
app = marimo.App(width="full")


@app.cell
def __():
    import marimo as mo
    return (mo,)


@app.cell
def __(mo):
    sel_start = mo.ui.run_button(label='Create list of dict')
    sel_start
    return (sel_start,)


@app.cell
def __(mo):
    get_finished, set_finished = mo.state(value=0)
    return get_finished, set_finished


@app.cell
def __(sel_start, set_finished):
    # Create a large list of dicts
    my_list_of_dict = []
    if sel_start.value:
        my_list_of_dict = [{
            'Column1': 'Value1',
            'Column2': 'Value2',
            'Column3': 'Value3'
        }]
        set_finished(1)
    return (my_list_of_dict,)


@app.cell(hide_code=True)
def __(mo):
    mo.md(r"""## This table does not display correctly due to race condition""")
    return


@app.cell
def __(mo, my_list_of_dict):
    mo.ui.table(my_list_of_dict)
    return


@app.cell(hide_code=True)
def __(mo):
    mo.md(r"""## This table is correctly shown as it waits for the state change""")
    return


@app.cell
def __(get_finished, mo, my_list_of_dict):
    if get_finished() == 1:
        mo.output.replace(mo.ui.table(my_list_of_dict))
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
This is an odd bug, thanks for finding this. I am even printing out the time and the execution order looks like it should be ok:

![Image](https://github.com/user-attachments/assets/2b9b70d6-f2a4-48d2-a567-edded60f4738)

We will look into this

**Comment by mscolnick** [comment]
Printing out the dictionaries look correct too

![Image](https://github.com/user-attachments/assets/c60860c6-caf2-4864-9eb4-a9e8d445f28e)
