### ISSUE TITLE
Add documentation for how to set up the `.marimo.toml` file

### ISSUE THREAD

**Issue by meliz19** [marimo-team/marimo#2922]
### Documentation is

- [x] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

The [Package Management](https://docs.marimo.io/guides/editor_features/package_management.html#package-management) section of the [Docs ](https://docs.marimo.io/) state that users can choose from a variety of package managers to install packages. I use `poetry` in most of my projects, so I opted to use the `.marimo.toml` file to set the package manager. This was a painful endeavor as I had to read through the source code to figure out the expected layout of the `.marimo.toml` file. 

### Your Suggestion for Changes

It would be very helpful if documentation could be added to the Docs regarding how to set up the `.marimo.toml` file if users desire to take advantage of it.

**Comment by meliz19** [comment]
For those wanting to use the `.marimo.toml` option, here's the link to the [default configs](https://github.com/marimo-team/marimo/blob/401b2d68679ca0ec37237bfc2f5bdcb8e8d460b0/marimo/_config/config.py#L264).

**Comment by akshayka** [comment]
Thanks for the issue; we have it on our roadmap to improve the configuration experience (including documentation).

**Comment by mscolnick** [comment]
Closing this as we now recommend overriding in your pyproject toml: https://docs.marimo.io/guides/configuration/index.html#overriding-settings-with-pyproject-toml

You can also use new commands like:
`marimo config describe` to list the possible keys and description and `marimo config show` to find the current values and the location of the files. 

Closed by https://github.com/marimo-team/marimo/pull/3071
