### ISSUE TITLE
[Poetry] Add ability for the `Manage Packages` feature to work when a `pyproject.toml` file is located in a parent directory

### ISSUE THREAD

**Issue by meliz19** [marimo-team/marimo#2923]
### Documentation is

- [x] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

I love the `Manage Packages` feature, however, it only works when a marimo notebook is located in the same directory as a `pyproject.toml` file. It would be helpful to have a way to use the `Manage Packages` feature when a `pyproject.toml` file is located in a parent directory.

### Your Suggestion for Changes

Add the ability for users to use the `Manage Packages` feature when a `pyproject.toml` file is located in a parent directory. If this capability already exists, then clear documentation for how to change the default setting would be very helpful.

**Comment by akshayka** [comment]
Thanks for the issue. What package manager are you using? What went wrong?

**Comment by meliz19** [comment]
Thanks for the quick response! I get the `No packages are installed in this environment. ` message in the `Manage Packages` section when the `pyproject.toml` file is in the parent directory.

**Comment by akshayka** [comment]
Oh interesting. This seems like a bug with our Poetry backend. We can look into, thanks for reporting.

**Comment by akshayka** [comment]
Is marimo in your environment too? That is are you starting marimo with `poetry run marimo ...` ?

**Comment by meliz19** [comment]
> Is marimo in your environment too? That is are you starting marimo with `poetry run marimo ...` ?

Yes, `marimo` is in the environment and I'm opening the notebook environment via `poetry run marimo ...`

**Comment by meliz19** [comment]
My bad, you're right. I'm sorry about that. That's what I get work working on different machines. 

I was originally using `uv` as the dependency manager and the functionality works as expected: packages show up in the "Manage Packages" panel when the `pyproject.toml` is located in this same directory as the notebooks or in a parent directory. Packages can also be added to the project environment/`pyproject.toml` via the "Manage Packages" panel. However, when I switch to `poetry`, I am still able to add packages via the "Manage Packages" panel and it shows up in the terminal as being added and it's added to the `pyproject.toml`; however, none of the installed packages are listed in the "Manage Packages" panel.

**Comment by akshayka** [comment]
@meliz19 -- this issue should be fixed in version 0.9.22, which will be on PyPI within 20 or so minutes. Thanks again for reporting!

**Comment by meliz19** [comment]
Awesome!! Thank y’all so much. I love what you’re doing with marimo. I really appreciate the quick turnaround.Best regards,Margaret BlackCell: 770 597 5083On Nov 22, 2024, at 18:37, Akshay Agrawal ***@***.***> wrote:﻿
@meliz19 -- this issue should be fixed in version 0.9.22, which will be on PyPI within 20 or so minutes. Thanks again for reporting!
