### ISSUE TITLE
Copy / paste image as base64 data in Markdown

### ISSUE THREAD

**Issue by s-celles** [marimo-team/marimo#2932]
### Description

Hello,

I was hoping to be able to copy/paste image in markdown cell simply (CTRL + C / CTRL + V).
Unfortunately this is not the case.

Kind regards

### Suggested solution

Encoding as base64 image could be a solution (I'm doing it through https://www.base64-image.de/ ) but that's not convenient at all.

Notebook could also have a kind of concept of resources which could be used in Markdown cells (at least).

**Comment by mscolnick** [comment]
great suggestion! i've added this here: https://github.com/marimo-team/marimo/pull/2934

**Comment by s-celles** [comment]
I haven't look at your PR but  the main problem to consider is that we should avoid having cell be full of base64 code so I think ressource should be stored inside notebook but in a different area than cell (what I called "ressource"). And cell where we want image be displayed only contains a reference to that "ressource".
Ressource could be image / sound / movie?
I know this could be a problem for git if people want embedding too much things in a notebook.

**Comment by mscolnick** [comment]
Yea it would copy the base64. We could create a file and place it under `resources/<resources>` and instead make it a path to that file

**Comment by s-celles** [comment]
I would keep ressource inside the notebook file (by default) to easily move notebook without the hassle of also thinking of external ressources.

A UI like a "ressource explorer" could be designed in Marimo notebook where user could give a name to the ressource (to ease usage of a ressource inside notebook)

**Comment by mscolnick** [comment]
I think the first step can first just inline these files (e.g. images). maybe that is another issue/discussion, since i can see a bigger debate on whether marimo should have a concept of "resources" attached to the notebook, or just use files (which is my preference)

**Comment by s-celles** [comment]
Thanks @mscolnick
