### ISSUE TITLE
Focus lost when cell is hidden

### ISSUE THREAD

**Issue by anjiro** [marimo-team/marimo#2941]
### Describe the bug

This happens both with the keyboard shortcut and when using the mouse, but it's only annoying with the keyboard shortcut.

Hide a cell. Now no cells have focus and the mouse must be used to focus on a cell. I find I can push shift-tab and then my cursor is inside the hidden cell, which seems odd.

I think the behavior I would expect is that upon hiding a cell, the hidden cell would become the focus, such that I could push CMD-H again to un-hide it. I would also expect cursor movement keypresses to move off of the cell (see #2940).

### Environment

```
{
  "marimo": "0.9.22",
  "OS": "Darwin",
  "OS Version": "24.1.0",
  "Processor": "arm",
  "Python Version": "3.11.2",
  "Binaries": {
    "Browser": "131.0.6778.86",
    "Node": "v22.9.0"
  },
  "Dependencies": {
    "click": "8.1.3",
    "docutils": "0.19",
    "itsdangerous": "2.2.0",
    "jedi": "0.18.2",
    "markdown": "3.5.2",
    "narwhals": "1.13.2",
    "packaging": null,
    "psutil": "5.9.4",
    "pygments": "2.14.0",
    "pymdown-extensions": "10.7",
    "pyyaml": "6.0",
    "ruff": "0.0.292",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing-extensions": "4.9.0",
    "uvicorn": "0.27.0.post1",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "pandas": "2.0.2",
    "polars": "0.19.12"
  }
}
```

**Comment by mscolnick** [comment]
Thanks for filing this. I have a fix out, will release in a bit.
