### ISSUE TITLE
Right-click to copy cell output if nothing is selected

### ISSUE THREAD

**Issue by wasimsandhu** [marimo-team/marimo#2944]
### Describe the bug

Using the latest marimo version, when I right click over a cell's output and select copy, I am expecting the cell's output to be copied to my clipboard. Instead, nothing is copied.

### Environment
```json
{
  "marimo": "0.9.23",
  "OS": "Darwin",
  "OS Version": "23.4.0",
  "Processor": "i386",
  "Python Version": "3.12.4",
  "Binaries": {
    "Browser": "131.0.6778.86",
    "Node": "v20.18.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.13.5",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.4.4",
    "starlette": "0.41.2",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "pandas": "2.2.3",
    "pyarrow": "18.0.0"
  }
}
```

**Comment by mscolnick** [comment]
Can you share a video? I cannot reproduce this.

**Comment by wasimsandhu** [comment]
I can't reproduce it anymore either... Not sure what happened. However, I think this issue still stands because I'm unable to right click and copy cell outputs, only cell code.

**Comment by mscolnick** [comment]
Are you selecting any text and then right-clicking?

**Comment by mscolnick** [comment]
Converting this to a FR, taking a guess at what you were probably trying to do. Let me know if the updated title is correct.

**Comment by wasimsandhu** [comment]
Yup, looks good thanks. Updated the initial comment too.

**Comment by disouzam** [comment]
I came to this issue via Discord channel. I guess I'm making something wrong because I can't copy cell output without selecting it entirely. 

Should I do something special or just clicking in the output area to ensure focus is in the correct cell?
