### ISSUE TITLE
Converting a Jupyter notebook with external (local) images to Marimo notebook leads to broken image link

### ISSUE THREAD

**Issue by s-celles** [marimo-team/marimo#2950]
### Describe the bug

Hello,

I'm trying to use Marimo with these examples (Jupyter notebooks from Pandapower)
https://github.com/e2nIEE/pandapower/tree/develop/tutorials

```
git clone https://github.com/e2nIEE/pandapower/
cd tutorials
marimo convert .\minimal_example.ipynb -o .\minimal_example.py
marimo edit minimal_example.py
```

![Image](https://github.com/user-attachments/assets/5aead939-05be-48c9-83d2-fcb1e222b41b)

As you can see `<img src="pics/3bus-system.png" width="50%">` is not rendered.

Any idea?

### Environment

```
> marimo env
{
  "marimo": "0.9.23",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 142 Stepping 12, GenuineIntel",
  "Python Version": "3.11.5",
  "Binaries": {
    "Browser": "131.0.6778.86",
    "Node": "v23.2.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.18.1",
    "itsdangerous": "2.0.1",
    "jedi": "0.18.1",
    "markdown": "3.6",
    "narwhals": "1.13.1",
    "packaging": "23.1",
    "psutil": "5.9.0",
    "pygments": "2.15.1",
    "pymdown-extensions": "10.8",
    "pyyaml": "6.0.1",
    "ruff": "0.7.2",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "10.4"
  },
  "Optional Dependencies": {
    "altair": "5.4.1",
    "pandas": "2.2.2",
    "pyarrow": "17.0.0"
  }
}
```

**Comment by mscolnick** [comment]
We don't support images this way. This is because `<img src="pics/3bus-system.png"` will make a network request `http://localhost:2719/pics/3bus-system.png`, which we do not expose as a way to read your files from your filesystem, as that could allow an attacker for example to read your `.env` file.

**Comment by mscolnick** [comment]
We _could_ add `public` folder to automatically server assets from that folder. This is what most modern frontend frameworks will do. 
This is similar to [streamlit's static folder](https://docs.streamlit.io/develop/concepts/configuration/serving-static-files)

**Comment by s-celles** [comment]
What is quite surprising is that Markdown syntax ![img](pics/img.png) is also unsupported.

**Comment by s-celles** [comment]
My opinion is that you should reduce any friction that trouble Jupyter notebook conversion to Marimo notebook while considering potential security breach.
I perfectly understand that listing .env content can be problematic. Maybe a rule "reject all content" except some (.png, .jpeg, .jpg ...) should be considered in this case.

**Comment by mscolnick** [comment]
Yea, since our markdown is dynamic `mo.md(f"Your name is {input.value}")` and often can include "end-user generated content", we need to be more careful with fetching assets from it. We could include a "public-assets" field, that you can configure to be "*.png", but I think a better/clearer/safer option would be a public folder. So, while `marimo convert` today would require you to copy `pics` to the public folder, it is possible that we can do this on your behalf as part of the `marimo convert` CLI`.

**Comment by s-celles** [comment]
In such a case, export could provide 2 options.Embed resources as base64 or store as external file in this directory

**Comment by mscolnick** [comment]
Sounds good - @s-celles, would you like to open up a new issue for this feature-request, or update this issue with the request (and I can close this one)?

**Comment by s-celles** [comment]
I'm off until tomorrow. Sorry

**Comment by mscolnick** [comment]
No worries, I will close this issue. Whenever you'd like, we can open a new issue about `public/` assets (unrelated to `marimo convert`)

**Comment by adonath** [comment]
I was running into a similar issue. Is there any way to include local images in the converted / downloaded markdown? The standard way would be to included the directive `![image](my-image.png)` in the markdown, however this is neither rendered in the editor nor is it included in the markdown (instead it is rendered as an invalid python cell) when downloading the notebook.
