### ISSUE TITLE
The order of the columns in Marino's uitable is very confusing for me

### ISSUE THREAD

**Issue by DualWield** [marimo-team/marimo#2968]
### Describe the bug

I hope Marino's uitable can be displayed in the order of the columns I set.

for example:  I want the order of the columns is ["-1", "0", "1", "2"]
![Image](https://github.com/user-attachments/assets/652eacea-3a29-4b38-a01c-d52e03da4401)

### Environment

Null

### Code to reproduce

import marimo as mo
import pandas as pd

data = {"row_1": [3, 2, 1, 0], "row_2": ["a", "b", "c", "d"]}

pd.DataFrame.from_dict(data, orient="index", columns=["-1", "0", "1", "2"])

**Comment by mscolnick** [comment]
Thanks for sending this. 

I am switching the data-structure that contains column info from a map to a list or preserve order.
