### ISSUE TITLE
Failed to instantiate

### ISSUE THREAD

**Issue by cotucotudu** [marimo-team/marimo#2973]
### Describe the bug

After upgrading to `marimo 0.9.24`, I can't launch my marimo notebooks from the terminal, the page says: `Something went wrong. Failed to instantiate`. When I attempt to `Try again`, the following error message appears: `Failed to instantiate. Method not allowed`. The log is empty

### Environment

marimo 0.9.24
Python 3.12.7

**Comment by mscolnick** [comment]
This is likely from my change: https://github.com/marimo-team/marimo/pull/2969.

I will revert this and re-publish

**Comment by mscolnick** [comment]
`0.9.25` is released, apologies for the issues.

**Comment by cs2018ncsa** [comment]
yep, fixed for me. thanks!
