### ISSUE TITLE
Copy Matplotlib figure

### ISSUE THREAD

**Issue by s-celles** [marimo-team/marimo#3001]
### Description

Hello,

Currently we can't copy Matplotlib figure (as image). 

Kind regards

### Suggested solution

It should be possible to copy paste this kind of figure (without having to use screen capture).

### Additional context

[machine_outil.py.txt](https://github.com/user-attachments/files/17955985/machine_outil.py.txt)

**Comment by mscolnick** [comment]
@s-celles - you can right-click to copy. do you have any issues with that?

**Comment by s-celles** [comment]
Thanks again @mscolnick
