### ISSUE TITLE
Sub-second info not shown for Pandas `datetime64[ns]` column in rich dataframe viewer

### ISSUE THREAD

**Issue by jamescooke** [marimo-team/marimo#3007]
## Current behaviour

No sub-second information is shown for a column with milliseconds / nanoseconds granularity in the rich dataframe viewer.

The following is shown - you can see the difference between the plain view and the rich view: the rich view is truncated (doesn't round at all which you can see when the 3rd row is displayed as `2024-11-27 16:17:07`.

![Image](https://github.com/user-attachments/assets/a13ff4d0-580a-4871-8f0a-797963f228b3)

A warning is received that some truncation is happening which is probably a clue - you can see that at the bottom of the screenshot.

## Expected behaviour

* Rich dataframe viewer shows the same granularity of time data as the plain view.
* Hovering the mouse also shows the same information - at the moment the hover on the rich view also truncates.

### Environment

```
{
  "marimo": "0.9.27",
  "OS": "Linux",
  "OS Version": "5.15.0-126-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.13",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.14.2",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.0",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "pandas": "2.2.3",
    "pyarrow": "18.1.0"
  }
}
```

### Code to reproduce

```python
import marimo

__generated_with = "0.9.27"
app = marimo.App(width="medium")


@app.cell
def __():
    import datetime

    import marimo as mo
    import pandas as pd
    return datetime, mo, pd


@app.cell
def __(datetime, pd):
    _start = datetime.datetime(2024, 11, 27, 16, 17, 7, 742951)
    _slice = datetime.timedelta(microseconds=123456)
    test_df = pd.DataFrame(
        data={
            'timestamp': [_start + n * _slice for n in range(5)],
        }
    )
    return (test_df,)


@app.cell
def __(mo, test_df):
    mo.plain(test_df)
    return


@app.cell
def __(test_df):
    test_df
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
thanks for the repro. i can fix this. we have a default formatter for dates (which doesn't include subseconds), but I can check if there are subseconds and update the formatter. 

in the meantime, there is a `format_mapping`, you could use to customize the format:
```python
# format_mapping is a dict keyed by column names,
# with values as formatting functions or strings
def format_name(name):
    return name.upper()


table = mo.ui.table(
    data=[
        {"first_name": "Michael", "last_name": "Scott", "age": 45},
        {"first_name": "Dwight", "last_name": "Schrute", "age": 40},
    ],
    format_mapping={
        "first_name": format_name,  # Use callable to format first names
        "age": "{:.1f}".format,  # Use string format for age
    },
    label="Format Mapping",
)
```

**Comment by mscolnick** [comment]
Actually format mapping may not work since it might get converted back to a `Date` object.

I have a fix out here: #3009 , but this only handle microseconds, but not nanoseconds (due to a browser limitation on Date objects). The best workaround right now for nanoseconds is to cast to a string:

```python
  _start = datetime.datetime(2024, 11, 27, 16, 17, 7, 742951)
  _slice = datetime.timedelta(microseconds=123456)
  test_df = pd.DataFrame(
      data={
          "timestamp": [_start + n * _slice for n in range(5)],
      }
  )
  nano_df = test_df.copy()
  nano_df["timestamp"] = nano_df["timestamp"].astype(str)
  nano_df
```

**Comment by jamescooke** [comment]
@mscolnick Can confirm that format mapping doesn't work.

It looks like the data has already been truncated somewhere - possibly where it's getting loaded into the table.

**Comment by jamescooke** [comment]
Nice one on the quick fix! 🙇🏻
