### ISSUE TITLE
Correction of errors in 'Intro' notebook

### ISSUE THREAD

**Issue by datapiquing** [marimo-team/marimo#3011]
### Documentation is

- [ ] Missing
- [x] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

In Sections 4 and 6 of the 'Intro' tutorial, the 'app window icon' and 'save icon' are described as being in the 'bottom-left' when in fact they are in the 'bottom-right'

### Your Suggestion for Changes

Replace 'bottom-left' with 'bottom-right' in 2 locations

**Comment by Brijeshthummar02** [comment]
@datapiquing i'm up for it, assign me.

**Comment by Brijeshthummar02** [comment]
just show me path to the file.

**Comment by datapiquing** [comment]
> just show me path to the file.

[Intro Tutorial](https://marimo.app/?slug=c7h6pz#code/JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoBODgRi4C05PADcAzCzSIwYJgmSoOAQRkAKAJQY0AAWlgOAYzwAbY2mEAzONg0AuNHEdxQkWPJQgIcRAGcE6BydPDhByVRYAYjgAdRMDCBA8OBgvAG0kDwgAXVU6GBgwH1sAemKcWjoAVwAjQwTijNQBMkQQBoVPdQBCOEAeDcAofd7AYX2WTSc4KDwYSqgCOFVPABpNDF0ZQxNjXOBhTHjhRgAVKEq8TUtrTAWIdXtx4NDVQPHHFjfnl4AqT8O6YD9Gp44AQIGRqhAIABrZx+SBUYgUODVACecFS0SUAGUALI5PIFIqleHVXw+PAgarGZEcaA4Yrqb53F6OWgAcj8JwIBGABBwcEIMGAkypzjmyIgMyRUAgVDJUC6GGZr3e43UhkQpglMA0H0m01mWjW+iMpm2u32eCOJzO5jwVhsnSZjmCiAM8Sg5GAEAITyVcAA3h8-SxonRCHAfHQJcZyHAAJJwSpkmJY7HA0F4cFQnwAfhYtlYKr9TgxOPTYIhkL8yCSeAAHibjAK4BZoBG6ApeU7i9U8AZEEmkvQ8KjOfyCILhaieckw1KZXLFrOR95Jvy6zBJokqUGlXhfKiUu2axw4AApJPwCBgcPD8uZyveAyC70IQiVbzwO8pMACFA4PJvAIchd2ZAxjGAAxoTvFhMQ7NdSzTEEKyhFgkUqfJXyPfB4EQY9JkQSkkgAVQAJQAGVPABNCU4H7AhQJeDUfC8cle1jcVJWQh8oVFOBQTDKA4GJMBEHwPwRGAPDEDmAADAAeYALBIRIAD5ZI4RVi0cRDVySeFTAEHxKloRFWyEgBHEyoJFesbw8AUeT5Gh6DoiBhCAkDtOddyTB8JdyAgJy4AggCYHhYAwrgchSGkggNWRHx-iXAd6GgYLKQgHBGPGSAfBgfzkgw9LmJS4D+XISp+xfeLjFXQVwLwQqZNjURw2qEyY2CnkyFmDUcqcFIIGMHxT1+Fca3LYTNiMkyyFjcz7yzKtZ1IaKvDDRARGRAbHHicAMNIL0CDK2Nh1RQKCFZeBjJkaB4BASpjEFZo6AIz1eXTKBdoQJ7BTAaUjB8JLeQAbhbNth2TfsyUKwdvAmPAcCe5B3FQJbK007zC0kP0AF8PjGJw9RmBjVj0DZTT+c1fKtU5zjtS5rluD4XTdaBPW9X0lUDbGWDjAh8o1CDPtEqCxKavjdO45afHzfwQjCH7xjeXGlWxGTUTFyEJb8GhTCRJJUoSI7+1MadBZgYWKEWRjxuhmTDYhypyrW1Jtd1gQeQEMBxU9YQ8XyQoSmKX33J2PAaSgOlCGKIWiOKJMJdD10dfEr2CB9v2I44PIQGMNUtOZAAxNsBOIOAPfEpd4ZASDpTAYAwHsRjZLb320oYv0XHuhB6+vJvGMQKhEFoPuDAbpuOB5IXTRYMBjFBKlRkYnu3AXpedr9NvZMY1WfqJ5kCdVXUplJw0KcbW17SuR0Ph8CDhCE5hghMjgH4jqBVF4JcACZf8PojfUcxVAfyfssC+6wr4XAdBAJcYDiAs3uBARW3NmQWH3n6QEXh-gI2+ARZ8wARB4G+HAAACsiTuGMoSaTtn8AE+5BarXgC7CCkIhwkE9DVDU1CqxLmwbwvw+CXZD2KkgBqwtkSkKoGGMUtFPCegsIeMMIB+LfW7hOYgrp4AuQYMRBMJhyQCkKmwoc9CIyP2IAWf0CCoB41oX6f0kQIhoQANSsGGGhT4FjP4cBEBqU4x8lSYKcIAkmBpyZQM2GaPAexabHHptfJmd9kGoL3kWZkEQoi8FPKRfchDiHrj7BhY6RcXhKDRkCGWj5cFIA8pUWQEArA+CQAbTKUE-BNPIZQqMcwLR0Wtl5JUjZRplPuB0Lw70-CcSEiMzy-hhAjWXNFPAN5gKEAMMASWrRvR8mHCAAsMjCBtXUUqPCjZmErIsDybZcAcCLxJHVfxKBCJNhZByF2-CJmMW+MbcRkFJETBdj4Uhws6KbD8PQNakwLAIgIEYS5zypJEQcUqPJ2iiG0FROw1Z0yJRCQBllFSEYrZkHmVqMAGE-Azh8MieFwkKhwBmW5YQtssGIEhMFRaeFyB0taJBSu0ocAqTrp9QgklpQEESBOS5AM2oTj8B1HAiq7TQDMSORiHYZCECxsEjJcAwlnwiToS+0TqaxItHTG0MCrgGA7LyG2-gkFODQS8B4StsYYP1X6b4gAKcjgAAOUgngLopDxpwH8cYU4-ErCyTtTJfA5BZIwnTFQAM8aHXkHsWMpUoZwycUTGAGK81lmRujV0u8SLXlJDjfaxNskvmZB+vg-J81SEoiBVyYK9BcEXL+abSRS5ez9nhj2vwV9sYwrhUDZZ9yICPIjQoatcBa0JooBpHNzJ0UFKxeOYykxIUdngMy6pvEhZktwRqEeiUfrxEFv8MgE4lwyMggwXtJxNk8MWoFYKOAISxh8JsjZeBwZsmrCNLwMjSA-UINWgEEzBHJC8IFGobzfBIeGtWcq3gZCjL5t60Jq8rAZsTYxPySR3WuuDAR5k3wBhwExHgJIY8ZwYu9BwUhAtllEA3OC0wS4SPqsXVGpIFaww-SrURRwq7M3JqPLJBJeAG3Lj6RBKCyyxwdUwgQXV2kQnMkAYa4BkDjSbCSTYZ1e062ImYMXZieBT7APmIJ8gEDImmaphHOJBxFMMxvszbsbN3Scx9IxXm3kWCHCbgWesxSapqKfvLKjEWaPFnDRzCuXS5lYTnKJfAcAOx+BBIbTsfJvTK0GnODLQkZwvrtXxpZk1YsGAwhQAsAjIQgllJc85ZnsbjHesFPCkm3mPXyp27wFherLIuVC+AVybnUpgGNehFXHDKSY3ij8R5aQyWAAALySMy-pM47zXsuUgdhh6KMQHymtiMhBkyLU4rp-r+niyAPGEExwRnz7ucplsc13nLS+fM7fG4gWUGPHSWrWjnwADiDyeHxUSACS8TsXbACspHMNrF4pSYIYKSSMBkSNvRj3WG3hGJ3vyiQHq-E5hRjTSj7Z2rUYzhGQWYr4UvBzKQBdO0Nzlk+FaA5v0I3I4w8Jo5v7JqomeZpj560fnkkQ9Zig10wXjrJccOFvTUXm7jn7IUFGNUkv3fe9jAAQqiDZ0hjLGCOp9Re5QDB8QsC7Qh3pCrgVJE1JcbYKFUIUU9f392C30T7tyOuh3uOVApJlqwc6F0S+pXIriGZlqvfw7Dj7jFvsGpl8ao0AOYnA6tSr2BlmFaa45trsLP1IvRcFUQ0gSRU-m-604S33kABqS6iKwhhcAOsiJdFAUTOsqAgG1V6VYADVvZA0JHl6-xiM6Au+OHOgMuYvYFtEFjB2x6z0m5vJGdnlLue-SfacAX37xfTUK4tfE5XYOAvq7SdRq-TgslwF-qefRfkJsaVAqTdF4AAYQhR334gwkpXgB6i0QKRIgMWAOMVPAFl6gxU+nHzwn0Rg1QJlV+TEQHXNmSH-HwGn14SKRaxqkZGElkR+gLQQJIGfAZVclwJQKMSfWcAKmE2jVwTJBlRJHUyPCD16VOhg2ISgFRFmyPURlhUmHhUljmyAK4PgI5DwD-BdlRW0gEUJUkmEGrBCmAGqBIGkJjTgEAMMRAMhV5yjFuySGUgSEnyfh+lkmwQ4BMg3S-2lwGyNTJjlw8zMBtXf1SUeFVjo36AYwSGQNUJsI428WOAtkwMIWwMZTvF7EXjTWsLQNVnvwCJL2gUZir27EglfBfhQTfnIAbkCioB9FSBYE8SXEaP6BYGaN9RYCyCXDLUtEaJGHyPmDKJOhWECIBzfyGP4TVz8JvEFBqj8AqM8OAHfksS-h-jgF4AADYlxHdMjGAMECB49ewhIul-Qhi-EAk8A8YCwV4-CnNVBJgZjaBjp-IRjCizMQiJjEZHi5jq9PiHipgnjvci8CjH9gjiirhPilgviASfjIdUFIhWA4B3Eziei4BvF-jZjnjziRN8iTNS8gdLVQcQiUkggocPU9Vv9HBf8xBTwBFcEAArdHMQ8rRiAROZUSafJIZkkBFqBnEUb)

**Comment by datapiquing** [comment]
![Image](https://github.com/user-attachments/assets/654631ca-5579-4abe-8bbe-0523e9ec97c8)

**Comment by mscolnick** [comment]
This was corrected, in the main repo, I just need to update the intro from the playground, which unfortunately is not open-source. I'll update this

**Comment by mscolnick** [comment]
Updated this in marimo.app

**Comment by henryharbeck** [comment]
Hi @mscolnick, despite this issue being closed, https://marimo.app/ still references icons being in the bottom left rather than bottom right

**Comment by mscolnick** [comment]
Thanks for the heads up. I'll fix that this week

**Comment by henryharbeck** [comment]
Now it says bottom right in both instances🤷 
Sorry about the noise @mscolnick
