### ISSUE TITLE
Anywidget _esm updates are not reflected on definition change

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/marimo#3018]
### Describe the bug

If developing an anywidget application, and the first run contains invalid _esm, then subsequent definition updates/ fixes do not occur.

E.g. Fresh Kernel, bad widget
![Image](https://github.com/user-attachments/assets/5bec86ed-9d0c-4981-ad73-842a9fb77417)

Same kernel, fixed widget

![Image](https://github.com/user-attachments/assets/de43d458-4557-4662-8f15-08f1a1b90f4a)

### Environment

This could be a browser issue. I didn't dig into it too much

Firefox 132.0.1 (64-bit)
Google Chrome 131.0.6778.85

### Code to reproduce

Maybe a little bit contrived. You can initially run an app with a syntax error, fix it, and see that the fixed widget won't work (like in the screenshots).

https://marimo.app/l/eaebt7

**Comment by dmadisetti** [comment]
Turns out just refreshing the page gets rid of the error. It seems like esm updated in general are not invalidated live.

**Comment by mscolnick** [comment]
Yea this is likely just a re-render issue, when _esm changes. I will look into this
