### ISSUE TITLE
Altair figures overflow in app mode

### ISSUE THREAD

**Issue by adigioacchino** [marimo-team/marimo#3023]
# Describe the bug

When a wide figure is plotted with Altair, in the "editor" mode it gets correctly visualized with the possibility of horizontal scrolling, but this does not happens in the "app" mode, the figure overflows the cell and gets cut, see screenshot below.

## In editor mode
![Image](https://github.com/user-attachments/assets/1000db6c-ed24-448a-8389-9e18cdb66d6d)

## In app mode
![Image](https://github.com/user-attachments/assets/46c8bf9d-2ce1-442e-9093-a6ea186be445)

# Environment
The example below resulted in the bug with the online WASM notebooks today.

# Code to reproduce

```
import altair as alt
import numpy as np
import pandas as pd

# Compute x^2 + y^2 across a 2D grid
x, y = np.meshgrid(range(-5, 100), range(-5, 5))
z = x ** 2 + y ** 2

# Convert this grid to columnar data expected by Altair
source = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
    color='z:Q'
)
```

**Comment by mscolnick** [comment]
This is somewhat expected / not sure the best way to handle this. We could consider clipping/scrolling app mode, like we do in edit mode, but this would make it hard to "break out" of this whatever less common cases.

In the meantime, you can add your own scroll container to the chart:

```python
chart = alt.Chart(source).mark_rect().encode(x="x:O", y="y:O", color="z:Q")
mo.Html(f"""
<div style="overflow: scroll">
{mo.as_html(chart)}
</div>
""")
```
