### ISSUE TITLE
Undocumented arguments to mo.ui.table

### ISSUE THREAD

**Issue by liquidcarbon** [marimo-team/marimo#3029]
### Documentation is

- [x] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

These options were introduced in #2017 by  @mutongx but are not documented in `mo.ui.table`

```
_internal_column_charts_row_limit: int | None = None,
_internal_summary_row_limit: int | None = None,
_internal_total_rows: int | Literal['too_many'] | None = None
```

### Your Suggestion for Changes

Seems like `_internal_total_rows` could be useful for limiting the output of large tables that would take too long to display otherwise.  However, pagination starts working strange with this option.

It would be nice to explain what these options do.

**Comment by mscolnick** [comment]
These are internal, non-public apis. They are not meant to be used and hence the underscore. 

They do not effect pagination or effect performance of dataframes, but rather there easier testing
