### ISSUE TITLE
SQL cell doesn't handle duckdb's struct datatype

### ISSUE THREAD

**Issue by cs2018ncsa** [marimo-team/marimo#3037]
### Description

`SELECT unnest([{'a': 42, 'b': 84}, {'a': 100, 'b': NULL}], recursive := true);` 

`ValueError: Invalid format specifier ' 42, 'b': 84' for object of type 'str'`

is it possible to execute this as a straight SQL cel or are `duckdb.sql ` or `mo.sql` required?

works fine:
```
_df = mo.sql(
    """
    SELECT unnest([{'a': 42, 'b': 84}, {'a': 100, 'b': NULL}]);
    """
)

_df
```

### Suggested solution

enable duckdb datatypes in SQL cells.

**Comment by mscolnick** [comment]
hi @cs2018ncsa, short answer is yes. 

Our "SQL" is really just python under the hood, this so the notebooks stay a "pure python" which can be run as scripts or used as production applications. By default we use `f-strings` for the SQL string, which is hidden to the user (by default) when viewing the SQL editor. This allows for parameterized sql, like: `SELECT * from table where value < {min}`. So there are 2 options:

1. Escape the real `{`/`}` that you don't want parameterized. You can escape with double `{{...}}` so in this case:
```sql
SELECT unnest([{{'a': 42, 'b': 84}}, {{'a': 100, 'b': NULL}}]);
```

2. Remove the f'string. You can trigger the SQL cell back to Python, and then either:
```python
_df = mo.sql(
    """
    SELECT unnest([{'a': 42, 'b': 84}, {'a': 100, 'b': NULL}]);
    """
)
_df
```

2b. You can also use `duckdb` as-is. `mo.sql` just wrapper add the output as a pretty table and returns a dataframe.
```python
import duckdb
relation = duckdb.sql(
    """
    SELECT unnest([{'a': 42, 'b': 84}, {'a': 100, 'b': NULL}]);
    """
)
relation
```

**Comment by cs2018ncsa** [comment]
thanks for the quick response! makes sense. loving marimo!
