### ISSUE TITLE
Mobile layout, full width, and hamburger menu issues

### ISSUE THREAD

**Issue by kai-mana** [marimo-team/marimo#304]
### Describe the bug

A few things I've noticed when using marimo on mobile:

The hamburger/settings buttons overlap the title sometimes.
Tapping the hamburger menu doesn't keep it open, you have to long-press on it to get it to stay open when you lift your finger.

With full width off in portrait, the block is cut off to the right, but is roughly the full width of the screen:
![image](https://github.com/marimo-team/marimo/assets/145619396/affe86c4-09ad-4543-841b-6ce4ca708647)

When you fill the block with text, it scrolls the page to the right, but you cannot manually scroll right/left:
![image](https://github.com/marimo-team/marimo/assets/145619396/3bf7e43b-fe70-4a44-b6e7-7831bbd975e7)

With full width on in portrait, the block gets tiny:
![image](https://github.com/marimo-team/marimo/assets/145619396/dad47cda-fd71-4056-a9c3-4e2a9e0bb2e9)

In landscape, full width on/off makes essentially no difference:
![Screenshot_20231104_142110_Firefox](https://github.com/marimo-team/marimo/assets/145619396/16e3a4f7-0f94-49a1-ae9b-00f34abc5d69)
![Screenshot_20231104_142132_Firefox](https://github.com/marimo-team/marimo/assets/145619396/e7372fc4-9748-4040-a2a7-961daae56c2e)

These are from Firefox, but the same behavior happens in Chrome, other than the hamburger menu long press issue.

### Version

0.1.43

**Comment by akshayka** [comment]
@kai-mana, thanks so much for documenting these issues thoroughly. It's very helpful.

Out of curiosity, were you using marimo on mobile just to test its responsive behavior, or were you trying to actually do work on mobile? As you can tell we haven't optimized the editing experience on mobile — if you and others are actually trying to do work on mobile, we may prioritize it higher. Thanks!

**Comment by kai-mana** [comment]
@akshayka I don't think it should be very high priority, but it is pretty useful for real work on mobile, especially as folding phones get more popular and processors get more suited for these kind of tasks. And it's potentially very useful to serve content to mobile devices with marimo even if it's just to view it. And marimo runs pretty well in Termux.

**Comment by mscolnick** [comment]
Going to close this - mobile run mode works and the layouting is not fixed of smaller screens. (however, edit mode is not very easy still)
