### ISSUE TITLE
Grid controls difficult to select

### ISSUE THREAD

**Issue by Wazarr** [marimo-team/marimo#3074]
### Describe the bug

The controls for adjusting the grid settings such as row width, height, etc are very hard to grab.
It seems the mouse gets confused by the overlapping div.

You can still use them by clicking on the bottom, but this seems to be unintended behavior.

![Image](https://github.com/user-attachments/assets/94d3cfbf-7ea9-4eb7-b081-221a9c98f932)

### Environment

{
  "marimo": "0.9.31",
  "OS": "Darwin",
  "OS Version": "24.1.0",
  "Processor": "arm",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "131.0.6778.109",
    "Node": "v21.7.3"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.14.1",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.0",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "pandas": "2.2.3",
    "polars": "1.14.0",
    "pyarrow": "18.0.0"
  }
}

### Code to reproduce

import marimo

**Comment by Light2Dark** [comment]
I thought this feature was disabled lol. What do you think about making the div's z-index the same as the AppHeader @mscolnick 
```.tsx
const GridControls: React.FC<{
  layout: GridLayout;
  setLayout: (layout: GridLayout) => void;
  isLocked: boolean;
  setIsLocked: (isLocked: boolean) => void;
}> = ({ layout, setLayout, isLocked, setIsLocked }) => {
  return (
    <div className="... z-50"> // here
```

**Comment by mscolnick** [comment]
Ah good old z-index issue. @Light2Dark - that would be great!
