### ISSUE TITLE
No Failure Hints When Using `marimo export html`

### ISSUE THREAD

**Issue by mbbyn** [marimo-team/marimo#3089]
### Describe the bug

When running `marimo export html` on a notebook that fails, there are no hints for the caller that something went wrong. It would be great to get a non-zero return value and/or some output without having to inspect the resulting HTML. Also, if the `--no-include-code` flag is passed, there doesn't seem to be a way to clearly know if the execution failed or succeeded.

I tried using `-l DEBUG` but that was too verbose, using `-l INFO` didn't show any hints of failure either.

### Environment

```json
{
  "marimo": "0.9.32",
  "OS": "Linux",
  "OS Version": "5.15.167.4-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.11.11",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.17.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.16.0",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.2",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "duckdb": "1.1.3",
    "pandas": "2.2.3",
    "polars": "1.16.0"
  }
}
```

**Comment by mscolnick** [comment]
Good callout. We can update the return code. And we can print out the errors.
