### ISSUE TITLE
Asyncio error when hosting marimo behind google IAP

### ISSUE THREAD

**Issue by regisverdin** [marimo-team/marimo#31]
### Describe the bug

Hey Marimo team,

We've been trying to host a Marimo notebook (using `marimo run`) in Google Cloud/Kubernetes, and have run into this issue which seems internal to Marimo. (see error log below). The template page loads, but none of the subsequent api calls to actually run the notebook code seem to work. For context, I've been able to successfully load this notebook locally, and have also successfully loaded it when port forwarding to the kubernetes service (the same one behind the public endpoint). But when we run it with our public endpoint, I get this error. 

On a possibly related note, we have Google IAP handling auth for the public endpoint, which I think causes the websockets requests to fail (since they can't authenticate) and fallback to http requests. I see a lot of `/api/kernel/instantiate/` requests failing with 404, for example (but some get 200).

Any ideas you might have here would be much appreciated. Thanks!

```
ERROR:asyncio:Exception in callback None() 
handle: <Handle cancelled>
Traceback (most recent call last):      
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run         
    self._context.run(self._callback, *self._args)
  File "/.../python/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)      
  File "/.../python/.venv/lib/python3.10/site-packages/marimo/server/sessions.py", line 207, in reader
    (op, data) = self.read_conn.recv() 
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()           
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 421, in _recv_bytes             
    return self._recv(size)            
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)    
OSError: [Errno 9] Bad file descriptor 
```

### Version

marimo-0.0.1a0-py3-none-any.whl

**Comment by mscolnick** [comment]
hey @regisverdin, how many instances of your container are you running? the server has internal state (including the active sessions) and GCP could be distributing your requests across instances. 

if you jump in https://discord.gg/rAhpfKwuaN, i can also help debug

**Comment by regisverdin** [comment]
We ended up updating to a newer marimo version, which had better logging and revealed a bunch of issues on our side. The main one being that IAP needed to have "Enable HTTP OPTIONS" activated.
