### ISSUE TITLE
table selection is cleared when placed in accordion and this is folded / unfolded

### ISSUE THREAD

**Issue by mrdobalina2k** [marimo-team/marimo#3142]
### Describe the bug

I have a table that I want to select a row from. The choice of row is used to populate a text field below, as part of a configuration. 

When I place the table inside an accordion, or another element, in which it is refreshed upon folding / unfolding, the selection is scrapped and my text field is empty again.

### Environment

{
  "marimo": "0.9.34",
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "Intel64 Family 6 Model 126 Stepping 5, GenuineIntel",
  "Python Version": "3.12.2",
  "Binaries": {
    "Browser": "129.0.6668.60",
    "Node": "v20.14.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.20.1",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.1",
    "markdown": "3.6",
    "narwhals": "1.14.0",
    "packaging": "24.0",
    "psutil": "5.9.8",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "pyyaml": "6.0.1",
    "ruff": "0.5.2",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.29.0",
    "websockets": "11.0.3"
  },
  "Optional Dependencies": {
    "pandas": "2.2.2"
  }
}

### Code to reproduce

Here's a way to test it. Unfold the accordion, select a row,  see how the text field is updated, fold the accordion, and unfold it, and see how the selection disappears, and the text field is now empty.

```python

import marimo

__generated_with = "0.9.34"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    return (mo,)


@app.cell
def __(mo):
    table=mo.ui.table([{"col1": "hello"},{"col1": "world"}], selection="single")
    return (table,)


@app.cell
def __(mo, table):
    if table.value:
        val = table.value[0]["col1"]
    else:
        val = ""
    text=mo.ui.text(label="Select from table", value=val)

    return text, val


@app.cell
def __(mo, table, text):
    mo.accordion({"fold down": mo.vstack([table, text])})
    return


if __name__ == "__main__":
    app.run()

**Comment by mscolnick** [comment]
Seems like a react state/initialization bug. Thanks for pointing this out.
