### ISSUE TITLE
kernel not found

### ISSUE THREAD

**Issue by rsamf** [marimo-team/marimo#3167]
### Describe the bug

On Python 3.12.3, marimo 0.10.2, I run marimo with
```bash
marimo tutorial intro
```
or `marimo run [file]`, and I get "kernel not found" in the web app.

While trying to downgrade marimo versions, I noticed this also happens on versions 0.10.1, 0.10.0, and 0.9.34.

### Environment

{
  "marimo": "0.10.2",
  "OS": "Linux",
  "OS Version": "6.8.0-49-generic",
  "Processor": "x86_64",
  "Python Version": "3.12.3",
  "Binaries": {
    "Browser": "124.0.6367.60",
    "Node": "v20.4.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.18.3",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.3",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {}
}

**Comment by akshayka** [comment]
Are there any errors in the browser console or terminal that you can share?

**Comment by rsamf** [comment]
Attaching browser logs:
![Image](https://github.com/user-attachments/assets/63ef3725-bf05-4408-a6bd-aca306b8578b)

You can also see this happening in the marimo Hugging Face Spaces template. I tried creating one here: https://huggingface.co/spaces/rsamf/marimo-space

**Comment by cmarqu** [comment]
FWIW, I'm seeing the same problem with
```
{
  "marimo": "0.10.2",
  "OS": "Linux",
  "OS Version": "3.10.0-1160.118.1.el7.x86_64",
  "Processor": "x86_64",
  "Python Version": "3.10.8",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.11.1"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.18.4",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.3",
    "starlette": "0.42.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "14.1"
  },
  "Optional Dependencies": {}
}
```

**Comment by vitorhirota** [comment]
had the same problem, had to downgrade all the way to 0.9.25 to work again. then figured it might be the same as #2596 and tried 0.10.2 on edge, instead of brave, and voila, it worked...

not sure which browsers are you in, but seems related.

**Comment by rsamf** [comment]
> had the same problem, had to downgrade all the way to 0.9.25 to work again. then figured it might be the same as [#2596](https://github.com/marimo-team/marimo/issues/2596) and tried 0.10.2 on edge, instead of brave, and voila, it worked...
> 
> not sure which browsers are you in, but seems related.

Ah, I tried 0.10.2 on Firefox, and it works!

I use Google Chrome. Has Chrome become unpopular nowadays? 😅

**Comment by PatWalters** [comment]
I was able to fix this by clearing the browser cache.
