### ISSUE TITLE
Permit CORS using marimo.app

### ISSUE THREAD

**Issue by engdan77** [marimo-team/marimo#3169]
### Description

It would be awesome if https://marimo.app/ were able permit CORS, e.g. using Python code such as

```
import micropip
await micropip.install('requests')
import requests
requests.get('http://www.cnn.com')
```

Without getting the following exception in the JavaScript Console:
```
[blocked] The page at https://marimo.app/e#code/JYWw....... was not allowed to display insecure content from http://www.cnn.com/.
```

... and as consequence resulting in the following in Marimo notebook:
```
....
requests.exceptions.ConnectionError: ('Connection aborted.', HTTPException('Exception thrown in fetch: Load failed'))
```

As what appears to be due to reasons as described in 
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin
https://docs.pyscript.net/2024.7.1/api/

PS. fantastic work with this project ⭐️

### Suggested solution

Ensure the web service serving this URL add following HTTP header in its responses, at least optionally by setting such a query-parameters

```
Access-Control-Allow-Origin: *
```

**Comment by mscolnick** [comment]
Hi @engdan77 - unfortunately that is not how cors works. As the sender, you cannot set it. The header you are reference is a Response header so that is on the receiving server (which we do not control).

**Comment by mscolnick** [comment]
@engdan77 this thread might help https://discord.com/channels/1059888774789730424/1226917030238883901/1226930992221126778

**Comment by engdan77** [comment]
Thanks @mscolnick for straighten out my misconception and point me into that direction, will definitely take a closer look there 😊👍
