### ISSUE TITLE
CLI option for controlling show-code for `export html-wasm`

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#3171]
### Description

When viewing an HTML file produced with `marimo export html-wasm`, one can control whether the code is shown via a query parameter in the URL, `?show-code=false`.

We should make this easier for our users.

### Suggested solution

Have a CLI option that controls the default behavior.

### Additional context

Links to requests and discussion:

* https://discord.com/channels/1059888774789730424/1179936876103225354/1317352306769137706
* https://discord.com/channels/1059888774789730424/1278810634472919082/1317434149048549429

**Comment by mscolnick** [comment]
`show-code` or `include-code` or both? I think `include-code` (which hides all the code and doesn't make it viewable) is likely what those Discord discussions wanted

**Comment by akshayka** [comment]
I think `show-code`. Since code will always be included in the index.html anyway, include code is less important in my mind.

Show-code is important for educational and tutorial use cases -- letting the reader view the code should they want to.

**Comment by mscolnick** [comment]
@Justyouraveragehomie 

* it uses https://pyodide.org/ to run python code in your browser. 
* pyodide and python packages are loaded on the fly so it does not work offline. by self-contained, we mean all the logic is included to run. we could eventually add an option to download and include pyodide
* [Here is a demo video](https://x.com/themylesfiles/status/1867615752750006507)
