### ISSUE TITLE
Default display of Pandas series hides entries, without any way of seeing them

### ISSUE THREAD

**Issue by gabrielgrant** [marimo-team/marimo#3191]
### Describe the bug

A pandas series is limited to showing the first and last 5 elements. Once the series is longer than that, middle elements are replaced with '...' and there doesn't appear to be any way to expand that

![Image](https://github.com/user-attachments/assets/25f83606-a286-4a15-9498-f2faa049c89b)

Seems clicking the `...` should expand and show the hidden values. Alternatively, could use the table UI with a single column

### Environment

```
(marimo-env) gabriel@LAPTOP-T6MCV0FC:~/repos/rxfood/MNT$ MARIMO_OUTPUT_MAX_BYTES=10_000_000 ~/marimo-env/bin/marimo env
{
  "marimo": "0.10.1",
  "OS": "Linux",
  "OS Version": "5.10.102.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.11.5",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.18.0"
  },
  "Dependencies": {
    "click": "8.1.3",
    "docutils": "0.21.2",
    "itsdangerous": "2.1.2",
    "jedi": "0.18.2",
    "markdown": "3.6",
    "narwhals": "1.13.3",
    "packaging": "22.0",
    "psutil": "5.9.6",
    "pygments": "2.14.0",
    "pymdown-extensions": "10.8.1",
    "pyyaml": "6.0",
    "ruff": "0.2.2",
    "starlette": "0.37.2",
    "tomlkit": "0.12.5",
    "typing-extensions": "4.11.0",
    "uvicorn": "0.29.0",
    "websockets": "12.0"
  },
  "Optional Dependencies": {
    "pandas": "1.5.3"
  }
}
```

### Code to reproduce

```python
pd.Series(range(11))
```

**Comment by mscolnick** [comment]
This is the default pandas html output. We could default to our table viewer (like we do for Dataframes).

**Comment by gabrielgrant** [comment]
Gotcha. Sorry. Agree that makes this more of a feature request than a bug
