### ISSUE TITLE
Support pl.Duration in dataframe viewer

### ISSUE THREAD

**Issue by v1gnesh** [marimo-team/marimo#3267]
### Description

First of all, most sincere thanks for building this and for sharing your work.
There is no doubt that your work is high quality and benefits way more people than you may have set out to, by simply removing developer friction.

Hopefully this is a minor item that can be picked up at your leisure - 
When viewing a dataframe that has `pl.Duration` columns, the table viewer doesn't know about these columns.  
It shows `Invalid Date-Invalid Date`, as seen below.

![Image](https://github.com/user-attachments/assets/4350ac78-5cbe-4372-b43e-40d986f73172)

### Suggested solution

Make the table code aware of pl.Duration.

### Additional context

Unrelated but just adding here as a general comment:  
I'm sure you're already aware of [Great Tables](https://posit-dev.github.io/great-tables/articles/intro.html).  
Please see if it helps in any part of the marimo experience.

**Comment by mscolnick** [comment]
Fix incoming! You can check it out here: https://github.com/marimo-team/marimo/pull/3274
