### ISSUE TITLE
`ui.table()` option `show_column_summaries` not working as documented

### ISSUE THREAD

**Issue by bulletmark** [marimo-team/marimo#3306]
### Describe the bug

As mentioned in issue #3132, I've just started using marimo and on version 0.10.7 which should have the feature documented in the [0.10.6 release notes](https://github.com/marimo-team/marimo/releases/tag/0.10.6) where the user can set stats/chart-only modes for table column summaries. However it does not work for me, nor if I use "charts". Gives same error with any string. Only accepts `None`, `True`, or `False`.

![Image](https://github.com/user-attachments/assets/a4ebe96f-6b4d-4075-a199-b206b1c9fbff)

Note `ddata` is a pandas DF.

### Environment

```
$ .venv/bin/marimo env
{
  "marimo": "0.10.7",
  "OS": "Linux",
  "OS Version": "6.12.7-arch1-1",
  "Processor": "",
  "Python Version": "3.13.1",
  "Binaries": {
    "Browser": "--",
    "Node": "v23.4.0"
  },
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.19.1",
    "packaging": "24.2",
    "psutil": "6.1.1",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.13",
    "pyyaml": "6.0.2",
    "ruff": "0.8.4",
    "starlette": "0.43.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "altair": "5.5.0",
    "duckdb": "1.1.3",
    "pandas": "2.2.3",
    "polars": "1.18.0",
    "pyarrow": "18.1.0"
  }
}
```

**Comment by metaboulie** [comment]
@bulletmark Thanks for reporting this 🙂. I forgot to update the data validation rule for `showColumnSummaries`, and I've fixed that. `show_column_summaries` should work in the next release 🩵

**Comment by akshayka** [comment]
@bulletmark , thanks for reporting. Version 0.10.8 includes the fix, available now on PyPI.
