### ISSUE TITLE
Cell clock only increases when tab is active

### ISSUE THREAD

**Issue by weidler** [marimo-team/marimo#355]
### Describe the bug

Its not necessarily a big issue, but I realized that the timer for a cells run time only increases when the tab/window is active. If I switch to another tab and then later return to the marimo tab, the clock continues at the previous earlier value and did not increase in the meantime.

### Version

1.50

**Comment by mscolnick** [comment]
This has been fixed by https://github.com/marimo-team/marimo/pull/361 and released in https://github.com/marimo-team/marimo/releases/tag/0.1.53
