### ISSUE TITLE
Is it possible to recover overwritten marimo notebooks (`.py` files)? 

### ISSUE THREAD

**Issue by tdiao** [marimo-team/marimo#356]
### Describe the bug

Is it possible to recover overwritten marimo notebooks (`.py` files)? I launched two different scripts in the same port and one overwrote the other, it seems.

Longer version/more details:
I was working in VS code (version 1.84.2) with a remote ssh connection. In the terminal of the ssh machine, I typed `marimo edit remote_script.py` which launched localhost:2718 (the default) in my *local* browser. I edited and saved there, with the "Notebook saved" notification on the bottom right corner popping up often.

I have, at the same time, another VS code window open that is local. When I typed `marimo edit different_script.py` in the terminal (of this local window) where `different_script.py` is a blank script, it launched to localhost:2718 in my local browser again by default, because I meant to but forgot to specify a port. Unfortunately, this action seemed to have overwritten the `remote_scripty.py` in my remote session.

I have tried a few different ways to recover the saving history, including looking at VS code Timeline/local history. The most recent save is my latest commit, ~2 days ago. I am able to see the edit history of my other scripts in the past two days though.

Thank you!

### Version

0.1.43

**Comment by tdiao** [comment]
Hi @akshayka, thanks for the quick and compassionate response. The loss is not huge and I am almost done rebuilding the progress.

Your understanding is correct. I meant to reproduce the error too and will do that as soon as I can. 

From what I recall, launching the tutorials in the same port did not lead to this overwriting issue. Instead, it displayed some error message on the browser page which I don't exactly recall. So it could be the case that this happens only when starting a blank new script. But mostly speculation now; more on that when I can.

**Comment by akshayka** [comment]
Hi @tdiao. We've implemented a fix (in #367) and released it as part of version `0.1.53`. Thanks so much once again for the thorough report!

I'll close this issue for now. But please write back and re-open if you're still running into issues.
