### ISSUE TITLE
Automatically executing cells based on a timer

### ISSUE THREAD

**Issue by anupamsobti** [marimo-team/marimo#365]
### Description

I have a use case for a dashboard where I would like to fetch data through an API and have plots/cards displayed for various parameters, say weather, energy, etc. 

PS: Loving the app! 

### Suggested solution

To implement this, it would be great if for some cells, we could specify a refresh rate so that they automatically get executed after a certain interval, thus updating data on the frontend.

**Comment by akshayka** [comment]
Hi @anupamsobti! Thanks for reaching out.

This is actually possible today, using `mo.ui.refresh`: https://docs.marimo.io/api/inputs/refresh.html#marimo.ui.refresh

The `refresh` element fires at a configurable refresh rate. Any cells that reference the refresh element will automatically run.

Here's a video example:
[refresh.webm](https://github.com/marimo-team/marimo/assets/1994308/2c517b3b-7731-4240-b8ed-6b59c321c98a)

Code:

```python
import marimo

__generated_with = "0.1.53"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    import random
    return mo, random


@app.cell
def __(mo):
    refresh = mo.ui.refresh(default_interval="1s")
    refresh
    return refresh,


@app.cell
def __(mo, random, refresh):
    refresh

    mo.md("#" + "🍃" * random.randint(1, 10))
    return


if __name__ == "__main__":
    app.run()
```

**Comment by anupamsobti** [comment]
That's fantastic! Thanks.
