### ISSUE TITLE
Additional mapping support

### ISSUE THREAD

**Issue by anupamsobti** [marimo-team/marimo#366]
### Description

Hi

I work with geospatial data and find leafmap, geemap, etc. useful. Any integration would help!
There is also a nice demonstrator of different mapping libraries [here](https://huggingface.co/spaces/giswqs/solara-geospatial) for example.

### Suggested solution

Deeper integration with mapping libraries. I personally have been using leafmap.

**Comment by akshayka** [comment]
Thanks for the feature request @anupamsobti! We'll look into this.

Besides `leafmap`, which others do you think are high priority to support?

**Comment by anupamsobti** [comment]
I think leafmap should suffice. It already supports a few mapping backends. So you'll be supporting multiple backends if you support leafmap.

**Comment by akshayka** [comment]
Hi @anupamsobti — version `0.1.60` has some support for `leafmap`. marimo now knows how to render `leafmap.Map` objects. Let us know if deeper integration is needed. Thanks for the feature request!

<img width="809" alt="image" src="https://github.com/marimo-team/marimo/assets/1994308/6d8b9206-0310-49e6-be49-d1075041b252">
