### ISSUE TITLE
password required when logging in

### ISSUE THREAD

**Issue by jetjinser** [marimo-team/marimo#395]
### Description

hi 👋, I just started trying marimo.

I deployed this as a public service on the server, considering that there might be some security risks. I'm hoping to restrict logins in some way.

Not sure if I've missed something, if marimo can do this please point it out.

Thank you for your great work!

### Suggested solution

If a password is set in the configuration, you need to provide the password to enter marimo.

**Comment by akshayka** [comment]
Hi @jetjinser! Thanks for the great suggestion.

marimo doesn't currently support password authentication -- sorry about that! But we can definitely add this to our list of future features.

**Comment by mscolnick** [comment]
@jetjinser  - you should be able to roll this yourself using `marimo.create_asgi_app`.

This example doesn't implement the password protection, but it close. you can likely go off this: https://github.com/marimo-team/marimo/blob/main/marimo/_smoke_tests/custom_server/my_server.py
FastAPI provides some middlewares and utils for sessions to make this even easier. 

Here are some docs: https://docs.marimo.io/guides/deploying/programmatically.html

**Comment by mscolnick** [comment]
Going to re-open this as we plan to add basic-auth support: https://github.com/marimo-team/marimo/pull/1363
