### ISSUE TITLE
Multiselect filter doesn't search consecutively

### ISSUE THREAD

**Issue by delennc** [marimo-team/marimo#457]
### Describe the bug

https://github.com/marimo-team/marimo/assets/29712687/4f9e64b8-f7a3-49ea-87ae-74a235955f5f

Not clear how the filtering works. I would expect it to search by substring, but searching `foo` also returns the result `farboo`.

### Environment

{
  "marimo": "0.1.65",
  "OS": "Darwin",
  "OS Version": "22.6.0",
  "Processor": "arm",
  "Python Version": "3.11.4",
  "Binaries": {
    "Chrome": "120.0.6099.71",
    "Node": "v20.3.1"
  },
  "Requirements": {
    "black": "23.10.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.3.1",
    "tomlkit": "0.12.1",
    "tornado": "6.3.3",
    "typing_extensions": "4.8.0"
  }
}

### Code to reproduce

```
import marimo as mo
multiselect = mo.ui.multiselect(["foo", "farboo"])
multiselect
```

**Comment by mscolnick** [comment]
@delennc, we use a library for this which does fuzzy matching. 

we can override this to lowercase + exact match as that is likely what is expected, and can later add back other filtering kinds when requested.
