### ISSUE TITLE
Control+K on MacOS

### ISSUE THREAD

**Issue by sswatson** [marimo-team/marimo#466]
### Describe the bug

In a marimo notebook in the browser, the key sequence `Control+K` results in the same behavior as `Command+K` on MacOS. Namely, it opens the command palette. This behavior is undesirable because:

1. Control+K is the MacOS keyboard shortcut for deleting the text from the cursor to the end of the line. Some users, like me, use this feature heavily and have a significantly degraded experience if it isn't available.
2. The command palette is already accessible with Command+K, so using Control+K doesn't make the command palette any more accessible.

For these reasons, I would argue that the behavior should be changed so that `Control+K` is not intercepted by the application and `Command+K` retains its current behavior of opening the command palette.

### Environment

`marimo env` threw an error so I can't put the output here, but the behavior mentioned above is completely in the frontend anyway.

**Comment by mscolnick** [comment]
Thanks for the suggestion, I agree. I will remove the `Ctrl` in favor of just the Meta key (`Command+K` on MacOS)
