### ISSUE TITLE
Add package to conda-forge channel

### ISSUE THREAD

**Issue by Episkiliski** [marimo-team/marimo#477]
### Description

Add package to conda-forge channel

### Suggested solution

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by akshayka** [comment]
Thanks! If anyone has experience with conda forge, we'd love help with this issue.

**Comment by akshayka** [comment]
Hi @Episkiliski! Thanks to @mfansler, this is now done.

You can install marimo using `conda install -c conda-forge marimo`.

**Comment by Episkiliski** [comment]
Hi @akshayka @mfansier, unfortunately I'm not able to find marimo in conda-forge channel. See screenshot.
<img width="721" alt="Marimo-conda" src="https://github.com/marimo-team/marimo/assets/53902830/a1a897d1-0159-4884-8ded-88316f4cc80d">

**Comment by mfansler** [comment]
@Episkiliski okay - we need to enable it for **osx-arm64** platform.

**Comment by Episkiliski** [comment]
Sorry about that @mfansler, I did not specify when opening the issue.... and thanks for your work!

**Comment by mfansler** [comment]
Expect it should be available in an hour or so after https://github.com/conda-forge/marimo-feedstock/pull/9 merges.

**Comment by akshayka** [comment]
Thanks @mfansler!
