### ISSUE TITLE
Pyodide kernel support, for serverless operation

### ISSUE THREAD

**Issue by kno10** [marimo-team/marimo#485]
### Description

Pyodide is python compiled into web assembly. This allows running the interpreter in a web worker within the browser.
JupyterLite is a modification that runs the entire jupyter IDE in the browser.
There are some limitations - e.g., file system access / storage is a mess and browser support varies.
Nevertheless, this allows for highly scalable solutions, as there are only static files to be served.

### Suggested solution

Add a pyodide kernel as an alternative to allow serverless operation.

**Comment by akshayka** [comment]
Hi @kno10, thanks for the feature request! A kernel that could be executed in-browser would definitely be very valuable.

It's a somewhat large project, because it would require non-trivial re-architecturing of our library and frontend, but it's definitely on our radar.

**Comment by akshayka** [comment]
Closing as completed: https://docs.marimo.io/guides/wasm.html
