### ISSUE TITLE
🙋 Have feedback? Get in touch!

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#503]
Hi! 👋 Thanks for your interest in marimo. We're excited you're here as we discover and build the future of Python notebooks — made for humans like **you**.

**We want to hear from you**: from minor bug reports or usability issues, to your most hoped-for wishlist features, and everything in between. Here are some ways you can get in touch:

1. 🔨 _Bug reports/feature requests_: Open a [Github issue](https://github.com/marimo-team/marimo/issues).
2. 🙋 _Help and free-flowing conversation_: Hop into [our Discord](https://discord.gg/JE7nhX6mD8) and chat with us in real-time.

**Comment by akshayka** [comment]
## Our roadmap

🚗 We have lots we plan to build! Some of our plans are sketched in a [public roamdap document](https://www.notion.so/marimo-team/The-marimo-roadmap-e5460b9f203e4adeae633523fce87a35).

Have an idea that you'd like to see there? [Let us know](https://discord.gg/JE7nhX6mD8)!

**Comment by akshayka** [comment]
> @akshayka FYI the roadmap does not seem to be public, as your link just redirects me to a login page.

Oops! Thanks for letting me know @jonas-w. I've fixed the link.

**Comment by misolietavec** [comment]
Hi, developers,
the version 0.1.82 (migration to `starlette`) is highly unstable on my system (Debian 12, kernel 5.19.0). Nearly all the time there are issues with saving notebook (page freeze) and often `Waiting for localhost` in browser. I will rather stick with 0.1.81 for now.

**Comment by akshayka** [comment]
> Hi, developers, the version 0.1.82 (migration to `starlette`) is highly unstable on my system (Debian 12, kernel 5.19.0). Nearly all the time there are issues with saving notebook (page freeze) and often `Waiting for localhost` in browser. I will rather stick with 0.1.81 for now.

Thanks for letting us know. We hit the same issues and yanked `0.1.82` from PyPI. The issue you saw should now be fixed in the latest version of marimo.

**Comment by misolietavec** [comment]
@akshayka  Installed 0.1.87 just now, seems to work without above-mentioned issues. I see,  you added --host to CLI, will try tomorrow.  Thanks for rapid response and also rapid development.

**Comment by skfrost19** [comment]
#feature_request I would love to see dark mode and also the indentation block highlight (it's a little bit tough to see indentation in the white background)

**Comment by fuenfundachtzig** [comment]
First of all, thanks for the great work on marimo!

I noticed a few inconveniences:
* When there is a bad symbolic link in a directory, [this line][1] will lead to an "Internal Server Error". ("Bad" can either be a recursive link (`ln -s broken`) or a link pointing to a non-existing file (`ln -s broken notthere`).)
* Saving will allow filenames such as "." ".." to be used as regular filenames.

[1]: https://github.com/marimo-team/marimo/blob/413bc9dbb20aa7be86b6cf661606134583ae5e6b/marimo/_server/files/os_file_system.py#L46

**Comment by akshayka** [comment]
I'm closing this issue — if you have feedback, please get in touch!

🔨 Bug reports/feature requests: Open a [Github issue](https://github.com/marimo-team/marimo/issues).
🙋 Help, free-flowing conversation: Hop into [our Discord](https://discord.gg/JE7nhX6mD8) and chat with us in real-time.
