### ISSUE TITLE
Feature Request: Add option to increase/decrease font size of Marimo Editor

### ISSUE THREAD

**Issue by sethbassetti** [marimo-team/marimo#534]
### Description

A slight improvement to the marimo editor interface (which I do love the UI of), would be to add the ability to increase or decrease the font size of code in the cells. Currently the only option is zooming in on the webpage, which isn't ideal.

### Suggested solution

Suggested solution is to add an option to customize the font size of the code in the editor.

**Comment by akshayka** [comment]
Thanks for the feature request, @sethbassetti! It's a very reasonable one. We'll try to get to it soon; added to our [roadmap](https://marimo-team.notion.site/The-marimo-roadmap-e5460b9f203e4adeae633523fce87a35?pvs=4).

**Comment by akshayka** [comment]
@sethbassetti , we just released version 0.1.75, which lets you edit the font size. Thanks for the suggestion!

<img width="332" alt="image" src="https://github.com/marimo-team/marimo/assets/1994308/33a2be96-bb7d-4dd7-b263-4cbee88eea3e">
