### ISSUE TITLE
Convert process can encounter decoding errors

### ISSUE THREAD

**Issue by Nouser** [marimo-team/marimo#540]
## Situation
I attempted to convert a Jupyter notebook that I made in Pycharm on Windows. The file has UTF-8 encoding. When I ran `marimo convert XXXXX.ipyby > marimoNotebook.py`, I hit a unicode decode error.

```
  File "********\venv\Lib\site-packages\marimo\_cli\cli.py", line 413, in convert
    print(ipynb_to_marimo.convert_from_path(ipynb))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "********\venv\Lib\site-packages\marimo\_cli\ipynb_to_marimo.py", line 22, in convert_from_path
    notebook = json.loads(f.read())
                          ^^^^^^^^
  File "********\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2273: character maps to <undefined>
```

## Solution?
https://github.com/marimo-team/marimo/blob/b52420ba5259ea9f5de37ef04dd606a43054f7b4/marimo/_cli/ipynb_to_marimo.py#L21

I traced it back to this line and was able to locally fix it by changing it to 

```with open(ipynb_path, "r", encoding="utf-8") as f:```

I'm not sure what the right solution is for making this support more platforms and encoding structures. From my understanding, without the encoding supplied in-line it uses the OS default. Maybe there's a solution that lets us override that, either manually with params or automatically with some analysis of the file.

**Comment by akshayka** [comment]
Thanks so much for the bug report! We'll look into it Or if you'd like, you're welcome to make a PR :) Happy to talk through and brainstorm solutions — will return to this soon
