### ISSUE TITLE
Cell execution interrupted when browser closed

### ISSUE THREAD

**Issue by twrightsman** [marimo-team/marimo#541]
### Description

I couldn't find any issue already raised about this, but it would be great if cells could continue execution on the server when the browser is closed or the internet connection is interrupted. This is a long-standing issue of Jupyter as well, with lots of recent progress being made (https://github.com/jupyterlab/jupyterlab/issues/2833).

I tested it with a simple loop and sleep, and saw that marimo currently re-runs everything when the page is refreshed.

### Suggested solution

The ideal solution seems to be decoupling the notebook execution state from the web client, if it isn't already.

### Additional context

This issue mostly comes into play with long-running cells, which I realize marimo suggests to [avoid with caching](https://docs.marimo.io/guides/best_practices.html), but it also comes up in areas where the internet connection is intermittent.

**Comment by akshayka** [comment]
Thanks for the feature request; I totally see the value. We'll put it on our roadmap.

**Comment by twrightsman** [comment]
If I can use similar workarounds in marimo that I do in Jupyter then this is only mildly painful. What I do in Jupyter is something like this:

```python
IS_NOTEBOOK = ('get_ipython' in locals()) and (get_ipython().__class__.__name__ == 'ZMQInteractiveShell')

data = load()
if IS_NOTEBOOK:
  data = data.downsample(frac = 0.01)
```

This let's me iterate quickly towards a working script, which is synced to a Python file with Jupytext that I can then let run for a long time. Marimo lets me skip the Jupytext step, which is nice.

Something that would be very painful is if marimo indeed re-runs the entire notebook when the page is refreshed, since I often come back to notebooks that have some expensive cached state. Definitely not a great practice, but saves time until I can come back and reduce expensive cells in the notebook :slightly_smiling_face:
