### ISSUE TITLE
Feature Request: Unpublish HTML

### ISSUE THREAD

**Issue by gutenye** [marimo-team/marimo#545]
### Description

After you publish the notebook as HTML, there should have an option to unpublish it.

### Suggested solution

Add option to unpublish it.an

**Comment by akshayka** [comment]
Thanks for the feature request, very sensible. In the meantime, if you need something unpublished you can contact me at akshay@marimo.io.

**Comment by mscolnick** [comment]
Going to close this as folks can use the community cloud (with publish/delete): https://marimo.io/sign-up
