### ISSUE TITLE
System theme for dark/light mode

### ISSUE THREAD

**Issue by pavelzw** [marimo-team/marimo#547]
### Description

It would be nice to have an automatic dark mode setting.
The [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature can tell you whether your system wants to be dark or light.

### Suggested solution

https://tailwindcss.com has a nice solution imo. They have a toggle between Light, Dark and System and store the selected value in the browser localstorage.

https://github.com/marimo-team/marimo/assets/29506042/5dfda14c-d4cc-4a90-913b-520e3f625f07

**Comment by mscolnick** [comment]
You can currently set your theme to light/dark in the dropdown in the top right. 

We can add an option for `system`, but to be more similar to other traditional IDEs, we may instead want to add different colors schemes (beyond light/dark, e.g. solarized, monokai)
