### ISSUE TITLE
Virtualize mo.ui.multiselect to handle large lists

### ISSUE THREAD

**Issue by mscolnick** [marimo-team/marimo#588]
### Description

Using `mo.ui.multiselect` with > 10,000 items can be laggy. This can happen if filtering on something with high-cardinality. 

### Suggested solution

We should virtualize lists (either by default, or past a certain number e.b. 1000)

We should use this library https://github.com/TanStack/virtual

### Additional context

```python
import marimo

__generated_with = "0.1.77"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    large_list = [str(i) for i in range(10000)]
    mo.ui.multiselect(large_list, label="Large List")
    return large_list,


if __name__ == "__main__":
    app.run()
```

**Comment by aashirisrar** [comment]
@mscolnick will this be the workaround:

import marimo
from virtual import ListModel

__generated_with = "0.1.77"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    large_list = [str(i) for i in range(10000)]
    
    # Wrap the large list with ListModel from the virtual library
    virtual_list = ListModel(large_list)
    
    mo.ui.multiselect(virtual_list, label="Large List")
    
    return virtual_list,


if __name__ == "__main__":
    app.run()

**Comment by mscolnick** [comment]
@aashirisrar, I'd imagine there would be no backend change and this feature would be implemented on the frontend only. 

Loading large lists (~10,000) to the frontend is not the non-performant part (although to a limit, it will be), but rather rendering those large lists. 
The solution would be leveraging https://github.com/TanStack/virtual in some of the components.

For much larger items (+100,000), this can be achieved with a search (`mo.ui.text()`) and filtering in Python.

**Comment by wasimsandhu** [comment]
Grabbing this one today

**Comment by mscolnick** [comment]
Closed by https://github.com/marimo-team/marimo/pull/1654
