### ISSUE TITLE
Implement multifile support in both edit and run mode.

### ISSUE THREAD

**Issue by anilgulecha** [marimo-team/marimo#601]
### Description

I'd like to host multiple notebooks (and hence apps) via a single marimo command. This opens up multiple usecases for end users.

Eg:
`marimo edit file1.py file2.py file3.py`
In the view - There's a dropdown at the top to activate one of the 3.

Similarly:
`marimo run file1.py file2.py file3.py`
In the view - i switch over b/w the 3 as needed.

This allows lightweight selection of apps to be hosted via a single instance on production.

### Suggested solution

A user flow of solution is suggested in description above.

**Comment by akshayka** [comment]
Thanks for the feature request, and the suggested user flow. This is something several people have asked for, so we are thinking about it. I've added it as an item to our [roadmap](https://marimo-team.notion.site/The-marimo-roadmap-e5460b9f203e4adeae633523fce87a35).
