### ISSUE TITLE
mo.ui.slider: show value on hover

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#626]
### Description

When hovering over a location in the slider (not necessarily the knob), it would be helpful to know what value would be selected on click. 

### Suggested solution

Show the value as a tooltip on hover. Potentially make this configurable in the Python API.

**Comment by abant07** [comment]
Hi can I work this as well. Is there anything I should know while reproducing the environment or the ReadMe is good enough?

Thanks!
Amogh

**Comment by ericjanto** [comment]
@abant07 are you still actively working on this? Might otherwise have a look myself.

**Comment by abant07** [comment]
No sorry, go ahead and take it over

**Comment by mscolnick** [comment]
@abant07 - let us know if you need any help getting started

**Comment by ericjanto** [comment]
@mscolnick Thank you for offering help getting started. I'm having a look at this right now but I'm not sure my development setup is correct. I tried to make a few changes (e.g. add a classname) to the `RangeSlider` component in `range-slider.tsx` but I can't see them in the front-end.

I run `marimo edit --no-token --headless notebook.py` and `pnpm dev` and open the localhost associated with the Vite dev server in my browser. Anything I might be missing?

**Comment by mscolnick** [comment]
Which URL are you visiting when you run those commands? `http://localhost:3000/`?

You _may_ need to refresh after changing some classnames since if its a new classname, it may not exist on the shadow dom (which each component is)

**Comment by ericjanto** [comment]
Yes, I'm visiting the :3000 URL and I also tried refreshing the page. Very peculiar.

I added a console.log statement and it appeared, so I might just go ahead anyway.

**Comment by ericjanto** [comment]
@mscolnick Realistically I won't be able to work on this in the near future–I'm currently busy with a relocation process. If anyone else wants to work on this, it's free for grabs!

**Comment by bookofbash** [comment]
@akshayka @ericjanto I wanted to get a look at what this is referring to and found this 
![image](https://github.com/user-attachments/assets/020a834f-d02b-4488-861d-18e4eae72e3d)

Am I correct in assuming that this issue can be closed?
