### ISSUE TITLE
mo.ui.slider: full width option

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#627]
### Description

Add an option to render the slider as full width.

### Suggested solution

add a `full_width` keyword argument to `mo.ui.slider`, defaulting to `False`

**Comment by abant07** [comment]
Hi can I work on this, I am new to github, but I was interested in this repo. Also, is there anything that I should know while reproducing the environment, or is the ReadMe good enough to follow?

Thanks!
Amogh
