### ISSUE TITLE
keyboard shortcuts for buttons

### ISSUE THREAD

**Issue by mscolnick** [marimo-team/marimo#633]
### Discussed in https://github.com/marimo-team/marimo/discussions/612

<div type='discussions-op-text'>

<sup>Originally posted by **tfriedel** January 20, 2024</sup>
I quite liked the example for data labeling. 
There are buttons to go to the next or previous image. It would be nice to attach keyboard shortcuts to buttons so such a tool could be used without a mouse.</div>

**Comment by rithik56** [comment]
Hi @mscolnick , can I work on this issue ?

**Comment by mscolnick** [comment]
@rithik56, that would be awesome! Feel free to ping me on Discord if you need any help getting set up

**Comment by rithik56** [comment]
Sure @mscolnick

**Comment by Light2Dark** [comment]
hi @mscolnick, I'd like to help with this. My thoughts so far:

- add a `keyboard_shortcut` parameter in Python, so users can call button(keyboard_shortcut='Ctrl+G')
- add a `keyboardShortcut` prop for ButtonProps in JSX
- if keyboardShortcut is present, add a document event listener for keydown which will trigger the button click
- render the button with the shortcut, so the button will look something like 
![Image](https://github.com/user-attachments/assets/162e923d-1d6a-4111-b0fb-27a3fb4cd888)
Still thinking about the design but yeah.

What do you think? This makes the keyboard shortcut a global listener which I think is the intended effect.

I'm aware of the custom hooks for hotkeys, still checking it out.

**Comment by mscolnick** [comment]
@Light2Dark that would be great! And what you laid out makes sense. 

Rather than modifying the label, could we default tooltip to be the keyboard shortcut if the tooltip is null. If the user wants to add the shortcut to the label, they can do that themselves manually. Thoughts?

**Comment by Light2Dark** [comment]
great idea, and we can always change it after getting wider feedback.
