### ISSUE TITLE
Marimo cannot load my package (TypeError: decode() argument 'encoding' must be str, not None)

### ISSUE THREAD

**Issue by lborcard** [marimo-team/marimo#634]
### Describe the bug

First time marimo user here, I love your product. I am using the module pymc and I was trying to load the module installed with pip install pymc. But I am getting the  following error:
`ìmport pymc as pm`
`TypeError: decode() argument 'encoding' must be str, not None`

### Environment

{
  "marimo": "0.1.80",
  "OS": "Linux",
  "OS Version": "4.18.0-477.21.1.el8_8.x86_64",
  "Processor": "x86_64",
  "Python Version": "3.11.2",
  "Binaries": {
    "Chrome": "--",
    "Node": "--"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "tomlkit": "0.12.3",
    "tornado": "6.4",
    "typing_extensions": "4.9.0"
  }
}

### Code to reproduce

import pymc as pm

**Comment by akshayka** [comment]
We just released 0.1.81, which includes a fix for this issue. Please reopen if it comes up again. Thanks!

**Comment by lborcard** [comment]
Thank you for the quick fix. Interestingly, I was not able to use pymc along with Marimo in the same conda env. It caused a compilation problem when running pymc. Do you know if it related?
