### ISSUE TITLE
Embedded PDF viewer

### ISSUE THREAD

**Issue by handrew** [marimo-team/marimo#64]
### Description

Would love a `marimo.ui` component which allows me to embed PDFs in a Marimo notebook, and ideally allows me to determine which part of the PDF to start at.

### Suggested solution

Open to what you guys come up with. 

### Alternative

Have considered just printing plain text.

### Additional context

Context is that I am building an LLM-enabled information retrieval app.

**Comment by daviddai-evenup** [comment]
@akshayka I'm unable to render local pdfs (see screenshot below), but it works fine when using a web URL. Interestingly I'm able to render local images, so it doesn't seem to be a file access issue. Do you know what might be causing this?

<img width="696" alt="Image" src="https://github.com/user-attachments/assets/de115bcf-dcf5-4917-963e-fb3b7edf122d" />

**Comment by akshayka** [comment]
This function doesn't support local filepaths. You have to pass it an open file. See the code example in the thread above
