### ISSUE TITLE
Individual on_change are lost in an array

### ISSUE THREAD

**Issue by meghprkh** [marimo-team/marimo#647]
### Describe the bug

I should be able to create a few say checkboxes with on_change and be able to show them in an array, but the on_change gets lost. I know that `mo.ui.array` exists but this is a simplified example.

In the following image you can see that change_printer was only called twice instead of thrice as x was toggled on, x was toggled off and then y\\\[1\\\] was toggled on

![image](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/08a5f091-c535-42dc-be5d-ee6abf7698b6/955fb97c-2c31-4bc4-b025-d2163d9e123c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS8wOGE1ZjA5MS1jNTM1LTQyZGMtYmU1ZC1lZTZhYmY3Njk4YjYvOTU1ZmI5N2MtMmMzMS00YmM0LWIwMjUtZDIxNjNkOWUxMjNjIiwiaWF0IjoxNzA2MTIzNjkxLCJleHAiOjMzMjc2NjgzNjkxfQ.DLlSclPKNQXfOgKC7KnTeUC1w5tkBD-PZtrA_ad7-1Y)

### Environment

```
{
    "marimo": "0.1.78",
    "OS": "Linux",
    "OS Version": "5.15.133.1-microsoft-standard-WSL2",
    "Processor": "x86_64",
    "Python Version": "3.12.1",
    "Binaries": {
        "Chrome": "--",
        "Node": "v21.1.0"
    },
    "Requirements": {
        "black": "23.12.1",
        "click": "8.1.7",
        "jedi": "0.19.1",
        "pymdown-extensions": "10.7",
        "tomlkit": "0.12.3",
        "tornado": "6.4",
        "typing_extensions": "4.9.0"
    }
}
```

### Code to reproduce

```
import marimo
  
__generated_with = "0.1.78"
app = marimo.App()
  
  
@app.cell
def __():
                import marimo as mo
                return mo,
  
  
@app.cell
def __():
                mylen = 5
                return mylen,
  
  
@app.cell
def __():
                def change_printer(v):
                                print("changed ", v)
                return change_printer,
  
  
@app.cell
def __(change_printer, mo):
                x = mo.ui.checkbox(False, on_change=change_printer)
                x
                return x,
  
  
@app.cell
def __(change_printer, mo, mylen):
                y = [mo.ui.checkbox(False, on_change=change_printer) for i in range(mylen)]
                y
                return y,
  
  
if __name__ == "__main__":
                app.run()
```

**Comment by akshayka** [comment]
Hi! Thanks for trying marimo and reporting this issue.

This is part of the contract of reactivity today -- for interactions to have any effect, the UI element must be assigned to a global variable (see [the docs](https://docs.marimo.io/guides/interactivity.html#how-interactions-run-cells)). Even if we managed to register the `on_change`, you wouldn't have true reactivity through `y`, since it's not a UI element and its members are not bound to any variables.

That said, I can see why being able to embed dynamically created UI elements in any output would be helpful in creating rich UIs. It's an enhancement that has been requested many times, so we are looking into how to support this, for example through lensing on `ui.array/ui.dictionary` (i.e., by accessing their members).

**Comment by meghprkh** [comment]
Thanks, while I dont understand the internals of marimo it would be really good if we can use `on_change` especially for updating a `mo.state` somewhere and accessing it in another place should retrigger the access.

**Comment by akshayka** [comment]
> Thanks, while I dont understand the internals of marimo it would be really good if we can use `on_change` especially for updating a `mo.state` somewhere and accessing it in another place should retrigger the access.

Yep, something like this is coming soon. I'll write back when it's ready.

**Comment by akshayka** [comment]
@meghprkh , in the latest release, you can accomplish what you're trying to do here, with one change. The elements do need to be created in `mo.ui.array` first to be registered with `marimo`, which needs to be assigned to a global variable. But then you can then pull them out of the array and use them in other places: the `on_change` handlers will get called (and the array's value will also be updated). Here's an example:

https://static.marimo.app/static/lens-example-k7ib

```python
import marimo

__generated_with = "0.1.88"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __():
    def change_printer(v):
        print("changed ", v)
    return change_printer,


@app.cell
def __(change_printer, mo, n_checkboxes):
    # First create your dynamic set of UI elements
    checkboxes = mo.ui.array(
        [
            mo.ui.checkbox(False, on_change=change_printer)
            for i in range(n_checkboxes.value)
        ]
    )
    return checkboxes,


@app.cell
def __(mo):
    n_checkboxes = mo.ui.slider(3, 10, label="number of checkboxes")
    n_checkboxes
    return n_checkboxes,


@app.cell
def __(checkboxes):
    python_list = [checkbox for checkbox in checkboxes]
    python_list
    return python_list,


@app.cell
def __(checkboxes, mo):
    mo.md(f"Here's the first checkbox: {checkboxes[0]}")
    return


@app.cell
def __(checkboxes):
    checkboxes.value
    return


if __name__ == "__main__":
    app.run()
```

**Comment by mrdobalina2k** [comment]
It seems this issue is still there. I tried the proposed solution, which works well for simple components, but for forms I cannot get it to work:

```
import marimo

__generated_with = "0.3.10"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __(mo):
    get_state1, set_state1 = mo.state(None)
    get_state2, set_state2 = mo.state(None)
    get_state3, set_state3 = mo.state(None)
    return (
        get_state1,
        get_state2,
        get_state3,
        set_state1,
        set_state2,
        set_state3,
    )


@app.cell
def __(mo):
    def new_form(form_name: str, on_change):
        form_ = mo.md("""
        Form 

        {field}

        """).batch(
            field=mo.ui.text("input")
        ).form(
            on_change=on_change
        )

        return form_
    return new_form,


@app.cell
def __(new_form, set_state1):
    set_state1("state 1 not set")
    def on_change_callback_works(*args):
        set_state1("state 1 set")

    new_form_ = new_form("test", on_change=on_change_callback_works)
    new_form_
    return new_form_, on_change_callback_works


@app.cell
def __(get_state1):
    print(get_state1())
    return


@app.cell
def __(new_form, set_state2):
    set_state2("state 2 not set")
    def on_change_callback_doesnt_work(*args):
        set_state2("state2 set")

    new_form("test2", on_change=on_change_callback_doesnt_work)
    return on_change_callback_doesnt_work,


@app.cell
def __(get_state2):
    print(get_state2())
    return


@app.cell
def __(mo, new_form, set_state, set_state3):
    # Following https://docs.marimo.io/recipes.html#create-a-table-column-of-buttons-with-on-change-handlers

    set_state3("state3 not set")
    def on_change_callback_doesnt_work_too(*args):
        set_state("state3 set")

    arr = mo.ui.array([new_form("test3", on_change=on_change_callback_doesnt_work_too)])
    return arr, on_change_callback_doesnt_work_too


@app.cell
def __(arr):
    arr[0]
    return


@app.cell
def __(get_state3):
    print(get_state3())
    return


if __name__ == "__main__":
    app.run()


Only the first method, where the form is declared as a global variable, works. This is unfortunate, since it makes dynamic components difficult to work with.

**Comment by akshayka** [comment]
Closing this issue -- the original issue has been solved, and the new issue related to forms is documented in #1131
