### ISSUE TITLE
traceback error doesn't  indicate which cell and line error occurs

### ISSUE THREAD

**Issue by themissingCRAM** [marimo-team/marimo#649]
### Describe the bug

marimo traceback error doesn't  indicate which cell and line error occurs. Not sure what is happening or if I made a mistake that caused this. I experience this after updating marimo.  
Example:  

```
Traceback (most recent call last):

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_hand_over_face_check_frame_by_frame.csv'
```

This example is not the best as it is easier to find where it happens but there are instances of errors that is harder to spot on the code.
### Environment

`{
  "marimo": "0.1.81",
  "OS": "Linux",
  "OS Version": "5.15.133.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.9.18",
  "Binaries": {
    "Chrome": "--",
    "Node": "--"
  },
  "Requirements": {
    "black": "23.11.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "tomlkit": "0.12.3",
    "tornado": "6.3.3",
    "typing_extensions": "4.7.1"
  }
}`  
  
This is on WSL2

**Comment by akshayka** [comment]
@themissingCRAM, thanks for reporting. It looks like we introduced this in version 0.1.79, when we added support for PDB. Sorry about that! I'll look into this.
