### ISSUE TITLE
Getting started issues

### ISSUE THREAD

**Issue by stantonius** [marimo-team/marimo#656]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

Hey team

Love this idea. The project has tonnes of potential. Thanks for all your work!

As a brand new user, I really struggled to get started with the given documentation - I almost gave up on trying the project. Could be user error, but unfortunately the docs should probably be written for the slowest common denominator (eg. me). 

The problem for me, boiled down to one thought, is I came to use Marimo as a Jupyter notebook replacement (what is advertised), but most of the getting started guides focus on the Marimo _library_ and not how to get started with basic code on running a notebook locally.

For context, I am trying to run Marimo in a VSCode `.py` file.

| What I tried | Outcome | Solution? |
| ------------ | ----------| ------------|
| Creating a `.py` file and pasting the code from the `Guides > Overview` into a `.py` file | This was library code so nothing happened | Clearer distinction when we should be using the library code vs the app code |
| Running the tutorial notebooks | Showed the potential of Marimo, but unclear where the raw code was to run in my own VScode `.py` file | Mention _early_ on the `Copy code to clipboard` button (which I only found later on) to replicate the tutorial code locally in your `.py` file |
| Following the recipes section | my expectation was it would show me recipes for running as an app, but again this was focused on library code | Recipes for running a notebook locally? |
| Using the VSCode extension | Still unsure how it even works? | Clearer docs on how to start the server with the plugin. Right now, the only thing I've been able to figure out is how to run the app in a browser (via the `marimo run file.py` command) |

I'm sure I am missing other things, but you probably get the idea.

Hopefully this is helpful - but if I have completely misunderstood anything do let me know. I want this project to succeed so I thought this might be helpful feedback.

### Your Suggestion for Changes

Ultimately to me, there is not a clear enough distinction between the library and running as an app (especially since this is "advertised" as a Jupyter replacement). It might be helpful to, on the Getting Started/Home page, to have a section like:

## Library vs App

If you are looking to replicate a Jupyter notebook-type experience, then follow [example of an app setup]. If you want to use the library on its own, then [heres an example] (maybe also include *when* you would need just the library, as this isn't clear to me?)

## Run an App Locally in VSCode

```python
import marimo

__generated_with = "0.1.82"
app = marimo.App()


@app.cell
def __(mo):
    mo.md("Hello Marimo")
    return
```

Save the file, then run:
a) in the browser by running `marimo run file.py`
b) in VSCode extension by (however this works, its not clear to me)

**Comment by akshayka** [comment]
@stantonius, thanks so much for taking the time to write such detailed feedback. Sorry to hear that the tutorials and guides were confusing! We definitely want to get users of all skill levels up and running as fast as possible, and we're sorry that getting up to speed was frustrating for you.

> Mention early on the Copy code to clipboard button (which I only found later on) to replicate the tutorial code locally in your .py file

That's a fantastic idea. Thank you!

Regarding marimo the notebook/app runner vs marimo the library: the `Getting Started` guide focuses on the former, and the rest of the docs focus on the latter. We can make that clearer in our documentation. You're right that the only time one would use the marimo library is within the marimo notebook.

We can also improve the docs for our VSCode plugin.

If you wouldn't mind, I would appreciate some more feedback on the [`Getting Started` page]( https://docs.marimo.io/getting_started/). It sounds like it wasn't clear enough to you -- could you help explain what you found confusing about it, and what else you would like to see there?

- It shows how to create new notebooks and how to work with existing notebooks, ie how to use marimo as a Jupyter replacement: https://docs.marimo.io/getting_started/index.html#notebooks.
- It also shows how to run notebooks as apps, here: https://docs.marimo.io/getting_started/index.html#apps

**Comment by stantonius** [comment]
<strike>
> It shows how to create new notebooks and how to work with existing notebooks, ie how to use marimo as a Jupyter replacement: https://docs.marimo.io/getting_started/index.html#notebooks.

Yep but for me I didn't know *what* to put in this `your_notebook.py`. Having never worked with this before, it might be helpful to say:

Create a file called `your_notebook.py`, add this simple code - this is a simple App. 
```python
import marimo

__generated_with = "0.1.82"
app = marimo.App()


@app.cell
def __(mo):
    mo.md("Where does this update?")
    return
```
Now run `marimo edit your_notebook.py` to see the notebook live in your browser. You can now add new cells and watch your code in `your_notebook.py` magically update.

Note that `marimo edit`

> It also shows how to run notebooks as apps, here: https://docs.marimo.io/getting_started/index.html#apps

Yes but at this point I still don't know what an app is (nor what the code is supposed to look like). However with the additional text above for point 1, then it might be easier to follow.
</strike>

**Wait!**

My comments above might be irrelevant. I just ran the `marimo edit` task and realized that I needed to hit `Tab` to have the `import marimo as mo` text appear, **which then updates my python file**.  I didn't pick up on the fact that the code **appears** in my python file when I run the cell that contains `import marimo as mo`. I looked at the example notebooks and saw the generated code, and I looked in my `.py` file and didn't see anything, so it had not clicked that I had to run that python command in the first cell. I also didn't clue in that we don't really have to touch the `.py` file - we do all of the coding in the notebook.

I know it seems obvious now that I say it, but it did trip me up.

I think this:
> You're right that the only time one would use the marimo library is within the marimo notebook.

would be helpful to mention to a new user that you must run this as a first cell in the notebook, and you will see the code generated in your python file. That is the missing link for me that *might* need to be clearer?

Or maybe the first cell in a new notebook should have some text like "Run the cell below and see the app code generate in your python file. You only need to update the code in this notebook, and Marimo updates the state of the python file automatically"

Hoping this is helpful. It seems like I might be rare in having had this issue - but if I did, then others might too.

**Comment by akshayka** [comment]
Thanks for taking the time to write back!

> I also didn't clue in that we don't really have to touch the .py file - we do all of the coding in the notebook.

You know, that's the second time I've heard that. It seems like it could help to have a sentence in "Getting Started" that makes this explicit -- many people have not worked with auto-generated Python files before. Totally get the confusion.

> would be helpful to mention to a new user that you must run this as a first cell in the notebook, and you will see the code generated in your python file. That is the missing link for me that might need to be clearer?

Yes, precisely! Thanks for the suggestion.

I'll keep this issue open until I get around to updating the docs. In the meantime please do let me know if you run into other issues. Hope you have fun trying marimo!
