### ISSUE TITLE
In vim mode allow j/k to move between cells like up/down

### ISSUE THREAD

**Issue by peterwilton-ttam** [marimo-team/marimo#658]
### Description

Using the vim keymap in normal mode, I'd like to be able to navigate between the current cell and the adjacent cells with j/k when I reach the bottom/top of the cell. This seems to be how up/down is set up in the normal keymap, so it seems like it should be possible with the vim keymap.

I'm coming from Jupyter, and Jupyter's various vim keybinding plugins have always supported this, so it's been a small hurdle as I get used to Marimo.

### Suggested solution

If possible, mirror the code that allows this to happen with up/down.

Also, IMO it would be nice if, for both j/k and up/down, navigating between cells with j/k/up/down either consistently moves the cursor to be beginning of the line in the destination cell or to the same column as in the source cell. Right now (with up/down), it moves to the column last used in the destination cell, which is often the last or first column because up/down moves to the beginning/end of the line before moving between cells. If possible I'd remove this behavior too and just have up/down/j/k move to the next cell rather than the end of the line. vim never moves to the end/beginning of the line with j/k.

### Alternative

The current keybindings of cmd+shift+j/k works well enough after some muscle memory adjustment, but I think allowing j/k to move between cells would make it a bit more fluid.

### Additional context

I'm loving Marimo so far. Thanks!

**Comment by akshayka** [comment]
Hi, thanks for the detailed feedback! As a vim user myself I'd also like this. We'll add it to our task list.

**Comment by mscolnick** [comment]
@peterwilton-ttam, thanks for the detailed write-up. We've made changes in #667 to fix this. The new behavior will be:

* Allows `j/k` to focus below/above when at the last line (and also works when the code is hidden)
* When you are at the last line and not the last character, Vim will automatically move you to the last character. This is the default in the [Vim extension](https://github.com/replit/codemirror-vim) we are using and the same behavior in https://colab.research.google.com/ - we can consider changing this in another PR
* When moving below we place the cursor at the first line, first character of the destination cell
* When moving above we place the cursor at the last line, first character of the destination cell

This feels the best to me. Let me know if you have strong opinions against this.

**Comment by peterwilton-ttam** [comment]
That seems great. Thanks so much for the quick response and changes!

Regarding these specifics:

> - When moving below we place the cursor at the first line, first character of the destination cell
> - When moving above we place the cursor at the last line, first character of the destination cell

I think that's a good solution. It's predictable and no inconvenience.
