### ISSUE TITLE
No updates in marimo 0.1.83

### ISSUE THREAD

**Issue by christianw** [marimo-team/marimo#665]
### Describe the bug

Fresh install on Ubuntu 22.04 in *venv*, after calling `marimo tutorial intro` the first slider works, the second does not. As soon as I access the second slider, the first also stops working.

`reactive_plots.py` also not working as expected (updates once, then only sporadically).

Tried different browsers without success.

### Environment

{
  "marimo": "0.1.83",
  "OS": "Linux",
  "OS Version": "5.15.133.1-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Chrome": "--",
    "Node": "--"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.0"
  }
}

### Code to reproduce

marimo tutorial intro

**Comment by christianw** [comment]
Everything works in 0.1.81, so probably related to Starlette, ASGI etc.

**Comment by mscolnick** [comment]
Thanks for pointing this out - @akshayka just hit this yesterday too. I cannot reproduce it on a Mac (if anyone can, please let me know), so we think its a Linux issue. We are investigating today.

**Comment by akshayka** [comment]
We hope to have a fix soon -- in the meantime, we've yanked versions `0.1.82` and `0.1.83` from PyPI.

**Comment by akshayka** [comment]
@christianw -- we just released `0.1.84` on PyPI. I believe it fixes the problem -- it does at least for me (Ubuntu 22.04).

Do you mind upgrading and reporting back whether the issue is fixed on your end?

**Comment by christianw** [comment]
Excellent, works perfectly for now. Thanks for the quick fix. 

BTW, I am working on an article about marimo for a German computer magazine right now.

**Comment by akshayka** [comment]
> Excellent, works perfectly for now. Thanks for the quick fix.
> 
> BTW, I am working on an article about marimo for a German computer magazine right now.

Awesome! If you want to chat with us for the article, feel free to reach out!
