### ISSUE TITLE
Describe how to run on a cloud server so one can accept connections on 0.0.0.0

### ISSUE THREAD

**Issue by truedat101** [marimo-team/marimo#676]
### Documentation is

- [X] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

The documentation says in the FAQ: https://docs.marimo.io/faq.html#faq-remote

there is a way to run the server on a remote host.  The suggested instructions say to run with the --headless flag.  However, this is only part of the solution.  If I don't want to tunnel over SSH, and I just want it serving and accepting connections not on localhost but on 0.0.0.0, how do I specify accept connections from any IP adcress?

### Your Suggestion for Changes

Please describe how to set up the system on a typical cloud provider, setting up ports to open, and how to configure for remote access.  In reality, we need more complete instructions on security best practices along with the details to set up on an AWS or some cloud server.

**Comment by mscolnick** [comment]
hi @truedat101, we are just adding this now via https://github.com/marimo-team/marimo/pull/674. you will be able to pass `--host` to the CLI for `marimo run` or `marimo edit`. 

We will update the documentation too in a follow-up.

**Comment by truedat101** [comment]
@mscolnick excellent, thanks for the response.

**Comment by akshayka** [comment]
Version `0.1.87` is now released, which lets you specify the host via `--host`.

**Comment by truedat101** [comment]
Thanks, will verify when I get back on my server.
