### ISSUE TITLE
import of a local module is running endlessly

### ISSUE THREAD

**Issue by eugeniemarescaux** [marimo-team/marimo#684]
### Describe the bug

I tried to import a class from a local python file, that I will call `my-module`.

```
import sys
sys.path.insert(0,absolute-path-of-the-directory-of-my-module)
import my-module
```

This leaded to the cell running endlessly (I stopped it after 15minutes via shutdown), with the buttons to interrupt the run not working.

### Environment

{
  "marimo": "0.1.86",
  "OS": "Linux",
  "OS Version": "6.2.0-36-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Chrome": "120.0.6099.129",
    "Node": "--"
  },
  "Requirements": {
    "black": "24.1.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.27.0",
    "tomlkit": "0.12.0",
    "typing_extensions": "4.8.0",
    "uvicorn": "0.24.0.post1"
  }
}

### Code to reproduce

```
import sys
sys.path.insert(0,absolute-path-of-the-directory-of-my-module)
import my-module
```

**Comment by akshayka** [comment]
Hi @eugeniemarescaux, thanks for reporting. I'm not able to reproduce this issue, but I would like to help. I have a couple questions:

1. Can you try running the notebook in the directory where `my_module` is (without modifying `sys.path`)? I'd like to see if the issue is with the path modification or the import itself.
2. If possible, can you share the source code of `my-module`, or a simplified version of it that still causes marimo to hang on import?

**Comment by eugeniemarescaux** [comment]
Hi @akshayka ,
Thanks for your help :)
I have investigated further, and the issue seems to be with an import done in `mymodule`. Unfortunately, the core of the problem seems to be an import of code from my company, which I cannot share :/ 

The closer to the issue I got was 
```python
from mycompanymodule.submodule1.submodule2 import MyClass
print("hey")
MyClass()
```
Doing that, the cell runs endlessly and cannot be interrupted, but "hey" has been printed and the import has worked.
It returns:
```
hey
Traceback (most recent call last):

TypeError: MyClass.__init__() missing 1 required positional argument: 'myargname'
```

**Comment by akshayka** [comment]
Thanks for sharing. That's helpful but I still can't reproduce, though I feel we're closer!

Can I ask you to try two things?

1. Try with an older marimo version 0.1.79 (`pip install marimo==0.1.79`) and see if the issue still exists there
2. Create a file called `foo.py`, with the following code:

```python
class Foo:
    def __init__(self, arg):
        pass
```

Save the below to `import_test.py`, then run `marimo edit import_test.py`. For me I see an error like yours but the cell finishes running in just a few milliseconds. I'm curious whether this notebook runs endlessly for you.

```python
import marimo

__generated_with = "0.1.86"
app = marimo.App()


@app.cell
def __():
    from foo import Foo
    print('hey')
    Foo()
    return Foo,


if __name__ == "__main__":
    app.run()
```

**Comment by eugeniemarescaux** [comment]
I tried your suggestions, and the issue persists with the older marimo version. The problem doesn't appear with import_test, it runs quickly and properly.

In case it would help, some additional information: ̀import mycompanymodule` and `from mycompanymodule import submodule1` both work and finish in a finite time. But `from mycompanymodule.submodule1 import submodule2` runs endlessly.

The file architecture is as follow : mycompanymodule/submodule1/submodule2.py

**Comment by akshayka** [comment]
Thanks. And just to confirm, a cell containing just the following line hangs?

```python
from mycompanymodule.submodule1 import submodule2
```

It's curious that

```python
from mycompanymodule.submodule1.submodule2 import MyClass
print("hey")
MyClass()
```

successfully emits the print statement and `TypeError`, but still hangs

**Comment by akshayka** [comment]
Is there anything special about `submodule2`?

- When you import it outside of marimo, say in the Python repl, is anything printed to the console? I'm wondering if there's an edge case in how we handle console output that gets hit when `submodule2` is imported.
- If I had the code of `submodule2`, I would try deleting blocks of code from it until the import worked, and then try to figure out what code marimo was tripped up on.
- I would also try running marimo with `marimo -l debug -d edit your_notebook.py` and see if the logs told me anything helpful

**Comment by akshayka** [comment]
@eugeniemarescaux , one more question that would provide me with more information:

- Does the cell hang in run mode? i.e., `marimo run your_notebook.py`

**Comment by eugeniemarescaux** [comment]
Thanks to your pointers, I have been able to isolate the problem ! 

If I put the following code in `foo.py`
```python
from multiprocessing import Manager
mymanager = Manager().dict()

class Foo:
    def __init__(self, arg):
        pass
```
and reuse the same `import_test.py` from your previous message (https://github.com/marimo-team/marimo/issues/684#issuecomment-1917530826), the cell runs endlessly on my machine - with the expected output:
```python
hey
Traceback (most recent call last):
  Cell /tmp/marimo_98667/__marimo__cell_Hbol__output.py, line 3
    Foo()
TypeError: Foo.__init__() missing 1 required positional argument: 'arg'
```

**Comment by eugeniemarescaux** [comment]
Sorry for the delay, I was on holiday. I just tested the latest version (0.2.4) and the problem is gone. Thanks a lot !
