### ISSUE TITLE
Support GitHub Copilot

### ISSUE THREAD

**Issue by xiaoxixxxx** [marimo-team/marimo#698]
### Description

Hey, marimo is a great Python notebook with a wonderful reactive UI. However, I'm really accustomed to Jupyter with VSCode and the GitHub Copilot plugin. I really hope you can support it in the future.

### Suggested solution

I'm not sure if it's okay to support a plugin system or something else.

**Comment by mscolnick** [comment]
Hi, thanks for the feedback! We do already support GitHub Copilot ([see the docs](https://docs.marimo.io/getting_started/index.html#github-copilot)). It is already built-in and not a plugin.
