### ISSUE TITLE
Click callback or state for mo.image

### ISSUE THREAD

**Issue by alefminus** [marimo-team/marimo#699]
### Description

I want to create an image / video processing app, where the user can click a pixel and see a graph of the same value for
all the frames in a video whose first frame is this image.

I need to get the location of the click from the mo.Image, but I could not find how to do this in the documentation, or an example showing explicit event handlers for mouse clicks on any other element.

### Suggested solution

I'm not sure at this point what the preferred UX would be, but either an explicit callback or using the marimo dependencies, i.e.

Cell1:
```python
image = mo.Image()
image
```

Cell1:
```python
if image.clicked is not None:
  x, y = image.clicked
  print(f'you clicked {x}x{y}')
```

Or more explicitly:
Cell1
```python
image = mo.image()
def handler(point):
    x, y = point
    print(f'you clicked {x}x{y}')
image.on_mouse_click(handler)
image
```

**Comment by mscolnick** [comment]
Would something like plotly with an image layer work? 

There is an example here: [examples/third_party/plotly_image_selection.py](https://github.com/marimo-team/marimo/blob/main/examples/third_party/plotly_image_selection.py)

Our a static notebook: https://static.marimo.app/static/image-select-v6k2

![image](https://github.com/marimo-team/marimo/assets/2753772/4c6c7d0f-950d-438a-9b62-ec8c7453c9ec)

**Comment by mscolnick** [comment]
Closing this as the solution above should work. Let us know if there are further improvements requested.
