### ISSUE TITLE
Feature or bug? Imported local variables from external files (modules) are visible in NB.

### ISSUE THREAD

**Issue by misolietavec** [marimo-team/marimo#701]
### Describe the bug

Let us have the files `functions.py` and `local_test.py` (`marimo` notebook) in the same directory.
File `functions.py`:
```python
import marimo as mo

def _md(s):
    return mo.md(s)
``` 
File `local_test.py` generated by `marimo`:
```python
import marimo

__generated_with = "0.1.88"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    return mo,


@app.cell
def __():
    from functions import _md
    return


@app.cell
def __():
    _md("# Hello marimo")
    return


if __name__ == "__main__":
    app.run()
```
The "local" variable `_md` is visible in cell below and the application runs correctly. I like such behaviour, because I can define things in (several) `.py` files and use them in notebook. It works with substantially larger notebook. Is this intended, or I should better not rely on that remarkable feature? 

### Environment

{
  "marimo": "0.1.88",
  "OS": "Linux",
  "OS Version": "5.19.0-0.deb11.2-amd64",
  "Processor": "",
  "Python Version": "3.11.2",
  "Binaries": {
    "Chrome": "--",
    "Node": "v18.19.0"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.0"
  }
}

**Comment by akshayka** [comment]
This is a feature you can rely on. We explicitly don't mangle imported names, with our reasoning being that in many cases the user may not have control over the naming conventions of imported packages. Not that you would have seen it, but there is a [comment to this effect in our codebase](https://github.com/marimo-team/marimo/blob/91e661bac4631e307518bd75464253a3392162b1/marimo/_ast/visitor.py#L101-L107).

Glad this feature was helpful for you!
