### ISSUE TITLE
ANSI Codes

### ISSUE THREAD

**Issue by zevburton** [marimo-team/marimo#707]
### Description

Hi! I'm hoping to use ANSI codes in my print statements (i.e. `\r\033[F`), but right now it does not appear to work. Is this a feature I'm missing, or perhaps this should be added to the roadmap.

This could be good for progress bars as well. 

### Suggested solution

Supporting ANSI codes broadly

**Comment by mscolnick** [comment]
Looking into this now

For normal ANSI printing via stdout, there are some changes we need to make as part of the library. If you are using something like `rich` or writing your own ansi, I wrote a small util that would support coloring stdout: https://static.marimo.app/static/ansi-enrm

You can use `rich` or `ansi2html`. This will only work in the output area and not the console area. We can make some changes to support ansi there as well. 

![image](https://github.com/marimo-team/marimo/assets/2753772/abc438d9-6bfb-4e34-a4df-71c8b4f2bc8e)

**Comment by mscolnick** [comment]
@zevburton, yea you can disregard the previous hack. 

I just put up a PR (https://github.com/marimo-team/marimo/pull/713) so that this works with `print` statements

**Comment by banteg** [comment]
the root cause with rich not rendering colors was no marimo detection mechanism. good news marimo fully supports its truecolor mode, so i added auto detection here https://github.com/Textualize/rich/pull/3651

**Comment by sebmestrallet** [comment]
With Rich, while awiting for https://github.com/Textualize/rich/pull/3651 to be merged, you can force coloring in the marimo console area with:

```python
from rich.console import Console

console = Console(color_system="truecolor")
```
