### ISSUE TITLE
Support custom base URL paths

### ISSUE THREAD

**Issue by kevin-hanselman** [marimo-team/marimo#721]
### Description

A quick aside: Thanks so much for creating marimo! Python notebooks are finally fun and productive.

I'd like to deploy a marimo app under a path other than `/`. For example, say I have a proxy at `example.com`, and I want my marimo app to be accessible at `example.com/marimo/`. This currently requires proxy middleware to transform requests before reaching marimo. 

### Suggested solution

Add a configuration option to change the base URL path.

**Comment by mscolnick** [comment]
@kevin-hanselman, fyi,  im looking into this today
