### ISSUE TITLE
Interactive Plot shows incorrect data with filter

### ISSUE THREAD

**Issue by yhenon** [marimo-team/marimo#727]
### Describe the bug

When using an altair plot with `transform_filter`, the interactive plot feature shows data that has been filtered out. For example:

```
    chart = alt.Chart(data.cars()).mark_point().encode(
        x='Horsepower',
        y='Miles_per_Gallon',
        color='Origin',
    ).transform_filter(datum.Origin == "Europe")
    chart = mo.ui.altair_chart(chart)
```

The data has been filtered out to only show points with origin==Europe. The top plot is correct. The bottom plot incorrectly shows filtered out points.

![Screenshot from 2024-02-03 12-51-27](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/3ff8f0e8-4a16-4702-b411-8cd2b8d6c8e3/8d0d2bb8-229c-4b73-a84e-9c0bd3bd84b6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS8zZmY4ZjBlOC00YTE2LTQ3MDItYjQxMS04Y2QyYjhkNmM4ZTMvOGQwZDJiYjgtMjI5Yy00YjczLWE4NGUtOWMwYmQzYmQ4NGI2IiwiaWF0IjoxNzA3MDEwNzQ5LCJleHAiOjMzMjc3NTcwNzQ5fQ.pDuMfJ7e6lovX1Vle2o1CpEBlQKByiWgQ1LZY49eZP8)

### Environment

{
  "marimo": "0.2.1",
  "OS": "Linux",
  "OS Version": "6.1.0-1029-oem",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Chrome": "120.0.6099.109",
    "Node": "--"
  },
  "Requirements": {
    "black": "24.1.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.8.0",
    "uvicorn": "0.27.0.post1"
  }
}

### Code to reproduce

```
import marimo

app = marimo.App(width="full")

@app.cell
def __():
    import altair as alt
    from altair import datum
    from vega_datasets import data
    import marimo as mo
    return alt, data, datum, mo

@app.cell
def __():
    chart = alt.Chart(data.cars()).mark_point().encode(
        x='Horsepower',
        y='Miles_per_Gallon',
        color='Origin',
    ).transform_filter(datum.Origin == "Europe")
    chart = mo.ui.altair_chart(chart)

@app.cell
def __():
    # View the chart and selected data as a dataframe
    mo.vstack([chart, chart.value])

if __name__ == "__main__":
    app.run()
```

**Comment by mscolnick** [comment]
We have a fix for this in this PR (https://github.com/marimo-team/marimo/pull/734). As a heads up, it will require you install vegafusion for this feature to work.
