### ISSUE TITLE
Docstring is obscured by other cells on hover

### ISSUE THREAD

**Issue by ForceBru** [marimo-team/marimo#740]
### Describe the bug

Setup: empty notebook.

1. In the first cell, call some function that has documentation. Hover over the function name. Docstring is shown in a floating view.
2. Create multiple one-line cells beneath.
3. Click one of these other cells to put the cursor there and select the cell.
4. Hover over the function from the first cell.

__Result__: the floating view with the docstring is shown beneath the other cells, so the docstring is obscured.

![screen](https://github.com/marimo-team/marimo/assets/8695383/de389839-f5d2-4949-b111-bc8f49667ea0)

__Expected__: docstring should be on top of all cells.

### Environment

```
{
  "marimo": "0.2.1",
  "OS": "Darwin",
  "OS Version": "22.6.0",
  "Processor": "i386",
  "Python Version": "3.12.1",
  "Binaries": {
    "Chrome": "--",
    "Node": "--"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.37.0",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.0"
  }
}
```

**Comment by mscolnick** [comment]
Thanks for catching this. I had some z-index logic for the focused cell, but its still possible get a tooltip without being focused on the cell. I have fixed this in https://github.com/marimo-team/marimo/pull/741

**Comment by mscolnick** [comment]
Ah I understand why this is happening. I'll see if there is a simple solution, I will re-open this for now.

**Comment by mscolnick** [comment]
this was fixed a while back - but i may have forgot to link the PR, closing this now
