### ISSUE TITLE
Support for the holoviz plotting system

### ISSUE THREAD

**Issue by rishikanthc** [marimo-team/marimo#743]
### Description

The [HoloViz](https://holoviz.org/) eco system - particularly [HoloViews](https://holoviews.org/) and [hvPlot](https://hvplot.holoviz.org/) are my favorite plotting tools. They work first hand with jupyter notebooks and provide interactivity easily. I notice that marimo does not support displaying these plots natively. 

### Suggested solution

Holoviews uses either the `matplotlib` or the `bokeh` backends for plotting. Would be nice if there is support for displaying these in marimo just like plotly/altair is supported.

**Comment by misolietavec** [comment]
__Remark__: `holoviz` can use `plotly` backend, too.

**Comment by matterda** [comment]
I would add that [Polars](https://pola.rs/), already supported by marimo, recently (v0.20) added plotting support through hvPlot.

**Comment by mscolnick** [comment]
I am not familiar with the `HoloViz` API, but it should not be difficult to support.  We support many optional libraries through our formatters under `marimo/_output/formatters` (which have plotly, matplotlib, etc. as examples).

If anyone wants to contribute this feature, it should be just adding a new file and entry to `marimo/_output/formatters/formatters.py` - and would be greatly appreciated 😄 

Otherwise, i can take a look end of this week or next

**Comment by mscolnick** [comment]
Started the work for holoviews support in https://github.com/marimo-team/marimo/pull/752

**Comment by rishikanthc** [comment]
Thanks for the quick update !! Appreciate the speed. This helps me be a lot more productive

**Comment by StankovicAleksa** [comment]
Hello! Thanks for the quick update on this and making a great next-gen notebook tool! 

I have noticed that composing plots (https://hvplot.holoviz.org/getting_started/hvplot.html#compose-plots) with hvplot is not rendering correctly, so I would like to report this. Minimal working example:

```
import marimo

__generated_with = "0.2.4"
app = marimo.App()


@app.cell
def __():
    import polars as pl
    return pl,


@app.cell
def __(pl):
    df = pl.DataFrame({"x":[1,2,3], "y":[1,2,3]})
    df2 = pl.DataFrame({"x":[1,2,3], "y":[3,2.5,3]})

    return df, df2


@app.cell
def __(df, df2):
    df.plot.line("x","y")* df2.plot.line("x","y")
    return


@app.cell
def __(df, df2):
    df.plot.line("x","y")+df2.plot.line("x","y")
    return


@app.cell
def __():
    return


if __name__ == "__main__":
    app.run()

```

**Comment by mscolnick** [comment]
@StankovicAleksa, do you mind making a new issue to track?

**Comment by StankovicAleksa** [comment]
@mscolnick Sounds good.
