### ISSUE TITLE
Ability to style / format mo.ui.table()

### ISSUE THREAD

**Issue by Norvie** [marimo-team/marimo#775]
### Description

Would be great to be able to format the output of mo.ui.table(). 
As an example to be able to add decimals, format numbers as percentages, datetime formating etc... 
![image](https://github.com/marimo-team/marimo/assets/72144431/7d850bc0-a241-450a-beea-7babf002cf9f)
This is the current output. 

### Suggested solution

A suggested solution would be to add the ability to handle pd options display like pd.options.display.float_format = "{:,.2f}".format.

**Comment by aopell** [comment]
This would be extremely useful!

It would be especially helpful for datetime formatting, as there doesn't seem to be any way to customize the display of dates in the table. At least for numbers, you can make them into strings to customize the number of decimal places, but any method of attempting to convert a datetime to a string leads to the table displaying it the same way.

Having a way to customize the default datetime formatting would be a good solution I believe, or possibly a way to disable automatic datetime identification per column.

**Example:**
![image](https://github.com/marimo-team/marimo/assets/5026980/0af87b05-4f0e-408a-92c5-458391acf696)

**Comment by mscolnick** [comment]
@Norvie, @aopell would appreciate your thoughts:

1. Do you want to format this programmatically? E.g. passing format options to the table. or do this on the frontend with the dropdown (this wont be persisted across into the application code)? or both?
2. Do you want to do this per table (.e.g `float_format`, `data_format`) or per column?

**Comment by Norvie** [comment]
Hi @mscolnick 

In my humble opinion :) 

1. Both 
2. Per column
