### ISSUE TITLE
marimo.ui.tabs in marimo 0.2.4 switch to first tab, whenever something is changed in another tabs

### ISSUE THREAD

**Issue by misolietavec** [marimo-team/marimo#779]
### Describe the bug

As the title said, whenever I change some `ui` element (e.g. `slider`) in another tab, the `tabs` switch to first tab. This was not the case in marimo `0.2.2`, where the `tabs` behaved normally. Then it was `mo.tabs`, not `mo.ui.tabs`.

### Environment

{
  "marimo": "0.2.4",
  "OS": "Linux",
  "OS Version": "5.19.0-0.deb11.2-amd64",
  "Processor": "",
  "Python Version": "3.11.2",
  "Binaries": {
    "Chrome": "--",
    "Node": "v18.19.0"
  },
  "Requirements": {
    "black": "23.12.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.0"
  }
}

### Code to reproduce

```python
import marimo
 
sld1 = mo.ui.slider(start=1, stop=10, value=5)
sld2 = mo.ui.slider(start=2, stop=8, value=4)
 
mo.ui.tabs({'first': sld1, 'second': sld2})
```

**Comment by akshayka** [comment]
I suppose this happens when the `tabs` are created in a cell that's separate from the sliders, right? At least that's how I can reproduce it.

I think what's happening is every time the slider is run, the cell with the tabs is recreated and opened at the default tab (the first tab).

If you declare the tabs in the same cell as the sliders, such as in the image below, it should work. Though perhaps this is inconvenient?

<img width="911" alt="image" src="https://github.com/marimo-team/marimo/assets/1994308/7e795bcd-c6f5-4c1a-bd5d-684050e08b38">

**Comment by misolietavec** [comment]
Yes, if defined in the same cell, it works. But, in 0.2.2, it worked also if sliders and tab were defined in different cells. I think,  this is the way, it should  normally work.

**Comment by akshayka** [comment]
Okay, that makes sense. We'll see if there's something we can do

**Comment by akshayka** [comment]
@misolietavec , the latest version of marimo (0.2.5) includes a fix for this issue. Thanks for bringing it to our attention!

**Comment by CCSun21** [comment]
@akshayka hello, same bug found in marimo(0.9.31). if content and tabs were defined in different cells. Whenever some UI element in another tab is changed, the `tabs.value` switches to the first tab.

## env
```
{
  "marimo": "0.9.31",
  "OS": "Linux",
  "OS Version": "5.15.0-125-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v21.2.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.15.2",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.2",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {
    "altair": "5.4.0",
    "anywidget": "0.9.13",
    "duckdb": "1.0.0",
    "pandas": "2.2.3",
    "pyarrow": "6.0.1"
  }
}
```
## Code to reproduce
```python
import marimo as mo
```

```python
sld1 = mo.ui.slider(start=1, stop=10, value=5)
sld2 = mo.ui.slider(start=2, stop=8, value=4)
```
```python
tabs = mo.ui.tabs({'first': sld1, 'second': sld2})
tabs
```
```python
tabs.value
```

**Comment by mscolnick** [comment]
@CCSun21, this is by design, since the tab cell get re-rendered. You could use [mo.state()](https://docs.marimo.io/api/state.html#state) and keep the tab state in sync from a separate cell (that does not get re-rendered
