### ISSUE TITLE
marimo.App(width="full") - consider adding to docs or recipes

### ISSUE THREAD

**Issue by vrtnis** [marimo-team/marimo#783]
### Documentation is

- [X] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

I found several references to marimo.App(width="full") in the examples (which is how I learnt it was available).
I used this feature to build out a marimo cheat sheet. However, the documentation (which is awesome btw) does not appear to explicitly mention marimo.App(width="full").

### Your Suggestion for Changes

*Consider adding something along these lines to *[*recipes.md*](http://recipes.md)

### Setting the application to full width

**Use cases.** Utilize the entire browser width for your Marimo application, ideal for dashboards, wide layouts, or when you need to display extensive content without constraints.

**Recipe.**

1. Initialize your Marimo application with the `width` parameter set to `"full"` to make the application use the full browser width.

```python
app = marimo.App(width="full")
```

**Comment by akshayka** [comment]
Thank you for the suggestion! We can add it to the docs. The recommended way is actually through the notebook UI:

<img width="370" alt="image" src="https://github.com/marimo-team/marimo/assets/1994308/3384172b-7c82-4c8c-a860-0c2735ed2cad">

**Comment by vrtnis** [comment]
Interesting, I do not see the notebook UI displayed when I run my notebooks locally.  I tried "marimo tutorial intro" just now and that does indeed display the entirety of the top right UI. 
However, if I run the same tutorial code using "marimo run tutorial.py" I do not see the menu.  It just might be that I'm doing something incorrectly in my Marimo workflow/setup. Or, do you see this as a separate issue?
