### ISSUE TITLE
marimo.app does not work on Firefox

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#788]
### Describe the bug

From Discord:

> When opening https://marimo.app/ in Firefox it gets stuck initializing. I see a Error: Could not extract indexURL path from pyodide module location in the javascript console. Works fine in Safari.

> running ff 122.0.1

### Environment

N/A

### Code to reproduce

Navigate to https://marimo.app on Firefox

**Comment by mcburton** [comment]
Trying to dig into this, I think this is the error in [pyodide's source](https://github.com/pyodide/pyodide/blob/dc4cb1b78fcf93ea1b313b16b3af5b8e1dd53085/src/js/compat.ts#L291). Looks to be related to an inability to find the index of the last slash in the URL that loads Pyoidide.

Looking at the [Marimo code that loads Pyoidide](https://github.com/marimo-team/marimo/blob/2eb2adf6212ff7ee28124d7637109f8d080937e0/frontend/src/core/pyodide/worker/worker.ts#L21)

you use the URL:
`https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.js`

But the Pyodide documentation recommends:
`https://cdn.jsdelivr.net/pyodide/v0.21.0/full/`

Not sure if this is the issue or if using the recommended URL would fix it, but the  I don't have a development environment to set up to test (are there instructions for setting up the WASM version?).

**Comment by mscolnick** [comment]
thanks @mcburton, that was the exact fix!
