### ISSUE TITLE
Theme switcher does not appear to function (wasm)

### ISSUE THREAD

**Issue by vrtnis** [marimo-team/marimo#789]
### Describe the bug

![screenshot12-40-53](https://github.com/marimo-team/marimo/assets/123119434/3685248a-0c61-4343-ad7b-a87edfb55aca)
When selecting various themes in the Display section, no theme switch occurs. Screenshot of console attached. (Uncaught Error: Method not implemented)

### Environment

wasm, chrome (Version 120.0.6099.216 (Official Build) (64-bit))

### Code to reproduce

Navigate to marimo.new and then try switching the theme.

**Comment by mscolnick** [comment]
Ah yea, I haven't implemented the user settings yet. Should be an easy fix though (May not get to it until next week)
