### ISSUE TITLE
App config (width) doesn't work in WASM notebooks

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#791]
### Describe the bug

A notebook's app config isn't saved to or read by WASM notebooks, making it hard to share full-width notebooks as WASM notebooks.

### Environment

marimo 0.2.5

### Code to reproduce

Share a full-width notebook as a WASM notebook

**Comment by mscolnick** [comment]
This works now at https://marimo.app/

**Comment by timoleistner** [comment]
The width is only kept by if one uses the long WebAssembly link which encodes the code as a parameter, not if one uses the permalink.
On the other hand, only the permalink allows sharing as an App by appending `?mode=read&include-code=false` to the permalink. This doesnt work with the WebAssembly link.
It would be nice to also be able to share as an App in full width.

As these are two kinda different things, should I open a separate issue?

**Comment by mscolnick** [comment]
@timoleistner - ill look at this today. in the meantime, can you DM me in our [Discord](https://marimo.io/discord), I can share a better workaround
