### ISSUE TITLE
Mathematical animations using Manim

### ISSUE THREAD

**Issue by akshayka** [marimo-team/marimo#794]
### Description

We'd like to make it easy for users to make and show beautiful mathematical animations in marimo.

### Suggested solution

Some sort of integration with [Manim](https://github.com/ManimCommunity/manim/) could work well. 

### Alternative

Matplotlib can be used for very basic animations, but it quickly becomes very cumbersome as the animations become more complex.

### Additional context

Manim does have a basic Jupyter integration, which we can look to for initial ideas. However, that implementation makes heavy use of magic commands, whereas we'd like to provide a pure Python experience for creating and showing Manim animations.

I can imagine two types of integration:

1. A basic integration that allows for showing Manim animations as videos, similar to the Jupyter integration ([example](https://try.manim.community/)).
2. An integration that supports creating interactive scenes. I believe this would need to use the [OpenGL renderer](https://www.youtube.com/watch?v=KeXBLPC1tns).

It would be a good idea to communicate with the Manim Community developers when designing a solution. We'd appreciate help with this issue!

**Comment by dmadisetti** [comment]
Manim and Manim slides both work in Marimo:

https://static.marimo.app/static/manim-example-rket

[manim-slides](https://github.com/jeertmans/manim-slides) is a lot of fun.

---
env with nix:

`nix-shell -p nodejs-18_x ffmpeg manim "python3.withPackages(ps: with ps; [ numpy marimo manim-slides ])"`

**Comment by akshayka** [comment]
Closing this issue given @dmadisetti's examples

**Comment by axiomtutor** [comment]
Does anyone know if it's possible to only show the video and hide the "output", meaning the terminal output 

```
[03/31/25 23:35:44] INFO     Animation 5 : Partial      scene_file_writer.py:588
                             movie file written in                              
                             '/videos/acira/1080p                         
                             60/partial_movie_files/Tri                         
                             angle/2852726489_388047445                         
                             2_312190291.mp4'                                   
                    INFO     Combining to Movie file.   scene_file_writer.py:739
                    INFO                                scene_file_writer.py:886
                             File ready at                                      
                             '/marimo/acir                         
                             a/media/videos/acira/1080p                         
                             60/Triangle.mp4'                                   
                                                                                
                    INFO     Rendered Triangle                      scene.py:255
                             Played 6 animations                                
                                                                                
                    INFO     Animation 4 : Using cached     cairo_renderer.py:89
                             data (hash :                                       
                             2852726489_917545911_185078368                     
                             6)                                                 
                                                                                
                    INFO     Animation 3 : Using cached     cairo_renderer.py:89
                             data (hash :                                       
                             2852726489_2219474480_72129236                     
                             4)                                                 
                                                                                
                    INFO     Animation 1 : Using cached     cairo_renderer.py:89
                             data (hash :                                       
                             2852726489_667144672_162688307                     
                             8)                                                 
                    INFO     Animation 2 : Using cached     cairo_renderer.py:89
                             data (hash :                                       
                             2852726489_1662830014_19771223                     
                             67)                                                
                                                                                
Manim Community v0.19.0

[03/31/25 23:35:41] INFO     Animation 0 : Using cached     cairo_renderer.py:89
                             data (hash :                                       
                             3977891868_1266074046_22313245                     
                             7)                                                 
```

This shows below the run cell, which I'd like to hide so that it doesn't confuse or distract a reader.  If I hide the output then it also hides the video.

**Comment by jlzhjp** [comment]
@axiomtutor Please check out this notebook: https://static.marimo.app/static/marimo-manim-l8vy

You can set `progress_bar` to `"none"` to disable the progress bar.
