### ISSUE TITLE
rustpython?

### ISSUE THREAD

**Issue by sublimeclemency** [marimo-team/marimo#798]
### Description

i suggest using rustpython as an interpreter option?
https://rustpython.github.io

### Suggested solution

rustpython can compile to webassembly too.

**Comment by akshayka** [comment]
I don't think our codebase assumes that marimo is executed using CPython (correct me if I am wrong). I think you could install RustPython, get pip, and try using marimo today.

Do you mean using RustPython as an alternative to Pyodide for WASM notebooks? Or what kind of integration would you like to see?

**Comment by sublimeclemency** [comment]
why, yes! using rustpython for WASM notebooks could prove really useful, and is a promising altermative to pyodide.
i really have no experience and am sorry i can't help more. have a nice day!
