### ISSUE TITLE
"Publish as HTML" static URLs returning empty pages (404 from jsdelivr) (wasm)

### ISSUE THREAD

**Issue by vrtnis** [marimo-team/marimo#801]
### Describe the bug

After navigating to a static url generated using the "Publish as HTML" feature on a WASM notebook, the page does not display any content.  Chrome indicates a 404 related to frontend@ 0.2.4 beta 
![screenshot18-18-16](https://github.com/marimo-team/marimo/assets/123119434/071c7ad2-ff91-4599-ae79-e72dec956ae0)

Static pages published earlier seem to work well (frontend@0.1.79)

### Environment

Wasm , Chrome Version 120.0.6099.216 (Official Build) (64-bit)

### Code to reproduce

Try the [Bayes Theorem WASM example](https://marimo.app/?code=JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoAmDgVhbSIwYJgmSoOAQWEAKAJQY0AASFgOAYzwAbLTLrByeTOoiHGAFSgBXPAsMAzONhkgIcgFxo43hBA4hyGS8fEKgWcOCQ7wBiOAAhRABPPABnAHI4czo8aDwQDCifTCzgFLhgAjISdRhgADc8OAIIMgAjCAgAazgqRDKkQx7aBgBtJBRXAF09GBgwFPcAekWcYatWjQgQRfHUAFoyRG3d1zkAGjhEAnJyspHWvoo4CAJL17wADzAtK9JgF%2BejgSyXSmWyuRAcFaiTgAHESJU4ABlK6GKApF7TOizeZLRZUAkcRIQKwwdZ4TbbXowdR0AD8dUYAAkAFqwgDCEAAagAxADMAE06gBZABkWlKMEYAAUADIALwAjgB2UwgGD2ADSAEUqFxNQBJVraxVsKDygDqUEVq3sTM1nWlsIAjKKKoYPoxXVK%2BSk5JgOAVCvEkqkMvQclA8nAwFAIHUDKlLnATAQGgRgIR4L0YTAICnEFp1FYfmQ4BGY3GHq1gBKYIlIlEII5EHA6IlIBGUqU4Hh0-AACRMgdwVbp3sJwwETRwAcAUQHnkbIQAOiNlz5pTImXAVyADHA53JRCv7NUAN5bpnHrdz3f7m7XgC%2Bl5kR6fgeDu8mii-ACo-yyRoCCsEBiFIaAOAAsFgNA8C8ygW5y2ySsIGrWtaBhZsJyzMp5xHVFZ2HNtVEICocA3bw83wCMoAAbmQ0hbjOINCjXSiQivG833vA9r1EW9d3UIQ4GvT9gxXH8OIAoC4CnLYKggqAoL-DiDVeVwUngYSixLP4XhSC5aCQ7ItDAewS3LfMoyoFAywreT9wIJTZ1vOQCLKVionYr83IE7c5EEvc%2BOPABqOAtxXIgcFEm84B44KbiivAYuvFiv0kryQiofRaXKV4ySgV5hNeQsMShRpbNoMhSpSX8JPXXy32PZgguEkR%2BPCtqROS1K5HEtify-cIBBCfqtDwewYHkRso0KghFBUYQNG0LQ0AcJxMBcNxPBCMBMAYZhXA4KxgA4FIJTRGRODYC5nQuH5Wm0RgWAHLiBxYC46kLGxGE4e64C0vAwD%2BjhnQUPbMCMMdCAO0RjtO87LuIa6OFuuAAce57XqCh9Yo%2Br6frwUG%2BQuIGQf%2BiGfH26H6lh5oYDho6-ERi7EygIIvxuu6HsQJ6tEYMI3oSvHevxz64G%2BrRfs4UnAbICmwcbKnvDmqwipjKHcDpggDouGntfTTAGb1zW6EW1QVp0dbJs2mQDZh3W6H1rXHeNlpTf2ugPEbGnRC9jgpZsP8HZ1g7A6JuBwpkZ04D2M2I%2Bl2wQ9dsOTboRObEbB4QUwKMUhLeBmADoPGj-TXaaNjPS7gRYK9mvB5qhUMUjz1JC5dvALeWzQdD0RNjFMYnLBsOxbecVxO8N2HnYr6fdfTl3vd2nxjoCTngygewRo4kJoliaUqz5jDalSLLgwFEkC2Kl57GAHB1caCtYzQ4%2B60zMpsIrPtcKIgcLnnLxR8-83g3EAYlXc0VRIDnPoUc8x0%2BgHRgCAXQIwvZTzdrPUORt06TDkE%2BWBURZLfBaBVLQEAqCS1KFYQswB5RJmfkfGs78kxf2yCkRoP9KgpA4HADiO8xpeTVkVbuahe5rQ2s4VMWlrA1EwC-dCdZEjyPITAH2IRpEwFkYzBRb9MIqJaDNUIjd1YLQwEtMRq1%2B6GEHmYEetgbaOGcDnVIbcC5aBgBcSeFcMFhywanHBHt-HL0bGvQIHEt4CK-D4Z0vDZLJB0BQuAUYahXBwBNZJwN86-2-v2P%2BFxCK0DKMgPArYezC34swc8JcibuE4FwewT4BwDWiTwGC5ZSlaEyakgg6TGjxmID8YQ5Ehj0GQo0BJ5DKEvEaFGWMqQckoS4YOO8K52rQIKdcXehQimXCjGUvCXEhLkFIbjEKohqnhxruXbBM9M54DqdwRpzTtneD5HElChwukpJgGkjJ9AmInNSAQNI8ABlQCGeMuAkykk-L%2BbMrJCzuFQuWbOVZ6yxbDk2eQV5IRdklIOa5GQmLjxrJOfAM5SUoGVLgOeGOccE6l2PDcgJ9Mgn3MeQ0ppgZcUADkWjABnAC%2BAFYC6QjYY0AlZQKizi4ARa4s4%2BQjh7Iw1%2BzDMJEqPBcmmnLnm8MISEAA8kQHoSQrLIQqN0PmJJ4DAjDDBCESEKz2AgIkmgvT3BQt0eq%2BsRKdwQKPMqsoqrFGYVxdhfCoC-4kWEGRXpVkaLZEQjICsBLARQrhb0jJA45XnDkvURMNxoReqYSfLCjhI10FIhmXpuKmKFi6SmlCYr02pv2Z-Ctcqo0DiVf1XF6kLVlGEhwi4drQRAUdSkJIdVcU%2BWid4K8QDDwtV3GeRA6hzyvn4pS2KT4XyvnfE%2BE8a6N2bpqUnI9ZLSGXMrnc0ue7903t1Q%2Bi5LjW750Ls%2B2dQ152sAiII4x81RFWwkePLatyna%2BMCYzYJ6ifAbU0do%2BRpalEGOmnBnZ4BoDwCQHMVREoNhgA7Koy4ZRvgwEIeRjgiAPipBmhxWIAAlRA5BgBWAWBjC49h114D2CYchUBPVRnIBcCg%2BA%2BOuugJ61oScOJUbvg-KMMgFPdnoYwGQAA2M4Gm5AqyiA8Dh-sPEcEY3gHpfSZDXQuGwPNAMAb2HUC9GT67OgSzMy9HKtA8AS0LGAKtoMuC8D0yEQ6MZjOmfMxNSz6MbNL3uTzOADmXowqoG5xzLBPNkAlljAWLAmQsGCz4W9TsjMwBM2Z35Wa8Ab3nVZuAsXcXnpsOlX9EGrlExa-OpLLAvmfVxe5jL%2Bgsudeib5-znBeAja-Dll6c4%2BtfkK94Yr7sYOlfK5F6ruL7btaTtZ2zDKmt4Cg2ymD8XEvpd66J9LmXvMFLMuNvgHFFthbKzgYS8hqPkEoGAUgtIZAGYcV%2BKjb3EAfZY9937dA9DPeB%2B9-q4P5GQ5kMt9OMPjMg7B19xHNIofLe9nJ4zE18DXCMZvExGtYeg708Im%2BBAZFWDkd6staGWLmMtuIxxdsMPlCw7AMQEx8x9F8A3Juk9FDACccbI4RhMBMGYCwbASAKjYBYCvbwltrAEHkEAA) and then publish as HTML

**Comment by mscolnick** [comment]
This works now
