### ISSUE TITLE
Adjust the number of rows displayed in a dataframe UI element 

### ISSUE THREAD

**Issue by klvbdmh** [marimo-team/marimo#822]
### Description

When I render the dataframe UI element with **`marimo.ui.dataframe`** the output is [fixed to display five rows](https://github.com/marimo-team/marimo/blob/main/frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx#L159) at a time.

### Suggested solution

I'd like to set the page size myself, similar to `page_size` argument in **`marimo.ui.table`**

**Comment by mscolnick** [comment]
Fixed by @metaboulie in https://github.com/marimo-team/marimo/pull/1288!
