### ISSUE TITLE
mo.ui.refresh doesn't accept options and default interval lower than 1

### ISSUE THREAD

**Issue by scls19fr** [marimo-team/marimo#833]
### Description

Hello,

    refresh_button = mo.ui.refresh(
        options=[0.1],
        default_interval=0.1,
    )
    refresh_button

raises

    Bad Data
    options.0: Number must be greater than or equal to 1
    defaultInterval: Number must be greater than or equal to 1

Maybe we can expect having a decent framerate with some plotting library (10 fps in this case but maybe 20 fps could be possible)

Kind regards

### Suggested solution

Remove with UI limitation

**Comment by mscolnick** [comment]
We can drop this down to `.1`. I initially made it 1 second to avoid shooting yourself in the foot and DDOS yourself 

Are you pulling in data from elsewhere? Can you describe the use-case more for having a refresh-rate of 0.1?

**Comment by scls19fr** [comment]
If you drop this down to .1 you (or someone else) should first focus on https://github.com/marimo-team/marimo/issues/834 because this kind of problem could occurs more frequently

**Comment by mscolnick** [comment]
Thanks for the example, and I will look at #834 as well.
