### ISSUE TITLE
Global variables with same name not getting deleted

### ISSUE THREAD

**Issue by yousufm97** [marimo-team/marimo#845]
### Describe the bug

When creating two cells with global variables of the same name it complains, but even after deleting, it doesn't let you run the remaining cell. See below:

- define variable in cell

<img width="967" alt="Screenshot 2024-02-27 at 12 36 10 PM" src="https://github.com/marimo-team/marimo/assets/63131149/cd310a3f-fa40-4637-a40f-e65519e94ac0">

- define same variable in second cell
   - both errors show which cell it conflicts with

<img width="906" alt="Screenshot 2024-02-27 at 12 36 26 PM" src="https://github.com/marimo-team/marimo/assets/63131149/4c4c8dad-3047-40df-a33e-0f10953c1fcb">

- delete second cell
   - first cell still has error AND shows `*` for the offending cell, no cell number, just bullet point.
<img width="908" alt="Screenshot 2024-02-27 at 12 36 45 PM" src="https://github.com/marimo-team/marimo/assets/63131149/1b358be4-fcd9-4bfa-8f9e-7fa846a23c75">

- Delete remaining cell and make an entirely new cell with the same variable
   - still doesn't work, now shows two blank bullet points (one for each of the first two cells
<img width="929" alt="Screenshot 2024-02-27 at 12 37 07 PM" src="https://github.com/marimo-team/marimo/assets/63131149/8ed20c71-3b90-4081-b499-05921e54e622">

### Environment

{
  "marimo": "0.2.8",
  "OS": "Darwin",
  "OS Version": "23.3.0",
  "Processor": "arm",
  "Python Version": "3.9.13",
  "Binaries": {
    "Chrome": "122.0.6261.69",
    "Node": "--"
  },
  "Requirements": {
    "black": "24.2.0",
    "click": "8.1.7",
    "importlib_resources": "6.1.2",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.37.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.10.0",
    "uvicorn": "0.27.1"
  }
}

### Code to reproduce

See above for description on reproducing. Its more steps then just code so that seemed better.

**Comment by akshayka** [comment]
Thanks for reporting this, and for the thorough description. Somehow I'm unable to reproduce the issue. Were there any other cells in your notebook, or any other clues you can provide to help us reproduce?

**Comment by yousufm97** [comment]
I had tested it multiple times on both new and old files, and kept seeing the same error, but like you, I am unable to replicate it now. Perhaps something went wrong in my kernel, though I'm fairly certain I had restarted in as well.

As we are unable to replicate, I guess its not an issue.
