### ISSUE TITLE
Plotly renderer config support

### ISSUE THREAD

**Issue by jamieray** [marimo-team/marimo#846]
### Describe the bug

I want to set plotly defaults. In Jupyter I normally use scrollZoom and editable plots by default.

But in Marimo it seems that plotly plots neither have scrollZoom nor are they editable. Are either possible? Do I need to choose a different 'renderer'? Wrapping in a mo.ui.plotly doesn't change the behavior.

### Environment

{
  "marimo": "0.2.5",
  "OS": "Linux",
  "OS Version": "6.2.0-1019-gcp",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Chrome": "--",
    "Node": "--"
  },
  "Requirements": {
    "black": "21.7b0",
    "click": "8.0.2",
    "jedi": "0.19.0",
    "pymdown-extensions": "9.11",
    "starlette": "0.37.1",
    "tomlkit": "0.12.1",
    "typing_extensions": "4.5.0",
    "uvicorn": "0.27.1"
  }
}

### Code to reproduce

```
import marimo as mo
import numpy as np
import plotly.express as px
import plotly.io as pio

pio.renderers.default = "notebook"
pio.renderers["notebook"].config["scrollZoom"] = True
pio.renderers["notebook"].config["editable"] = True
fig = px.scatter(np.random.rand(5))
# mo.ui.plotly(fig)  # this didn't help
fig
```

**Comment by akshayka** [comment]
@jamieray , thanks for opening this issue. We haven't really looked into default Plotly rendering options. How important is it to you that we support this?

**Comment by jamieray** [comment]
I'll still have some use for Marimo without `editable`, but I use `scrollZoom` on almost every plot because I don't know what axis limits will be useful a priori. So I would end up using Jupyter for much of my plotting if it's not available in marimo. I can look into other plotting options but thought I would check if I was doing something wrong here.

**Comment by akshayka** [comment]
> So I would end up using Jupyter for much of my plotting if it's not available in marimo. I can look into other plotting options but thought I would check if I was doing something wrong here.

Thanks for letting us know. In that case, we can look into supporting this

**Comment by astrowonk** [comment]
Not sure if it's related but plotly usually default to the tool being _zoom_ (drag a rectangle to zoom) but in Marimo it is default to _select_. (drag a rectangle and select some points, useful for a callback or getting the data, less helpful for data exploration.)

**Comment by mscolnick** [comment]
@jamieray , @astrowonk  This will be fixed in the next release (https://github.com/marimo-team/marimo/pull/1170)

You can pass config or a renderer name to the plugin. We still have the default tool being "selection", just we want people to use the marimo reactivity, but happy to change it if people feel strongly.

**Comment by astrowonk** [comment]
I would prefer zoom be the default, but as long as there's a way to change the default I am ok with whatever you want to do. I can see how it makes sense for reactivity demonstration purposes for selection to be default.
