### ISSUE TITLE
Naming in cycle resolution

### ISSUE THREAD

**Issue by jamieray** [marimo-team/marimo#847]
### Description

I am trying to migrate a notebook with a cycle. It is hard to debug especially when the cycle is long.

### Suggested solution

Could the edges of the dependency graph be annotated with the variable names? For example 
```
This cell is in a cycle:
cell-5 -> cell-0
cell-0 -> cell-5
```

Change to 
`cell-5 (var a...) -> cell-0`?
Or it could be shown graphically in the dependency explorer, on the edges, maybe even just on hover?

**Comment by akshayka** [comment]
Fantastic suggestion -- we should do this! Will get around to it when we have spare time.
