### ISSUE TITLE
Exported HTML does not render content when opened (wasm)

### ISSUE THREAD

**Issue by vrtnis** [marimo-team/marimo#860]
### Describe the bug

Console screenshot:
![screenshot10-14-07](https://github.com/marimo-team/marimo/assets/123119434/558085af-8017-4191-acc2-77f43202b960)

### Environment

Chrome Version 120.0.6099.216 (Official Build) (64-bit)

### Code to reproduce

Open a new notebook using marimo.new. Go to a tutorial (e.g., Plotting) and then "Download as HTML". Open the file.

**Comment by mscolnick** [comment]
I have a fix out for this. It will be in the next release
