### ISSUE TITLE
Blank pngs when downloaded in toggled code view mode (wasm)

### ISSUE THREAD

**Issue by vrtnis** [marimo-team/marimo#861]
### Describe the bug

Exported pngs have the right dimensions but are blank when generated in code view mode.  Appear to have expected content in app view.

### Environment

Chrome Version 120.0.6099.216 (Official Build) (64-bit)

### Code to reproduce

Open a wasm notebook. Open any tutorial and export a png in code view.  Toggle to app view and try again.

**Comment by mscolnick** [comment]
I cannot reproduce this. Are you exporting the full notebook from the top right dropdown menu?
