### ISSUE TITLE
marimo_csv transformer not available when using altair plots

### ISSUE THREAD

**Issue by andrewhill157** [marimo-team/marimo#877]
### Describe the bug

Following [this page](https://docs.marimo.io/api/plotting.html#performance-and-data-transformers) referencing using the `marimo_csv` data transformer, I tried to run

```
import altair as alt
alt.data_transformers.enable('marimo_csv')
```

This results in an error:

```
This cell raised an exception: NoSuchEntryPoint('No 'marimo_csv' entry point found in group 'altair.vegalite.v5.data_transformer'')
```

And running

```
alt.data_transformers.names()
```

I get

```
[
0:"csv"
1:"default"
2:"json"
3:"vegafusion"
]
```

However, when I instead put my altair chart into a `mo.ui.altair_chart`, I don't get any errors and plots with far more points than the 20k limit for altair charts render.

I would stick with that method, but I have some plots where it happens to be convenient to have the plot have a horizontal scroll within the UI rather than shrinking things to try and make everything fit into a fixed space. The vanilla altair charts do this, but I haven't been able to figure out a way to have `mo.ui.altair_chart`s to do so.

Apologies if I'm missing something obvious here, thank you for the help and for all the work on marimo, I love it!

### Environment

```
{
  "marimo": "0.2.11",
  "OS": "Darwin",
  "OS Version": "23.1.0",
  "Processor": "arm",
  "Python Version": "3.10.4",
  "Binaries": {
    "Chrome": "--",
    "Node": "v21.6.2"
  },
  "Requirements": {
    "black": "24.2.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.37.1",
    "tomlkit": "0.12.4",
    "typing_extensions": "4.10.0",
    "uvicorn": "0.27.1"
  }
}
```

Also note that I'm using a virtual env with the following requirements.txt

```
altair==5.2.0
vegafusion==1.6.5
vegafusion-python-embed==1.6.5
arrow==1.3.0
marimo==0.2.11
numpy==1.26.4
pandas==2.2.1
polars==0.20.10
pyarrow==15.0.0
black==24.2.0
```

### Code to reproduce

```
import altair as alt
alt.data_transformers.enable('marimo_csv')
```

**Comment by mscolnick** [comment]
it looks like we lazily register our own tranformers. they don't get added until you run `mo.ui.altair_chart` at least once. 
i can add a hook to register these as well manually

**Comment by andrewhill157** [comment]
Ah great thanks for clarifying!

Just confirmed that this workaround runs without errors on my end in the meantime:
```
import altair as alt
import pandas as pd

empty_df = pd.DataFrame({'A': []})
empty_chart = mo.ui.altair_chart(alt.Chart(empty_df).mark_point())

alt.data_transformers.enable('marimo_csv')
```
