### ISSUE TITLE
Display of floats in mo.ui.table broken

### ISSUE THREAD

**Issue by andrewhill157** [marimo-team/marimo#881]
### Describe the bug

Dataframes with floats can break `mo.ui.table`

@akshayka points this out here, but I also just came across this bug after upgrading from `0.2.8` recently:
https://github.com/marimo-team/marimo/pull/853

Since that discussion was locked and and there did not seem to be an existing issue, I figured I would open here just to make sure.

### Environment

Marimo 2.10, 2.11, and 2.12, I believe

### Code to reproduce
```
import pandas as pd
import marimo as mo
df = pl.DataFrame({"data": [2.0]})
mo.ui.table(df)
```

**Comment by akshayka** [comment]
Thanks for reporting. Working on a fix

**Comment by akshayka** [comment]
@andrewhill157 , thanks again for reporting this. Version 0.2.13 has a fix, and it should be available on PyPI momentarily.

**Comment by andrewhill157** [comment]
Awesome, thank you!
