### ISSUE TITLE
VSCode extension pastes the clipboard twice

### ISSUE THREAD

**Issue by kejtos** [marimo-team/marimo#886]
### Describe the bug

In the VSCode extension, the copied text gets pasted twice.

https://github.com/marimo-team/marimo/assets/101019159/c27a05fb-ca1d-43d5-9bef-d3a2beb174f9

Tested on 2 different machines (W11 and W10). I have not had this issue with anything else.

### Environment

Marimo extension: v0.1.13
Marimo: v0.2.13
OS: Windows 11 adn Windows 10

**Comment by mscolnick** [comment]
We've seen this before https://github.com/marimo-team/vscode-marimo/issues/14, but I cannot repro this on a Mac. Looks like this happens on Windows too.

We are open to contributions as I don't have a reliable way to test this myself

**Comment by mscolnick** [comment]
Closing this - should be fixed on the latest
