### ISSUE TITLE
Download marimo files as HTML through CLI

### ISSUE THREAD

**Issue by egemenimre** [marimo-team/marimo#892]
### Description

I would like to generate project documentation using sphinx, ultimately destined for readthedocs. To this end, I would like to generate static HTML versions of the marimo "notebooks" (sacrificing interactive elements) and downloading them locally, eventually uploading them to readthedocs along with the sphinx generated stuff. I can achieve this through the web interface ("Download HTML") but I can't do it with, say marimo CLI.

### Suggested solution

A sphinx add-on to do all this for me would be great, something like 'nbsphinx' (converting the .ipynb files into static HTMLs). :)

### Alternative

If I could do something like "marimo download my_marimo_notebook.py  --html", then I can run a script to generate the HTMLs of my marimo files.

**Comment by akshayka** [comment]
Thanks for the feature request! Generating HTML from the CLI is on our TODO list; just some of work we need to do to make it possible to generate the HTML on the backend. We haven't considered a sphinx add on yet, but that's also interesting.

**Comment by scls19fr** [comment]
Something like

    marimo export html my_notebook_1.py my_notebook_2.py my_notebook_3.py 

or accepting wildcards would be great

    marimo export html my_notebook_*.py

**Comment by scls19fr** [comment]
An other import option to consider is the ability to:
- allow to regenerate notebook from HTML static page (exported from Marimo notebook)
- not allow that

**Comment by akshayka** [comment]
> allow to regenerate notebook from HTML static page (exported from Marimo notebook)

Oh cool, interesting idea

**Comment by scls19fr** [comment]
I think you ever had this great feature to regenerate a notebook from its HTML static page with `marimo-code hidden=""` into HTML static page.

The other option would be to be able to disallow it (not necessary with UI, a CLI command might be enough)

Something like

    marimo export html my_notebook_*.py --no-generate-code

**Comment by mscolnick** [comment]
@scls19fr, we just merged this feature. This will be in the next release:

We added the ability to generate HTML from the command line as well as `watch`:

```bash
# prints to stdout
marimo export html notebook.py > out.html
# writes to the outfile
marimo export html notebook.py --out-file out.html
# writes to the outfile and watch notebook.py for changes
marimo export html notebook.py --watch --out-file out.html
```

I am sure there are more CLI args we could add, but you can get pretty far with `|` and `>`.

**Comment by scls19fr** [comment]
Thanks @mscolnick
