### ISSUE TITLE
Displaying media (image, audio, video) into Marimo notebook

### ISSUE THREAD

**Issue by scls19fr** [marimo-team/marimo#900]
### Documentation is

- [X] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

Hello,

currently Marimo documentation doesn't explain how to display media such as image, audio and/or video in a Marimo notebook.
This may be a problem for not experienced users.

Kind regard

### Your Suggestion for Changes

Maybe documentation should explain how to:

- use a media which is available using an URL (an image on a website for example)
- use a media which is available locally (explaining that if you send your notebook without this image... image won't appear in this notebook
- embed an base 64 encoded media and use it in Marimo (explaining that it's not really well suited for large media)

**Comment by akshayka** [comment]
Thanks for the suggestion.

Our docs have this API reference: https://docs.marimo.io/api/media/index.html

But perhaps we could add a section to the [Outputs guide](https://docs.marimo.io/guides/outputs.html) with examples on how to show media? We'd welcome a PR if you're interested

**Comment by scls19fr** [comment]
embedding media into notebook itself could be interesting also.

I won't be able to send a PR quickly. Anyway I don't know what kind of media you want to show in your examples
