### ISSUE TITLE
Embed Marimo in FastAPI/Starlette Server

### ISSUE THREAD

**Issue by ben-pr-p** [marimo-team/marimo#904]
### Description

I'd like to make Marimo embeddable in another FastAPI / Starlette server, i.e. Marimo as a library.

### Suggested solution

```python
from marimo import Instance # made up :) 

my_notebook = Instance('/path/to/notebook.py')

my_notebook.start_kernel() # also has stop_kernel, etc.

app = FastAPI()
app.include_router(my_notebook.router(), prefix="/my-prefix")
```

Then I could integrate my own authentication, etc.

I'd also like to be able to provide a function that provides some global variable overrides to the instance based on the user request, so that I can implement some security for serving the same notebook to different internal users. 

Maybe something like:
```python
from marimo import Instance

department_analytics = Instance('/path/to/department_analytics.py')
department_analytics.start_kernel()

async def get_initial_params():
    department_options = await get_allowed_departments_for_dropdown_from_req()
    return { "department_options": department_options }

app = FastAPI()
app.include_router(
    department_analytics.router(get_initial_params=get_initial_params),
    prefix="/analytics"
)
```

**Comment by mscolnick** [comment]
This is something I've thought about and makes a lot of sense. I'm not sure what the best entrypoint is (file-path, app code, etc) and what the API is (return a starlette app, routes, etc)

We will need to think about this, and we are open to suggestions. Ideally the API is minimal but room to expand.

Have you seen other libraries do this well?

**Comment by ben-pr-p** [comment]
I think Benjie has done this well with [graphile-worker](https://github.com/graphile/worker) and [Postgraphile](https://github.com/graphile/crystal). Obviously a different ecosystem and different type of projects, but those both support CLI mode and library mode. CLI mode just supports the most common user, and then most customization requires ejecting to library usage.

For each, I think those projects answered your questions with "all of the above". Basically build a higher level API out of lower level ones, but still expose the lower level building blocks for you to use directly when you need more customization. The graphile projects also use their own lower level building blocks to construct the higher level APIs, so I can go and look in the code for the higher level API to see how to use the building blocks correctly.

I haven't done too much server programming in Python so not sure what all of the equivalents are though

**Comment by ben-pr-p** [comment]
Personally, I think requiring users to provide the imported `marimo.App` would be fine (that's supportable, right?). I think the key requirement for the API is that it can be proxyable and share auth and other middleware with other routes in your app.

**Comment by mscolnick** [comment]
Thanks for the examples - will try to take some inspiration. Yea we would need to update some of the utils / exposed classes. 

I think we can start small and expose just the right amount, and include snippets to say integrate with fastapi
