### ISSUE TITLE
inline latex not working

### ISSUE THREAD

**Issue by Eloitor** [marimo-team/marimo#913]
### Describe the bug

After updating marimo, inline equations show in a separate line.

### Environment

{
  "marimo": "0.3.0",
  "OS": "Linux",
  "OS Version": "6.6.20_1",
  "Processor": "",
  "Python Version": "3.12.2",
  "Binaries": {
    "Chrome": "--",
    "Node": "v18.19.1"
  },
  "Requirements": {
    "black": "24.1.1",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.37.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.10.0",
    "uvicorn": "0.24.0"
  }
}

### Code to reproduce

[https://static.marimo.app/static/inline-latex-test-f78w](https://static.marimo.app/static/inline-latex-test-f78w)

```
import marimo as mo
mo.md(
    r'''
    The exponential function $f(x) = e^x$ can be represented as

    \[
        f(x) = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \ldots.
    \]
    '''
)
```

**Comment by akshayka** [comment]
@Eloitor , version 0.3.1 of marimo contains the fix

**Comment by Eloitor** [comment]
Great! It works, thanks!
