### ISSUE TITLE
Arrows spin the carousel when trying to move cursor inside mo.ui.code_editor()

### ISSUE THREAD

**Issue by kejtos** [marimo-team/marimo#923]
### Describe the bug

When there is a code_editor inside the carousel, using arrows inside that code_editor spins the carousel as well. I assume it is unintended.

### Environment

WASM notebook.
Brave [Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (64-bit)]

**Comment by akshayka** [comment]
Yes, unintended :) Thanks for reporting
