### ISSUE TITLE
File System Incompatibilities with WASM Notebooks

### ISSUE THREAD

**Issue by gvarnavi** [marimo-team/marimo#938]
### Describe the bug

The file system on the WASM notebooks behaves inconsistently with the local kernel.

While one seems to be able to upload files as expected on WASM notebooks (by clicking `View files` > `Upload file`), the behavior appears to be inconsistent:
- SVG files seem to work as expected, e.g. downloading & uploading the marimo logo from [here](https://docs.marimo.io/_static/marimo-logotype-thick.svg), and running:
```python
import marimo as mo
mo.image("marimo-logotype-thick.svg")
```
- General files written from the WASM notebook itself, seem to be read fine, e.g:
```python
import numpy as np
np.save("test-dataset.npy",np.arange(16).reshape(4,4))
print(np.load("test-dataset.npy"))
```
- General files uploaded to the WASM notebook, don't seem to work. Here, I upload the same "test-dataset.npy" file and attempt to read it:
```python
import numpy as np
print(np.load("test-dataset_1.npy"))
```
which produces the following error:
```
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/marimo/_runtime/cell_runner.py", line 228, in run
    return_value = execute_cell(cell, self.glbls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/marimo/_ast/cell.py", line 394, in execute_cell
    return eval(cell.last_expr, glbls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/marimo_42/__marimo__cell_RqPv__output.py", line 3, in <module>
  File "/lib/python3.11/site-packages/numpy/lib/npyio.py", line 462, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

What is more, it seems like the size of the file is also different (meaning the following output is inconsistent) 🤔 
```python
import os
os.path.getsize("test-dataset.npy")
```

### Environment

- Local environment (which works fine)
```bash
{
  "marimo": "0.3.2",
  "OS": "Linux",
  "OS Version": "5.15.0-97-generic",
  "Processor": "x86_64",
  "Python Version": "3.12.2",
  "Binaries": {
    "Chrome": "122.0.6261.111",
    "Node": "v18.17.0"
  },
  "Requirements": {
    "black": "24.2.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7.1",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing_extensions": "4.10.0",
    "uvicorn": "0.27.1"
  }
}
```
- WASM environment
default `marimo.app` on Chrome on Linux

**Comment by hoodmane** [comment]
Never mind, I can't reproduce in Pyodide by itself, so probably it has something to do with the way marimo sets up the file system. I do note that when Pyodide calls `np.save` it produces a file that is 192 bytes, but when I call `np.save` in x64 linux it creates a file that is 256 bytes. Both files can be loaded both by Pyodide and native Python. So the difference in file size that @gvarnavi may not be diagnostic of the actual problem since it reproduces upstream but the problem does not.

**Comment by gvarnavi** [comment]
That being said, this does not seem to happen with many other filetypes.

The following seem to work file (when I save them locally, upload to marimo.app, and try to import):
- text files
```python
with open("/marimo/hello-marimo.txt", "r") as _f:
    print(_f.read())
```
outputs correctly
```python
hello, marimo!
```
- CSV files
```python
np.genfromtxt("/marimo/test-csv.csv",delimiter=',')
```
outputs correctly
```python
array([[1. , 2. ],
       [3. , 4.5]])
```
- binary files
```python
np.fromfile("/marimo/test-binary.npy",dtype=np.int64)
```
outputs correctly
```python
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)
```
However, it also happens for my actual use-case which is hdf5 files:
```python
import h5py
with h5py.File("/marimo/test-h5py.h5","r") as f:
    f["dataset"][:]
```
errors with `OSError: Unable to open file (file signature not found)`, which often implies a corrupted file.

Attaching the files used here for completeness. 
[marimo-file-system-tests.zip](https://github.com/marimo-team/marimo/files/14590711/marimo-file-system-tests.zip)

**Comment by hoodmane** [comment]
It would be helpful to check whether you can reproduce any of these things directly in Pyodide without marimo to make it clear whether these are upstream bugs or not.

**Comment by gvarnavi** [comment]
Not entirely sure how to do that (uploading files that is)?  As far as I can tell, Pyodide doesn't ship with a native file system so won't that be testing the specific implementation of a file system in whatever downstream application I use to test? 

FWIW, The `np.load` command e.g. seems to work fine in JupyterLite's and [react-py](https://elilambnz.github.io/react-py/)'s Pyodide kernels.

**Comment by hoodmane** [comment]
> FWIW, The np.load command e.g. seems to work fine in JupyterLite's and [react-py](https://elilambnz.github.io/react-py/)'s Pyodide kernels.

I think that is enough to conclusively rule out any upstream problem. (I was also unable to reproduce your issue in Pyodide but this could have been due to misunderstanding the steps.)

**Comment by akshayka** [comment]
@gvarnavi , we've merged a fix. It should be available on marimo.app within the next hour or so.

Thanks for bringing this to our attention!

**Comment by gvarnavi** [comment]
@akshayka Not sure if the merge fixed the issue?
When I upload binary files from the bottom-left UI they seem to be corrupted and won't load. E.g. both of these cells fail:
```python
np.load("test-dataset.npy")

with h5py.File("test-dataset.h5","r") as f:
    print(f["dataset"][:])
```

However, when I upload the files using `marimo.ui.file()` seems to work fine:
```python
file_h5py=mo.ui.file()
file_h5py

with h5py.File(io.BytesIO(file_h5py.contents()),'r') as _f:
    print(_f['dataset'][:])
```

```python
file_npy=mo.ui.file()
file_npy

with io.BytesIO(file_npy.contents()) as _f:
    print(np.load(_f))
```

See screencast below:
[Screencast from 03-14-2024 12_10_41 PM.webm](https://github.com/marimo-team/marimo/assets/19610677/bddd08b6-7145-4d66-943f-637e751b1dd3)

**Comment by akshayka** [comment]
It looks like our development release failed to upload, so marimo.app is still serving a version of marimo without the fix. Looking into it
