### ISSUE TITLE
Cell names in variable explorer not connected to cells

### ISSUE THREAD

**Issue by anjiro** [marimo-team/marimo#944]
### Describe the bug

I have a moderate-sized notebook with 25 cells. When I open the variable explorer, I get a nice list of variables and the cells that are using them. However, those are named as `cell-N`. The cells themselves have no numbers on them, and when I click the cell menu, I see a name in the box like `cell_Hstk`.

I see when I click on a cell I get a blue highlight around the cell, but it is rather subtle and fades fairly quickly. Especially when there's an exception in the cell, the border reverts to being thick and red, which makes that blue border even harder to see.

I'd suggest maybe displaying cell numbers next to the cells, maybe optionally only when the Variables window is open?

### Environment

```
{
  "marimo": "0.3.1",
  "OS": "Darwin",
  "OS Version": "23.3.0",
  "Processor": "arm",
  "Python Version": "3.11.2",
  "Binaries": {
    "Chrome": "122.0.6261.112",
    "Node": "v21.6.2"
  },
  "Requirements": {
    "black": "23.3.0",
    "click": "8.1.3",
    "jedi": "0.18.2",
    "pymdown-extensions": "10.7",
    "starlette": "0.36.1",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.9.0",
    "uvicorn": "0.27.0.post1"
  }
}
```

**Comment by mscolnick** [comment]
@anjiro - you can name your cells. if you name them, they will show up on the cell and in the variable panel. 


I have the fix for the cell name mismatch, and increasing time of the focus color highlighting https://github.com/marimo-team/marimo/pull/1553/commits/971ea33803dd33b5a1e6323f201cd6dce8b72103
