### ISSUE TITLE
File browser

### ISSUE THREAD

**Issue by MaWeffm** [marimo-team/marimo#946]
### Description

I use Marimo to implement or wrap local analysis workflows that require loading different files. It would be great to have a file browser element to select (server-side) files.

### Suggested solution

Something like https://pypi.org/project/ipyfilechooser/

### Alternative

One alternative solution is to use text input fields to copy&paste file paths.

**Comment by mscolnick** [comment]
This feature makes sense - I can probably get to it within the next few weeks. 

In the meantime, you could use `os.listdir()` and `mo.ui.dropdown`. Using that is a bit harder with nested folders, but we can improve that with a custom ui element.

**Comment by wasimsandhu** [comment]
Picking this one up.

**Comment by wasimsandhu** [comment]
@MaWeffm Component added! cc: @mscolnick
