### ISSUE TITLE
Keep cursor position after executing cell

### ISSUE THREAD

**Issue by anjiro** [marimo-team/marimo#947]
### Description

When I type some code and hit shift-enter to execute it, then go back to that cell (I'm using vim mode, so I hit `k`), the cursor goes to the bottom of the cell. This is rather annoying when I'm rapidly testing by changing code in the middle of the cell, since I have to now re-locate my cursor where it was previously.

### Suggested solution

Save the cursor location in a cell when it's executed, then restore it when returning to it.

**Comment by akshayka** [comment]
Thanks for the feature suggestion. You could also use `Cmd/Ctrl+Enter` to execute the current cell without moving focus to the next cell. That's what I do. Would that work?
