### ISSUE TITLE
Support for URL parameters

### ISSUE THREAD

**Issue by creativedutchmen** [marimo-team/marimo#951]
### Description

It would be great if it were possible to pass url parameters to a running notebook. This would make it possible to create a shareable URL that would take the recipient right to where they need to be. For instance, by pre-filling a textbox, or providing a date-range.

### Suggested solution

The easiest (to implement) solution would be to simply expose the url parameters through a dictionary-like object in the `marimo` namespace. While something inspired by FastAPI would be nice, it would probably also be overkill - we're building quick interactive notebooks, doing some validation on input isn't that inconvenient.

Example of how the API could work. Example URL: `https://example.com/notebook?seed=42&country=us`

```
> marimo.query_params
{
    'seed': '42',
    'country': 'us'
}
```

### Additional context

Streamlit uses a very similar approach: https://docs.streamlit.io/library/api-reference/utilities/st.query_params

**Comment by ben-pr-p** [comment]
In addition to the above approach, I'd like to be able to set the initial value of a Marimo variable via URL parameters that is linked to an input, so if I have:
```
text_input = mo.ui.text()
```

I should be able to do ?text_input=hello

As the notebook author, I can either choose to render the text input and hello will be the initial value, or I can choose not to expose it in the UI, and the URL parameter will be the only way to set it.

This is what I would want - if this is a common use case for others, it may simplify things vs. using query_params as the initial value (although raw access  to the query params would be very useful too).

**Comment by mscolnick** [comment]
automatically connecting query params to variables could open the author up to bad actors with a xss-like hack. 
it also makes the API a bit more opaque and not clear. 

I think we will query params explicit, with some sort of validation/parsing/coercion
