### ISSUE TITLE
feature request: a variable table like Jupyter Variable Explorer

### ISSUE THREAD

**Issue by ultranity** [marimo-team/marimo#96]
### Description

 Variable Explorer will be very helpful for debugging and improve UX.

It may visualize variables with their  data graph dependencies as a further enhancement.

### Suggested solution

provide a table for visualizing variables and/or data graph dependencies for better ux

**Comment by akshayka** [comment]
Thanks for the feature request! These are great suggestions.

We're iterating on designs for both, and will write back here as we make progress.

**Comment by akshayka** [comment]
@ultranity, we just shipped a variable explorer with version 0.1.11 of marimo. Clicking on the variables icon in the bottom left of the editor brings up a variable pane that describes the types and values of each variable, as well as the cells its declared and referenced in. Here's an example of what it looks like:

![image](https://github.com/marimo-team/marimo/assets/1994308/093cc189-810f-4137-847c-45fce2d15329)

Right now the format is just tabular. In the future we might visualize the cell dependencies in a graph view.

Please share any feedback you have!

**Comment by ultranity** [comment]
> @ultranity, we just shipped a variable explorer with version 0.1.11 of marimo. Clicking on the variables icon in the bottom left of the editor brings up a variable pane that describes the types and values of each variable, as well as the cells its declared and referenced in. Here's an example of what it looks like:
> 
> ![image](https://github.com/marimo-team/marimo/assets/1994308/093cc189-810f-4137-847c-45fce2d15329)
> 
> Right now the format is just tabular. In the future we might visualize the cell dependencies in a graph view.
> 
> Please share any feedback you have!

cool!!!

**Comment by akshayka** [comment]
Hi @ultranity, I'm going to close this issue as completed. But feel free to re-open if you have other feedback!

We are planning to add a graph view as well — will write back here to let you know when we make progress.
