### ISSUE TITLE
Unable to import venv installed packages

### ISSUE THREAD

**Issue by Eloitor** [marimo-team/marimo#968]
### Describe the bug

I have packages installed on venv. I could import them before updating to 0.3.3.

### Environment

{
  "marimo": "0.3.3",
  "OS": "Linux",
  "OS Version": "6.6.22_1",
  "Processor": "",
  "Python Version": "3.12.2",
  "Binaries": {
    "Chrome": "--",
    "Node": "v18.19.1"
  },
  "Requirements": {
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7",
    "starlette": "0.37.2",
    "tomlkit": "0.12.3",
    "typing_extensions": "4.10.0",
    "uvicorn": "0.28.0"
  }
}

### Code to reproduce

```
python -m venv --system-site-packages ~/venv
git clone https://github.com/gdamjan/hello-world-python-package.git
cd hello-world-python-package
~/venv/bin/pip install -e .
cd ..
. ~/venv/bin/activate
marimo edit test.py
```

In marimo

```
from cool_lib import a
```
I think this worked on marimo 0.3.1. On 0.3.3 doesn't work.

**Comment by Eloitor** [comment]
Note: If I open marimo in the hello-world-python-package folder, it works.
Before the update it worked in any folder.

**Comment by akshayka** [comment]
Can you type `which marimo`? Want to make sure `marimo` wasn't accidentally installed in your system python installation.

If you downgrade, does it work?

**Comment by Eloitor** [comment]
$ which marimo      
/usr/bin/marimo

I don't understand why it stopped working... I'm downgrading it to every version until 0.2.7 but still does not work...

**Comment by Eloitor** [comment]
I got it working on 0.2.7

**Comment by Eloitor** [comment]
... this is very strange, since if i just run `. ~/venv/bin/activate` and  `python` and in it I write `from cool_lib import a` it does work!

**Comment by Eloitor** [comment]
Using `python -m marimo edit test.py` works, but before just `marimo edit test.py` worked...

Maybe something about python has changed...

**Comment by akshayka** [comment]
I think you may have accidentally installed marimo globally. Can you deactivate your virtual environment, uninstall marimo with pip uninstall marimo, then try again?

**Comment by Eloitor** [comment]
I've willingly installed marimo globally... I'm attempting to package it for void-linux

**Comment by Eloitor** [comment]
Closing since this is expected behavior in void linux: https://github.com/void-linux/void-packages/issues/49402
