### ISSUE TITLE
"Add cell above/below" missing from command palette

### ISSUE THREAD

**Issue by mgunyho** [marimo-team/marimo#976]
### Describe the bug

This is really a minor thing, but in the very beginning, when I didn't know the keyboard shortcuts for add cell above/below (but I knew the shortcut for the command palette), I was trying to create cells from the command palette. My expectation was that I could find those commands from the command palette and learn the shortcuts from there. Instead, I had to mouse over to the add cell/below buttons to see the shortcut.

### Environment

```json
{
  "marimo": "0.3.3",
  "OS": "Linux",
  "OS Version": "5.15.0-100-generic",
  "Processor": "x86_64",
  "Python Version": "3.8.10",
  "Binaries": {
    "Chrome": "123.0.6312.58",
    "Node": "--"
  },
  "Requirements": {
    "black": "24.3.0",
    "click": "8.1.7",
    "jedi": "0.19.1",
    "pygments": "2.17.2",
    "pymdown-extensions": "10.7.1",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0"
  }
}
```

**Comment by akshayka** [comment]
Thanks for reporting -- we'll fix this
