### ISSUE TITLE
Connect to all network interface

### ISSUE THREAD

**Issue by shuther** [marimo-team/marimo#977]
### Documentation is

- [X] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

when I run the code below, I would expect marimo to listen to all network interface, so I can login from a different computer.
`marimo -d tutorial intro`

### Your Suggestion for Changes

Add a command line pushed to uvicorn to specify the listen network (host and port), see: https://www.uvicorn.org/settings/

**Comment by akshayka** [comment]
This can be done via the CLI:

```
marimo tutorial intro --host 0.0.0.0 --port 888
```

`marimo edit` and `marimo run` also accept the `--host` and `--port` arguments.

You can learn more by typing `marimo edit --help` at the command-line.
