### ISSUE TITLE
Support a monospace font for notebook outputs

### ISSUE THREAD

**Issue by deepyaman** [marimo-team/marimo#988]
### Description

Hi! I started playing with Marimo last night, and so far it's been a fun experience. However, there have been a couple of issues preventing me for using it for certain use cases (e.g. demos).

The big one so far is that I don't seem to be able to choose a monospace font for output. There are a number of libraries that output ASCII-based tables that need a monospace font to render correctly (see example in "Additional context" below).

### Suggested solution

I think it would work to support a monospace font option, at least for code outputs.

### Alternative

*No response*

### Additional context

![image](https://uploads.linear.app/63f65126-890b-4810-98cb-b7f8eaee40ee/71034c27-95b1-4fe9-a4bb-973e358a288e/0219cb64-25d7-4f77-8f40-86167847a4b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYzZjY1MTI2LTg5MGItNDgxMC05OGNiLWI3ZjhlYWVlNDBlZS83MTAzNGMyNy05NWIxLTRmZTktYTRiYi05NzNlMzU4YTI4OGUvMDIxOWNiNjQtMjVkNy00Zjc3LThmNDAtODYxNjc4NDdhNGIyIiwiaWF0IjoxNzExNTUyOTgwLCJleHAiOjMzMjgyMTEyOTgwfQ.R6wSjNLrusqCG_zlxAPkAL8bx6ixOR1GWHgiV15w07s "=1300x")

**Comment by mscolnick** [comment]
You can use `mo.plain_text` https://docs.marimo.io/api/media/plain_text.html#plain-text

**Comment by mscolnick** [comment]
@deepyaman - going to close this out, feel free to re-open if you still have issues

**Comment by deepyaman** [comment]
> @deepyaman - going to close this out, feel free to re-open if you still have issues

@mscolnick Sorry, I dropped the ball on this.

> Settings the font is also something we would like to do (monospace or not)

This would be great! If there's already something tracking this, sounds good to me (#989 seems somewhat related, though doesn't necessarily support in the editor view?).

> You can use `mo.plain_text` https://docs.marimo.io/api/media/plain_text.html#plain-text.

Ideally, I don't want to have to wrap all the reprs in this; makes the notebook experience a bit inconvenient. :)

**Comment by mscolnick** [comment]
#989 will cover setting the output font. this is visual outputs by the way (not console outputs), so changing the output font to monospace would do that for all outputs (even markdown which could look weird for users). but you will be able to theme it that way if you'd like
