### ISSUE TITLE
Broken Altair docs

### ISSUE THREAD

**Issue by aangelopoulos** [marimo-team/marimo#993]
### Describe the bug

<img width="881" alt="image" src="https://github.com/marimo-team/marimo/assets/25397074/44d274e1-7d3a-4d6c-a0e9-69ad8ba2a383">

Altair doc image is broken at https://docs.marimo.io/api/plotting.html

### Environment

{
  "marimo": "0.3.3",
  "OS": "Darwin",
  "OS Version": "23.3.0",
  "Processor": "arm",
  "Python Version": "3.11.5",
  "Binaries": {
    "Chrome": "123.0.6312.58",
    "Node": "v20.11.1"
  },
  "Requirements": {
    "black": "24.3.0",
    "click": "8.1.7",
    "importlib_resources": "6.4.0",
    "jedi": "0.19.1",
    "pymdown-extensions": "10.7.1",
    "starlette": "0.37.2",
    "tomlkit": "0.12.4",
    "typing_extensions": "4.10.0",
    "uvicorn": "0.29.0"
  }
}

### Code to reproduce

The documentation is broken online, this is not in my local environment.
https://docs.marimo.io/api/plotting.html

**Comment by mscolnick** [comment]
Thanks for pointing this out - I just released and there is a slight race condition. It should be back now

**Comment by aangelopoulos** [comment]
Sick! :)

Best,
Anastasios Angelopoulos
https://people.eecs.berkeley.edu/~angelopoulos/
