### ISSUE TITLE
Cannot copy code to clipboard from marimo preview iframe

### ISSUE THREAD

**Issue by wasimsandhu** [marimo-team/marimo#994]
### Documentation is

- [x] Broken
- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

I'm using Google Chrome. Noticed that the Copy To Clipboard button (top right) is not working in the iframe previews:

![Screenshot 2024-03-23 at 6 09 46 PM](https://github.com/marimo-team/marimo/assets/7220175/d0b0817d-ec3b-4060-85e7-61ac1b5144a0)

Got the following error:

> [Violation] Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.

### Your Suggestion for Changes

Quick Google search leads to this StackOverflow thread: [Can text within an iframe be copied to clipboard?](https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard). But for me, adding the `allow="clipboard-read; clipboard-write"` attribute from the accepted answer didn't work. Will play around with building the docs later.

**Comment by mscolnick** [comment]
Thanks for finding this. your suggestion was write - i just tried it and works, and deployed it. Should all be good now
