### ISSUE TITLE
RangeSlider UI Component?

### ISSUE THREAD

**Issue by gvarnavi** [marimo-team/marimo#995]
### Description

It would be great if slider could accept a list of values and describe a range.

### Suggested solution

Perhaps something like
```python
range_slider = mo.ui.slider(start=1, stop=10, step=2, value=[2,7])
```

### Alternative

Currently, the best I could come up with is the following hack:
![result](https://github.com/marimo-team/marimo/assets/19610677/4890fbd1-78d9-4ebb-a592-3e217c56a54f)

```python
import marimo as mo

left_slider = mo.ui.slider(start=1,stop=5,step=1,value=2)
right_slider = mo.ui.slider(start=5,stop=10,step=1,value=7)

range_slider = mo.hstack(
    [
        left_slider.style({"filter": "grayscale(100%) brightness(50%)"}),
        right_slider.style({"filter": "grayscale(100%)"}),
    ],
    gap=0,
    justify="center",
)
range_slider
```

### Additional context

For a less contrived example of why this feature might be useful, see [here](https://marimo.app/l/27iouz).

**Comment by akshayka** [comment]
> range_slider = mo.ui.slider(start=1, stop=10, step=2, value=[2,7])

I think I like this ...! So value would either be `None`, a scalar, or a list/tuple of length `>= 1`. If `None`, scalar, or list of length 1, UI defaults to today's behavior. If value is a list or tuple, then `range_slider.value` would also be a list or tuple; otherwise, it is a scalar. 

Does that make sense?

> For a less contrived example of why this feature might be useful, see [here](https://marimo.app/l/27iouz).

Woah, awesome!!

**Comment by gvarnavi** [comment]
Yup, that design pattern makes sense to me!
There is of-course an argument to be made about being more explicit and having this be a different component called `mo.ui.range_slider` or something. This is closer to how [ipywidgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#intrangeslider) does it, although I'll admit their distinction between `IntSlider` and `FloatSlider` seems a bridge too far.

**Comment by wasimsandhu** [comment]
Grabbing this one!
