### ISSUE TITLE
WebAssembly link 431: REQUEST_HEADER_FIELDS_TOO_LARGE error

### ISSUE THREAD

**Issue by serdar-** [marimo-team/marimo#997]
### Describe the bug

When trying to open WebAssembly link following error page shows: 
```
431: REQUEST_HEADER_FIELDS_TOO_LARGE 
Code: REQUEST_HEADER_TOO_LARGE 
ID: fra1::ztcd8-1711289802749-a34a2b869922
```
As far as I understand the host does not accept big request headers. How can I get the content of my notebook in this case?

### Environment

marimo.app

**Comment by mscolnick** [comment]
We currently store the code in a query params which has limits (b/c its sent to the server), but I will switch this to a `#hash` which doesn't so could store larger text.

If you plan to use the `marimo.app` playground in a more serious manner and want to save/share your notebooks and include more files/data, we are building out a way to create different projects each with their own notebook/data. If you want to be an early user of this, reach out to me in our [Discord](https://discord.gg/rAhpfKwuaN)

**Comment by serdar-** [comment]
Thank you for your response. Yes I would like to use marimo in a more serious way. I will contact you for that. 

However, currently I saved my notebook in a query parameter and I do not have any other backup for it. Is there any way for me to open it and get the content of my notebook?

**Comment by mscolnick** [comment]
@serdar- we encode and lz-compress it. You can grab the value of the queryparam `code` and try to Decode it from this codepen: https://codepen.io/mscolnick/pen/KKYqWxN

**Comment by serdar-** [comment]
@mscolnick I already saw in the source code that you use `lz-string` for it. I thought that you did some preprocessing to the string and that is why I was not able to decode it. When I tried to decode the query string I got the first few lines of the content and not the rest, as here: 

```
import marimo

__generated_with = "0.3.3"
app = marimo.App()


@app.cell(hide_coaprt.t
```
I see the same output in the Codepen you sent. 

I tried it both with JavaScript and Python libraries to decode. Python library yields `Key error: "%"` and does not decode at all. The text included non-English characters, could that be the reason?

**Comment by mscolnick** [comment]
that is possible - could you share a small repro (maybe just some of the characters)? can you share for smaller notebooks?

**Comment by serdar-** [comment]
Sure, you can check the link [in this gist](https://gist.github.com/serdar-/2f4a285000a09ff81a6f2f6a9019e131).

**Comment by serdar-** [comment]
This issue seems to be closed but I was wondering if you have the solution for it already. Would it be possible for you to share the solution?

**Comment by mscolnick** [comment]
@serdar- yes, we now store the code in the URL as a hash: e.g. `https://marimo.app/#code/<your code>`. Hash's do not get send the to server, so we will never hit the `REQUEST_HEADER_FIELDS_TOO_LARGE`
